### ISSUE TITLE
broken benchmark for pallet_offences (report_offence_im_online)

### ISSUE THREAD

**Issue by bernardoaraujor** [paritytech/substrate#10027]
I want to run all possible benchmarks on FRAME.

I have `substrate` checked out at `monthly-2021-10`. While running the benchmarks on my machine (i7 CPU, 16Gb RAM), I got stuck with the following error:

```
$ ./target/release/substrate benchmark --chain dev --steps 50 --repeat 20 --pallet=* --extrinsic=*
...
2021-10-13 01:49:58 Running Benchmark:	pallet_offences	report_offence_im_online	214/50	0/1    
2021-10-13 01:50:10 Running Benchmark:	pallet_offences	report_offence_im_online	215/50	0/1    

====================

Version: 3.0.0-dev-bf9683eee4-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:626:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:519:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   5: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   6: core::panicking::assert_failed_inner
   7: core::panicking::assert_failed
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}
   9: <pallet_offences_benchmarking::Pallet<T> as frame_benchmarking::utils::Benchmarking>::run_benchmark
  10: <node_runtime::Runtime as frame_benchmarking::utils::runtime_decl_for_Benchmark::Benchmark<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<sp_runtime::multiaddress::MultiAddress<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,u32>,node_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<node_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<node_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<node_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<node_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<node_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<node_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<node_runtime::Runtime>)>>>>::dispatch_benchmark
  11: node_runtime::api::dispatch
  12: <node_executor::ExecutorDispatch as sc_executor::native_executor::NativeExecutionDispatch>::dispatch
  13: std::thread::local::LocalKey<T>::with
  14: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
  15: sc_executor::wasm_runtime::RuntimeCache::with_instance
  16: <sc_executor::native_executor::NativeElseWasmExecutor<D> as sp_core::traits::CodeExecutor>::call
  17: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
  18: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute
  19: frame_benchmarking_cli::command::<impl frame_benchmarking_cli::BenchmarkCmd>::run
  20: node_cli::command::run
  21: substrate::main
  22: std::sys_common::backtrace::__rust_begin_short_backtrace
  23: std::rt::lang_start::{{closure}}
  24: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
      std::panicking::try
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
      std::panic::catch_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:45:48
      std::panicking::try::do_call
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
      std::panicking::try
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
      std::panic::catch_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
      std::rt::lang_start_internal
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:45:20
  25: main
  26: __libc_start_main
  27: _start


Thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `5`', /home/bear/develop/parity/substrate/substrate/frame/offences/benchmarking/src/lib.rs:358

This is a bug. Please report it at:

	https://github.com/paritytech/substrate/issues/new

2021-10-13 01:50:11 Evicting failed runtime instance: RuntimePanicked("assertion failed: `(left == right)`\n  left: `2`,\n right: `5`")    
Error: Input("Error executing and verifying runtime benchmark: RuntimePanicked(\"assertion failed: `(left == right)`\\n  left: `2`,\\n right: `5`\")")
```

Is this an actual bug, or did I do something wrong when I started the benchmarking?

**Comment by bernardoaraujor** [comment]
```
$ git show -s
commit bf9683eee40f82cc4e01a05cd375b0e8bba3c8ef (HEAD, tag: monthly-2021-10, tag: devhub/latest)
Author: Shawn Tabrizi <shawntabrizi@gmail.com>
Date:   Thu Sep 30 12:46:48 2021 -0400

    Simple Trait to Inspect Metadata (#9893)
    
    * simple trait to inspect metadata
    
    * import vec
    
    
$ ./target/release/substrate --version
substrate 3.0.0-dev-bf9683eee4-x86_64-linux-gnu


$ ./target/release/substrate benchmark --chain dev --steps 50 --repeat 20 --pallet=* --extrinsic=* --features runtime-benchmarks
error: Found argument '--features' which wasn't expected, or isn't valid in this context

USAGE:
    substrate benchmark --chain <CHAIN_SPEC> --extrinsic <extrinsic> --pallet <pallet> --repeat <repeat> --steps <steps>

For more information try --help
```

**Comment by thiolliere** [comment]
maybe the benchmark expect some specific configuration and the way you configured the runtime is inconsistent with this expectation.
So either the configuration of runtime is not sane and the expectation of the benchmark are good or the benchmark is not generic enough on the configuration and needs to be fixed.

**Comment by kianenigma** [comment]
@bernardoaraujor if this is not solved, can you please end an exact commit and command to run to reproduce the issue?

**Comment by kianenigma** [comment]
I get the same issue on current master. It needs a fix. Probably a configuration is broken in node-runtime (and is seemingly fine in `polkadot-runtime` because we run those benchmarks there and they are all fine? )

**Comment by thiolliere** [comment]
sidenote: out of curiosity where is the result of those benchmark used ?

**Comment by shawntabrizi** [comment]
@ggwpez

**Comment by ggwpez** [comment]
I will look into this now.

**Comment by ggwpez** [comment]
Somehow the one test that works, only checks the event emission when run in `test` config.  
https://github.com/paritytech/substrate/blob/542a8585339d2581e641df339d254d7dd22b1456/frame/offences/benchmarking/src/lib.rs#L365
If I add this to the failing event tests in `report_offence_grandpa`, then it also works.  
Does anyone know, why it is only checking correct event count for `test` config?
