### ISSUE TITLE
Flaky test: `notifications_back_pressure` 

### ISSUE THREAD

**Issue by bkchr** [paritytech/substrate#10219]
```
failures:
---- service::tests::notifications_back_pressure stdout ----
thread 'service::tests::notifications_back_pressure' panicked at 'called `Result::unwrap()` on an `Err` value: Closed', client/network/src/service/tests.rs:462:84
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::result::unwrap_failed
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1617:5
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   5: async_io::driver::block_on
   6: std::thread::local::LocalKey<T>::with
   7: std::thread::local::LocalKey<T>::with
   8: async_std::task::builder::Builder::blocking
   9: sc_network::service::tests::notifications_back_pressure
  10: core::ops::function::FnOnce::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
failures:
    service::tests::notifications_back_pressure
```

CC @tomaka @kpp

**Comment by kpp** [comment]
It's a duplicate of https://github.com/paritytech/substrate/issues/9045. I could not find any idea how to repro this.

**Comment by bkchr** [comment]
Ahh sorry!
