### ISSUE TITLE
Bug report of format chainspec file to raw format

### ISSUE THREAD

**Issue by ff13dfly** [paritytech/substrate#10390]
Hi, team.

There is a message asking me to report the bug when I tried to start my private blockchain netwok. 

The message as follow:
--------------------------------start of message------------------------------------
Version: 3.0.0-dev-a8117ad-x86_64-macos

   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: sp_panic_handler::set::{{closure}}
   3: std::panicking::rust_panic_with_hook
             at /rustc/5d04957a4b4714f71d38326fc96a0b0ef6dc5800/library/std/src/panicking.rs:595:17
   4: std::panicking::begin_panic::{{closure}}
   5: std::sys_common::backtrace::__rust_end_short_backtrace
   6: std::panicking::begin_panic
   7: pallet_babe::<impl pallet_babe::pallet::Pallet<T>>::initialize_authorities
   8: <(TupleElement0,TupleElement1,TupleElement2,TupleElement3) as pallet_session::SessionHandler<AId>>::on_genesis_session
   9: std::thread::local::LocalKey<T>::with
  10: sp_state_machine::basic::BasicExternalities::execute_with_storage
  11: <node_runtime::GenesisConfig as sp_runtime::BuildStorage>::assimilate_storage
  12: sp_runtime::BuildStorage::build_storage
  13: <sc_chain_spec::chain_spec::ChainSpec<G,E> as sc_chain_spec::ChainSpec>::as_json
  14: sc_service::chain_ops::import_blocks::build_spec
  15: sc_cli::commands::build_spec_cmd::BuildSpecCmd::run
  16: sc_cli::runner::Runner<C>::sync_run
  17: node_cli::command::run
  18: substrate::main
  19: std::sys_common::backtrace::__rust_begin_short_backtrace
  20: std::rt::lang_start::{{closure}}
  21: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/5d04957a4b4714f71d38326fc96a0b0ef6dc5800/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/5d04957a4b4714f71d38326fc96a0b0ef6dc5800/library/std/src/panicking.rs:379:40
      std::panicking::try
             at /rustc/5d04957a4b4714f71d38326fc96a0b0ef6dc5800/library/std/src/panicking.rs:343:19
      std::panic::catch_unwind
             at /rustc/5d04957a4b4714f71d38326fc96a0b0ef6dc5800/library/std/src/panic.rs:431:14
      std::rt::lang_start_internal
             at /rustc/5d04957a4b4714f71d38326fc96a0b0ef6dc5800/library/std/src/rt.rs:51:25
  22: _main

Thread 'main' panicked at 'Authorities are already initialized!', /Users/fuzhongqiang/Desktop/www/Anchor/frame/babe/src/lib.rs:734
--------------------------------end of message------------------------------------

Hope to help.

Best regard.
Fuu

**Comment by ff13dfly** [comment]
The command line triggered this message  as follow:
./anchor_mac_v1.0 build-spec --chain=anchor.json --raw --disable-default-bootnode > anchorRaw.json

**Comment by ff13dfly** [comment]
The json file without code as follow:

{
    "name": "Anchor network",
    "id": "anchor_root",
    "chainType": "Local",
    "bootNodes": [],
    "telemetryEndpoints": null,
    "protocolId": null,
    "properties": null,
    "forkBlocks": null,
    "badBlocks": null,
    "consensusEngine": null,
    "lightSyncState": null,
    "codeSubstitutes": {},
    "genesis": {
        "runtime": {
            "system": {
                "changesTrieConfig": null,
                "code": ""
            },
            "babe": {
                "authorities": [
                    [
                        "5EySVY7i9iWNGmJcnS8TEVZftmb4ZxtWdqVx3ofsCvRW9riH",
                        1
                    ],
                    [
                        "5FXEQrr15B5ccxjNg3HrxuP5LGzZy9RwiatxpcgoSw1nonxw",
                        1
                    ],
                    [
                        "5F7RxuC5b6aey34CeB2JK8SSrRNmvL42WKfZWi6kSvaG5DYg",
                        1
                    ]
                ],
                "epochConfig": {
                    "c": [
                        1,
                        4
                    ],
                    "allowed_slots": "PrimaryAndSecondaryPlainSlots"
                }
            },
            "grandpa": {
                "authorities": [
                    [
                        "5D3AsszGaLBKB5Jsc4qmxUEXERvKPo8HZHHcvqfCSFDquUSt",
                        1
                    ],
                    [
                        "5GXstkLHzs9fiTHYmATaVadK8BE6XrePb5NtCbGusBondS9o",
                        1
                    ],
                    [
                        "5HUKsBUbY1wa95ovRMQ7UcXvmF6bRt8qcKRfaeksknc1kgXS",
                        1
                    ]
                ]
            },
            "indices": {
                "indices": []
            },
            "balances": {
                "balances": [
                    [
                        "5EySVY7i9iWNGmJcnS8TEVZftmb4ZxtWdqVx3ofsCvRW9riH",
                        1000000000000000000000
                    ],
                    [
                        "5FXEQrr15B5ccxjNg3HrxuP5LGzZy9RwiatxpcgoSw1nonxw",
                        1000000000000000000000
                    ],
                    [
                        "5F7RxuC5b6aey34CeB2JK8SSrRNmvL42WKfZWi6kSvaG5DYg",
                        1000000000000000000000
                    ]
                ]
            },
            "staking": {
                "historyDepth": 84,
                "validatorCount": 2,
                "minimumValidatorCount": 2,
                "invulnerables": [
                    "5EySVY7i9iWNGmJcnS8TEVZftmb4ZxtWdqVx3ofsCvRW9riH",
                    "5FXEQrr15B5ccxjNg3HrxuP5LGzZy9RwiatxpcgoSw1nonxw"
                ],
                "forceEra": "NotForcing",
                "slashRewardFraction": 100000000,
                "canceledPayout": 0,
                "stakers": [
                    [
                        "5EySVY7i9iWNGmJcnS8TEVZftmb4ZxtWdqVx3ofsCvRW9riH",
                        "5D3AsszGaLBKB5Jsc4qmxUEXERvKPo8HZHHcvqfCSFDquUSt",
                        1000000000000000000,
                        "Validator"
                    ],
                    [
                        "5FXEQrr15B5ccxjNg3HrxuP5LGzZy9RwiatxpcgoSw1nonxw",
                        "5GXstkLHzs9fiTHYmATaVadK8BE6XrePb5NtCbGusBondS9o",
                        1000000000000000000,
                        "Validator"
                    ]
                ],
                "minNominatorBond": 0,
                "minValidatorBond": 0
            },
            "session": {
                "keys": [
                    [
                        "5GNJqTPyNqANBkUVMN1LPPrxXnFouWXoe2wNSmmEoLctxiZY",
                        "5GNJqTPyNqANBkUVMN1LPPrxXnFouWXoe2wNSmmEoLctxiZY",
                        {
                            "grandpa": "5FA9nQDVg267DEd8m1ZypXLBnvN7SFxYwV7ndqSYGiN9TTpu",
                            "babe": "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
                            "im_online": "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
                            "authority_discovery": "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"
                        }
                    ],
                    [
                        "5HpG9w8EBLe5XCrbczpwq5TSXvedjrBGCwqxK1iQ7qUsSWFc",
                        "5HpG9w8EBLe5XCrbczpwq5TSXvedjrBGCwqxK1iQ7qUsSWFc",
                        {
                            "grandpa": "5GoNkf6WdbxCFnPdAnYYQyCjAKPJgLNxXwPjwTh6DGg6gN3E",
                            "babe": "5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty",
                            "im_online": "5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty",
                            "authority_discovery": "5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty"
                        }
                    ]
                ]
            },
            "democracy": {
                "phantom": null
            },
            "council": {
                "phantom": null,
                "members": []
            },
            "technicalCommittee": {
                "phantom": null,
                "members": [
                    "5EySVY7i9iWNGmJcnS8TEVZftmb4ZxtWdqVx3ofsCvRW9riH",
                    "5FXEQrr15B5ccxjNg3HrxuP5LGzZy9RwiatxpcgoSw1nonxw",
                    "5F7RxuC5b6aey34CeB2JK8SSrRNmvL42WKfZWi6kSvaG5DYg"
                ]
            },
            "elections": {
                "members": [
                    [
                        "5EySVY7i9iWNGmJcnS8TEVZftmb4ZxtWdqVx3ofsCvRW9riH",
                        1000000000000000000
                    ],
                    [
                        "5FXEQrr15B5ccxjNg3HrxuP5LGzZy9RwiatxpcgoSw1nonxw",
                        1000000000000000000
                    ],
                    [
                        "5F7RxuC5b6aey34CeB2JK8SSrRNmvL42WKfZWi6kSvaG5DYg",
                        1000000000000000000
                    ]
                ]
            },
            "technicalMembership": {
                "members": [],
                "phantom": null
            },
            "treasury": null,
            "sudo": {
                "key": "5EySVY7i9iWNGmJcnS8TEVZftmb4ZxtWdqVx3ofsCvRW9riH"
            },
            "imOnline": {
                "keys": []
            },
            "authorityDiscovery": {
                "keys": []
            },
            "society": {
                "pot": 0,
                "maxMembers": 999,
                "members": [
                    "5EySVY7i9iWNGmJcnS8TEVZftmb4ZxtWdqVx3ofsCvRW9riH",
                    "5FXEQrr15B5ccxjNg3HrxuP5LGzZy9RwiatxpcgoSw1nonxw",
                    "5F7RxuC5b6aey34CeB2JK8SSrRNmvL42WKfZWi6kSvaG5DYg"
                ]
            },
            "vesting": {
                "vesting": []
            },
            "anchor": {
                "fee": 0
            },
            "gilt": null,
            "transactionStorage": {
                "byteFee": 10,
                "entryFee": 1000,
                "storagePeriod": 100800,
                "maxBlockTransactions": 512,
                "maxTransactionSize": 8388608
            }
        }
    }
}
