### ISSUE TITLE
Error: cargo doc --package substrate --open

### ISSUE THREAD

**Issue by jiangfuyao** [paritytech/substrate#1056]
```
threebody@linux:~/Desktop/substrate/$ cargo doc --package substrate --open
 Documenting app_dirs v1.2.1                                                                              
 Documenting typenum v1.10.0                                                                              
    Checking bytes v0.4.10                                                                                
 Documenting bytes v0.4.10                                                                                
 Documenting rand v0.3.22                                                                                 
    Checking rand v0.3.22                                                                                 
    Checking futures-cpupool v0.1.8                                                                       
 Documenting futures-cpupool v0.1.8                                                                       
    Checking lock_api v0.1.4                                                                              
 Documenting lock_api v0.1.4                                                                              
 Documenting want v0.0.6                                                                                  
    Checking mio v0.6.16                                                                                  
 Documenting mio v0.6.16                                                                                  
    Checking tokio-current-thread v0.1.3                                                                  
error: internal compiler error: librustc/traits/structural_impls.rs:178: impossible case reached          
                                                                                                          
thread '<unnamed>' panicked at 'Box<Any>', librustc_errors/lib.rs:587:9                                   
note: Run with `RUST_BACKTRACE=1` for a backtrace.                                                        
                                                                                                          
note: the compiler unexpectedly panicked. this is a bug.                                                  
                                                                                                          
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
                                                                                                          
note: rustc 1.30.0 (da5f414c2 2018-10-24) running on x86_64-unknown-linux-gnu                             
                                                                                                          
error: Could not document `typenum`.                                                                      

Caused by:
  process didn't exit successfully: `rustdoc --crate-name typenum /home/threebody/.cargo/registry/src/github.com-1ecc6299db9ec823/typenum-1.10.0/src/lib.rs --cap-lints allow --color always -o /media/threebody/DATA/Desktop/substrate/substrate/target/doc -L dependency=/media/threebody/DATA/Desktop/substrate/substrate/target/debug/deps` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
error: build failed   
```

```
$ cargo doc --package node-cli --open
 Documenting typenum v1.10.0                                                                              
 Documenting httparse v1.3.3                                                                              
    Checking clap v2.32.0                                                                                 
 Documenting clap v2.32.0                                                                                 
 Documenting memchr v2.1.0                                                                                
    Checking memchr v2.1.0                                                                                
 Documenting unicase v1.4.2                                                                               
    Checking unicase v1.4.2                                                                               
    Checking unicase v2.2.0                                                                               
 Documenting unicase v2.2.0                                                                               
    Checking generic-array v0.9.0                                                                         
    Checking tempfile v3.0.4                                                                              
error: internal compiler error: librustc/traits/structural_impls.rs:178: impossible case reached          
                                                                                                          
thread '<unnamed>' panicked at 'Box<Any>', librustc_errors/lib.rs:587:9                                   
note: Run with `RUST_BACKTRACE=1` for a backtrace.                                                        
                                                                                                          
note: the compiler unexpectedly panicked. this is a bug.                                                  
                                                                                                          
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
                                                                                                          
note: rustc 1.30.0 (da5f414c2 2018-10-24) running on x86_64-unknown-linux-gnu                             
                                                                                                          
error: Could not document `typenum`.                                                                      

Caused by:
  process didn't exit successfully: `rustdoc --crate-name typenum /home/threebody/.cargo/registry/src/github.com-1ecc6299db9ec823/typenum-1.10.0/src/lib.rs --cap-lints allow --color always -o /media/threebody/DATA/Desktop/substrate/substrate/target/doc -L dependency=/media/threebody/DATA/Desktop/substrate/substrate/target/debug/deps` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
error: build failed                                
```

- `$ cargo doc --package srml-contract --open` is ok.

**Comment by bkchr** [comment]
Hey, for me this works without any problems, but I'm also using a nightly compiler.
As you see in the message print by `rustc`, it is a compiler error and should be reported upstream. As it is already fixed in nightly (at least for me), you probably don't need to report it anymore.
