### ISSUE TITLE
Error when running try-runtime

### ISSUE THREAD

**Issue by ntn-x2** [paritytech/substrate#11079]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

When executing `try-runtime` against a live parachain with dependencies on `polkadot-v0.9.17`, the CLI executable crashes with the following stack trace:

```
     Running `target/release/kilt-parachain try-runtime --chain dev --execution native on-runtime-upgrade live --uri 'wss://spiritnet.kilt.io'`
thread 'main' panicked at 'Argument "pallets"
  Arg::is_use_value_delimiter_set is required when Arg::is_require_value_delimiter_set is set.
', .cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.6/src/build/debug_asserts.rs:659:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154/library/core/src/panicking.rs:107:14
   2: clap::build::debug_asserts::assert_arg_flags
             at .cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.6/src/build/debug_asserts.rs:659:5
   3: clap::build::debug_asserts::assert_arg
             at .cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.6/src/build/debug_asserts.rs:621:5
   4: clap::build::debug_asserts::assert_app
             at .cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.6/src/build/debug_asserts.rs:57:9
   5: clap::build::command::App::_build
             at .cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.6/src/build/command.rs:4101:13
   6: clap::build::command::App::_build_subcommand
             at .cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.6/src/build/command.rs:4045:9
   7: clap::parse::parser::Parser::parse_subcommand
             at .cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.6/src/parse/parser.rs:677:27
   8: clap::parse::parser::Parser::get_matches_with
             at .cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.6/src/parse/parser.rs:469:13
   9: clap::parse::parser::Parser::parse_subcommand
             at .cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.6/src/parse/parser.rs:694:37
  10: clap::parse::parser::Parser::get_matches_with
             at .cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.6/src/parse/parser.rs:469:13
  11: clap::parse::parser::Parser::parse_subcommand
             at .cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.6/src/parse/parser.rs:694:37
  12: clap::parse::parser::Parser::get_matches_with
             at .cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.6/src/parse/parser.rs:469:13
  13: clap::build::command::App::_do_parse
             at .cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.6/src/build/command.rs:3971:29
  14: clap::build::command::App::try_get_matches_from_mut
             at .cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.6/src/build/command.rs:681:9
  15: clap::build::command::App::try_get_matches_from
             at .cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.6/src/build/command.rs:597:9
  16: sc_cli::SubstrateCli::from_iter
             at .cargo/git/checkouts/substrate-7e08433d4c370a21/22d40c7/client/cli/src/lib.rs:142:17
  17: sc_cli::SubstrateCli::from_args
             at .cargo/git/checkouts/substrate-7e08433d4c370a21/22d40c7/client/cli/src/lib.rs:104:3
  18: kilt_parachain::command::run
             at ./nodes/parachain/src/command.rs:218:16
  19: kilt_parachain::main
             at ./nodes/parachain/src/main.rs:31:2
  20: core::ops::function::FnOnce::call_once
             at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by bkchr** [comment]
This is fixed in master. I will backport the fix to 0.9.18.
