### ISSUE TITLE
Thread 'main' panicked at 'Stash does not have enough balance to bond.'

### ISSUE THREAD

**Issue by BeginArtem** [paritytech/substrate#11080]
I want to run local blockchain, but after 5-th point i have this error:

```
Version: 3.0.0-dev-1cb0290-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/1af55d19c7a9189374d89472f97dc119659bb67e/library/std/src/panicking.rs:628:17
   2: std::panicking::begin_panic::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: std::panicking::begin_panic
   5: std::thread::local::LocalKey<T>::with
   6: sp_state_machine::basic::BasicExternalities::execute_with_storage
   7: <realis_node_runtime::GenesisConfig as sp_runtime::BuildStorage>::assimilate_storage
   8: sp_runtime::BuildStorage::build_storage
   9: <sc_chain_spec::chain_spec::ChainSpec<G,E> as sp_runtime::BuildStorage>::build_storage
  10: sc_service::client::client::Client<B,E,Block,RA>::new
  11: sc_service::builder::new_full_parts
  12: realis_service::new_full
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: tokio::park::thread::CachedParkThread::block_on
  15: tokio::runtime::thread_pool::ThreadPool::block_on
  16: tokio::runtime::Runtime::block_on
  17: sc_cli::runner::Runner<C>::run_node_until_exit
  18: node_cli::command::run
  19: realis::main
  20: std::sys_common::backtrace::__rust_begin_short_backtrace
  21: std::rt::lang_start::{{closure}}
  22: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/1af55d19c7a9189374d89472f97dc119659bb67e/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/1af55d19c7a9189374d89472f97dc119659bb67e/library/std/src/panicking.rs:403:40
      std::panicking::try
             at /rustc/1af55d19c7a9189374d89472f97dc119659bb67e/library/std/src/panicking.rs:367:19
      std::panic::catch_unwind
             at /rustc/1af55d19c7a9189374d89472f97dc119659bb67e/library/std/src/panic.rs:133:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/1af55d19c7a9189374d89472f97dc119659bb67e/library/std/src/rt.rs:128:48
      std::panicking::try::do_call
             at /rustc/1af55d19c7a9189374d89472f97dc119659bb67e/library/std/src/panicking.rs:403:40
      std::panicking::try
             at /rustc/1af55d19c7a9189374d89472f97dc119659bb67e/library/std/src/panicking.rs:367:19
      std::panic::catch_unwind
             at /rustc/1af55d19c7a9189374d89472f97dc119659bb67e/library/std/src/panic.rs:133:14
      std::rt::lang_start_internal
             at /rustc/1af55d19c7a9189374d89472f97dc119659bb67e/library/std/src/rt.rs:128:20
  23: main
  24: __libc_start_main
  25: _start


Thread 'main' panicked at 'Stash does not have enough balance to bond.', /home/user/CLionProjects/Realis.Network-main/frame/staking-pool/src/pallet/mod.rs:536

This is a bug. Please report it at:

        https://github.com/paritytech/substrate/issues/new
```

What i need to do, to fix this error. Where did the error come from?

**Comment by ggwpez** [comment]
Please explain what you did with a bit more detail.  
Which tutorial did you follow, which commands did you execute?

**Comment by BeginArtem** [comment]
> Please explain what you did with a bit more detail.
> Which tutorial did you follow, which commands did you execute?

Sorry, i forgot to tell my way. 
To put it bluntly, I was refactoring a substrate-based blockchain from polkadot-v0.9.9 branch to an updated polkadot-v0.9.13 branch. The main changes were the addition of parachain pallets and the change in pallet staking (it is custom). Then I fixed all the errors and tried to run the blockchain to see if it was successfully or not to add the desired functionality (parachain). But I could not start, because I received the error that I described above.
I follow this tutorial to run blockchain after changes: https://docs.substrate.io/tutorials/v3/private-network/. 
The last command I used was: 
```
./target/release/node-template \
--base-path /tmp/alice \
--chain local \
--alice \
--port 30333 \
--ws-port 9945 \
--rpc-port 9933 \
--node-key 0000000000000000000000000000000000000000000000000000000000000001 \
--telemetry-url "wss://telemetry.polkadot.io/submit/ 0" \
--validator
```

**Comment by BeginArtem** [comment]
I'm using standart polkadot chain-spec from branch "release-v0.9.13". Firstly i tried to use this without any changes, just to run a chain. But i'm using a custom pallet-staking that works earlier with substrate from branch "polkadot-v0.9.9". 
At now i can't even generate spec.json file to run a chain with this command: 
```
./target/release/myProjectName build-spec --chain=customSpec.json --raw --disable-default-bootnode > spec.json
```
Before that i generated a customSpec.json with this command:
```
./target/release/myProjectName build-spec --disable-default-bootnode --chain local > customSpec.json
```

**Comment by Kofituo** [comment]
I'm facing this same issue

**Comment by kianenigma** [comment]
The mentioned version is quite old. did either one of you try this on a more recent version?

**Comment by Kofituo** [comment]
I've fixed this now
`pallet_balances` should come before `pallet_staking` in the `construct_runtime` macro

**Comment by sayyed-kamran** [comment]
I have the same issue and I do not have pallet_staking in my runtime
