### ISSUE TITLE
benchmark pallet panics with --record-proof

### ISSUE THREAD

**Issue by nbaztec** [paritytech/substrate#12464]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Running a benchmark with `--record-proof` leads to a panic in the runtime. Removing the flag fixes the issue, but having the proof sizes recorded is quite important for benchmark analysis.

```
$ ./node-template benchmark pallet --execution=wasm --wasm-execution=compiled --pallet foo --extrinsic bar --steps 2 --repeat 1 --template=./benchmarking/frame-weight-template.hbs --json-file raw.json --record-proof --output weights.rs

Version: 0.27.0-12f1a369eb4

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/1d37ed661a6922e7a167609b8cd7eb31e972b19b/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/1d37ed661a6922e7a167609b8cd7eb31e972b19b/library/std/src/panicking.rs:588:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/1d37ed661a6922e7a167609b8cd7eb31e972b19b/library/std/src/sys_common/backtrace.rs:138:18
   4: rust_begin_unwind
             at /rustc/1d37ed661a6922e7a167609b8cd7eb31e972b19b/library/std/src/panicking.rs:584:5
   5: core::panicking::panic_fmt
             at /rustc/1d37ed661a6922e7a167609b8cd7eb31e972b19b/library/core/src/panicking.rs:142:14
   6: <sc_client_db::bench::BenchmarkingState<B> as sp_state_machine::backend::Backend<<<B as sp_runtime::traits::Block>::Header as sp_runtime::traits::Header>::Hashing>>::proof_size
   7: tracing::span::Span::in_scope
   8: frame_benchmarking::utils::benchmarking::proof_size_version_1
   9: frame_benchmarking::utils::benchmarking::ExtBenchmarkingProofSizeVersion1::call
  10: <sc_executor_wasmtime::imports::Registry as sp_wasm_interface::HostFunctionRegistry>::with_function_context
  11: std::panicking::try
  12: <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,),R>>::into_func::wasm_to_host_shim
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: wasmtime_runtime::traphandlers::catch_traps::call_closure
  18: wasmtime_setjmp
  19: wasmtime_runtime::traphandlers::catch_traps
  20: wasmtime::func::invoke_wasm_and_catch_traps
  21: wasmtime::func::typed::TypedFunc<Params,Results>::call
  22: sc_executor_wasmtime::instance_wrapper::EntryPoint::call
  23: sc_executor_wasmtime::runtime::perform_call
  24: <sc_executor_wasmtime::runtime::WasmtimeInstance as sc_executor_common::wasm_runtime::WasmInstance>::call_with_allocation_stats
  25: sc_executor_common::wasm_runtime::WasmInstance::call_export
  26: std::panicking::try
  27: environmental::using
  28: sc_executor::native_executor::WasmExecutor<H>::with_instance::{{closure}}
  29: sc_executor::wasm_runtime::RuntimeCache::with_instance
  30: <sc_executor::native_executor::NativeElseWasmExecutor<D> as sp_core::traits::CodeExecutor>::call
  31: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_aux
  32: sp_state_machine::execution::StateMachine<B,H,Exec>::execute
  33: frame_benchmarking_cli::pallet::command::<impl frame_benchmarking_cli::pallet::PalletCmd>::run
  34: sc_cli::runner::Runner<C>::sync_run
  35: moonbeam_cli::command::run
  36: moonbeam::main
  37: std::sys_common::backtrace::__rust_begin_short_backtrace
  38: std::rt::lang_start::{{closure}}
  39: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/1d37ed661a6922e7a167609b8cd7eb31e972b19b/library/core/src/ops/function.rs:280:13
      std::panicking::try::do_call
             at /rustc/1d37ed661a6922e7a167609b8cd7eb31e972b19b/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/1d37ed661a6922e7a167609b8cd7eb31e972b19b/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/1d37ed661a6922e7a167609b8cd7eb31e972b19b/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/1d37ed661a6922e7a167609b8cd7eb31e972b19b/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/1d37ed661a6922e7a167609b8cd7eb31e972b19b/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/1d37ed661a6922e7a167609b8cd7eb31e972b19b/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/1d37ed661a6922e7a167609b8cd7eb31e972b19b/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal
             at /rustc/1d37ed661a6922e7a167609b8cd7eb31e972b19b/library/std/src/rt.rs:148:20
  40: main
  41: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  42: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:392:3
  43: _start


Thread 'main' panicked at 'proof rec root 0xd651f54302c585aa7dce2b43e5fe0e3a9cd0a99da8956fd734cf7f2c02198ed8, root 0xd651f54302c585aa7dce2b43e5fe0e3a9cd0a99da8956fd734cf7f2c02198ed8, genesis 0xf61f7338edf2ad8ed1e9090afdd5ad57aa627eee2ba6ffc327c59e23326b4df0, rec_len 0', /home/nish/.cargo/git/checkouts/substrate-189071a041b0d328/a18cb81/client/db/src/bench.rs:614

This is a bug. Please report it at:

	https://github.com/PureStake/moonbeam/issues/new


Error: Input("Error executing and verifying runtime benchmark: Execution aborted due to trap: host code panicked while being called by the runtime: proof rec root 0xd651f54302c585aa7dce2b43e5fe0e3a9cd0a99da8956fd734cf7f2c02198ed8, root 0xd651f54302c585aa7dce2b43e5fe0e3a9cd0a99da8956fd734cf7f2c02198ed8, genesis 0xf61f7338edf2ad8ed1e9090afdd5ad57aa627eee2ba6ffc327c59e23326b4df0, rec_len 0
WASM backtrace:

    0: 0x639ae - <unknown>!frame_benchmarking::utils::benchmarking::extern_host_function_impls::proof_size::h22668c0142c4cfa3
    1: 0x4339f7 - <unknown>!pallet_parachain_staking::benchmarks::<impl frame_benchmarking::utils::Benchmarking for pallet_parachain_staking::pallet::Pallet<T>>::run_benchmark::hbdd17be450735bc9
    2: 0x408842 - <unknown>!<moonbase_runtime::Runtime as frame_benchmarking::utils::runtime_decl_for_Benchmark::BenchmarkV1<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,fp_self_contained::unchecked_extrinsic::UncheckedExtrinsic<<<account::EthereumSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,moonbase_runtime::Call,account::EthereumSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<moonbase_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<moonbase_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<moonbase_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<moonbase_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<moonbase_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<moonbase_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<moonbase_runtime::Runtime>)>>>>::dispatch_benchmark::hd427c4321ca922e3
    3: 0x32b8b3 - <unknown>!Benchmark_dispatch_benchmark
")
```

### Steps to reproduce

1. Compile a node with `--features runtime-benchmarks`
2. Run a `benchmark pallet` with `--record-proof` arg, for example:
```
./node-template benchmark pallet --execution=wasm --wasm-execution=compiled --pallet foo --extrinsic bar --steps 2 --repeat 1 --template=./benchmarking/frame-weight-template.hbs --json-file raw.json --record-proof --output weights.rs
```

**Comment by ggwpez** [comment]
Thanks for reporting. https://github.com/paritytech/substrate/pull/11637 will change the behaviour and should fix this as well.  
I will still take a look if it is easy to fix, although I am not sure if there are tests in place that it actually works correctly.

**Comment by ggwpez** [comment]
Done in https://github.com/paritytech/substrate/pull/11637
