### ISSUE TITLE
panic while building `subkey`, error: failed to run custom build command for `tikv-jemalloc-sys v0.5.1+5.3.0-patched`

### ISSUE THREAD

**Issue by M4n5ter** [paritytech/substrate#12596]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

```zsh
❯ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/m4n5ter/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
aarch64-apple-ios
aarch64-apple-ios-sim
wasm32-unknown-unknown
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.64.0 (a55dd71d5 2022-09-19)

```

```zsh
❯ neofetch
██████████████████  ████████   m4n5ter@m4n5ter-yoga14 
██████████████████  ████████   ---------------------- 
██████████████████  ████████   OS: Manjaro Linux x86_64 
██████████████████  ████████   Host: 82MS Yoga 14sACH 2021 
████████            ████████   Kernel: 6.0.2-2-MANJARO 
████████  ████████  ████████   Uptime: 7 hours, 18 mins 
████████  ████████  ████████   Packages: 1335 (pacman) 
████████  ████████  ████████   Shell: zsh 5.9 
████████  ████████  ████████   Resolution: 2880x1800 
████████  ████████  ████████   DE: Plasma 5.25.5 
████████  ████████  ████████   WM: KWin 
████████  ████████  ████████   Theme: [Plasma], Breeze [GTK2/3] 
████████  ████████  ████████   Icons: [Plasma], WhiteSur-dark [GTK2/3] 
████████  ████████  ████████   Terminal: konsole 
                               CPU: AMD Ryzen 7 5800H with Radeon Graphics (16) @ 3.200GHz 
                               GPU: AMD ATI 03:00.0 Cezanne 
                               Memory: 6997MiB / 15337MiB 

```

```zsh
❯ git clone https://github.com/paritytech/substrate.git
❯ cd substrate
❯ RUST_BACKTRACE=full cargo +nightly build --package subkey --release
......
......
......
error: failed to run custom build command for `tikv-jemalloc-sys v0.5.1+5.3.0-patched`

Caused by:
  process didn't exit successfully: `/home/m4n5ter/src/rust/substrate/target/release/build/tikv-jemalloc-sys-df3f36a466860053/build-script-build` (exit status: 101)
  --- stdout
  TARGET=x86_64-unknown-linux-gnu
  HOST=x86_64-unknown-linux-gnu
  NUM_JOBS=16
  OUT_DIR="/home/m4n5ter/src/rust/substrate/target/release/build/tikv-jemalloc-sys-55888a2b5fc74670/out"
  BUILD_DIR="/home/m4n5ter/src/rust/substrate/target/release/build/tikv-jemalloc-sys-55888a2b5fc74670/out/build"
  SRC_DIR="/home/m4n5ter/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tikv-jemalloc-sys-0.5.1+5.3.0-patched"
  cargo:rerun-if-env-changed=JEMALLOC_OVERRIDE
  OPT_LEVEL = Some("3")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,llvm14-builtins-abi,sse,sse2")
  CC="cc"
  CFLAGS="-O3 -ffunction-sections -fdata-sections -fPIC -m64 -Wall"
  JEMALLOC_REPO_DIR="jemalloc"
  cargo:rerun-if-env-changed=JEMALLOC_SYS_WITH_MALLOC_CONF
  cargo:rerun-if-env-changed=JEMALLOC_SYS_WITH_LG_PAGE
  cargo:rerun-if-env-changed=JEMALLOC_SYS_WITH_LG_HUGEPAGE
  cargo:rerun-if-env-changed=JEMALLOC_SYS_WITH_LG_QUANTUM
  cargo:rerun-if-env-changed=JEMALLOC_SYS_WITH_LG_VADDR
  running: "sh" "/home/m4n5ter/src/rust/substrate/target/release/build/tikv-jemalloc-sys-55888a2b5fc74670/out/build/configure" "--disable-cxx" "--enable-doc=no" "--enable-shared=no" "--with-private-namespace=_rjem_" "--host=x86_64-unknown-linux-gnu" "--build=x86_64-unknown-linux-gnu" "--prefix=/home/m4n5ter/src/rust/substrate/target/release/build/tikv-jemalloc-sys-55888a2b5fc74670/out"
  checking for xsltproc... /usr/bin/xsltproc
  checking for x86_64-unknown-linux-gnu-gcc... cc
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables... 
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether we are using the GNU C compiler... yes
  checking whether cc accepts -g... yes
  checking for cc option to accept ISO C89... none needed
  checking whether compiler is cray... no
  checking whether compiler supports -std=gnu11... yes
  checking whether compiler supports -Werror=unknown-warning-option... no
  checking whether compiler supports -Wall... yes
  checking whether compiler supports -Wextra... yes
  checking whether compiler supports -Wshorten-64-to-32... no
  checking whether compiler supports -Wsign-compare... yes
  checking whether compiler supports -Wundef... yes
  checking whether compiler supports -Wno-format-zero-length... yes
  checking whether compiler supports -Wpointer-arith... yes
  checking whether compiler supports -Wno-missing-braces... yes
  checking whether compiler supports -Wno-missing-field-initializers... yes
  checking whether compiler supports -Wno-missing-attributes... yes
  checking whether compiler supports -pipe... yes
  checking whether compiler supports -g3... yes
  checking how to run the C preprocessor... cc -E
  checking for grep that handles long lines and -e... /usr/bin/grep
  checking for egrep... /usr/bin/grep -E
  checking for ANSI C header files... yes
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking whether byte ordering is bigendian... no
  checking size of void *... 8
  checking size of int... 4
  checking size of long... 8
  checking size of long long... 8
  checking size of intmax_t... 8
  checking build system type... x86_64-unknown-linux-gnu
  checking host system type... x86_64-unknown-linux-gnu
  checking whether pause instruction is compilable... yes
  checking number of significant virtual address bits... 48
  checking for x86_64-unknown-linux-gnu-ar... no
  checking for ar... ar
  checking for x86_64-unknown-linux-gnu-nm... no
  checking for nm... nm
  checking for gawk... gawk
  checking malloc.h usability... yes
  checking malloc.h presence... yes
  checking for malloc.h... yes
  checking whether malloc_usable_size definition can use const argument... no
  checking for library containing log... -lm
  checking whether __attribute__ syntax is compilable... yes
  checking whether compiler supports -fvisibility=hidden... yes
  checking whether compiler supports -fvisibility=hidden... no
  checking whether compiler supports -Werror... yes
  checking whether compiler supports -herror_on_warning... yes
  checking whether tls_model attribute is compilable... yes
  checking whether compiler supports -Werror... yes
  checking whether compiler supports -herror_on_warning... yes
  checking whether alloc_size attribute is compilable... yes
  checking whether compiler supports -Werror... yes
  checking whether compiler supports -herror_on_warning... yes
  checking whether format(gnu_printf, ...) attribute is compilable... yes
  checking whether compiler supports -Werror... yes
  checking whether compiler supports -herror_on_warning... yes
  checking whether format(printf, ...) attribute is compilable... yes
  checking whether compiler supports -Werror... yes
  checking whether compiler supports -herror_on_warning... yes
  checking whether format(printf, ...) attribute is compilable... yes
  checking whether compiler supports -Wimplicit-fallthrough... yes
  checking whether fallthrough attribute is compilable... yes
  checking whether compiler supports -Wimplicit-fallthrough... yes
  checking whether compiler supports -Wimplicit-fallthrough... no
  checking whether compiler supports -Werror... yes
  checking whether compiler supports -herror_on_warning... yes
  checking whether cold attribute is compilable... yes
  checking whether vm_make_tag is compilable... no
  checking for a BSD-compatible install... /usr/bin/install -c
  checking for x86_64-unknown-linux-gnu-ranlib... no
  checking for ranlib... ranlib
  checking for ld... /usr/bin/ld
  checking for autoconf... false
  checking for memalign... yes
  checking for valloc... yes
  checking for malloc_size... no
  checking for __libc_calloc... yes
  checking for __libc_free... yes
  checking for __libc_malloc... yes
  checking for __libc_memalign... yes
  checking for __libc_realloc... yes
  checking for __libc_valloc... yes
  checking for __posix_memalign... no
  checking whether compiler supports -O3... yes
  checking whether compiler supports -O3... no
  checking whether compiler supports -funroll-loops... yes
  checking configured backtracing method... N/A
  checking for sbrk... yes
  checking whether utrace(2) is compilable... no
  checking whether utrace(2) with label is compilable... no
  checking whether a program using __builtin_unreachable is compilable... yes
  checking whether a program using __builtin_ffsl is compilable... yes
  checking whether a program using __builtin_popcountl is compilable... yes
  checking LG_PAGE... 12
  checking pthread.h usability... yes
  checking pthread.h presence... yes
  checking for pthread.h... yes
  checking for pthread_create in -lpthread... yes
  checking dlfcn.h usability... yes
  checking dlfcn.h presence... yes
  checking for dlfcn.h... yes
  checking for dlsym... yes
  checking whether pthread_atfork(3) is compilable... yes
  checking whether pthread_setname_np(3) is compilable... yes
  checking whether pthread_getname_np(3) is compilable... yes
  checking whether pthread_get_name_np(3) is compilable... no
  checking for library containing clock_gettime... none required
  checking whether clock_gettime(CLOCK_MONOTONIC_COARSE, ...) is compilable... yes
  checking whether clock_gettime(CLOCK_MONOTONIC, ...) is compilable... yes
  checking whether mach_absolute_time() is compilable... no
  checking whether clock_gettime(CLOCK_REALTIME, ...) is compilable... yes
  checking whether compiler supports -Werror... yes
  checking whether syscall(2) is compilable... yes
  checking for secure_getenv... yes
  checking for sched_getcpu... yes
  checking for sched_setaffinity... yes
  checking for issetugid... no
  checking for _malloc_thread_cleanup... no
  checking for _pthread_mutex_init_calloc_cb... no
  checking for memcntl... no
  checking for TLS... yes
  checking whether C11 atomics is compilable... yes
  checking whether GCC __atomic atomics is compilable... yes
  checking whether GCC 8-bit __atomic atomics is compilable... yes
  checking whether GCC __sync atomics is compilable... yes
  checking whether GCC 8-bit __sync atomics is compilable... yes
  checking whether Darwin OSAtomic*() is compilable... no
  checking whether madvise(2) is compilable... yes
  checking whether madvise(..., MADV_FREE) is compilable... yes
  checking whether madvise(..., MADV_DONTNEED) is compilable... yes
  checking whether madvise(..., MADV_DO[NT]DUMP) is compilable... yes
  checking whether madvise(..., MADV_[NO]HUGEPAGE) is compilable... yes
  checking whether madvise(..., MADV_[NO]CORE) is compilable... no
  checking whether mprotect(2) is compilable... yes
  checking for __builtin_clz... yes
  checking whether Darwin os_unfair_lock_*() is compilable... no
  checking whether glibc malloc hook is compilable... no
  checking whether glibc memalign hook is compilable... no
  checking whether pthreads adaptive mutexes is compilable... yes
  checking whether compiler supports -D_GNU_SOURCE... yes
  checking whether compiler supports -Werror... yes
  checking whether compiler supports -herror_on_warning... yes
  checking whether strerror_r returns char with gnu source is compilable... yes
  checking for stdbool.h that conforms to C99... yes
  checking for _Bool... yes
  configure: creating ./config.status
  config.status: creating Makefile
  config.status: creating jemalloc.pc
  config.status: creating doc/html.xsl
  config.status: creating doc/manpages.xsl
  config.status: creating doc/jemalloc.xml
  config.status: creating include/jemalloc/jemalloc_macros.h
  config.status: creating include/jemalloc/jemalloc_protos.h
  config.status: creating include/jemalloc/jemalloc_typedefs.h
  config.status: creating include/jemalloc/internal/jemalloc_preamble.h
  config.status: creating test/test.sh
  config.status: creating test/include/test/jemalloc_test.h
  config.status: creating config.stamp
  config.status: creating bin/jemalloc-config
  config.status: creating bin/jemalloc.sh
  config.status: creating bin/jeprof
  config.status: creating include/jemalloc/jemalloc_defs.h
  config.status: creating include/jemalloc/internal/jemalloc_internal_defs.h
  config.status: creating test/include/test/jemalloc_test_defs.h
  config.status: executing include/jemalloc/internal/public_symbols.txt commands
  config.status: executing include/jemalloc/internal/private_symbols.awk commands
  config.status: executing include/jemalloc/internal/private_symbols_jet.awk commands
  config.status: executing include/jemalloc/internal/public_namespace.h commands
  config.status: executing include/jemalloc/internal/public_unnamespace.h commands
  config.status: executing include/jemalloc/jemalloc_protos_jet.h commands
  config.status: executing include/jemalloc/jemalloc_rename.h commands
  config.status: executing include/jemalloc/jemalloc_mangle.h commands
  config.status: executing include/jemalloc/jemalloc_mangle_jet.h commands
  config.status: executing include/jemalloc/jemalloc.h commands
  ===============================================================================
  jemalloc version   : 5.3.0-0-g54eaed1d8b56b1aa528be3bdd1877e59c56fa90c
  library revision   : 2

  CONFIG             : --disable-cxx --enable-doc=no --enable-shared=no --with-private-namespace=_rjem_ --host=x86_64-unknown-linux-gnu --build=x86_64-unknown-linux-gnu --prefix=/home/m4n5ter/src/rust/substrate/target/release/build/tikv-jemalloc-sys-55888a2b5fc74670/out build_alias=x86_64-unknown-linux-gnu host_alias=x86_64-unknown-linux-gnu CC=cc 'CFLAGS=-O3 -ffunction-sections -fdata-sections -fPIC -m64 -Wall' 'LDFLAGS=-O3 -ffunction-sections -fdata-sections -fPIC -m64 -Wall' 'CPPFLAGS=-O3 -ffunction-sections -fdata-sections -fPIC -m64 -Wall'
  CC                 : cc
  CONFIGURE_CFLAGS   : -std=gnu11 -Wall -Wextra -Wsign-compare -Wundef -Wno-format-zero-length -Wpointer-arith -Wno-missing-braces -Wno-missing-field-initializers -Wno-missing-attributes -pipe -g3 -fvisibility=hidden -Wimplicit-fallthrough -O3 -funroll-loops
  SPECIFIED_CFLAGS   : -O3 -ffunction-sections -fdata-sections -fPIC -m64 -Wall
  EXTRA_CFLAGS       : 
  CPPFLAGS           : -O3 -ffunction-sections -fdata-sections -fPIC -m64 -Wall -D_GNU_SOURCE -D_REENTRANT
  CXX                : 
  CONFIGURE_CXXFLAGS : 
  SPECIFIED_CXXFLAGS : 
  EXTRA_CXXFLAGS     : 
  LDFLAGS            : -O3 -ffunction-sections -fdata-sections -fPIC -m64 -Wall
  EXTRA_LDFLAGS      : 
  DSO_LDFLAGS        : -shared -Wl,-soname,$(@F)
  LIBS               : -lm  -pthread
  RPATH_EXTRA        : 

  XSLTPROC           : /usr/bin/xsltproc
  XSLROOT            : 

  PREFIX             : /home/m4n5ter/src/rust/substrate/target/release/build/tikv-jemalloc-sys-55888a2b5fc74670/out
  BINDIR             : /home/m4n5ter/src/rust/substrate/target/release/build/tikv-jemalloc-sys-55888a2b5fc74670/out/bin
  DATADIR            : /home/m4n5ter/src/rust/substrate/target/release/build/tikv-jemalloc-sys-55888a2b5fc74670/out/share
  INCLUDEDIR         : /home/m4n5ter/src/rust/substrate/target/release/build/tikv-jemalloc-sys-55888a2b5fc74670/out/include
  LIBDIR             : /home/m4n5ter/src/rust/substrate/target/release/build/tikv-jemalloc-sys-55888a2b5fc74670/out/lib
  MANDIR             : /home/m4n5ter/src/rust/substrate/target/release/build/tikv-jemalloc-sys-55888a2b5fc74670/out/share/man

  srcroot            : 
  abs_srcroot        : /home/m4n5ter/src/rust/substrate/target/release/build/tikv-jemalloc-sys-55888a2b5fc74670/out/build/
  objroot            : 
  abs_objroot        : /home/m4n5ter/src/rust/substrate/target/release/build/tikv-jemalloc-sys-55888a2b5fc74670/out/build/

  JEMALLOC_PREFIX    : 
  JEMALLOC_PRIVATE_NAMESPACE
                     : _rjem_je_
  install_suffix     : 
  malloc_conf        : 
  documentation      : 0
  shared libs        : 0
  static libs        : 1
  autogen            : 0
  debug              : 0
  stats              : 1
  experimental_smallocx : 0
  prof               : 0
  prof-libunwind     : 0
  prof-libgcc        : 0
  prof-gcc           : 0
  fill               : 1
  utrace             : 0
  xmalloc            : 0
  log                : 0
  lazy_lock          : 0
  cache-oblivious    : 1
  cxx                : 0
  ===============================================================================
  running: "make" "-j" "16"

  --- stderr
  thread 'main' panicked at 'failed to execute command: No such file or directory (os error 2)', /home/m4n5ter/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tikv-jemalloc-sys-0.5.1+5.3.0-patched/build.rs:327:19
  stack backtrace:
     0:     0x556c9fcbe4c0 - std::backtrace_rs::backtrace::libunwind::trace::he5712a3b730274ef
                                 at /rustc/95a3a7277b44bbd2dd3485703d9a05f64652b60e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0x556c9fcbe4c0 - std::backtrace_rs::backtrace::trace_unsynchronized::hd4189b91290b2c2f
                                 at /rustc/95a3a7277b44bbd2dd3485703d9a05f64652b60e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x556c9fcbe4c0 - std::sys_common::backtrace::_print_fmt::ha91bca0221bb9d27
                                 at /rustc/95a3a7277b44bbd2dd3485703d9a05f64652b60e/library/std/src/sys_common/backtrace.rs:65:5
     3:     0x556c9fcbe4c0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3a771605a410cd0e
                                 at /rustc/95a3a7277b44bbd2dd3485703d9a05f64652b60e/library/std/src/sys_common/backtrace.rs:44:22
     4:     0x556c9fcde32e - core::fmt::write::hf6163bde4ca91df2
                                 at /rustc/95a3a7277b44bbd2dd3485703d9a05f64652b60e/library/core/src/fmt/mod.rs:1209:17
     5:     0x556c9fcbaf55 - std::io::Write::write_fmt::hc21ca21bde700bca
                                 at /rustc/95a3a7277b44bbd2dd3485703d9a05f64652b60e/library/std/src/io/mod.rs:1682:15
     6:     0x556c9fcbe285 - std::sys_common::backtrace::_print::h127bd2c75f8a95ae
                                 at /rustc/95a3a7277b44bbd2dd3485703d9a05f64652b60e/library/std/src/sys_common/backtrace.rs:47:5
     7:     0x556c9fcbe285 - std::sys_common::backtrace::print::h94a89ffb412ed8a5
                                 at /rustc/95a3a7277b44bbd2dd3485703d9a05f64652b60e/library/std/src/sys_common/backtrace.rs:34:9
     8:     0x556c9fcbfcaf - std::panicking::default_hook::{{closure}}::h28198923484faf54
                                 at /rustc/95a3a7277b44bbd2dd3485703d9a05f64652b60e/library/std/src/panicking.rs:267:22
     9:     0x556c9fcbf9ea - std::panicking::default_hook::h0b7011e510eb6c59
                                 at /rustc/95a3a7277b44bbd2dd3485703d9a05f64652b60e/library/std/src/panicking.rs:286:9
    10:     0x556c9fcc03a8 - std::panicking::rust_panic_with_hook::h37194ee0814373fe
                                 at /rustc/95a3a7277b44bbd2dd3485703d9a05f64652b60e/library/std/src/panicking.rs:688:13
    11:     0x556c9fcc0147 - std::panicking::begin_panic_handler::{{closure}}::hf046abbc79eadaa2
                                 at /rustc/95a3a7277b44bbd2dd3485703d9a05f64652b60e/library/std/src/panicking.rs:579:13
    12:     0x556c9fcbe96c - std::sys_common::backtrace::__rust_end_short_backtrace::h29eb3665d762db8e
                                 at /rustc/95a3a7277b44bbd2dd3485703d9a05f64652b60e/library/std/src/sys_common/backtrace.rs:137:18
    13:     0x556c9fcbfe62 - rust_begin_unwind
                                 at /rustc/95a3a7277b44bbd2dd3485703d9a05f64652b60e/library/std/src/panicking.rs:575:5
    14:     0x556c9fc43513 - core::panicking::panic_fmt::h8dcdd3e0ec3bc834
                                 at /rustc/95a3a7277b44bbd2dd3485703d9a05f64652b60e/library/core/src/panicking.rs:65:14
    15:     0x556c9fc49d9b - build_script_build::execute::hf3905fdbc701e73d
    16:     0x556c9fc49906 - build_script_build::run::h0b99e8d2299e417e
    17:     0x556c9fc485da - build_script_build::main::h66d3a141a5eabd5f
    18:     0x556c9fc4ac73 - core::ops::function::FnOnce::call_once::heba7eac553d65473
    19:     0x556c9fc50e69 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5b3ee46030349f45
    20:     0x556c9fc4c4f9 - std::rt::lang_start::{{closure}}::hc1dbacb3976ef135
    21:     0x556c9fcb730b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h75c150f3d2b21cf1
                                 at /rustc/95a3a7277b44bbd2dd3485703d9a05f64652b60e/library/core/src/ops/function.rs:286:13
    22:     0x556c9fcb730b - std::panicking::try::do_call::h05a8bdc781486607
                                 at /rustc/95a3a7277b44bbd2dd3485703d9a05f64652b60e/library/std/src/panicking.rs:483:40
    23:     0x556c9fcb730b - std::panicking::try::h486661fd26d9871b
                                 at /rustc/95a3a7277b44bbd2dd3485703d9a05f64652b60e/library/std/src/panicking.rs:447:19
    24:     0x556c9fcb730b - std::panic::catch_unwind::h0c1f9932ffdbdfb7
                                 at /rustc/95a3a7277b44bbd2dd3485703d9a05f64652b60e/library/std/src/panic.rs:137:14
    25:     0x556c9fcb730b - std::rt::lang_start_internal::{{closure}}::h0d043fc48041eb87
                                 at /rustc/95a3a7277b44bbd2dd3485703d9a05f64652b60e/library/std/src/rt.rs:148:48
    26:     0x556c9fcb730b - std::panicking::try::do_call::h56b3cb6636b51dac
                                 at /rustc/95a3a7277b44bbd2dd3485703d9a05f64652b60e/library/std/src/panicking.rs:483:40
    27:     0x556c9fcb730b - std::panicking::try::h9e1089a5d461531b
                                 at /rustc/95a3a7277b44bbd2dd3485703d9a05f64652b60e/library/std/src/panicking.rs:447:19
    28:     0x556c9fcb730b - std::panic::catch_unwind::ha050087be5a112c8
                                 at /rustc/95a3a7277b44bbd2dd3485703d9a05f64652b60e/library/std/src/panic.rs:137:14
    29:     0x556c9fcb730b - std::rt::lang_start_internal::h947bbd053cc7a2d8
                                 at /rustc/95a3a7277b44bbd2dd3485703d9a05f64652b60e/library/std/src/rt.rs:148:20
    30:     0x556c9fc4c4d7 - std::rt::lang_start::h5f4897f6ce2e8657
    31:     0x556c9fc4a3a5 - main
    32:     0x7f7fb01d3290 - <unknown>
    33:     0x7f7fb01d334a - __libc_start_main
    34:     0x556c9fc438a5 - _start
                                 at /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115
    35:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...

```

**Comment by bkchr** [comment]
Do you have `make` installed?

**Comment by M4n5ter** [comment]
> Do you have `make` installed?

oh, I recently reinstalled the system and I forgot about it. Now that machine is where I work, so I can't confirm it for now.

I successfully built on another system with a similar environment, this issue should be caused by no `make` on the system

**Comment by bkchr** [comment]
So it is solved now?

**Comment by M4n5ter** [comment]
Thank you for your reply, it is solved.
