### ISSUE TITLE
Fix tests for Rust 1.65

### ISSUE THREAD

**Issue by alvicsam** [paritytech/substrate#12629]
In order to update rust version in CI image tests should be fixed: 
[This PR](https://github.com/paritytech/substrate/pull/12628) contains ci image with updated rust and can be used for fixing them.

```bash
test tests/pallet_ui/pass/trait_constant_valid_bounds.rs [should pass] ... ok
thread 'pallet_ui' panicked at '8 of 71 tests failed', /cargo_home/registry/src/github.com-1ecc6299db9ec823/trybuild-1.0.60/src/run.rs:85:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: trybuild::run::<impl trybuild::Runner>::run
   3: <trybuild::TestCases as core::ops::drop::Drop>::drop
   4: core::ops::function::FnOnce::call_once
   5: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
        PASS [ 513.992s]                                                  frame-support-test::derive_no_bound_ui derive_no_bound_ui
        PASS [ 516.846s]                                                     frame-support-test::decl_storage_ui decl_storage_ui
------------
     Summary [ 516.954s] 1596 tests run: 1593 passed (8 slow), 3 failed, 2985 skipped
        FAIL [ 353.310s]                                                frame-support-test::construct_runtime_ui ui
        FAIL [ 504.512s]                                                           frame-support-test::pallet_ui pallet_ui
        FAIL [ 326.503s]                                                                   sp-api-test::trybuild ui
error: test run failed
```

cc https://github.com/paritytech/ci_cd/issues/653

**Comment by bkchr** [comment]
@alvicsam you just need to run `.maintain/update-rust-stable.sh 1.65.0`
