### ISSUE TITLE
Bad input data provided to query_info: Input buffer has still data left after decoding!

### ISSUE THREAD

**Issue by blackjooohn** [paritytech/substrate#12750]
====================

Version: 4.0.0-424ffcc-x86_64-macos

   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: sp_panic_handler::set::{{closure}}
   3: std::panicking::rust_panic_with_hook
             at /rustc/6bda5b331cfe7e04e1fe348c58a928fc2b650f4f/library/std/src/panicking.rs:610:17
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/6bda5b331cfe7e04e1fe348c58a928fc2b650f4f/library/std/src/panicking.rs:502:13
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/6bda5b331cfe7e04e1fe348c58a928fc2b650f4f/library/std/src/sys_common/backtrace.rs:139:18
   6: rust_begin_unwind
             at /rustc/6bda5b331cfe7e04e1fe348c58a928fc2b650f4f/library/std/src/panicking.rs:498:5
   7: core::panicking::panic_fmt
             at /rustc/6bda5b331cfe7e04e1fe348c58a928fc2b650f4f/library/core/src/panicking.rs:107:14
   8: node_runtime::api::dispatch
   9: <node_executor::ExecutorDispatch as sc_executor::native_executor::NativeExecutionDispatch>::dispatch
  10: std::thread::local::LocalKey<T>::with
  11: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
  12: sc_executor::wasm_runtime::RuntimeCache::with_instance
  13: <sc_executor::native_executor::NativeElseWasmExecutor<D> as sp_core::traits::CodeExecutor>::call
  14: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_aux
  15: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_using_consensus_failure_handler
  16: <sc_service::client::call_executor::LocalCallExecutor<Block,B,E> as sc_client_api::call_executor::CallExecutor<Block>>::call
  17: <sc_rpc::state::state_full::FullState<BE,Block,Client> as sc_rpc::state::StateBackend<Block,Client>>::call
  18: <jsonrpc_core::delegates::DelegateAsyncMethod<T,F> as jsonrpc_core::calls::RpcMethod<M>>::call
  19: <sc_rpc_server::middleware::RpcMiddleware as jsonrpc_core::middleware::Middleware<M>>::on_call
  20: <sc_rpc_server::middleware::RpcMiddleware as jsonrpc_core::middleware::Middleware<M>>::on_request
  21: jsonrpc_core::io::MetaIoHandler<T,S>::handle_request
  22: <jsonrpc_ws_server::session::Session<M,S> as parity_ws::handler::Handler>::on_message
  23: parity_ws::connection::Connection<H>::read_frames
  24: parity_ws::connection::Connection<H>::read
  25: parity_ws::io::Handler<F>::handle_event
  26: parity_ws::io::Handler<F>::run
  27: std::sys_common::backtrace::__rust_begin_short_backtrace
  28: core::ops::function::FnOnce::call_once{{vtable.shim}}
  29: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/6bda5b331cfe7e04e1fe348c58a928fc2b650f4f/library/alloc/src/boxed.rs:1811:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/6bda5b331cfe7e04e1fe348c58a928fc2b650f4f/library/alloc/src/boxed.rs:1811:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/6bda5b331cfe7e04e1fe348c58a928fc2b650f4f/library/std/src/sys/unix/thread.rs:108:17
  30: __pthread_start

Thread '<unnamed>' panicked at 'Bad input data provided to query_info: Input buffer has still data left after decoding!', node/runtime/src/lib.rs:1451

This is a bug. Please report it at:

        https://github.com/paritytech/substrate/issues/new

2022-11-21 15:51:25 Evicting failed runtime instance: RuntimePanicked("Bad input data provided to query_info: Input buffer has still data left after decoding!")    
2022-11-21 15:51:25 Unknown error: Client(Execution(RuntimePanicked("Bad input data provided to query_info: Input buffer has still data left after decoding!")))

**Comment by bkchr** [comment]
This just means that someone has send an invalid transaction to the node to query. No error.
