### ISSUE TITLE
build-linux-substrate job fails in master pipeline

### ISSUE THREAD

**Issue by alvicsam** [paritytech/substrate#12803]
Link: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2096430

Error: 

```
   Compiling sc-network-gossip v0.10.0-dev (https://github.com/paritytech/substrate.git?rev=a0e00dc87cc1c2e52281bff3db61a4d4cc1aa983#a0e00dc8)
error[E0433]: failed to resolve: could not find `derive_prelude` in `swarm`
  --> /cargo_home/git/checkouts/substrate-7e08433d4c370a21/a0e00dc/client/network/src/behaviour.rs:56:10
   |
56 | #[derive(NetworkBehaviour)]
   |          ^^^^^^^^^^^^^^^^ could not find `derive_prelude` in `swarm`
   |
   = note: this error originates in the derive macro `NetworkBehaviour` (in Nightly builds, run with -Z macro-backtrace for more info)
error[E0432]: unresolved import `libp2p`
  --> /cargo_home/git/checkouts/substrate-7e08433d4c370a21/a0e00dc/client/network/src/behaviour.rs:56:10
   |
56 | #[derive(NetworkBehaviour)]
   |          ^^^^^^^^^^^^^^^^ could not find `derive_prelude` in `swarm`
   |
   = note: this error originates in the derive macro `NetworkBehaviour` (in Nightly builds, run with -Z macro-backtrace for more info)
Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `sc-network` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
warning: Could not find `Cargo.lock` for `/tmp/.tmp6bIIgj/node-template/runtime/Cargo.toml`, while searching from `/cargo_target_dir/debug/build/node-template-runtime-93cc08eff2c1ca44/out`. To fix this, point the `WASM_BUILD_WORKSPACE_HINT` env variable to the directory of the workspace being compiled.
warning: Could not find `Cargo.lock` for `/tmp/.tmp6bIIgj/node-template/runtime/Cargo.toml`, while searching from `/cargo_target_dir/debug/build/node-template-runtime-93cc08eff2c1ca44/out`. To fix this, point the `WASM_BUILD_WORKSPACE_HINT` env variable to the directory of the workspace being compiled.
warning: Could not find `Cargo.lock` for `/tmp/.tmp6bIIgj/node-template/runtime/Cargo.toml`, while searching from `/cargo_target_dir/debug/build/node-template-runtime-93cc08eff2c1ca44/out`. To fix this, point the `WASM_BUILD_WORKSPACE_HINT` env variable to the directory of the workspace being compiled.
thread 'main' panicked at 'assertion failed: Command::new(\"cargo\").args(&[\"build\",\n                                \"--all\"]).current_dir(path).status().expect(\"Compiles node\").success()', src/main.rs:183:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
   3: node_template_release::build_and_test
             at ./src/main.rs:183:2
   4: node_template_release::main
             at ./src/main.rs:270:2
   5: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Jinsipang** [comment]
Exactly, I'm also facing same issue
