### ISSUE TITLE
Error creating cargo docs for pallet uniques

### ISSUE THREAD

**Issue by tapiocaboy** [paritytech/substrate#13282]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Im trying to generate a doc for uniques pallet using cargo doc and ended up with following error

```
thread 'rustc' panicked at 'no entry found for key', src/librustdoc/passes/collect_intra_doc_links.rs:781:16
stack backtrace:
   0:     0x7fb13549a810 - std::backtrace_rs::backtrace::libunwind::trace::haefc0dd0a0a62b67
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7fb13549a810 - std::backtrace_rs::backtrace::trace_unsynchronized::h231f73070a372c1c
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fb13549a810 - std::sys_common::backtrace::_print_fmt::haa15dcb5c660c296
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7fb13549a810 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfcfc314fff15b0e4
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fb1354f66ce - core::fmt::write::h2e893235039ae031
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/core/src/fmt/mod.rs:1209:17
   5:     0x7fb13548a985 - std::io::Write::write_fmt::h310687acf0f328ac
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/io/mod.rs:1682:15
   6:     0x7fb13549a5d5 - std::sys_common::backtrace::_print::h7594904cd4694801
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7fb13549a5d5 - std::sys_common::backtrace::print::hc63fb4b3dff70d7e
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7fb13549d3df - std::panicking::default_hook::{{closure}}::h6ab59645549c33df
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/panicking.rs:267:22
   9:     0x7fb13549d11a - std::panicking::default_hook::h9d471aa0319ef778
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/panicking.rs:286:9
  10:     0x7fb13549dbe8 - std::panicking::rust_panic_with_hook::hedb82473dd3f5a0d
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/panicking.rs:688:13
  11:     0x7fb13549d987 - std::panicking::begin_panic_handler::{{closure}}::h7e1d229967107c2d
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/panicking.rs:579:13
  12:     0x7fb13549acbc - std::sys_common::backtrace::__rust_end_short_backtrace::he5492151b8b5b3a1
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x7fb13549d6a2 - rust_begin_unwind
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/panicking.rs:575:5
  14:     0x7fb1354f30b3 - core::panicking::panic_fmt::hf762b822ffcd739c
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/core/src/panicking.rs:65:14
  15:     0x7fb1354f3201 - core::panicking::panic_display::h6b3e06ee369cb282
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/core/src/panicking.rs:139:5
  16:     0x7fb1354f31ab - core::panicking::panic_str::heaf5e09d79be0e66
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/core/src/panicking.rs:123:5
  17:     0x7fb1354f2e26 - core::option::expect_failed::h581bb50ba961001e
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/core/src/option.rs:1876:5
  18:     0x5573a458c9d4 - rustdoc[e6b092b8ebcfcef]::passes::collect_intra_doc_links::resolve_associated_trait_item
  19:     0x5573a458b671 - <rustdoc[e6b092b8ebcfcef]::passes::collect_intra_doc_links::LinkCollector>::resolve_associated_item
  20:     0x5573a4589711 - <rustdoc[e6b092b8ebcfcef]::passes::collect_intra_doc_links::LinkCollector>::resolve
  21:     0x5573a458e7a8 - <rustdoc[e6b092b8ebcfcef]::passes::collect_intra_doc_links::LinkCollector as rustdoc[e6b092b8ebcfcef]::visit::DocVisitor>::visit_item
  22:     0x5573a4587ec1 - rustdoc[e6b092b8ebcfcef]::passes::collect_intra_doc_links::collect_intra_doc_links
  23:     0x5573a477448d - <rustc_session[4ded857a98b896bc]::session::Session>::time::<rustdoc[e6b092b8ebcfcef]::clean::types::Crate, rustdoc[e6b092b8ebcfcef]::core::run_global_ctxt::{closure#7}>
  24:     0x5573a456d769 - rustdoc[e6b092b8ebcfcef]::core::run_global_ctxt
  25:     0x5573a4774769 - <rustc_session[4ded857a98b896bc]::session::Session>::time::<(rustdoc[e6b092b8ebcfcef]::clean::types::Crate, rustdoc[e6b092b8ebcfcef]::config::RenderOptions, rustdoc[e6b092b8ebcfcef]::formats::cache::Cache), rustdoc[e6b092b8ebcfcef]::main_args::{closure#1}::{closure#0}::{closure#1}::{closure#0}>
  26:     0x5573a47b3741 - <rustc_interface[a64a4e4385c65420]::passes::QueryContext>::enter::<rustdoc[e6b092b8ebcfcef]::main_args::{closure#1}::{closure#0}::{closure#1}, core[1359fc6eb4466362]::result::Result<(), rustc_errors[192e0008dc26bff9]::ErrorGuaranteed>>
  27:     0x5573a46d0844 - <rustc_interface[a64a4e4385c65420]::interface::Compiler>::enter::<rustdoc[e6b092b8ebcfcef]::main_args::{closure#1}::{closure#0}, core[1359fc6eb4466362]::result::Result<(), rustc_errors[192e0008dc26bff9]::ErrorGuaranteed>>
  28:     0x5573a454af23 - std[aff2bf53d717ad31]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[a64a4e4385c65420]::util::run_in_thread_pool_with_globals<rustc_interface[a64a4e4385c65420]::interface::run_compiler<core[1359fc6eb4466362]::result::Result<(), rustc_errors[192e0008dc26bff9]::ErrorGuaranteed>, rustdoc[e6b092b8ebcfcef]::main_args::{closure#1}>::{closure#0}, core[1359fc6eb4466362]::result::Result<(), rustc_errors[192e0008dc26bff9]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1359fc6eb4466362]::result::Result<(), rustc_errors[192e0008dc26bff9]::ErrorGuaranteed>>
  29:     0x5573a481f49a - <<std[aff2bf53d717ad31]::thread::Builder>::spawn_unchecked_<rustc_interface[a64a4e4385c65420]::util::run_in_thread_pool_with_globals<rustc_interface[a64a4e4385c65420]::interface::run_compiler<core[1359fc6eb4466362]::result::Result<(), rustc_errors[192e0008dc26bff9]::ErrorGuaranteed>, rustdoc[e6b092b8ebcfcef]::main_args::{closure#1}>::{closure#0}, core[1359fc6eb4466362]::result::Result<(), rustc_errors[192e0008dc26bff9]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1359fc6eb4466362]::result::Result<(), rustc_errors[192e0008dc26bff9]::ErrorGuaranteed>>::{closure#1} as core[1359fc6eb4466362]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  30:     0x7fb1354a76a3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h27f3134faf8b42b4
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/alloc/src/boxed.rs:1987:9
  31:     0x7fb1354a76a3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h46d82bf285dffad3
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/alloc/src/boxed.rs:1987:9
  32:     0x7fb1354a76a3 - std::sys::unix::thread::Thread::new::thread_start::hdb1ca70a964535d0
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/sys/unix/thread.rs:108:17
  33:     0x7fb135345609 - start_thread
                               at /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
  34:     0x7fb13526a133 - clone
                               at /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  35:                0x0 - <unknown>
error: could not document `pallet-balances`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2021 --crate-type lib --crate-name pallet_balances /home/kalanamith/.cargo/git/checkouts/substrate-7e08433d4c370a21/a3ed011/frame/balances/src/lib.rs --cap-lints allow -o /home/kalanamith/Desktop/Projects/NEOS/neos-node/target/doc --cfg 'feature="default"' --cfg 'feature="std"' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat -C metadata=593100c9b6f35e39 -L dependency=/home/kalanamith/Desktop/Projects/NEOS/neos-node/target/debug/deps --extern frame_support=/home/kalanamith/Desktop/Projects/NEOS/neos-node/target/debug/deps/libframe_support-89777a7f49b4fa72.rmeta --extern frame_system=/home/kalanamith/Desktop/Projects/NEOS/neos-node/target/debug/deps/libframe_system-2d40b22770a49794.rmeta --extern log=/home/kalanamith/Desktop/Projects/NEOS/neos-node/target/debug/deps/liblog-79050d46c61221cc.rmeta --extern codec=/home/kalanamith/Desktop/Projects/NEOS/neos-node/target/debug/deps/libparity_scale_codec-68873c04c23bf8ed.rmeta --extern scale_info=/home/kalanamith/Desktop/Projects/NEOS/neos-node/target/debug/deps/libscale_info-d60fc89473859032.rmeta --extern sp_runtime=/home/kalanamith/Desktop/Projects/NEOS/neos-node/target/debug/deps/libsp_runtime-840d047d66d42f74.rmeta --extern sp_std=/home/kalanamith/Desktop/Projects/NEOS/neos-node/target/debug/deps/libsp_std-b25a072090bd09a2.rmeta --crate-version 4.0.0-dev` (exit status: 101)
warning: build failed, waiting for other jobs to finish...
thread 'rustc' panicked at 'no entry found for key', src/librustdoc/passes/collect_intra_doc_links.rs:781:16
stack backtrace:
   0:     0x7f1b47407810 - std::backtrace_rs::backtrace::libunwind::trace::haefc0dd0a0a62b67
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7f1b47407810 - std::backtrace_rs::backtrace::trace_unsynchronized::h231f73070a372c1c
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f1b47407810 - std::sys_common::backtrace::_print_fmt::haa15dcb5c660c296
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f1b47407810 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfcfc314fff15b0e4
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f1b474636ce - core::fmt::write::h2e893235039ae031
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/core/src/fmt/mod.rs:1209:17
   5:     0x7f1b473f7985 - std::io::Write::write_fmt::h310687acf0f328ac
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/io/mod.rs:1682:15
   6:     0x7f1b474075d5 - std::sys_common::backtrace::_print::h7594904cd4694801
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f1b474075d5 - std::sys_common::backtrace::print::hc63fb4b3dff70d7e
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f1b4740a3df - std::panicking::default_hook::{{closure}}::h6ab59645549c33df
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/panicking.rs:267:22
   9:     0x7f1b4740a11a - std::panicking::default_hook::h9d471aa0319ef778
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/panicking.rs:286:9
  10:     0x7f1b4740abe8 - std::panicking::rust_panic_with_hook::hedb82473dd3f5a0d
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/panicking.rs:688:13
  11:     0x7f1b4740a987 - std::panicking::begin_panic_handler::{{closure}}::h7e1d229967107c2d
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/panicking.rs:579:13
  12:     0x7f1b47407cbc - std::sys_common::backtrace::__rust_end_short_backtrace::he5492151b8b5b3a1
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x7f1b4740a6a2 - rust_begin_unwind
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/panicking.rs:575:5
  14:     0x7f1b474600b3 - core::panicking::panic_fmt::hf762b822ffcd739c
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/core/src/panicking.rs:65:14
  15:     0x7f1b47460201 - core::panicking::panic_display::h6b3e06ee369cb282
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/core/src/panicking.rs:139:5
  16:     0x7f1b474601ab - core::panicking::panic_str::heaf5e09d79be0e66
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/core/src/panicking.rs:123:5
  17:     0x7f1b4745fe26 - core::option::expect_failed::h581bb50ba961001e
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/core/src/option.rs:1876:5
  18:     0x55a4b93fe9d4 - rustdoc[e6b092b8ebcfcef]::passes::collect_intra_doc_links::resolve_associated_trait_item
  19:     0x55a4b93fd671 - <rustdoc[e6b092b8ebcfcef]::passes::collect_intra_doc_links::LinkCollector>::resolve_associated_item
  20:     0x55a4b93fb711 - <rustdoc[e6b092b8ebcfcef]::passes::collect_intra_doc_links::LinkCollector>::resolve
  21:     0x55a4b94007a8 - <rustdoc[e6b092b8ebcfcef]::passes::collect_intra_doc_links::LinkCollector as rustdoc[e6b092b8ebcfcef]::visit::DocVisitor>::visit_item
  22:     0x55a4b93f9ec1 - rustdoc[e6b092b8ebcfcef]::passes::collect_intra_doc_links::collect_intra_doc_links
  23:     0x55a4b95e648d - <rustc_session[4ded857a98b896bc]::session::Session>::time::<rustdoc[e6b092b8ebcfcef]::clean::types::Crate, rustdoc[e6b092b8ebcfcef]::core::run_global_ctxt::{closure#7}>
  24:     0x55a4b93df769 - rustdoc[e6b092b8ebcfcef]::core::run_global_ctxt
  25:     0x55a4b95e6769 - <rustc_session[4ded857a98b896bc]::session::Session>::time::<(rustdoc[e6b092b8ebcfcef]::clean::types::Crate, rustdoc[e6b092b8ebcfcef]::config::RenderOptions, rustdoc[e6b092b8ebcfcef]::formats::cache::Cache), rustdoc[e6b092b8ebcfcef]::main_args::{closure#1}::{closure#0}::{closure#1}::{closure#0}>
  26:     0x55a4b9625741 - <rustc_interface[a64a4e4385c65420]::passes::QueryContext>::enter::<rustdoc[e6b092b8ebcfcef]::main_args::{closure#1}::{closure#0}::{closure#1}, core[1359fc6eb4466362]::result::Result<(), rustc_errors[192e0008dc26bff9]::ErrorGuaranteed>>
  27:     0x55a4b9542844 - <rustc_interface[a64a4e4385c65420]::interface::Compiler>::enter::<rustdoc[e6b092b8ebcfcef]::main_args::{closure#1}::{closure#0}, core[1359fc6eb4466362]::result::Result<(), rustc_errors[192e0008dc26bff9]::ErrorGuaranteed>>
  28:     0x55a4b93bcf23 - std[aff2bf53d717ad31]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[a64a4e4385c65420]::util::run_in_thread_pool_with_globals<rustc_interface[a64a4e4385c65420]::interface::run_compiler<core[1359fc6eb4466362]::result::Result<(), rustc_errors[192e0008dc26bff9]::ErrorGuaranteed>, rustdoc[e6b092b8ebcfcef]::main_args::{closure#1}>::{closure#0}, core[1359fc6eb4466362]::result::Result<(), rustc_errors[192e0008dc26bff9]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1359fc6eb4466362]::result::Result<(), rustc_errors[192e0008dc26bff9]::ErrorGuaranteed>>
  29:     0x55a4b969149a - <<std[aff2bf53d717ad31]::thread::Builder>::spawn_unchecked_<rustc_interface[a64a4e4385c65420]::util::run_in_thread_pool_with_globals<rustc_interface[a64a4e4385c65420]::interface::run_compiler<core[1359fc6eb4466362]::result::Result<(), rustc_errors[192e0008dc26bff9]::ErrorGuaranteed>, rustdoc[e6b092b8ebcfcef]::main_args::{closure#1}>::{closure#0}, core[1359fc6eb4466362]::result::Result<(), rustc_errors[192e0008dc26bff9]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1359fc6eb4466362]::result::Result<(), rustc_errors[192e0008dc26bff9]::ErrorGuaranteed>>::{closure#1} as core[1359fc6eb4466362]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  30:     0x7f1b474146a3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h27f3134faf8b42b4
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/alloc/src/boxed.rs:1987:9
  31:     0x7f1b474146a3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h46d82bf285dffad3
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/alloc/src/boxed.rs:1987:9
  32:     0x7f1b474146a3 - std::sys::unix::thread::Thread::new::thread_start::hdb1ca70a964535d0
                               at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/sys/unix/thread.rs:108:17
  33:     0x7f1b472b2609 - start_thread
                               at /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
  34:     0x7f1b471d7133 - clone
                               at /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  35:                0x0 - <unknown>
error: could not document `pallet-uniques`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2021 --crate-type lib --crate-name pallet_uniques /home/kalanamith/.cargo/git/checkouts/substrate-7e08433d4c370a21/a3ed011/frame/uniques/src/lib.rs --cap-lints allow -o /home/kalanamith/Desktop/Projects/NEOS/neos-node/target/doc --cfg 'feature="std"' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat -C metadata=d91d73c075361070 -L dependency=/home/kalanamith/Desktop/Projects/NEOS/neos-node/target/debug/deps --extern frame_support=/home/kalanamith/Desktop/Projects/NEOS/neos-node/target/debug/deps/libframe_support-89777a7f49b4fa72.rmeta --extern frame_system=/home/kalanamith/Desktop/Projects/NEOS/neos-node/target/debug/deps/libframe_system-2d40b22770a49794.rmeta --extern log=/home/kalanamith/Desktop/Projects/NEOS/neos-node/target/debug/deps/liblog-79050d46c61221cc.rmeta --extern codec=/home/kalanamith/Desktop/Projects/NEOS/neos-node/target/debug/deps/libparity_scale_codec-68873c04c23bf8ed.rmeta --extern scale_info=/home/kalanamith/Desktop/Projects/NEOS/neos-node/target/debug/deps/libscale_info-d60fc89473859032.rmeta --extern sp_runtime=/home/kalanamith/Desktop/Projects/NEOS/neos-node/target/debug/deps/libsp_runtime-840d047d66d42f74.rmeta --extern sp_std=/home/kalanamith/Desktop/Projects/NEOS
```

### Steps to reproduce

Make sure you have the following reference 

`pallet-uniques 					= { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.30", default-features = false }`

execute  cargo doc -p pallet-uniques`

**Comment by bkchr** [comment]
That is a rustdoc bug, nothing in our code.
