### ISSUE TITLE
`try-runtime-cli` panics on Polkadot

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#14006]
On commit Polkadot 3595684b0293439c32dfe563008958c7d0091289 ran:  

```sh
cargo b -r --bin polkadot  --features try-runtime

RUST_LOG=runtime=debug,remote-ext=trace target/release/polkadot  try-runtime --detailed-log-output --chain polkadot-dev --runtime target/release/wbuild/polkadot-runtime/polkadot_runtime.wasm on-runtime-upgrade --checks=pre-and-post live --uri wss://polkadot-try-runtime-node.parity-chains.parity.io:443
```

Truncated output:
```pre
DEBUG ThreadId(47) remote-ext: Remaining payloads: 36003 Batch request size: 2435    
 INFO main remote-ext: inserting keys progress = 3% [50000 / 1843038]    
DEBUG ThreadId(35) remote-ext: Remaining payloads: 8902 Batch request size: 11787    
DEBUG ThreadId(51) remote-ext: Batch request failed, trying again with smaller batch size. Networking or low-level protocol error: The request body was too large    
DEBUG ThreadId(51) remote-ext: Remaining payloads: 24471 Batch request size: 2679    
DEBUG ThreadId(45) remote-ext: Remaining payloads: 8902 Batch request size: 11787    
DEBUG ThreadId(36) remote-ext: Remaining payloads: 8902 Batch request size: 11787    
 INFO main remote-ext: inserting keys progress = 5% [100000 / 1843038]    
DEBUG ThreadId(32) remote-ext: Remaining payloads: 8902 Batch request size: 11787    
 INFO main remote-ext: inserting keys progress = 8% [150000 / 1843038]    
 INFO main remote-ext: inserting keys progress = 11% [200000 / 1843038]    
 INFO main remote-ext: inserting keys progress = 14% [250000 / 1843038]    
DEBUG ThreadId(48) remote-ext: Remaining payloads: 58582 Batch request size: 1215    
 INFO main remote-ext: inserting keys progress = 16% [300000 / 1843038]    

====================

Version: 0.9.41-3595684b029

   0: sp_panic_handler::set::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/boxed.rs:2001:9
      std::panicking::rust_panic_with_hook
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:696:13
   2: std::panicking::begin_panic::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: std::panicking::begin_panic
   5: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
   6: <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as core::future::future::Future>::poll
   7: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
   8: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
   9: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  10: hyper::client::client::Client<C,B>::retryably_send_request::{{closure}}
  11: <hyper::client::client::ResponseFuture as core::future::future::Future>::poll
  12: <tokio::time::timeout::Timeout<T> as core::future::future::Future>::poll
  13: <jsonrpsee_http_client::client::HttpClient as jsonrpsee_core::client::ClientT>::batch_request::{{closure}}
  14: frame_remote_externalities::Builder<B>::get_storage_data_dynamic_batch_size::{{closure}}
  15: frame_remote_externalities::Builder<B>::get_storage_data_dynamic_batch_size::{{closure}}
  16: frame_remote_externalities::Builder<B>::get_storage_data_dynamic_batch_size::{{closure}}
  17: frame_remote_externalities::Builder<B>::get_storage_data_dynamic_batch_size::{{closure}}
  18: frame_remote_externalities::Builder<B>::get_storage_data_dynamic_batch_size::{{closure}}
  19: frame_remote_externalities::Builder<B>::get_storage_data_dynamic_batch_size::{{closure}}
  20: frame_remote_externalities::Builder<B>::get_storage_data_dynamic_batch_size::{{closure}}
  21: frame_remote_externalities::Builder<B>::get_storage_data_dynamic_batch_size::{{closure}}
  22: frame_remote_externalities::Builder<B>::get_storage_data_dynamic_batch_size::{{closure}}
  23: frame_remote_externalities::Builder<B>::get_storage_data_dynamic_batch_size::{{closure}}
  24: frame_remote_externalities::Builder<B>::get_storage_data_dynamic_batch_size::{{closure}}
  25: tokio::runtime::park::CachedParkThread::block_on
  26: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
  27: tokio::runtime::runtime::Runtime::block_on
  28: std::sys_common::backtrace::__rust_begin_short_backtrace
  29: core::ops::function::FnOnce::call_once{{vtable.shim}}
  30: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/boxed.rs:1987:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/boxed.rs:1987:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys/unix/thread.rs:108:17
  31: <unknown>
  32: <unknown>


Thread '<unnamed>' panicked at 'dispatch dropped without returning error', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.20/src/client/conn.rs:329

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot/issues/new
```

Need this for testing a change. Full log from the [CI](https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2726382).

**Comment by ggwpez** [comment]
The stack is going 94 frames deep on [Westend](https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2726634). Should maybe re-write this to use a loop to prevent an overflow.

**Comment by kianenigma** [comment]
Seems like some of the parallelization added in #12537 is causing more issues than helping :(

**Comment by ggwpez** [comment]
>Seems like some of the parallelization added in https://github.com/paritytech/substrate/pull/12537 is causing more issues than helping :(

Yea not sure how much it helped with the speed, came up in the review here https://github.com/paritytech/substrate/pull/13923#discussion_r1171035228  

But the panic is not from your parallel change, but rather also #13923. We should add a test that it does not break in Polkadot :sweat_smile:

**Comment by liamaharon** [comment]
Looking into this later today 👍

**Comment by niklasad1** [comment]
https://github.com/hyperium/hyper/issues/2112

**Comment by ggwpez** [comment]
Yea this still fails, so i cant test https://github.com/paritytech/substrate/pull/13417

**Comment by niklasad1** [comment]
The same error after #14030? Then we need what I wrote in the PR

**Comment by ggwpez** [comment]
Yea looks like the same error

<details><summary>BT</summary>
<p>

```pre
2023-04-28 08:51:43.840 DEBUG ThreadId(48) remote-ext: Remaining payloads: 57361 Batch request size: 1336                                                                                                            
2023-04-28 08:51:44.178  INFO main remote-ext: inserting keys progress = 24% [450000 / 1842910]                                                                                                                      
                                                                                                                                                                                                                     
====================                                                                                                                                                                                                 
                                                                                                                                                                                                                     
Version: 0.9.41-3ec08c0ac34                                                                                                                                                                                          
                                                                                                                                                                                                                     
   0: sp_panic_handler::set::{{closure}}                                                                                                                                                                             
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call                                                                                                                                                
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/boxed.rs:2001:9                                                                                                                    
      std::panicking::rust_panic_with_hook                                                                                                                                                                           
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:696:13                                                                                                                  
   2: std::panicking::begin_panic::{{closure}}                                                                                                                                                                       
   3: std::sys_common::backtrace::__rust_end_short_backtrace                                                                                                                                                         
   4: std::panicking::begin_panic                                                                                                                                                                                    
   5: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll                                                                                                                          
   6: <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as core::future::future::Future>::poll                                                                                                                                   
   7: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll          
   8: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll                                              
   9: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll        
  10: hyper::client::client::Client<C,B>::retryably_send_request::{{closure}}                                                            
  11: <hyper::client::client::ResponseFuture as core::future::future::Future>::poll
  12: <tokio::time::timeout::Timeout<T> as core::future::future::Future>::poll                                                           
  13: <jsonrpsee_http_client::client::HttpClient as jsonrpsee_core::client::ClientT>::batch_request::{{closure}}                                                                                                                                                                  
  14: frame_remote_externalities::Builder<B>::get_storage_data_dynamic_batch_size::{{closure}}                                                                                                                       
  15: frame_remote_externalities::Builder<B>::get_storage_data_dynamic_batch_size::{{closure}}
  16: frame_remote_externalities::Builder<B>::get_storage_data_dynamic_batch_size::{{closure}}
  17: frame_remote_externalities::Builder<B>::get_storage_data_dynamic_batch_size::{{closure}}
  18: frame_remote_externalities::Builder<B>::get_storage_data_dynamic_batch_size::{{closure}}
  19: frame_remote_externalities::Builder<B>::get_storage_data_dynamic_batch_size::{{closure}}
  20: frame_remote_externalities::Builder<B>::get_storage_data_dynamic_batch_size::{{closure}}
  21: frame_remote_externalities::Builder<B>::get_storage_data_dynamic_batch_size::{{closure}}                                                                                                                       
  22: frame_remote_externalities::Builder<B>::get_storage_data_dynamic_batch_size::{{closure}}
  23: frame_remote_externalities::Builder<B>::get_storage_data_dynamic_batch_size::{{closure}}
  24: frame_remote_externalities::Builder<B>::get_storage_data_dynamic_batch_size::{{closure}}
  25: frame_remote_externalities::Builder<B>::get_storage_data_dynamic_batch_size::{{closure}}
  26: tokio::runtime::park::CachedParkThread::block_on                                        
  27: tokio::runtime::scheduler::multi_thread::MultiThread::block_on                          
  28: tokio::runtime::runtime::Runtime::block_on                                                          
  29: std::sys_common::backtrace::__rust_begin_short_backtrace                                
  30: core::ops::function::FnOnce::call_once{{vtable.shim}}                                   
  31: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once                
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/boxed.rs:1987:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once                
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/boxed.rs:1987:9
      std::sys::unix::thread::Thread::new::thread_start             
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys/unix/thread.rs:108:17                                
  32: <unknown>                                                                                           
  33: <unknown>                                                                                           
                                                                                                          
                                                                                                          
Thread '<unnamed>' panicked at 'dispatch dropped without returning error', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.20/src/client/conn.rs:329
```

</p>
</details>

Now after a re-run it does work. so probably something flaky…

**Comment by liamaharon** [comment]
Thanks for the logs. I'm going to prioritise refactoring this to remove the redundant multi-threading, which should resolve this issue.

**Comment by ggwpez** [comment]
Thanks for looking into it!  
I did run it with `TRY_RUNTIME_MAX_THREADS=1` :shrug:. Full command:  
```bash
RUST_LOG=runtime=debug,remote-ext=trace target/release/polkadot try-runtime --detailed-log-output --chain polkadot-dev --runtime target/release/wbuild/polkadot-runtime/polkadot_runtime.compact.compressed.wasm on-runtime-upgrade --checks=pre-and-post live --uri wss://polkadot-try-runtime-node.parity-chains.parity.io:443
```

**Comment by ggwpez** [comment]
It also happens with `TRY_RUNTIME_MAX_THREADS=1` :man_shrugging:

**Comment by niklasad1** [comment]
No, the problem is that the runtime that created client is closed when the background task tries to perform the RPC call ^^

The number of threads shouldn't matter
