### ISSUE TITLE
Crash on boot with 0.9.40

### ISSUE THREAD

**Issue by crystalin** [paritytech/substrate#14068]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Starting the moonbeam node (using 0.9.40) crashes from time to time at the start of the node:

Params:
```
~/projects/moonbeam/target/release/moonbeam --chain moonbeam --base-path /home/crystalin/networks/moonbeam --database paritydb --blocks-pruning archive --state-pruning archive --trie-cache-size 4096 -- --sync fast  --state-pruning 56000 --blocks-pruning 56000 --database paritydb
```

Error
```
====================

Version: 0.31.1-ba76e693b6b

   0: sp_panic_handler::set::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:2002:9
      std::panicking::rust_panic_with_hook
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:692:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:577:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:137:18
   4: rust_begin_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   5: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   6: core::panicking::panic
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:114:5
   7: cranelift_codegen::machinst::lower::Lower<I>::put_value_in_regs
   8: cranelift_codegen::isa::x64::lower::isle::<impl cranelift_codegen::isa::x64::lower::isle::generated_code::Context for cranelift_codegen::machinst::isle::IsleContext<cranelift_codegen::isa::x64::lower::isle::generated_code::MInst,cranelift_codegen::isa::x64::X64Backend>>::put_in_reg_mem_imm
   9: cranelift_codegen::isa::x64::lower::isle::generated_code::constructor_put_in_gpr_mem_imm
  10: cranelift_codegen::isa::x64::lower::isle::generated_code::constructor_lower
  11: cranelift_codegen::machinst::lower::Lower<I>::lower
  12: cranelift_codegen::machinst::compile::compile
  13: <cranelift_codegen::isa::x64::X64Backend as cranelift_codegen::isa::TargetIsa>::compile_function
  14: cranelift_codegen::context::Context::compile_stencil
  15: cranelift_codegen::context::Context::compile
  16: cranelift_codegen::context::Context::compile_and_emit
  17: wasmtime_cranelift::compiler::compile_maybe_cached
  18: <wasmtime_cranelift::compiler::Compiler as wasmtime_environ::compilation::Compiler>::compile_function
  19: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  20: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
  21: rayon::iter::plumbing::bridge_producer_consumer::helper
  22: rayon_core::join::join_context::{{closure}}
  23: rayon_core::registry::in_worker
  24: rayon::iter::plumbing::bridge_producer_consumer::helper
  25: rayon_core::job::StackJob<L,F,R>::run_inline
  26: rayon_core::join::join_context::{{closure}}
  27: rayon_core::registry::in_worker
  28: rayon::iter::plumbing::bridge_producer_consumer::helper
  29: rayon_core::join::join_context::{{closure}}
  30: rayon_core::registry::in_worker
  31: rayon::iter::plumbing::bridge_producer_consumer::helper
  32: rayon_core::job::StackJob<L,F,R>::run_inline
  33: rayon_core::join::join_context::{{closure}}
  34: rayon_core::registry::in_worker
  35: rayon::iter::plumbing::bridge_producer_consumer::helper
  36: rayon_core::job::StackJob<L,F,R>::run_inline
  37: rayon_core::join::join_context::{{closure}}
  38: rayon_core::registry::in_worker
  39: rayon::iter::plumbing::bridge_producer_consumer::helper
  40: rayon_core::join::join_context::{{closure}}
  41: rayon_core::registry::in_worker
  42: rayon::iter::plumbing::bridge_producer_consumer::helper
  43: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  44: rayon_core::registry::WorkerThread::wait_until_cold
  45: rayon_core::join::join_context::{{closure}}
  46: rayon_core::registry::in_worker
  47: rayon::iter::plumbing::bridge_producer_consumer::helper
  48: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  49: rayon_core::registry::WorkerThread::wait_until_cold
  50: rayon_core::join::join_context::{{closure}}
  51: rayon_core::registry::in_worker
  52: rayon::iter::plumbing::bridge_producer_consumer::helper
  53: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  54: rayon_core::registry::WorkerThread::wait_until_cold
  55: rayon_core::join::join_context::{{closure}}
  56: rayon_core::registry::in_worker
  57: rayon::iter::plumbing::bridge_producer_consumer::helper
  58: rayon_core::job::StackJob<L,F,R>::run_inline
  59: rayon_core::join::join_context::{{closure}}
  60: rayon_core::registry::in_worker
  61: rayon::iter::plumbing::bridge_producer_consumer::helper
  62: rayon_core::job::StackJob<L,F,R>::run_inline
  63: rayon_core::join::join_context::{{closure}}
  64: rayon_core::registry::in_worker
  65: rayon::iter::plumbing::bridge_producer_consumer::helper
  66: rayon_core::join::join_context::{{closure}}
  67: rayon_core::registry::in_worker
  68: rayon::iter::plumbing::bridge_producer_consumer::helper
  69: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  70: rayon_core::registry::WorkerThread::wait_until_cold
  71: rayon_core::join::join_context::{{closure}}
  72: rayon_core::registry::in_worker
  73: rayon::iter::plumbing::bridge_producer_consumer::helper
  74: rayon_core::join::join_context::{{closure}}
  75: rayon_core::registry::in_worker
  76: rayon::iter::plumbing::bridge_producer_consumer::helper
  77: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  78: rayon_core::registry::WorkerThread::wait_until_cold
  79: rayon_core::registry::ThreadBuilder::run
  80: std::sys_common::backtrace::__rust_begin_short_backtrace
  81: core::ops::function::FnOnce::call_once{{vtable.shim}}
  82: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:1988:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:1988:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys/unix/thread.rs:108:17
  83: start_thread
             at ./nptl/pthread_create.c:442:8
  84: clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81


Thread '<unnamed>' panicked at 'assertion failed: regs.is_valid()', /home/crystalin/.cargo/registry/src/github.com-1ecc6299db9ec823/cranelift-codegen-0.93.2/src/machinst/lower.rs:1327

This is a bug. Please report it at:

        https://github.com/PureStake/moonbeam/issues/new
```

### Steps to reproduce

build moonbeam with branch https://github.com/PureStake/moonbeam/tree/upgrade-v0.9.40 and sync a node (few days) and then launch the node from time to time.

**Comment by crystalin** [comment]
I got it to crash again, but the error is different:
```
====================

Version: 0.31.1-ba76e693b6b

   0: sp_panic_handler::set::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:2002:9
      std::panicking::rust_panic_with_hook
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:692:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:577:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:137:18
   4: rust_begin_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   5: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   6: core::panicking::panic
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:114:5
   7: cranelift_codegen::simple_gvn::do_simple_gvn
   8: cranelift_codegen::context::Context::optimize
   9: cranelift_codegen::context::Context::compile_stencil
  10: cranelift_codegen::context::Context::compile
  11: cranelift_codegen::context::Context::compile_and_emit
  12: wasmtime_cranelift::compiler::compile_maybe_cached
  13: <wasmtime_cranelift::compiler::Compiler as wasmtime_environ::compilation::Compiler>::compile_function
  14: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  15: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
  16: rayon::iter::plumbing::bridge_producer_consumer::helper
  17: rayon_core::join::join_context::{{closure}}
  18: rayon_core::registry::in_worker
  19: rayon::iter::plumbing::bridge_producer_consumer::helper
  20: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  21: rayon_core::registry::WorkerThread::wait_until_cold
  22: rayon_core::join::join_context::{{closure}}
  23: rayon_core::registry::in_worker
  24: rayon::iter::plumbing::bridge_producer_consumer::helper
  25: rayon_core::join::join_context::{{closure}}
  26: rayon_core::registry::in_worker
  27: rayon::iter::plumbing::bridge_producer_consumer::helper
  28: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  29: rayon_core::registry::WorkerThread::wait_until_cold
  30: rayon_core::join::join_context::{{closure}}
  31: rayon_core::registry::in_worker
  32: rayon::iter::plumbing::bridge_producer_consumer::helper
  33: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  34: rayon_core::registry::WorkerThread::wait_until_cold
  35: rayon_core::join::join_context::{{closure}}
  36: rayon_core::registry::in_worker
  37: rayon::iter::plumbing::bridge_producer_consumer::helper
  38: rayon_core::join::join_context::{{closure}}
  39: rayon_core::registry::in_worker
  40: rayon::iter::plumbing::bridge_producer_consumer::helper
  41: rayon_core::join::join_context::{{closure}}
  42: rayon_core::registry::in_worker
  43: rayon::iter::plumbing::bridge_producer_consumer::helper
  44: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  45: rayon_core::registry::WorkerThread::wait_until_cold
  46: rayon_core::join::join_context::{{closure}}
  47: rayon_core::registry::in_worker
  48: rayon::iter::plumbing::bridge_producer_consumer::helper
  49: rayon_core::job::StackJob<L,F,R>::run_inline
  50: rayon_core::join::join_context::{{closure}}
  51: rayon_core::registry::in_worker
  52: rayon::iter::plumbing::bridge_producer_consumer::helper
  53: rayon_core::job::StackJob<L,F,R>::run_inline
  54: rayon_core::join::join_context::{{closure}}
  55: rayon_core::registry::in_worker
  56: rayon::iter::plumbing::bridge_producer_consumer::helper
  57: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  58: rayon_core::registry::WorkerThread::wait_until_cold
  59: rayon_core::registry::ThreadBuilder::run
  60: std::sys_common::backtrace::__rust_begin_short_backtrace
  61: core::ops::function::FnOnce::call_once{{vtable.shim}}
  62: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:1988:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:1988:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys/unix/thread.rs:108:17
  63: start_thread
             at ./nptl/pthread_create.c:442:8
  64: clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81


Thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/crystalin/.cargo/registry/src/github.com-1ecc6299db9ec823/cranelift-codegen-0.93.2/src/simple_gvn.rs:135
```

**Comment by bkchr** [comment]
This is an issue in wasmtime. Could you please report this upstream?

**Comment by bkchr** [comment]
Closing as this seems to be an upstream issue.
