### ISSUE TITLE
Regression: Setting --in-peers and --out-peers to 0 panics on 0.9.43

### ISSUE THREAD

**Issue by crystalin** [paritytech/substrate#14569]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

When using `--in-peers 0 --out-peers 0` (in my case on Moonbeam), it panics with:
```
   0: sp_panic_handler::set::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/boxed.rs:2001:9
      std::panicking::rust_panic_with_hook
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:696:13
   2: std::panicking::begin_panic::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: std::panicking::begin_panic
   5: async_channel::bounded
   6: sc_network_sync::state_request_handler::StateRequestHandler<B,Client>::new
   7: sc_service::builder::build_network
   8: moonbeam_service::start_node_impl::{{closure}}
   9: tokio::runtime::park::CachedParkThread::block_on
  10: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
  11: tokio::runtime::runtime::Runtime::block_on
  12: sc_cli::runner::Runner<C>::run_node_until_exit
  13: moonbeam_cli::command::run
  14: moonbeam::main
  15: std::sys_common::backtrace::__rust_begin_short_backtrace
  16: std::rt::lang_start::{{closure}}
  17: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:287:13
      std::panicking::try::do_call
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
      std::panicking::try
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
      std::panic::catch_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
      std::panicking::try
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
      std::panic::catch_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
      std::rt::lang_start_internal
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:20
  18: main
  19: <unknown>
  20: __libc_start_main
  21: _start


Thread 'main' panicked at 'capacity cannot be zero', /home/crystalin/.cargo/registry/src/github.com-1ecc6299db9ec823/async-channel-1.8.0/src/lib.rs:110
```

### Steps to reproduce

`node --in-peers 0 --out-peers 0`

(on v0.9.43 substrate)

**Comment by crystalin** [comment]
A workaround for those who want to run a node without syncing, you can use `--reserved-only`

**Comment by altonen** [comment]
@dmitry-markin 

It looks like this is related to the recent change to use `async-channel` in the request-response code. I think some kind of sanity check needs to be introduced for the zero peers case.
