### ISSUE TITLE
Panic on restart

### ISSUE THREAD

**Issue by arkpar** [paritytech/substrate#1556]
Authorities panic on restart occasionally. A re-sync is required.

```
   6:     0x5648fd98501e - std::panicking::begin_panic_fmt::h11fdc4cc73917110
                        at src/libstd/panicking.rs:353
   7:     0x5648fcc084f4 - <substrate_client::client::Client<B, E, Block, RA>>::best_containing::h26fd1fc2011c9726
   8:     0x5648fcc444a1 - <substrate_finality_grandpa::GrandpaBlockImport<B, E, Block, RA, PRA> as substrate_consensus_common::block_import::BlockImport<Block>>::on_start::h7dde0534af552587
   9:     0x5648fcf45658 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd34448c7eb13c8bb
  10:     0x5648fcf45ec4 - std::panicking::try::do_call::h8eb8460746f943e3
  11:     0x5648fd996289 - __rust_maybe_catch_panic
                        at src/libpanic_unwind/lib.rs:102
  12:     0x5648fcb384e5 - <F as alloc::boxed::FnBox<A>>::call_box::hec5da594425da52e
  13:     0x5648fd989e6d - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::hece536cf07b94f8d
                        at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/liballoc/boxed.rs:683
                         - std::sys_common::thread::start_thread::h9605a7df0f911844
                        at src/libstd/sys_common/thread.rs:24
                         - std::sys::unix::thread::Thread::new::thread_start::hca8e72c41fa9d291
                        at src/libstd/sys/unix/thread.rs:90
  14:     0x7fdf3e7646b9 - start_thread
  15:     0x7fdf3e28441c - clone
  16:                0x0 - <unknown>

Thread 'ImportQueue' panicked at 'internal error: entered unreachable code: this is a bug. `target_hash` is in blockchain but wasn't found following all leaves backwards', /builds/parity/polkadot/.cargo/git/checkouts/substrate-7e08433d4c370a21/8ee9727/core/client/src/client.rs:976
```

**Comment by rphmeier** [comment]
#1559 made this less of an issue.
