### ISSUE TITLE
Bug :- Latest Substrate master getting crashed with DB key error

### ISSUE THREAD

**Issue by Kalanamith** [paritytech/substrate#1618]
The latest substrate master getting crashed after producing 4 blocks

```
Thread 'tokio-runtime-worker-0' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Database missing expected key: 0x20c0170e84c9e9645ed644a4b77fa9385f3acf8089ca2ca6eb2ead21852396d2"', src/libcore/result.rs:997

This is a bug. Please report it at:

    https://github.com/paritytech/polkadot/issues/new
```

Complete log

```
0: substrate_cli::panic_hook::panic_hook::hf9dbaabc92834d6b (0x100e4b917)
             at /Users/developer/Documents/substrate/substrate/substrate/core/cli/src/panic_hook.rs:51
   1: core::ops::function::Fn::call::h2be76bf5b8bb92e0 (0x100e46268)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libcore/ops/function.rs:69
   2: std::panicking::rust_panic_with_hook::h148886a5853f7b8e (0x10327c5f6)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/panicking.rs:482
   3: std::panicking::continue_panic_fmt::he3814e809e7e97d7 (0x10327c04c)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/panicking.rs:385
   4: _rust_begin_unwind (0x10327bf38)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/panicking.rs:312
   5: core::panicking::panic_fmt::h151984404fe3a86d (0x103295781)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libcore/panicking.rs:85
   6: core::result::unwrap_failed::hcb1dd39d314e23b8 (0x100e3435e)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libcore/macros.rs:16
   7: <core::result::Result<T, E>>::expect::h2f422c6b0804b12f (0x10072a219)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libcore/result.rs:825
   8: <substrate_state_machine::ext::Ext<'a, H, B, T> as substrate_state_machine::Externalities<H>>::storage::{{closure}}::h203b5ad780904466 (0x1002c9d53)
             at /Users/developer/Documents/substrate/substrate/substrate/core/state-machine/src/ext.rs:184
   9: <core::option::Option<T>>::unwrap_or_else::had41b9b8f4c67bcb (0x100874f8c)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libcore/option.rs:386
  10: <substrate_state_machine::ext::Ext<'a, H, B, T> as substrate_state_machine::Externalities<H>>::storage::h246978786906ff3d (0x1002c9bde)
             at /Users/developer/Documents/substrate/substrate/substrate/core/state-machine/src/ext.rs:183
  11: <substrate_executor::wasm_executor::FunctionExecutor<'e, E> as wasmi::host::Externals>::invoke_index::{{closure}}::h79fea5193a61dbb9 (0x1007d8a7d)
             at /Users/developer/Documents/substrate/substrate/substrate/core/executor/src/wasm_executor.rs:314
  12: <substrate_executor::wasm_executor::FunctionExecutor<'e, E> as wasmi::host::Externals>::invoke_index::hf2e41f9fffcfa4cd (0x1007bf4c1)
             at /Users/developer/Documents/substrate/substrate/substrate/core/executor/src/wasm_utils.rs:131
  13: wasmi::func::FuncInstance::invoke::h4f1ceac6af795a61 (0x10090007b)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmi-0.4.3/src/func.rs:149
  14: wasmi::runner::Interpreter::run_interpreter_loop::ha88597b6a79efe1a (0x1006bfdce)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmi-0.4.3/src/runner.rs:304
  15: wasmi::runner::Interpreter::start_execution::h7888951932ccd714 (0x1006bbe65)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmi-0.4.3/src/runner.rs:212
  16: wasmi::func::FuncInstance::invoke::h4f1ceac6af795a61 (0x1009000f0)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmi-0.4.3/src/func.rs:144
  17: wasmi::module::ModuleInstance::invoke_export::hed9d55d1592bda11 (0x100b68b64)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmi-0.4.3/src/module.rs:635
  18: substrate_executor::wasm_executor::WasmExecutor::call_in_wasm_module::hb381851c269ef10f (0x1007f84a0)
             at /Users/developer/Documents/substrate/substrate/substrate/core/executor/src/wasm_executor.rs:689
  19: <substrate_executor::native_executor::NativeExecutor<D> as substrate_state_machine::CodeExecutor<substrate_primitives::hasher::blake2::Blake2Hasher>>::call::{{closure}}::hc780ed0d06b1d81f (0x1006a2341)
             at /Users/developer/Documents/substrate/substrate/substrate/core/executor/src/native_executor.rs:229
  20: <std::thread::local::LocalKey<T>>::try_with::ha591dd36b191981b (0x100b404f3)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/thread/local.rs:296
  21: <std::thread::local::LocalKey<T>>::with::h2da634e2744b791e (0x100b38b58)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/thread/local.rs:242
  22: <substrate_executor::native_executor::NativeExecutor<D> as substrate_state_machine::CodeExecutor<substrate_primitives::hasher::blake2::Blake2Hasher>>::call::h0686e5c36b6607c4 (0x10069320c)
             at /Users/developer/Documents/substrate/substrate/substrate/core/executor/src/native_executor.rs:198
  23: substrate_state_machine::execute_using_consensus_failure_handler::hae95f5edf4db3b00 (0x10027ef63)
             at /Users/developer/Documents/substrate/substrate/substrate/core/state-machine/src/lib.rs:379
  24: <substrate_client::call_executor::LocalCallExecutor<B, E> as substrate_client::call_executor::CallExecutor<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call::h1c178424e0d4e46f (0x10046cc64)
             at /Users/developer/Documents/substrate/substrate/substrate/core/client/src/call_executor.rs:227
  25: <substrate_client::client::Client<B, E, Block, RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at::hdb7bba3248b7a773 (0x100928e3e)
             at /Users/developer/Documents/substrate/substrate/substrate/core/client/src/client.rs:1276
  26: <node_runtime::RuntimeApiImpl<C>>::call_api_at::hf2be286c4978562f (0x10080c146)
             at /Users/developer/Documents/substrate/substrate/substrate/node/runtime/src/lib.rs:236
  27: <node_runtime::RuntimeApiImpl<RuntimeApiImplCall> as substrate_client::block_builder::api::BlockBuilder<<node_runtime::Runtime as sr_primitives::traits::GetNodeBlockType>::NodeBlock>>::finalise_block::hb36e3032a3fa40a2 (0x1007fab30)
             at /Users/developer/Documents/substrate/substrate/substrate/node/runtime/src/lib.rs:236
  28: <substrate_client::block_builder::block_builder::BlockBuilder<'a, Block, A>>::bake::hc1a0cb66e12ca032 (0x100304f93)
             at /Users/developer/Documents/substrate/substrate/substrate/core/client/src/block_builder/block_builder.rs:103
  29: <substrate_client::client::Client<B, E, Block, RA> as substrate_basic_authorship::basic_authorship::AuthoringApi>::build_block::h6ddc0bd86279c5f3 (0x10092d9f4)
             at /Users/developer/Documents/substrate/substrate/substrate/core/basic-authorship/src/basic_authorship.rs:108
  30: <substrate_basic_authorship::basic_authorship::Proposer<Block, C, A>>::propose_with::hc8743a5c15032e3d (0x100b5bafc)
             at /Users/developer/Documents/substrate/substrate/substrate/core/basic-authorship/src/basic_authorship.rs:191
  31: <substrate_basic_authorship::basic_authorship::Proposer<Block, C, A> as substrate_consensus_common::Proposer<<C as substrate_basic_authorship::basic_authorship::AuthoringApi>::Block>>::propose::hde989e988c141901 (0x100b5b9f6)
             at /Users/developer/Documents/substrate/substrate/substrate/core/basic-authorship/src/basic_authorship.rs:175
  32: substrate_consensus_aura::start_aura::{{closure}}::{{closure}}::hb797d127b8a6ef3d (0x1005a7094)
             at /Users/developer/Documents/substrate/substrate/substrate/core/consensus/aura/src/lib.rs:297
  33: <futures::stream::for_each::ForEach<S, F, U> as futures::future::Future>::poll::hfe8858fff56138ea (0x1008141f9)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/stream/for_each.rs:46
  34: futures::future::catch_unwind::<impl futures::future::Future for std::panic::AssertUnwindSafe<F>>::poll::h7fd1ca06eda2e8c2 (0x100a8ea44)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/catch_unwind.rs:49
  35: <futures::future::catch_unwind::CatchUnwind<F> as futures::future::Future>::poll::{{closure}}::hc8a3d6ce48b8f17c (0x1009257ea)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/catch_unwind.rs:32
  36: std::panicking::try::do_call::he5120b731c48d76b (0x100a7b339)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/panicking.rs:297
  37: ___rust_maybe_catch_panic (0x10328170e)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libpanic_unwind/lib.rs:92
  38: std::panicking::try::h616ac240f4c773dc (0x100a79664)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/panicking.rs:276
  39: std::panic::catch_unwind::hf6e02d1a73f6ca1e (0x100a8ea1c)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/panic.rs:388
  40: <futures::future::catch_unwind::CatchUnwind<F> as futures::future::Future>::poll::he91cdaf06dc9f85f (0x100925334)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/catch_unwind.rs:32
  41: <futures::future::chain::Chain<A, B, C>>::poll::h8185f5cc2679cadc (0x100b52eb2)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/chain.rs:26
  42: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll::hf04d994453257ac3 (0x100585f54)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/then.rs:32
  43: <futures::future::loop_fn::LoopFn<A, F> as futures::future::Future>::poll::h0e1b7fb35c9cfd78 (0x1004aaa50)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/loop_fn.rs:93
  44: <futures::future::select::Select<A, B> as futures::future::Future>::poll::hc75ff5ff35c6d770 (0x100b1ce00)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/select.rs:48
  45: <futures::future::chain::Chain<A, B, C>>::poll::h99c6ea679a83f76e (0x100b546a8)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/chain.rs:26
  46: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll::hea83c0e81f66a7c5 (0x100585f24)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/then.rs:32
  47: <alloc::boxed::Box<F> as futures::future::Future>::poll::h19029f3e3e012ba9 (0x102e51cb4)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/mod.rs:113
  48: <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}::h3a303873e2886650 (0x102d90e14)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:326
  49: <futures::task_impl::Spawn<T>>::enter::{{closure}}::hdddfc7021191f5a3 (0x102d910bf)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:396
  50: futures::task_impl::std::set::hdb798dca35e43415 (0x102d87f46)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/std/mod.rs:78
  51: <futures::task_impl::Spawn<T>>::enter::h6d6ad9d633d13c32 (0x102d90f47)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:396
  52: <futures::task_impl::Spawn<T>>::poll_fn_notify::h904a95a7a0842357 (0x102d90c47)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:288
  53: <futures::task_impl::Spawn<T>>::poll_future_notify::h0860b06bdea9bcdb (0x102d90da4)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:326
  54: tokio_threadpool::task::Task::run::{{closure}}::h2cbc554b1f116e81 (0x102d81f4c)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.10/src/task/mod.rs:122
  55: core::ops::function::FnOnce::call_once::h194dd118867d2985 (0x102d7c09c)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libcore/ops/function.rs:231
  56: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h221dfa33a26b9a25 (0x102d90387)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/panic.rs:309
  57: std::panicking::try::do_call::h7470a6e43bad585a (0x102d90aa4)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/panicking.rs:297
  58: ___rust_maybe_catch_panic (0x10328170e)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libpanic_unwind/lib.rs:92
  59: std::panicking::try::h34f990f8960131d0 (0x102d908b2)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/panicking.rs:276
  60: std::panic::catch_unwind::h5df5ad1c99d29826 (0x102d907de)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/panic.rs:388
  61: tokio_threadpool::task::Task::run::h0bb1ef14fe320412 (0x102d81a0e)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.10/src/task/mod.rs:108
  62: tokio_threadpool::worker::Worker::run_task2::hedca61aaeeae952f (0x102db12b0)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.10/src/worker/mod.rs:555
  63: tokio_threadpool::worker::Worker::run_task::hd8749cbc0ae86c0f (0x102db0dd1)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.10/src/worker/mod.rs:454
  64: tokio_threadpool::worker::Worker::try_steal_task::h68da4ec5ebc73b4b (0x102db0a99)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.10/src/worker/mod.rs:421
  65: tokio_threadpool::worker::Worker::try_run_task::h33d5a4e9577fa821 (0x102db012b)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.10/src/worker/mod.rs:306
  66: tokio_threadpool::worker::Worker::run::h6355e48fcfc9eef6 (0x102daff9a)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.10/src/worker/mod.rs:246
  67: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}::hf851c68c00098f67 (0x102d3039b)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.14/src/runtime/threadpool/builder.rs:340
  68: tokio_timer::timer::handle::with_default::{{closure}}::h877680d0f9ad0834 (0x102d30779)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.8/src/timer/handle.rs:94
  69: <std::thread::local::LocalKey<T>>::try_with::ha5688988406326d9 (0x102d31ef1)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/thread/local.rs:296
  70: <std::thread::local::LocalKey<T>>::with::h2ecf2f01b1d37e96 (0x102d315bf)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/thread/local.rs:242
  71: tokio_timer::timer::handle::with_default::h45fd334cc8983262 (0x102d3060b)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.8/src/timer/handle.rs:81
  72: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::hb3f33771047d59d5 (0x102d303f5)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.14/src/runtime/threadpool/builder.rs:339
  73: tokio_timer::clock::clock::with_default::{{closure}}::h1c27ccc129b3d025 (0x102d38965)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.8/src/clock/clock.rs:136
  74: <std::thread::local::LocalKey<T>>::try_with::h2ccc090cfeec047b (0x102d31abc)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/thread/local.rs:296
  75: <std::thread::local::LocalKey<T>>::with::h821fc4ed787dc82b (0x102d31628)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/thread/local.rs:242
  76: tokio_timer::clock::clock::with_default::ha494fc06cb3600e3 (0x102d38879)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.8/src/clock/clock.rs:119
  77: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::h3c75aa12e75a45f5 (0x102d30439)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.14/src/runtime/threadpool/builder.rs:338
  78: tokio_reactor::with_default::{{closure}}::h043cc2f7b7227192 (0x102d30ac4)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.8/src/lib.rs:229
  79: <std::thread::local::LocalKey<T>>::try_with::h6694d1c9a458ae36 (0x102d31cf1)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/thread/local.rs:296
  80: <std::thread::local::LocalKey<T>>::with::h8fe71696bc6cc650 (0x102d31688)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/thread/local.rs:242
  81: tokio_reactor::with_default::ha2aa5328064f0e22 (0x102d308be)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.8/src/lib.rs:212
  82: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h520fe744583fdf17 (0x102d304ba)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.14/src/runtime/threadpool/builder.rs:337
  83: tokio_threadpool::callback::Callback::call::h5411b992c15c3623 (0x102d80cc5)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.10/src/callback.rs:21
  84: tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}}::h3af9a9d4b2003cb3 (0x102dafc95)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.10/src/worker/mod.rs:132
  85: tokio_executor::global::with_default::{{closure}}::he31dfb59fbfd5a2b (0x102dab7d2)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.6/src/global.rs:192
  86: <std::thread::local::LocalKey<T>>::try_with::h2392b0a3a05dcfdd (0x102d9804d)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/thread/local.rs:296
  87: <std::thread::local::LocalKey<T>>::with::h5e027562a7f6af8b (0x102d9751f)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/thread/local.rs:242
  88: tokio_executor::global::with_default::he1656f499815c9d9 (0x102dab6ce)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.6/src/global.rs:162
  89: tokio_threadpool::worker::Worker::do_run::{{closure}}::h40f71151eaf9e647 (0x102dafd36)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.10/src/worker/mod.rs:130
  90: <std::thread::local::LocalKey<T>>::try_with::h6cccf6c1eac45a50 (0x102d98602)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/thread/local.rs:296
  91: <std::thread::local::LocalKey<T>>::with::hf97bd58e4fc6ac78 (0x102d9766c)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/thread/local.rs:242
  92: tokio_threadpool::worker::Worker::do_run::hcead9ce6aadfe063 (0x102dafb86)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.10/src/worker/mod.rs:121
  93: tokio_threadpool::pool::Pool::spawn_thread::{{closure}}::h44bf1ce88e338d25 (0x102db5389)
             at /Users/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.10/src/pool/mod.rs:354
  94: std::sys_common::backtrace::__rust_begin_short_backtrace::h586890a3b99321b7 (0x102d9079f)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/sys_common/backtrace.rs:135
  95: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hf561044934d72960 (0x102d7b88f)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/thread/mod.rs:469
  96: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hd73bf01c7d3897b1 (0x102d903cf)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/panic.rs:309
  97: std::panicking::try::do_call::h924c2df56f58fa59 (0x102d90b1c)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/panicking.rs:297
  98: ___rust_maybe_catch_panic (0x10328170e)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libpanic_unwind/lib.rs:92
  99: std::panicking::try::hc8e261f9356fcb24 (0x102d909b4)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/panicking.rs:276
 100: std::panic::catch_unwind::h7666acec520e2e06 (0x102d9081f)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/panic.rs:388
 101: std::thread::Builder::spawn_unchecked::{{closure}}::ha51e492c0d674367 (0x102d7b6dd)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/thread/mod.rs:468
 102: <F as alloc::boxed::FnBox<A>>::call_box::hb1ede90331bca290 (0x102d809a7)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/liballoc/boxed.rs:734
 103: std::sys::unix::thread::Thread::new::thread_start::hd18efd5f907321e2 (0x103280cab)
             at /rustc/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/libstd/sys_common/thread.rs:14
 104: __pthread_body (0x7fff7f699304)
 105: __pthread_start (0x7fff7f69c26e)
```

**Comment by rphmeier** [comment]
Seems like a case of storage not being written correctly to DB. Maybe related to #1616

**Comment by gavofyork** [comment]
Yup.
