### ISSUE TITLE
Build of librocksdb-sys v5.14.3 fails on Windows 10, VS2017

### ISSUE THREAD

**Issue by Qubeo** [paritytech/substrate#1681]
Hi, when building on Win10, I'm repeatedly getting the following error:

```
Compiling librocksdb-sys v5.14.3
error: failed to run custom build command for `librocksdb-sys v5.14.3`
process didn't exit successfully: `D:\prog\rust\substrate\target\debug\build\librocksdb-sys-44dede36929ce51e\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at '

Internal error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\lib.exe" "/OUT:D:\\prog\\rust\\substrate\\target\\debug\\build\\librocksdb-sys-b83d57c6961cd33b\\out\\librocksdb.a" "/nologo" "@D:\\prog\\rust\\substrate\\target\\debug\\build\\librocksdb-sys-b83d57c6961cd33b\\out\\librocksdb.a.args" with args "lib.exe" did not execute successfully (status code exit code: 1180).

', C:\Users\My PC\.cargo\registry\src\github.com-1ecc6299db9ec823\cc-1.0.26\src\lib.rs:2295:5
```

Rust: rustc 1.34.0-nightly
Last master branch update of 04.02.2019.

Where do you think might be the problem?

**Comment by gnunicorn** [comment]
could you run the build with `--verbose` so we can see the actual error produces by librocksdb. I suspect you are missing some libsrocksdb dependency...

**Comment by Qubeo** [comment]
Thanks for the answers. I'll try building the standalone version.

This is the --verbose output:

error: failed to run custom build command for `librocksdb-sys v5.14.3`
process didn't exit successfully: `D:\prog\rust\substrate\target\debug\build\librocksdb-sys-44dede36929ce51e\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at '
```

Internal error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\cl.exe" "/nologo" "/MD" "/Z7" "/I" "rocksdb/include/" "/I" "rocksdb/" "/I" "rocksdb/third-party/gtest-1.7.0/fused-src/" "/I" "snappy/" "/I" "lz4/lib/" "/I" "zstd/lib/" "/I" "zstd/lib/dictBuilder/" "/I" "zlib/" "/I" "bzip2/" "/I" "."
"/W4" "-EHsc" "/DSNAPPY=1" "/DLZ4=1" "/DZSTD=1" "/DZLIB=1" "/DBZIP2=1" "/DNDEBUG=1" "/DOS_WIN=1" "/FoD:\\prog\\rust\\substrate\\target\\debug\\build\\librocksdb-sys-b83d57c6961cd33b\\out\\rocksdb/table\\meta_blocks.o" "/c" "rocksdb/table/meta_blocks.cc" with args "cl.exe" did not execute successfully (status code exit code: 2).

', C:\Users\My PC\.cargo\registry\src\github.com-1ecc6299db9ec823\cc-1.0.26\src\lib.rs:2295:5
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/f6fac4225f4ea4881e9146f0a14f2cd36b8ac22f\/src\libstd\sys\windows\backtrace\mod.rs:94
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/f6fac4225f4ea4881e9146f0a14f2cd36b8ac22f\/src\libstd\sys\windows\backtrace\mod.rs:81
   2: std::sys_common::backtrace::_print
             at /rustc/f6fac4225f4ea4881e9146f0a14f2cd36b8ac22f\/src\libstd\sys_common\backtrace.rs:70
   3: std::sys_common::backtrace::print
             at /rustc/f6fac4225f4ea4881e9146f0a14f2cd36b8ac22f\/src\libstd\sys_common\backtrace.rs:58
   4: std::panicking::default_hook::{{closure}}
             at /rustc/f6fac4225f4ea4881e9146f0a14f2cd36b8ac22f\/src\libstd\panicking.rs:200
   5: std::panicking::default_hook
             at /rustc/f6fac4225f4ea4881e9146f0a14f2cd36b8ac22f\/src\libstd\panicking.rs:215
   6: std::panicking::rust_panic_with_hook
             at /rustc/f6fac4225f4ea4881e9146f0a14f2cd36b8ac22f\/src\libstd\panicking.rs:478
   7: std::panicking::continue_panic_fmt
             at /rustc/f6fac4225f4ea4881e9146f0a14f2cd36b8ac22f\/src\libstd\panicking.rs:385
   8: std::panicking::begin_panic_fmt
             at /rustc/f6fac4225f4ea4881e9146f0a14f2cd36b8ac22f\/src\libstd\panicking.rs:340
   9: cc::fail
             at C:\Users\My PC\.cargo\registry\src\github.com-1ecc6299db9ec823\cc-1.0.26\src\lib.rs:2295
  10: cc::Build::compile
             at C:\Users\My PC\.cargo\registry\src\github.com-1ecc6299db9ec823\cc-1.0.26\src\lib.rs:950
  11: build_script_build::build_rocksdb
             at .\build.rs:150
  12: build_script_build::main
             at .\build.rs:290
  13: std::rt::lang_start::{{closure}}<()>
             at /rustc/f6fac4225f4ea4881e9146f0a14f2cd36b8ac22f\src\libstd\rt.rs:64
  14: std::rt::lang_start_internal::{{closure}}
             at /rustc/f6fac4225f4ea4881e9146f0a14f2cd36b8ac22f\/src\libstd\rt.rs:49
  15: std::panicking::try::do_call<closure,i32>
             at /rustc/f6fac4225f4ea4881e9146f0a14f2cd36b8ac22f\/src\libstd\panicking.rs:297
  16: panic_unwind::__rust_maybe_catch_panic
             at /rustc/f6fac4225f4ea4881e9146f0a14f2cd36b8ac22f\/src\libpanic_unwind\lib.rs:92
  17: std::panicking::try
             at /rustc/f6fac4225f4ea4881e9146f0a14f2cd36b8ac22f\/src\libstd\panicking.rs:276
  18: std::panic::catch_unwind
             at /rustc/f6fac4225f4ea4881e9146f0a14f2cd36b8ac22f\/src\libstd\panic.rs:388
  19: std::rt::lang_start_internal
             at /rustc/f6fac4225f4ea4881e9146f0a14f2cd36b8ac22f\/src\libstd\rt.rs:48
  20: std::rt::lang_start<()>
             at /rustc/f6fac4225f4ea4881e9146f0a14f2cd36b8ac22f\src\libstd\rt.rs:64
  21: main
  22: invoke_main
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  23: __scrt_common_main_seh
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  24: BaseThreadInitThunk
  25: RtlUserThreadStart
```

**Comment by gnunicorn** [comment]
Hmm... odd. No obvious dependency problem in librocksdb-sys and their released version [build on windows successfully](https://travis-ci.org/rust-rocksdb/rust-rocksdb/jobs/477912579) (and travis windows system have [no obvious other dependencies installed](https://docs.travis-ci.com/user/reference/windows/#pre-installed-chocolatey-packages)). Doesn't appear to be any specific substrate problem either.

I guess the only way forward would be for you to pull the [rust-rocksdb repo](https://github.com/rust-rocksdb/rust-rocksdb) and build that directly (`cargo build`) and if the error still persists report the error there.

**Comment by bkchr** [comment]
@gnunicorn he has already done this ;)

**Comment by arkpar** [comment]
@Qubeo please try again with `-vv`. This should give a more detailed error.
