### ISSUE TITLE
Network misbehaviour from peer resulting in panic core/network-p2p

### ISSUE THREAD

**Issue by mnaamani** [paritytech/substrate#1855]
Running `substrate 0.10.0-1ca4cc0a-x86_64-macos`
on `Dried Danta`

```
2019-02-22 22:56:54 Network misbehaviour from PeerId(QmePFHyN1kNNdKCQ77Yxdf2bB4dnt2eummzAowoPuVc1y8) with protocol [115, 117, 112]: Upgrade(Select(NoProtocolFound))
2019-02-22 22:56:57 Syncing  8.8 bps, target=#32212 (4 peers), best: #417 (0xdae8…5d94), finalized #0 (0xfc0f…8777), ⬇ 3.3kiB/s ⬆ 2.1kiB/s

====================

stack backtrace:
   0: substrate_panic_handler::panic_hook::h70084b292c45b2c3 (0x10cb7d315)
             at /Users/mokhtar/parity/substrate/core/panic-handler/src/lib.rs:82
   1: substrate_panic_handler::set::{{closure}}::h4dcb908a375d5a0b (0x10cb7bae6)
             at /Users/mokhtar/parity/substrate/core/panic-handler/src/lib.rs:31
   2: std::panicking::rust_panic_with_hook::h3fe6a67edb032589 (0x10cf59461)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/panicking.rs:495
   3: std::panicking::begin_panic::hc2a3d67d0fbf4e0a (0x10ccfe297)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/panicking.rs:425
   4: substrate_network_libp2p::custom_proto::topology::NetTopology::set_unreachable::hecccf833cad9f473 (0x10b15c948)
             at /Users/mokhtar/parity/substrate/core/network-libp2p/src/custom_proto/topology.rs:418
   5: <substrate_network_libp2p::custom_proto::behaviour::CustomProtos<TMessage, TSubstream> as libp2p_core::swarm::NetworkBehaviour>::inject_dial_failure::h9970eb33641f4a72 (0x10a177de9)
             at /Users/mokhtar/parity/substrate/core/network-libp2p/src/custom_proto/behaviour.rs:502
   6: <substrate_network_libp2p::behaviour::Behaviour<TMessage, TSubstream> as libp2p_core::swarm::NetworkBehaviour>::inject_dial_failure::haa90e068b9d9caf6 (0x10a35b24f)
             at /Users/mokhtar/parity/substrate/core/network-libp2p/src/behaviour.rs:34
   7: <libp2p_core::swarm::Swarm<TTransport, TBehaviour> as futures::stream::Stream>::poll::h2be1d346d1dcc78d (0x10a45b182)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-core-0.4.0/src/swarm.rs:280
   8: <substrate_network_libp2p::service_task::Service<TMessage>>::poll_swarm::hde7d45b18641902f (0x10a379d8e)
             at /Users/mokhtar/parity/substrate/core/network-libp2p/src/service_task.rs:381
   9: <substrate_network_libp2p::service_task::Service<TMessage> as futures::stream::Stream>::poll::hb6f56c4cc9b54365 (0x10a3767ff)
             at /Users/mokhtar/parity/substrate/core/network-libp2p/src/service_task.rs:478
  10: substrate_network::service::run_thread::{{closure}}::hfac3540ab644088a (0x10a43c05c)
             at /Users/mokhtar/parity/substrate/core/network/src/service.rs:540
  11: <futures::stream::poll_fn::PollFn<F> as futures::stream::Stream>::poll::hde3ffc16a9d0088c (0x10a0c514b)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/stream/poll_fn.rs:47
  12: <futures::stream::for_each::ForEach<S, F, U> as futures::future::Future>::poll::hb1e49effe8005e78 (0x10a592d10)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/stream/for_each.rs:45
  13: <alloc::boxed::Box<F> as futures::future::Future>::poll::hf29bb27b75bf28f4 (0x10a06407b)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/mod.rs:113
  14: <futures::future::select_all::SelectAll<A> as futures::future::Future>::poll::{{closure}}::h202007525e6169b7 (0x109d28962)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/select_all.rs:53
  15: <core::iter::FilterMap<I, F> as core::iter::iterator::Iterator>::next::hf200da58b5c9fc0b (0x10a1d8937)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/iter/mod.rs:1574
  16: <futures::future::select_all::SelectAll<A> as futures::future::Future>::poll::h02358fddd95a4b96 (0x109d28469)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/select_all.rs:52
  17: <futures::future::chain::Chain<A, B, C>>::poll::hd3ca123c6639fffc (0x109d75ba1)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/chain.rs:26
  18: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::h9cd2f96df19d1a68 (0x10a179dfb)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/and_then.rs:32
  19: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll::h32588d8fc44be133 (0x10a1e664c)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/map_err.rs:30
  20: <futures::future::select::Select<A, B> as futures::future::Future>::poll::hba7da791a9d237cd (0x10a76d531)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/select.rs:48
  21: <futures::future::map::Map<A, F> as futures::future::Future>::poll::h837469644eb9a97d (0x109c0f610)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/map.rs:30
  22: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll::h50e80bafac5ceb23 (0x10a1e73fc)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/map_err.rs:30
  23: <futures::future::chain::Chain<A, B, C>>::poll::h7459b1a53c8f5272 (0x109d6aa12)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/chain.rs:26
  24: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll::h7c83dfce77ca5f8a (0x10a357b34)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/then.rs:32
  25: <alloc::boxed::Box<F> as futures::future::Future>::poll::h22feb737d8db31ed (0x10caba3e4)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/mod.rs:113
  26: <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}::hd9ab110c668f9a73 (0x10ca02a94)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:326
  27: <futures::task_impl::Spawn<T>>::enter::{{closure}}::hb7a95ea7e35999b3 (0x10ca02d3f)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:396
  28: futures::task_impl::std::set::h1ba508f1145a3bc4 (0x10ca133f6)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/std/mod.rs:78
  29: <futures::task_impl::Spawn<T>>::enter::ha88314cd1b3ec322 (0x10ca02cb7)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:396
  30: <futures::task_impl::Spawn<T>>::poll_fn_notify::h8bcc858b4fd0914a (0x10ca02897)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:288
  31: <futures::task_impl::Spawn<T>>::poll_future_notify::h9b406a6a80fdab04 (0x10ca02a34)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:326
  32: tokio_threadpool::task::Task::run::{{closure}}::hffd50ea625f17617 (0x10ca0cf5c)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.11/src/task/mod.rs:141
  33: core::ops::function::FnOnce::call_once::ha4b655fe50f4e703 (0x10ca030ec)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/ops/function.rs:238
  34: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h847b55131618dbf3 (0x10c9ffda7)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/panic.rs:319
  35: std::panicking::try::do_call::hca60c70b95a00c87 (0x10ca01fa4)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/panicking.rs:310
  36: ___rust_maybe_catch_panic (0x10cf68e6e)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libpanic_unwind/lib.rs:102
  37: std::panicking::try::h1727823ab5f45c26 (0x10ca01d42)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/panicking.rs:289
  38: std::panic::catch_unwind::h6497f41a0e8fe1f1 (0x10ca01cbe)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/panic.rs:398
  39: tokio_threadpool::task::Task::run::h4cbfbaac012e581d (0x10ca0ca09)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.11/src/task/mod.rs:127
  40: tokio_threadpool::worker::Worker::run_task2::h2cfedfda28aac775 (0x10ca3d870)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.11/src/worker/mod.rs:572
  41: tokio_threadpool::worker::Worker::run_task::hf0736d338f936026 (0x10ca3d206)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.11/src/worker/mod.rs:461
  42: tokio_threadpool::worker::Worker::try_steal_task::h98844cbb98929b13 (0x10ca3cdc2)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.11/src/worker/mod.rs:421
  43: tokio_threadpool::worker::Worker::try_run_task::hb7500a271b16be3f (0x10ca3c41b)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.11/src/worker/mod.rs:306
  44: tokio_threadpool::worker::Worker::run::hcb1ed23c5b99eb35 (0x10ca3c28a)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.11/src/worker/mod.rs:246
  45: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}::he552fcb7019966e2 (0x10c9bd6cb)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.15/src/runtime/threadpool/builder.rs:340
  46: tokio_timer::timer::handle::with_default::{{closure}}::h47c5becb211d0e60 (0x10c9be369)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.10/src/timer/handle.rs:94
  47: <std::thread::local::LocalKey<T>>::try_with::hf8ae5e83174f6f06 (0x10c9bf2e1)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/thread/local.rs:309
  48: <std::thread::local::LocalKey<T>>::with::h937f49e58d5cd06c (0x10c9bea5f)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/thread/local.rs:255
  49: tokio_timer::timer::handle::with_default::h73092438dcab7f0f (0x10c9be1fb)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.10/src/timer/handle.rs:81
  50: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::hf2c32172edf0a266 (0x10c9bd725)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.15/src/runtime/threadpool/builder.rs:339
  51: tokio_timer::clock::clock::with_default::{{closure}}::hdbc0105a06e625dd (0x10c9c76e5)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.10/src/clock/clock.rs:141
  52: <std::thread::local::LocalKey<T>>::try_with::h2f83e99ab37d64a7 (0x10c9becbc)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/thread/local.rs:309
  53: <std::thread::local::LocalKey<T>>::with::he00781a21eb673dd (0x10c9beac8)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/thread/local.rs:255
  54: tokio_timer::clock::clock::with_default::hdb7d0d9dc76f9c36 (0x10c9c75f9)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.10/src/clock/clock.rs:124
  55: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::h298679925971a5be (0x10c9bd769)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.15/src/runtime/threadpool/builder.rs:338
  56: tokio_reactor::with_default::{{closure}}::h3d43e43887d58755 (0x10c9bdb54)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.8/src/lib.rs:229
  57: <std::thread::local::LocalKey<T>>::try_with::hbd26023483cb5954 (0x10c9bf0e1)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/thread/local.rs:309
  58: <std::thread::local::LocalKey<T>>::with::h743c386c68b38bb4 (0x10c9bea08)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/thread/local.rs:255
  59: tokio_reactor::with_default::h3bca93ef748b46f9 (0x10c9bd94e)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.8/src/lib.rs:212
  60: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h9f88fd300ccd3f9b (0x10c9bd7ea)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.15/src/runtime/threadpool/builder.rs:337
  61: tokio_threadpool::callback::Callback::call::hb68c1eb85608769d (0x10ca32945)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.11/src/callback.rs:21
  62: tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}}::hba99087566228fdd (0x10ca3bf85)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.11/src/worker/mod.rs:132
  63: tokio_executor::global::with_default::{{closure}}::hfb12a25763fa97ea (0x10ca11222)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.6/src/global.rs:192
  64: <std::thread::local::LocalKey<T>>::try_with::hb8a52afc6c9528da (0x10ca0a37d)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/thread/local.rs:309
  65: <std::thread::local::LocalKey<T>>::with::h885bdcde76908730 (0x10ca08eef)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/thread/local.rs:255
  66: tokio_executor::global::with_default::h1c30f5d51ed522c5 (0x10ca1111e)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.6/src/global.rs:162
  67: tokio_threadpool::worker::Worker::do_run::{{closure}}::h5d0d02e1addeb85d (0x10ca3c026)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.11/src/worker/mod.rs:130
  68: <std::thread::local::LocalKey<T>>::try_with::h6710be6bd53db735 (0x10ca09da2)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/thread/local.rs:309
  69: <std::thread::local::LocalKey<T>>::with::h37850633f253baca (0x10ca08e8c)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/thread/local.rs:255
  70: tokio_threadpool::worker::Worker::do_run::he5c444f49373b3fa (0x10ca3be76)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.11/src/worker/mod.rs:121
  71: tokio_threadpool::pool::Pool::spawn_thread::{{closure}}::hff97c4938da5e82c (0x10ca41a89)
             at /Users/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.11/src/pool/mod.rs:346
  72: std::sys_common::backtrace::__rust_begin_short_backtrace::h5a46df296ca0d1e3 (0x10ca112cf)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/sys_common/backtrace.rs:136
  73: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h29d07f1d6460e322 (0x10ca3089f)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/thread/mod.rs:477
  74: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hd8de27a46be726f8 (0x10c9ffdef)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/panic.rs:319
  75: std::panicking::try::do_call::ha05a14e2b32a1560 (0x10ca01f3c)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/panicking.rs:310
  76: ___rust_maybe_catch_panic (0x10cf68e6e)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libpanic_unwind/lib.rs:102
  77: std::panicking::try::h8b487467151ca79a (0x10ca01e44)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/panicking.rs:289
  78: std::panic::catch_unwind::h08f1babf523ed612 (0x10ca01c6f)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/panic.rs:398
  79: std::thread::Builder::spawn_unchecked::{{closure}}::h0fe5b714cfc4a2f3 (0x10ca306ed)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/thread/mod.rs:476
  80: <F as alloc::boxed::FnBox<A>>::call_box::hb550701ca7a4a7fe (0x10ca315b7)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/liballoc/boxed.rs:673
  81: std::sys::unix::thread::Thread::new::thread_start::hb66fd5e16b37cfd7 (0x10cf5d03b)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/sys_common/thread.rs:24
  82: __pthread_body (0x7fff61656304)
  83: __pthread_start (0x7fff6165926e)

Thread 'tokio-runtime-worker-9' panicked at 'assertion failed: !a.is_connected()', core/network-libp2p/src/custom_proto/topology.rs:418
```

**Comment by rphmeier** [comment]
cc @tomaka

**Comment by tomaka** [comment]
I actually realized that and fixed it in #1796.
I can backport the fix if necessary.

**Comment by rphmeier** [comment]
Should be fine just to close it in 1796

**Comment by tomaka** [comment]
Should be fixed now that 1796 is merged.
The fix actually consisted in removing the assertion, so I'm sure that it will no longer happen.
