### ISSUE TITLE
Thread 'tokio-runtime-worker-4' panicked at 'Bad input data provided to execute_block', runtime/src/lib.rs:228

### ISSUE THREAD

**Issue by jkcomment** [paritytech/substrate#2225]
Thread panic error when I have playing template-node. node version(substrate) is 1.0.0.

Reproduce steps:
1. run node `./target/release/substrate-test --dev`
2. Set the value to Value defined in `runtime/src/mytemplate.rs` (via poladkt.js.org/apps/)
```
runtime/src/mytemplate.rs

decl_storage! {
    trait Store for Module<T: Trait> as MyStorage {
        Value get(value_getter): map T::AccountId => u64;
    }
}
```

Logs
```
====================
 
 stack backtrace:
    0: substrate_panic_handler::set::{{closure}}::hae047da797da35b0 (0x109b58cd0)
    1: std::panicking::rust_panic_with_hook::h4a3495c63f64f755 (0x109cb5e11)
    2: std::panicking::continue_panic_fmt::h3de7ba5e03709cd8 (0x109cb585c)
    3: std::panicking::begin_panic_fmt::hacd31b9797a72469 (0x109cb57b0)
    4: node_template_runtime::api::dispatch::h799c8f6abd8b6647 (0x1098958aa)
    5: std::panicking::try::do_call::ha9cece7285213e43 (0x108c90013)
    6: ___rust_maybe_catch_panic (0x109cbf1fe)
    7: substrate_executor::native_executor::safe_call::h9d5c5f979b020bee (0x108d9207a)
    8: <std::thread::local::LocalKey<T>>::with::h0869561142f3f1c6 (0x108c922fe)
    9: <substrate-test::service::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch::hc512aaa42e2598b2 (0x108df5790)
   10: <std::thread::local::LocalKey<T>>::with::h74f844da3551185e (0x108ca479b)
   11: <substrate_state_machine::StateMachine<'a, H, B, T, O, Exec>>::execute_aux::hcb29428672c53e13 (0x109018c72)
   12: <substrate_state_machine::StateMachine<'a, H, B, T, O, Exec>>::execute_call_with_native_else_wasm_strategy::hf5510a3969474177 (0x1090493d7)
   13: <substrate_state_machine::StateMachine<'a, H, B, T, O, Exec>>::execute_using_consensus_failure_handler::h9646787ea25dd5b3 (0x1090352e5)
   14: <substrate_client::call_executor::LocalCallExecutor<B, E> as substrate_client::call_executor::CallExecutor<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state::h76bb61ddd145ff3e (0x108d95f3f)
   15: <substrate_client::client::Client<B, E, Block, RA>>::apply_block::h812094d0e0a56723 (0x108f8ff43)
   16: <substrate_client::client::Client<B, E, Block, RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::h47b80d39cf62e8f7 (0x108f763a8)
   17: <futures::future::map::Map<A, F> as futures::future::Future>::poll::h90a4408471a141bf (0x108d15647)
   18: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll::h571757c7b307f255 (0x108e6ae01)
   19: <futures::future::either::Either<A, B> as futures::future::Future>::poll::hb57e351061e5a45c (0x108e68d3f)
   20: <futures::stream::for_each::ForEach<S, F, U> as futures::future::Future>::poll::hb44b2fee1ec53c37 (0x108c13300)
   21: std::panicking::try::do_call::h18cdebfc20d74b1d (0x108c8f6ba)
   22: ___rust_maybe_catch_panic (0x109cbf1fe)
   23: <futures::future::chain::Chain<A, B, C>>::poll::hc74d3a5908f4ece3 (0x108e4d7c6)
   24: <futures::future::select::Select<A, B> as futures::future::Future>::poll::hd3a314aa2bcaa893 (0x108bd8085)
   25: <futures::future::chain::Chain<A, B, C>>::poll::hee05849463690fc1 (0x108e4ef68)
   26: futures::task_impl::std::set::h0d86a834a1e10977 (0x109b1665c)
   27: std::panicking::try::do_call::h7cc9311932bf7101 (0x109b1d7c5)
   28: ___rust_maybe_catch_panic (0x109cbf1fe)
   29: tokio_threadpool::task::Task::run::h8e82860acde7025b (0x109b190d4)
   30: tokio_threadpool::worker::Worker::run_task::h42a44be839b50ddb (0x109b13571)
   31: tokio_threadpool::worker::Worker::run::hac5f32903566b3fb (0x109b12c35)
   32: tokio_trace_core::dispatcher::with_default::h9a38aebbfac6de48 (0x109afa4f4)
   33: <std::thread::local::LocalKey<T>>::with::hec2535a1406bf0cd (0x109afc19e)
   34: <std::thread::local::LocalKey<T>>::with::he9141585252698a5 (0x109afc06c)
   35: <std::thread::local::LocalKey<T>>::with::h83150cfddfa7042f (0x109afbea1)
   36: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h72a1acc35647081f (0x109afd6d8)
   37: <std::thread::local::LocalKey<T>>::with::hb858a5178ff552cf (0x109b1b0e8)
   38: <std::thread::local::LocalKey<T>>::with::h0db4639a846986f4 (0x109b1aae5)
   39: std::sys_common::backtrace::__rust_begin_short_backtrace::h06fdc74486cb11e3 (0x109b1d46f)
   40: std::panicking::try::do_call::hf8ff3c7c403b189a (0x109b1d82f)
   41: ___rust_maybe_catch_panic (0x109cbf1fe)
   42: <F as alloc::boxed::FnBox<A>>::call_box::h8c8210f4dda0b820 (0x109b14425)
   43: std::sys::unix::thread::Thread::new::thread_start::h2ccd51efe09a6d88 (0x109cbe7bb)
   44: __pthread_body (0x7fff7765a2ea)
   45: __pthread_start (0x7fff7765d248)
 
 Thread 'tokio-runtime-worker-4' panicked at 'Bad input data provided to execute_block', runtime/src/lib.rs:228
 
 This is a bug. Please report it at:
 
         support.anonymous.an
 
 bad origin: expected to be a root origin
```

**Comment by bkchr** [comment]
Can you please show the full code of your module and how do you set the value? Via a transaction?

**Comment by jkcomment** [comment]
Thank you.
That value generates trasaction from the Extrinsics menu at polkadot.js.org. But, It was solved after rebuilding. Maybe it is my mistake. I'm sorry. I will report if there is anything else.
Here is my source code:

runtime/src/lib.rs
```
//! The Substrate Node Template runtime. This can be compiled with `#[no_std]`, ready for Wasm.

#![cfg_attr(not(feature = "std"), no_std)]
#![cfg_attr(not(feature = "std"), feature(alloc))]
// `construct_runtime!` does a lot of recursion and requires us to increase the limit to 256.
#![recursion_limit="256"]

#[cfg(feature = "std")]
use serde_derive::{Serialize, Deserialize};
use parity_codec::{Encode, Decode};
use rstd::prelude::*;
#[cfg(feature = "std")]
use primitives::bytes;
use primitives::{ed25519, sr25519, OpaqueMetadata};
use runtime_primitives::{
	ApplyResult, transaction_validity::TransactionValidity, generic, create_runtime_str,
	traits::{self, NumberFor, BlakeTwo256, Block as BlockT, StaticLookup, Verify}
};
use client::{
	block_builder::api::{CheckInherentsResult, InherentData, self as block_builder_api},
	runtime_api, impl_runtime_apis
};
use version::RuntimeVersion;
#[cfg(feature = "std")]
use version::NativeVersion;

// A few exports that help ease life for downstream crates.
#[cfg(any(feature = "std", test))]
pub use runtime_primitives::BuildStorage;
pub use consensus::Call as ConsensusCall;
pub use timestamp::Call as TimestampCall;
pub use balances::Call as BalancesCall;
pub use runtime_primitives::{Permill, Perbill};
pub use timestamp::BlockPeriod;
pub use support::{StorageValue, construct_runtime};

/// The type that is used for identifying authorities.
pub type AuthorityId = <AuthoritySignature as Verify>::Signer;

/// The type used by authorities to prove their ID.
pub type AuthoritySignature = ed25519::Signature;

/// Alias to pubkey that identifies an account on the chain.
pub type AccountId = <AccountSignature as Verify>::Signer;

/// The type used by authorities to prove their ID.
pub type AccountSignature = sr25519::Signature;

/// A hash of some data used by the chain.
pub type Hash = primitives::H256;

/// Index of a block number in the chain.
pub type BlockNumber = u64;

/// Index of an account's extrinsic in the chain.
pub type Nonce = u64;

mod mytemplate;

/// Opaque types. These are used by the CLI to instantiate machinery that don't need to know
/// the specifics of the runtime. They can then be made to be agnostic over specific formats
/// of data like extrinsics, allowing for them to continue syncing the network through upgrades
/// to even the core datastructures.
pub mod opaque {
	use super::*;

	/// Opaque, encoded, unchecked extrinsic.
	#[derive(PartialEq, Eq, Clone, Default, Encode, Decode)]
	#[cfg_attr(feature = "std", derive(Serialize, Deserialize))]
	pub struct UncheckedExtrinsic(#[cfg_attr(feature = "std", serde(with="bytes"))] pub Vec<u8>);
	#[cfg(feature = "std")]
	impl std::fmt::Debug for UncheckedExtrinsic {
		fn fmt(&self, fmt: &mut std::fmt::Formatter) -> std::fmt::Result {
			write!(fmt, "{}", primitives::hexdisplay::HexDisplay::from(&self.0))
		}
	}
	impl traits::Extrinsic for UncheckedExtrinsic {
		fn is_signed(&self) -> Option<bool> {
			None
		}
	}
	/// Opaque block header type.
	pub type Header = generic::Header<BlockNumber, BlakeTwo256, generic::DigestItem<Hash, AuthorityId, AuthoritySignature>>;
	/// Opaque block type.
	pub type Block = generic::Block<Header, UncheckedExtrinsic>;
	/// Opaque block identifier type.
	pub type BlockId = generic::BlockId<Block>;
	/// Opaque session key type.
	pub type SessionKey = AuthorityId;
}

/// This runtime version.
pub const VERSION: RuntimeVersion = RuntimeVersion {
	spec_name: create_runtime_str!("substrate-test"),
	impl_name: create_runtime_str!("substrate-test"),
	authoring_version: 3,
	spec_version: 3,
	impl_version: 0,
	apis: RUNTIME_API_VERSIONS,
};

/// The version infromation used to identify this runtime when compiled natively.
#[cfg(feature = "std")]
pub fn native_version() -> NativeVersion {
	NativeVersion {
		runtime_version: VERSION,
		can_author_with: Default::default(),
	}
}

impl system::Trait for Runtime {
	/// The identifier used to distinguish between accounts.
	type AccountId = AccountId;
	/// The lookup mechanism to get account ID from whatever is passed in dispatchers.
	type Lookup = Indices;
	/// The index type for storing how many extrinsics an account has signed.
	type Index = Nonce;
	/// The index type for blocks.
	type BlockNumber = BlockNumber;
	/// The type for hashing blocks and tries.
	type Hash = Hash;
	/// The hashing algorithm used.
	type Hashing = BlakeTwo256;
	/// The header digest type.
	type Digest = generic::Digest<Log>;
	/// The header type.
	type Header = generic::Header<BlockNumber, BlakeTwo256, Log>;
	/// The ubiquitous event type.
	type Event = Event;
	/// The ubiquitous log type.
	type Log = Log;
	/// The ubiquitous origin type.
	type Origin = Origin;
}

impl aura::Trait for Runtime {
	type HandleReport = ();
}

impl consensus::Trait for Runtime {
	/// The identifier we use to refer to authorities.
	type SessionKey = AuthorityId;
	// The aura module handles offline-reports internally
	// rather than using an explicit report system.
	type InherentOfflineReport = ();
	/// The ubiquitous log type.
	type Log = Log;
}

impl indices::Trait for Runtime {
	/// The type for recording indexing into the account enumeration. If this ever overflows, there
	/// will be problems!
	type AccountIndex = u32;
	/// Use the standard means of resolving an index hint from an id.
	type ResolveHint = indices::SimpleResolveHint<Self::AccountId, Self::AccountIndex>;
	/// Determine whether an account is dead.
	type IsDeadAccount = Balances;
	/// The uniquitous event type.
	type Event = Event;
}

impl timestamp::Trait for Runtime {
	/// A timestamp: seconds since the unix epoch.
	type Moment = u64;
	type OnTimestampSet = Aura;
}

impl balances::Trait for Runtime {
	/// The type for recording an account's balance.
	type Balance = u128;
	/// What to do if an account's free balance gets zeroed.
	type OnFreeBalanceZero = ();
	/// What to do if a new account is created.
	type OnNewAccount = Indices;
	/// The uniquitous event type.
	type Event = Event;

	type TransactionPayment = ();
	type DustRemoval = ();
	type TransferPayment = ();
}

impl sudo::Trait for Runtime {
	/// The uniquitous event type.
	type Event = Event;
	type Proposal = Call;
}

impl mytemplate::Trait for Runtime {

}

construct_runtime!(
	pub enum Runtime with Log(InternalLog: DigestItem<Hash, AuthorityId, AuthoritySignature>) where
		Block = Block,
		NodeBlock = opaque::Block,
		UncheckedExtrinsic = UncheckedExtrinsic
	{
		System: system::{default, Log(ChangesTrieRoot)},
		Timestamp: timestamp::{Module, Call, Storage, Config<T>, Inherent},
		Consensus: consensus::{Module, Call, Storage, Config<T>, Log(AuthoritiesChange), Inherent},
		Aura: aura::{Module},
		Indices: indices,
		Balances: balances,
		Sudo: sudo,
		Mytemplate: mytemplate::{Module, Call, Storage},
	}
);

/// The type used as a helper for interpreting the sender of transactions.
type Context = system::ChainContext<Runtime>;
/// The address format for describing accounts.
type Address = <Indices as StaticLookup>::Source;
/// Block header type as expected by this runtime.
pub type Header = generic::Header<BlockNumber, BlakeTwo256, Log>;
/// Block type as expected by this runtime.
pub type Block = generic::Block<Header, UncheckedExtrinsic>;
/// BlockId type as expected by this runtime.
pub type BlockId = generic::BlockId<Block>;
/// Unchecked extrinsic type as expected by this runtime.
pub type UncheckedExtrinsic = generic::UncheckedMortalCompactExtrinsic<Address, Nonce, Call, AccountSignature>;
/// Extrinsic type that has already been checked.
pub type CheckedExtrinsic = generic::CheckedExtrinsic<AccountId, Nonce, Call>;
/// Executive: handles dispatch to the various modules.
pub type Executive = executive::Executive<Runtime, Block, Context, Balances, AllModules>;

// Implement our runtime API endpoints. This is just a bunch of proxying.
impl_runtime_apis! {
	impl runtime_api::Core<Block> for Runtime {
		fn version() -> RuntimeVersion {
			VERSION
		}

		fn execute_block(block: Block) {
			Executive::execute_block(block)
		}

		fn initialize_block(header: &<Block as BlockT>::Header) {
			Executive::initialize_block(header)
		}

		fn authorities() -> Vec<AuthorityId> {
			panic!("Deprecated, please use `AuthoritiesApi`.")
		}
	}

	impl runtime_api::Metadata<Block> for Runtime {
		fn metadata() -> OpaqueMetadata {
			Runtime::metadata().into()
		}
	}

	impl block_builder_api::BlockBuilder<Block> for Runtime {
		fn apply_extrinsic(extrinsic: <Block as BlockT>::Extrinsic) -> ApplyResult {
			Executive::apply_extrinsic(extrinsic)
		}

		fn finalize_block() -> <Block as BlockT>::Header {
			Executive::finalize_block()
		}

		fn inherent_extrinsics(data: InherentData) -> Vec<<Block as BlockT>::Extrinsic> {
			data.create_extrinsics()
		}

		fn check_inherents(block: Block, data: InherentData) -> CheckInherentsResult {
			data.check_extrinsics(&block)
		}

		fn random_seed() -> <Block as BlockT>::Hash {
			System::random_seed()
		}
	}

	impl runtime_api::TaggedTransactionQueue<Block> for Runtime {
		fn validate_transaction(tx: <Block as BlockT>::Extrinsic) -> TransactionValidity {
			Executive::validate_transaction(tx)
		}
	}

	impl consensus_aura::AuraApi<Block> for Runtime {
		fn slot_duration() -> u64 {
			Aura::slot_duration()
		}
	}

	impl offchain_primitives::OffchainWorkerApi<Block> for Runtime {
		fn offchain_worker(n: NumberFor<Block>) {
			Executive::offchain_worker(n)
		}
	}

	impl consensus_authorities::AuthoritiesApi<Block> for Runtime {
		fn authorities() -> Vec<AuthorityId> {
			Consensus::authorities()
		}
	}
}
```

runtime/src/mytemplate.rs
```
use support::{decl_storage, decl_module, StorageMap, dispatch::Result};

use system::ensure_signed;

pub trait Trait: balances::Trait {}

decl_storage! {
    trait Store for Module<T: Trait> as MyStorage {
        Value get(value_getter): map T::AccountId => u64;
    }
}

decl_module! {
    pub struct Module<T: Trait> for enum Call where origin: T::Origin {
        fn set_value(origin, value: u64) -> Result {
            let sender = ensure_signed(origin)?;
            <Value<T>>::insert(&sender, value);
            Ok(())
        }
    }
}
```

**Comment by bkchr** [comment]
Good, then I will close this.
