### ISSUE TITLE
contract usage of child storage lacks child storage prefix

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#2277]
EDIT (previous test was wrong):

if we create a contract that insert a value in storage and change code as following:
```diff
@@ -108,8 +124,15 @@ impl<T: Trait> AccountDb<T> for DirectAccountDb {
                                                new_storage_size -= value.len() as u64;
                                        }
                                        if let Some(value) = v {
+                                               #[cfg(feature="std")] {
+                                                       println!("put raw:\n{:?}\n{:?}\n{:?}", info.trie_id, k, value);
+                                               }
                                                new_storage_size += value.len() as u64;
                                                child::put_raw(&info.trie_id[..], &k, &value[..]);
+                                               let get_raw = child::get_raw(&info.trie_id, &k);
+                                               #[cfg(feature="std")] {
+                                                       println!("get raw:\n{:?}", get_raw);
+                                               }
```

then second call returns None

**Comment by thiolliere** [comment]
The test is wrong as as it uses ./core/state-machine/src/basic.rs

But we still have an issue on contract side

**Comment by thiolliere** [comment]
this returns false:
```
		if !is_child_storage_key(&storage_key) || !is_child_trie_key_valid::<H>(&storage_key) {
			return false;
		}
```

**Comment by thiolliere** [comment]
sloving is_child_storage_key by inserting PREFIX into trie_id at generation bring another issue:
```
Hash not equal
3b2f255a996d460598d7a4c37830dc654d7676ca4465b7aa1d9a6259e4eeea7b
6573a6b2efda9802f31eb3f760d5a870fddaec2d0298db7f53f5715048390131
/home/thiolliere/Developpement/substrate/srml/executive/src/lib.rs


2019-04-14 10:48:36 Error with block built on 0x37a38338bbd4c3c5780a2ca7c5362ad878d08f0f298b926efb79e1f5a0842836: Error(ClientImport("Import failed: Execution: Trap: Trap { kind: Unreachable }"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
```

**Comment by bkchr** [comment]
The hash equal is no bug. If you change the storage in a test in a different way, the storage root changes. If you expected the storage root to change, you just need to modify the test to use the new hash.

**Comment by thiolliere** [comment]
It wasn't trigger in a test, I just set a value in a child storage in --dev:

just call setstorage in this branch: https://github.com/paritytech/substrate/compare/gui-resolve-contract-storage?expand=1, or with this diff
```
diff --git a/srml/contract/src/lib.rs b/srml/contract/src/lib.rs
index c47145125..30df500a8 100644
--- a/srml/contract/src/lib.rs
+++ b/srml/contract/src/lib.rs
@@ -106,6 +106,7 @@ use srml_support::dispatch::{Result, Dispatchable};
 use srml_support::{Parameter, StorageMap, StorageValue, decl_module, decl_event, decl_storage, storage::child};
 use srml_support::traits::{OnFreeBalanceZero, OnUnbalanced, Currency};
 use system::{ensure_signed, RawOrigin};
+use substrate_primitives::storage::well_known_keys::CHILD_STORAGE_KEY_PREFIX;
 use timestamp;
 
 pub type CodeHash<T> = <T as system::Trait>::Hash;
@@ -159,7 +160,11 @@ where
                let mut buf = Vec::new();
                buf.extend_from_slice(account_id.as_ref());
                buf.extend_from_slice(&new_seed.to_le_bytes()[..]);
-               T::Hashing::hash(&buf[..]).as_ref().into()
+
+               CHILD_STORAGE_KEY_PREFIX.iter()
+                       .chain(T::Hashing::hash(&buf[..]).as_ref().iter())
+                       .cloned()
+                       .collect()
        }
 }
 
@@ -270,6 +275,14 @@ decl_module! {
                        result.map(|_| ())
                }
 
+               fn set_storage(origin) {
+                       let trie_id = CHILD_STORAGE_KEY_PREFIX.iter()
+                               .chain(b"toto")
+                               .cloned()
+                               .collect::<Vec<_>>();
+                       srml_support::storage::child::put_raw(&trie_id, b"foo", b"foo");
+               }
+
```

result in 

```
Hash: given=a3cc11540b067f30d1536517893593e206ea09111ebf074d6d344af0b23d6d1d, expected=9799314dd897795bb22ac85f8f7b58287d309a88924257538294c66ca5911fd5

====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h4d58cecdb0979199 (0x55b322357300)
   1: std::panicking::rust_panic_with_hook::h744417edfe714d72 (0x55b3224e6949)
             at src/libstd/panicking.rs:482
   2: std::panicking::begin_panic::hf9b96a83efe501eb (0x55b321bb59d4)
   3: <srml_executive::Executive<System, Block, Context, Payment, AllModules>>::execute_block::h61437164faf2c4f7 (0x55b321bb3224)
   4: node_runtime::api::dispatch::h14aae3dd968162d2 (0x55b321b18ad4)
   5: std::panicking::try::do_call::h3eabd09856e2d563 (0x55b321b122a1)
   6: __rust_maybe_catch_panic (0x55b3224ecca9)
             at src/libpanic_unwind/lib.rs:92
   7: substrate_executor::native_executor::safe_call::hcc1e8410067782d7 (0x55b321b11e32)
   8: <std::thread::local::LocalKey<T>>::with::h490df750a6d6bf3d (0x55b321b1176d)
   9: <node_executor::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch::h4881ca9bb1e29578 (0x55b321b112cc)
  10: <std::thread::local::LocalKey<T>>::with::h8d9603369ab1a75b (0x55b32155e14e)
  11: <substrate_state_machine::StateMachine<'a, H, B, T, O, Exec>>::execute_aux::h63b80ec2c931cb3b (0x55b321706562)
  12: <substrate_state_machine::StateMachine<'a, H, B, T, O, Exec>>::execute_call_with_native_else_wasm_strategy::hde3a578e15536360 (0x55b32174b052)
  13: <substrate_state_machine::StateMachine<'a, H, B, T, O, Exec>>::execute_using_consensus_failure_handler::h4392fb91ed15cb6d (0x55b321720c7b)
  14: <substrate_client::call_executor::LocalCallExecutor<B, E> as substrate_client::call_executor::CallExecutor<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state::h376aa0bf03533b2a (0x55b321952061)
  15: <substrate_client::client::Client<B, E, Block, RA>>::lock_import_and_run::{{closure}}::he67880112ec8ecfb (0x55b32152e304)
  16: <substrate_client::client::Client<B, E, Block, RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::hcb579a0923aa39e0 (0x55b32151c111)
  17: <substrate_finality_grandpa::import::GrandpaBlockImport<B, E, Block, RA, PRA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::hccaf93022d9975d1 (0x55b32177027d)
  18: <futures::future::map::Map<A, F> as futures::future::Future>::poll::h0e44b370c0ce3890 (0x55b3219e1f22)
  19: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll::hd290d731216e712b (0x55b3215d9420)
  20: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll::ha65cbb48f97c7a62 (0x55b3215d8530)
  21: <futures::stream::for_each::ForEach<S, F, U> as futures::future::Future>::poll::hb062c575a11b4762 (0x55b321a8b60c)
  22: std::panicking::try::do_call::hea03a242343a10fe (0x55b32188d846)
  23: __rust_maybe_catch_panic (0x55b3224ecca9)
             at src/libpanic_unwind/lib.rs:92
  24: <futures::future::catch_unwind::CatchUnwind<F> as futures::future::Future>::poll::h5970b4dde17dcc0c (0x55b321aa56da)
  25: <futures::future::chain::Chain<A, B, C>>::poll::he5237d288e0667d3 (0x55b321a116aa)
  26: <futures::future::select::Select<A, B> as futures::future::Future>::poll::h455f97e63ed444b1 (0x55b321a40946)
  27: <futures::future::chain::Chain<A, B, C>>::poll::hd9a265e6c2b9bf96 (0x55b321a10b98)
  28: futures::task_impl::std::set::hf7bd2527e7352ec9 (0x55b322317691)
  29: <futures::task_impl::Spawn<T>>::poll_future_notify::h31a3309670f97963 (0x55b32231b995)
  30: std::panicking::try::do_call::h867ec35fa3ce2eb2 (0x55b32230dbf0)
  31: __rust_maybe_catch_panic (0x55b3224ecca9)
             at src/libpanic_unwind/lib.rs:92
  32: tokio_threadpool::task::Task::run::hcc9d94925bc53476 (0x55b32230be2b)
  33: tokio_threadpool::worker::Worker::run_task::h709fee0f5964208c (0x55b3223098c0)
  34: tokio_threadpool::worker::Worker::run::h7df65ad59e30228c (0x55b322308f96)
  35: <std::thread::local::LocalKey<T>>::with::hbc1b4eba6b7db2fd (0x55b3222f2f36)
  36: <std::thread::local::LocalKey<T>>::with::h5e011cdc468f42dd (0x55b3222f2dfe)
  37: <std::thread::local::LocalKey<T>>::with::h22c5babca88ef977 (0x55b3222f2c1b)
  38: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::hc1dc7a0192002a0e (0x55b3222eb42d)
  39: <std::thread::local::LocalKey<T>>::with::h93bd31ca01b49086 (0x55b322314932)
  40: <std::thread::local::LocalKey<T>>::with::h1270a6ea613fabf3 (0x55b322314709)
  41: std::sys_common::backtrace::__rust_begin_short_backtrace::h8e163f9990748a95 (0x55b32230d135)
  42: std::panicking::try::do_call::hfe8ec7fcff8803fa (0x55b32230dc3b)
  43: __rust_maybe_catch_panic (0x55b3224ecca9)
             at src/libpanic_unwind/lib.rs:92
  44: <F as alloc::boxed::FnBox<A>>::call_box::h7d214f819e6e12d4 (0x55b322311eaf)
  45: <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h2263113ac6678036 (0x55b3224ec01d)
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/liballoc/boxed.rs:744
      std::sys_common::thread::start_thread::h7f66efdea8634396
             at src/libstd/sys_common/thread.rs:14
      std::sys::unix::thread::Thread::new::thread_start::h6fb76bcf544b6181
             at src/libstd/sys/unix/thread.rs:81
  46: start_thread (0x7fc06270b58d)
  47: clone (0x7fc06261d682)
  48: <unknown> (0x0)

Thread 'main-tokio-5' panicked at 'Storage root must match that calculated.', srml/executive/src/lib.rs:243

This is a bug. Please report it at:

	https://github.com/paritytech/substrate/issues/new
```

**Comment by pepyakin** [comment]
So the process was killed after that? The runtime is not supposed to take down the entire process.

**Comment by thiolliere** [comment]
I don't know why but I think it continued building block ok after.

But when I testing with the actual contract, blocks couldn't be build anymore. I don't what differ there.

**Comment by thiolliere** [comment]
as we found another bug while solving this one I created another issue https://github.com/paritytech/substrate/issues/2284

**Comment by thiolliere** [comment]
fixed by https://github.com/paritytech/substrate/pull/2292
