### ISSUE TITLE
Error: Thread 'tokio-runtime-worker-1' panicked at 'Storage root must match that calculated.', /Users/user/.cargo/git/checkouts/substrate-7e08433d4c370a21/4999397/srml/executive/src/lib.rs:281

### ISSUE THREAD

**Issue by satellitex** [paritytech/substrate#2357]
I happened runtime error when I execute api for polkadotjs.
```
stack backtrace:
   0: substrate_panic_handler::panic_hook::h07e3c7f9805d10ca (0x1110d261b)
             at /Users/user/.cargo/git/checkouts/substrate-7e08433d4c370a21/4999397/core/panic-handler/src/lib.rs:82
   1: substrate_panic_handler::set::{{closure}}::hcd99665932cc1ab3 (0x1110d2226)
             at /Users/user/.cargo/git/checkouts/substrate-7e08433d4c370a21/4999397/core/panic-handler/src/lib.rs:31
   2: std::panicking::rust_panic_with_hook::hff16cb2217d41f10 (0x111585740)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:482
   3: std::panicking::begin_panic::hc09baf7e911dfac6 (0x110d6a5d7)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:412
   4: <srml_executive::Executive<System, Block, Context, Payment, AllModules>>::final_checks::h9f1aeb10006fe5dc (0x1107874b9)
             at /Users/user/userllitex/Plasm/<::std::macros::panic macros>:3
   5: <srml_executive::Executive<System, Block, Context, Payment, AllModules>>::execute_block::h1ebb1b645a6a3fa8 (0x110787648)
             at /Users/user/.cargo/git/checkouts/substrate-7e08433d4c370a21/4999397/srml/executive/src/lib.rs:166
   6: <plasm_runtime::Runtime as substrate_client::runtime_api::runtime_decl_for_Core::Core<sr_primitives::generic::block::Block<sr_primitives::generic::header::Header<u64, sr_primitives::traits::BlakeTwo256, plasm_runtime::Log>, sr_primitives::generic::unchecked_mortal_compact_extrinsic::UncheckedMortalCompactExtrinsic<<srml_indices::Module<plasm_runtime::Runtime> as sr_primitives::traits::StaticLookup>::Source, u64, plasm_runtime::Call, substrate_primitives::sr25519::Signature>>>>::execute_block::h32548c00f4f7bcd3 (0x1107ef512)
             at /Users/user/userllitex/Plasm/runtime/src/lib.rs:286
   7: plasm_runtime::api::dispatch::ha98197d4360c66de (0x110752fe1)
             at /Users/user/userllitex/Plasm/runtime/src/lib.rs:279
   8: <plasm_node::service::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch::{{closure}}::h1e71dd3ddb794ec0 (0x10f5abcf0)
             at /Users/user/userllitex/Plasm/<::substrate_executor::native_executor::native_executor_instance macros>:14
   9: std::panicking::try::do_call::h8c6c54a663a05dcd (0x10f101373)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:297
  10: ___rust_maybe_catch_panic (0x11158ee5e)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libpanic_unwind/lib.rs:87
  11: std::panicking::try::h46b186f2fd78882d (0x10f0feb34)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:276
  12: std::panic::catch_unwind::h19885bc8abf7ed83 (0x10ec02206)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:388
  13: substrate_executor::native_executor::safe_call::hca84cec544d0af56 (0x10eb3ae66)
             at /Users/user/.cargo/git/checkouts/substrate-7e08433d4c370a21/4999397/core/executor/src/native_executor.rs:103
  14: substrate_executor::native_executor::with_native_environment::{{closure}}::h8a549bc11ba3575b (0x10eb34366)
             at /Users/user/.cargo/git/checkouts/substrate-7e08433d4c370a21/4999397/core/executor/src/native_executor.rs:112
  15: environmental::using::{{closure}}::h98f27424c60d37c7 (0x10f0f771a)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.0.1/src/lib.rs:88
  16: <std::thread::local::LocalKey<T>>::try_with::h0951e88d23e12485 (0x10e98b534)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/thread/local.rs:300
  17: <std::thread::local::LocalKey<T>>::with::haddf2b851964569b (0x10e98968c)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/thread/local.rs:246
  18: environmental::using::hd8f72c814df51846 (0x10f0f5a5e)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.0.1/src/lib.rs:65
  19: sr_io::ext::using::h72e5652fd338b380 (0x10e9f20a5)
             at /Users/user/userllitex/Plasm/<::environmental::environmental macros>:21
  20: sr_io::with_externalities::h84de23b4bc7e175a (0x10e9f1416)
             at /Users/user/.cargo/git/checkouts/substrate-7e08433d4c370a21/4999397/core/sr-io/src/../with_std.rs:233
  21: substrate_executor::native_executor::with_native_environment::h15eaadec64f22bf8 (0x10eb33606)
             at /Users/user/.cargo/git/checkouts/substrate-7e08433d4c370a21/4999397/core/executor/src/native_executor.rs:112
  22: <plasm_node::service::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch::hbb1e80b07f80b260 (0x10f5dc88d)
             at /Users/user/userllitex/Plasm/<::substrate_executor::native_executor::native_executor_instance macros>:13
  23: <substrate_executor::native_executor::NativeExecutor<D> as substrate_state_machine::CodeExecutor<substrate_primitives::hasher::blake2::Blake2Hasher>>::call::{{closure}}::h4d8640c4960bef1f (0x10eb16131)
             at /Users/user/.cargo/git/checkouts/substrate-7e08433d4c370a21/4999397/core/executor/src/native_executor.rs:261
  24: <std::thread::local::LocalKey<T>>::try_with::hb103977bfaffab01 (0x10e998971)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/thread/local.rs:300
  25: <std::thread::local::LocalKey<T>>::with::h9b984ebfba4790ed (0x10e989375)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/thread/local.rs:246
  26: <substrate_executor::native_executor::NativeExecutor<D> as substrate_state_machine::CodeExecutor<substrate_primitives::hasher::blake2::Blake2Hasher>>::call::h8f317672b95de22f (0x10eb0c74a)
             at /Users/user/.cargo/git/checkouts/substrate-7e08433d4c370a21/4999397/core/executor/src/native_executor.rs:201
  27: <substrate_state_machine::StateMachine<'a, H, B, T, O, Exec>>::execute_aux::hc6917d0ca0262959 (0x10f274b70)
             at /Users/user/.cargo/git/checkouts/substrate-7e08433d4c370a21/4999397/core/state-machine/src/lib.rs:366
  28: <substrate_state_machine::StateMachine<'a, H, B, T, O, Exec>>::execute_call_with_native_else_wasm_strategy::he8a200f064caa54a (0x10f2c2494)
             at /Users/user/.cargo/git/checkouts/substrate-7e08433d4c370a21/4999397/core/state-machine/src/lib.rs:423
  29: <substrate_state_machine::StateMachine<'a, H, B, T, O, Exec>>::execute_using_consensus_failure_handler::h64a7133b0210aa2b (0x10f298b48)
             at /Users/user/.cargo/git/checkouts/substrate-7e08433d4c370a21/4999397/core/state-machine/src/lib.rs:479
  30: <substrate_client::call_executor::LocalCallExecutor<B, E> as substrate_client::call_executor::CallExecutor<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state::hc340c55d25b38b89 (0x10f1ed9dd)
             at /Users/user/.cargo/git/checkouts/substrate-7e08433d4c370a21/4999397/core/client/src/call_executor.rs:298
  31: <substrate_client::client::Client<B, E, Block, RA>>::block_execution::h4d1623c2dd642b0e (0x10f741e05)
             at /Users/user/.cargo/git/checkouts/substrate-7e08433d4c370a21/4999397/core/client/src/client.rs:863
  32: <substrate_client::client::Client<B, E, Block, RA>>::execute_and_import_block::hbf610bea5b59a918 (0x10f751262)
             at /Users/user/.cargo/git/checkouts/substrate-7e08433d4c370a21/4999397/core/client/src/client.rs:778
  33: <substrate_client::client::Client<B, E, Block, RA>>::apply_block::h61efdd551966391d (0x10f73df88)
             at /Users/user/.cargo/git/checkouts/substrate-7e08433d4c370a21/4999397/core/client/src/client.rs:713
  34: <substrate_client::client::Client<B, E, Block, RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::{{closure}}::h2583dd92d029c18b (0x10f73abf3)
             at /Users/user/.cargo/git/checkouts/substrate-7e08433d4c370a21/4999397/core/client/src/client.rs:1399
  35: <substrate_client::client::Client<B, E, Block, RA>>::lock_import_and_run::{{closure}}::h2b3e88bfccf5711f (0x10f749274)
             at /Users/user/.cargo/git/checkouts/substrate-7e08433d4c370a21/4999397/core/client/src/client.rs:630
  36: <substrate_client::client::Client<B, E, Block, RA>>::lock_import_and_run::h5bd42588f06d3f6b (0x10f748240)
             at /Users/user/.cargo/git/checkouts/substrate-7e08433d4c370a21/4999397/core/client/src/client.rs:643
  37: <substrate_client::client::Client<B, E, Block, RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::h020a9ce5c2087bf2 (0x10f73aa38)
             at /Users/user/.cargo/git/checkouts/substrate-7e08433d4c370a21/4999397/core/client/src/client.rs:1398
  38: <substrate_consensus_aura::AuraWorker<C, E, I, P, SO> as substrate_consensus_slots::SlotWorker<B>>::on_slot::{{closure}}::he3fef266cdf99cc7 (0x10f232f8e)
             at /Users/user/.cargo/git/checkouts/substrate-7e08433d4c370a21/4999397/core/consensus/aura/src/lib.rs:449
  39: <core::result::Result<T, E>>::map::hbd081920959c145a (0x10f002c96)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libcore/result.rs:458
  40: <futures::future::map::Map<A, F> as futures::future::Future>::poll::hd91a6b6743417f0a (0x10eedc33e)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/map.rs:35
  41: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll::h15e99ddea971253d (0x10f3f2acc)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/map_err.rs:30
  42: <alloc::boxed::Box<F> as futures::future::Future>::poll::hb880c7d32a7ae54c (0x10ef7e74b)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/mod.rs:113
  43: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll::h946ff763b5e4f176 (0x10f3f68a9)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/map_err.rs:30
  44: <futures::future::either::Either<A, B> as futures::future::Future>::poll::hea99b46e56b3ca8d (0x10f539769)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/either.rs:35
  45: <futures::stream::for_each::ForEach<S, F, U> as futures::future::Future>::poll::h1c7904f3707f3182 (0x10f25653a)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/stream/for_each.rs:39
  46: futures::future::catch_unwind::<impl futures::future::Future for std::panic::AssertUnwindSafe<F>>::poll::hc6f864910a1136e3 (0x10ec02b74)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/catch_unwind.rs:49
  47: <futures::future::catch_unwind::CatchUnwind<F> as futures::future::Future>::poll::{{closure}}::h455e409c70b94327 (0x10f54ed21)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/catch_unwind.rs:32
  48: std::panicking::try::do_call::hb5732976fb17e95e (0x10f101716)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:297
  49: ___rust_maybe_catch_panic (0x11158ee5e)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libpanic_unwind/lib.rs:87
  50: std::panicking::try::h3c34a6cef0358053 (0x10f0fe554)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:276
  51: std::panic::catch_unwind::h4e31773ac654d0e5 (0x10ec02447)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:388
  52: <futures::future::catch_unwind::CatchUnwind<F> as futures::future::Future>::poll::h24a06f76566f0cfb (0x10f54e89e)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/catch_unwind.rs:32
  53: <futures::future::chain::Chain<A, B, C>>::poll::he341d1e1439dc17b (0x10f5f880d)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/chain.rs:26
  54: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll::h5f5f0c3b163262fc (0x10ec038a4)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/then.rs:32
  55: <futures::future::loop_fn::LoopFn<A, F> as futures::future::Future>::poll::he98c53ed5acd265d (0x10f4cfef0)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/loop_fn.rs:93
  56: <futures::future::select::Select<A, B> as futures::future::Future>::poll::ha75b1084bd21c3bc (0x10ece6466)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/select.rs:48
  57: <futures::future::chain::Chain<A, B, C>>::poll::hd1e086a64b3df19d (0x10f5f5f9d)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/chain.rs:26
  58: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll::h49b4a9758926bb94 (0x10ec03844)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/then.rs:32
  59: <alloc::boxed::Box<F> as futures::future::Future>::poll::hc02851a2223e288f (0x11100cf74)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/mod.rs:113
  60: <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}::h26e04f43a478af69 (0x110f71854)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/task_impl/mod.rs:329
  61: <futures::task_impl::Spawn<T>>::enter::{{closure}}::h45d511294c0cfaa0 (0x110f71acf)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/task_impl/mod.rs:399
  62: futures::task_impl::std::set::hc8be7fa6580c466b (0x110f96d56)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/task_impl/std/mod.rs:78
  63: <futures::task_impl::Spawn<T>>::enter::hb78a64d5219c825a (0x110f71a77)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/task_impl/mod.rs:399
  64: <futures::task_impl::Spawn<T>>::poll_fn_notify::h1fd8f0cb8f0e5efa (0x110f71657)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/task_impl/mod.rs:291
  65: <futures::task_impl::Spawn<T>>::poll_future_notify::h4e70c2750d7905e0 (0x110f717b4)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/task_impl/mod.rs:329
  66: tokio_threadpool::task::Task::run::{{closure}}::h788d4614536dcba5 (0x110f77f4c)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/task/mod.rs:145
  67: core::ops::function::FnOnce::call_once::hbedac8c034610a75 (0x110f85f2c)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libcore/ops/function.rs:231
  68: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hb82e8c422fb0b387 (0x110f6d147)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:309
  69: std::panicking::try::do_call::hcdc3207c31f74837 (0x110f6dcb4)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:297
  70: ___rust_maybe_catch_panic (0x11158ee5e)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libpanic_unwind/lib.rs:87
  71: std::panicking::try::h3ad41165747def0c (0x110f6dac2)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:276
  72: std::panic::catch_unwind::heb8f78ad457fef46 (0x110f6da3e)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:388
  73: tokio_threadpool::task::Task::run::h54ad5b57275ca36f (0x110f77a1e)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/task/mod.rs:130
  74: tokio_threadpool::worker::Worker::run_task2::h42285b991e0ede4e (0x110f8c1d0)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/worker/mod.rs:567
  75: tokio_threadpool::worker::Worker::run_task::h62d45f80fe73bd0a (0x110f8bb86)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/worker/mod.rs:459
  76: tokio_threadpool::worker::Worker::try_steal_task::h6acb5ddc85bd4341 (0x110f8b751)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/worker/mod.rs:416
  77: tokio_threadpool::worker::Worker::try_run_task::h867700b8d4c0b85a (0x110f8addb)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/worker/mod.rs:301
  78: tokio_threadpool::worker::Worker::run::ha78c8daad4fd25fa (0x110f8ac4a)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/worker/mod.rs:241
  79: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}::{{closure}}::hb1e38d9f4ec12694 (0x110f15477)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.18/src/runtime/threadpool/builder.rs:349
  80: tokio_trace_core::dispatcher::with_default::hb2e12ddc3fc91c0c (0x110f1312c)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-trace-core-0.1.0/src/dispatcher.rs:54
  81: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}::hd0bf0e3cca9f46e8 (0x110f154a8)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.18/src/runtime/threadpool/builder.rs:348
  82: tokio_timer::timer::handle::with_default::{{closure}}::hf9b99581e5bdeb3b (0x110f1983d)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.10/src/timer/handle.rs:94
  83: <std::thread::local::LocalKey<T>>::try_with::h579dfbb08c4bc11b (0x110f17e9d)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/thread/local.rs:300
  84: <std::thread::local::LocalKey<T>>::with::h8256da3d595f0345 (0x110f17837)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/thread/local.rs:246
  85: tokio_timer::timer::handle::with_default::h1631cc9660bf33c1 (0x110f196c7)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.10/src/timer/handle.rs:81
  86: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::hccf7acb86c8a41b9 (0x110f15501)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.18/src/runtime/threadpool/builder.rs:347
  87: tokio_timer::clock::clock::with_default::{{closure}}::h2b99bf023248b2c6 (0x110f22b03)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.10/src/clock/clock.rs:141
  88: <std::thread::local::LocalKey<T>>::try_with::hdd0068b4d0424aec (0x110f1833b)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/thread/local.rs:300
  89: <std::thread::local::LocalKey<T>>::with::h6327a896f6650644 (0x110f17778)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/thread/local.rs:246
  90: tokio_timer::clock::clock::with_default::hd23eb436cb9432d8 (0x110f22a01)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.10/src/clock/clock.rs:124
  91: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::h3effe80475b53d5d (0x110f15551)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.18/src/runtime/threadpool/builder.rs:346
  92: tokio_reactor::with_default::{{closure}}::h8057bb72f5736696 (0x110f18819)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.9/src/lib.rs:237
  93: <std::thread::local::LocalKey<T>>::try_with::h00ba8a82cb27d1c5 (0x110f17a97)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/thread/local.rs:300
  94: <std::thread::local::LocalKey<T>>::with::h63ff15c7fa3bcf3a (0x110f177d8)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/thread/local.rs:246
  95: tokio_reactor::with_default::hdf5209c37ca8c48d (0x110f18606)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.9/src/lib.rs:217
  96: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::hd9ab4b22117253a8 (0x110f155e6)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.18/src/runtime/threadpool/builder.rs:345
  97: tokio_threadpool::callback::Callback::call::h9d289e2a9480d0e5 (0x110f7e265)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/callback.rs:22
  98: tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}}::h46b6eed82e7ed552 (0x110f8a947)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/worker/mod.rs:127
  99: tokio_executor::global::with_default::{{closure}}::h5d0cf2cbb7884f13 (0x110f8d812)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.7/src/global.rs:209
 100: <std::thread::local::LocalKey<T>>::try_with::h022cd95c09b14529 (0x110f8e4db)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/thread/local.rs:300
 101: <std::thread::local::LocalKey<T>>::with::h85859236c38d8c2b (0x110f8e23f)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/thread/local.rs:246
 102: tokio_executor::global::with_default::heedf1e0a65d430af (0x110f8d70e)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.7/src/global.rs:178
 103: tokio_threadpool::worker::Worker::do_run::{{closure}}::h3f4ed456a8b72f9c (0x110f8a9e6)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/worker/mod.rs:125
 104: <std::thread::local::LocalKey<T>>::try_with::he8d7be8f2224c728 (0x110f8f0b0)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/thread/local.rs:300
 105: <std::thread::local::LocalKey<T>>::with::hb64e722919c9ec39 (0x110f8e28c)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/thread/local.rs:246
 106: tokio_threadpool::worker::Worker::do_run::hf1f2e04821344315 (0x110f8a846)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/worker/mod.rs:116
 107: tokio_threadpool::pool::Pool::spawn_thread::{{closure}}::h515950ace402b0ec (0x110f94b09)
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/pool/mod.rs:344
 108: std::sys_common::backtrace::__rust_begin_short_backtrace::h482b73d76e16471b (0x110f8dc1f)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/sys_common/backtrace.rs:135
 109: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hce94f9d68facf3cc (0x110f7bb5f)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/thread/mod.rs:469
 110: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h8c2af399beb18a4b (0x110f6d10f)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:309
 111: std::panicking::try::do_call::hff9963c2d7b81031 (0x110f6dd2c)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:297
 112: ___rust_maybe_catch_panic (0x11158ee5e)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libpanic_unwind/lib.rs:87
 113: std::panicking::try::hbf8be894624a8325 (0x110f6dbc4)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:276
 114: std::panic::catch_unwind::h2b7e22602dcba7d5 (0x110f6d9ef)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:388
 115: std::thread::Builder::spawn_unchecked::{{closure}}::h84d6ada236c8f2d4 (0x110f7b9ad)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/thread/mod.rs:468
 116: <F as alloc::boxed::FnBox<A>>::call_box::hc405e1d5fc8d9716 (0x110f7e017)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/liballoc/boxed.rs:749
 117: std::sys::unix::thread::Thread::new::thread_start::h20d3ef41b46f13b9 (0x11158e2db)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/sys_common/thread.rs:14
 118: __pthread_body (0x7fff641b42ea)
 119: __pthread_start (0x7fff641b7248)

Thread 'tokio-runtime-worker-1' panicked at 'Storage root must match that calculated.', /Users/user/.cargo/git/checkouts/substrate-7e08433d4c370a21/4999397/srml/executive/src/lib.rs:281

This is a bug. Please report it at:

	support.anonymous.an
```

Please tell me What is the reason to think?

**Comment by bkchr** [comment]
What did you execute? The stack trace looks says that it crashed while importing a block.

**Comment by satellitex** [comment]
I execute this command on my srml.
https://github.com/stakedtechnologies/Plasm/blob/master/core/utxo/src/lib.rs#L402

And, I have a place in mind.
I use storage, but not use `decl_storage!`.
(using ↑ command it: https://github.com/stakedtechnologies/Plasm/blob/master/core/merkle/src/lib.rs#L35)

**Comment by bkchr** [comment]
I don't really understand, you are using `decl_storage!` and also use the type that is generated by `decl_storage!`. Do you use your own merkle trie implementation/database interface?

**Comment by satellitex** [comment]
Yes. I use my merkle on Inserter implemention. (This is abstracted. For we can select use merkle or not.)
https://github.com/stakedtechnologies/Plasm/blob/master/core/utxo/src/mvp.rs

Is this no problem?(I see implementation that use child::get (directly access database ) on contract srml implementation.)

**Comment by bkchr** [comment]
Do you somehow intercept the `storage_root` generation?

**Comment by satellitex** [comment]
Yes. I want to see internal node on trie.

**Comment by bkchr** [comment]
So you maybe have a faulty implementation that does not calculate the correct storage root?

**Comment by satellitex** [comment]
Sorry, I mistake. A cause of the bug is `deposit_event` (https://github.com/stakedtechnologies/Plasm/blob/master/core/utxo/src/lib.rs#L419) (I remove here, don't show error.)

**Comment by satellitex** [comment]
I resolve this problem.
A cause of the bug is using `usize` type.

`usize` type is not fixed size. So it happened error.
