### ISSUE TITLE
Panic while stuck at finalizing block

### ISSUE THREAD

**Issue by vjoke** [paritytech/substrate#2518]
Panic location is the expect line 
```
fn storage(&self, key: &[u8]) -> Option<Vec<u8>> {
		let _guard = panic_handler::AbortGuard::new(true);
		self.overlay.storage(key).map(|x| x.map(|x| x.to_vec())).unwrap_or_else(||
			self.backend.storage(key).expect(EXT_NOT_ALLOWED_TO_FAIL))
	}
```
Below are the logs
```
2019-05-09 11:24:25.853 Protocol TRACE afg  Peer QmXyqPw58TRRfUj9uWhDZtDKEPGwVoeLXS39oAWiP47c5k updated view. Now at Round(667), SetId(1)
2019-05-09 11:24:26.003 Protocol TRACE afg  Peer QmXyqPw58TRRfUj9uWhDZtDKEPGwVoeLXS39oAWiP47c5k updated view. Now at Round(667), SetId(1)
2019-05-09 11:24:26.162 Protocol TRACE afg  Peer QmXyqPw58TRRfUj9uWhDZtDKEPGwVoeLXS39oAWiP47c5k updated view. Now at Round(667), SetId(1)
2019-05-09 11:24:26.342 Protocol TRACE afg  Peer QmXyqPw58TRRfUj9uWhDZtDKEPGwVoeLXS39oAWiP47c5k updated view. Now at Round(667), SetId(1)
2019-05-09 11:24:26.425 Protocol TRACE afg  Peer QmfRsAGQjcebwdD6MG69uEvoRvsgq5NhgVRK7PYvBBEbPU updated view. Now at Round(667), SetId(1)
2019-05-09 11:24:26.626 Protocol TRACE afg  Peer QmXyqPw58TRRfUj9uWhDZtDKEPGwVoeLXS39oAWiP47c5k updated view. Now at Round(667), SetId(1)
2019-05-09 11:24:26.678 Protocol TRACE afg  Peer QmfRsAGQjcebwdD6MG69uEvoRvsgq5NhgVRK7PYvBBEbPU updated view. Now at Round(667), SetId(1)
2019-05-09 11:24:26.847 Protocol TRACE afg  Peer QmXyqPw58TRRfUj9uWhDZtDKEPGwVoeLXS39oAWiP47c5k updated view. Now at Round(667), SetId(1)
2019-05-09 11:24:26.910 Protocol TRACE afg  Peer QmfRsAGQjcebwdD6MG69uEvoRvsgq5NhgVRK7PYvBBEbPU updated view. Now at Round(667), SetId(1)
2019-05-09 11:24:27.097 Protocol TRACE afg  Peer QmXyqPw58TRRfUj9uWhDZtDKEPGwVoeLXS39oAWiP47c5k updated view. Now at Round(667), SetId(1)
2019-05-09 11:24:27.127 Protocol TRACE afg  Peer QmfRsAGQjcebwdD6MG69uEvoRvsgq5NhgVRK7PYvBBEbPU updated view. Now at Round(667), SetId(1)
2019-05-09 11:24:27.208 tokio-runtime-worker-1 TRACE afg  Polling round 666, state = State { prevote_ghost: None, finalized: None, estimate: None, completable: false }, step = Some(Prevoted)
2019-05-09 11:24:27.496 Protocol TRACE afg  Peer QmfRsAGQjcebwdD6MG69uEvoRvsgq5NhgVRK7PYvBBEbPU updated view. Now at Round(667), SetId(1)
2019-05-09 11:24:27.558 Protocol TRACE afg  Peer QmXyqPw58TRRfUj9uWhDZtDKEPGwVoeLXS39oAWiP47c5k updated view. Now at Round(667), SetId(1)
2019-05-09 11:24:27.782 Protocol TRACE afg  Peer QmfRsAGQjcebwdD6MG69uEvoRvsgq5NhgVRK7PYvBBEbPU updated view. Now at Round(667), SetId(1)
2019-05-09 11:24:27.915 Protocol TRACE afg  Peer QmXyqPw58TRRfUj9uWhDZtDKEPGwVoeLXS39oAWiP47c5k updated view. Now at Round(667), SetId(1)
2019-05-09 11:24:28.115 Protocol TRACE afg  Peer QmfRsAGQjcebwdD6MG69uEvoRvsgq5NhgVRK7PYvBBEbPU updated view. Now at Round(667), SetId(1)
2019-05-09 11:24:28.265 Protocol TRACE afg  Peer QmXyqPw58TRRfUj9uWhDZtDKEPGwVoeLXS39oAWiP47c5k updated view. Now at Round(667), SetId(1)
2019-05-09 11:24:28.501 Protocol TRACE afg  Peer QmfRsAGQjcebwdD6MG69uEvoRvsgq5NhgVRK7PYvBBEbPU updated view. Now at Round(667), SetId(1)
2019-05-09 11:24:28.705 Protocol TRACE afg  Peer QmXyqPw58TRRfUj9uWhDZtDKEPGwVoeLXS39oAWiP47c5k updated view. Now at Round(667), SetId(1)
2019-05-09 11:24:28.716 tokio-runtime-worker-1 TRACE afg  Polling round 666, state = State { prevote_ghost: None, finalized: None, estimate: None, completable: false }, step = Some(Prevoted)
2019-05-09 11:24:28.716 tokio-runtime-worker-1 DEBUG afg  Waiting to import block 0xff2f…8875 before 1 votes can be imported. Possible fork?
2019-05-09 11:24:28.717 tokio-runtime-worker-1 DEBUG afg  Waiting to import block 0xccf0…06c5 before 1 votes can be imported. Possible fork?
2019-05-09 11:24:28.865 Protocol TRACE afg  Peer QmfRsAGQjcebwdD6MG69uEvoRvsgq5NhgVRK7PYvBBEbPU updated view. Now at Round(667), SetId(1)
2019-05-09 11:24:29.154 Protocol TRACE afg  Peer QmXyqPw58TRRfUj9uWhDZtDKEPGwVoeLXS39oAWiP47c5k updated view. Now at Round(667), SetId(1)
2019-05-09 11:24:29.155 Protocol TRACE afg  Peer QmfRsAGQjcebwdD6MG69uEvoRvsgq5NhgVRK7PYvBBEbPU updated view. Now at Round(667), SetId(1)
2019-05-09 11:24:29.406 Protocol TRACE afg  Peer QmfRsAGQjcebwdD6MG69uEvoRvsgq5NhgVRK7PYvBBEbPU updated view. Now at Round(667), SetId(1)
2019-05-09 11:24:29.582 Protocol TRACE afg  Peer QmXyqPw58TRRfUj9uWhDZtDKEPGwVoeLXS39oAWiP47c5k updated view. Now at Round(667), SetId(1)
2019-05-09 11:24:29.824 Protocol TRACE afg  Peer QmfRsAGQjcebwdD6MG69uEvoRvsgq5NhgVRK7PYvBBEbPU updated view. Now at Round(667), SetId(1)
2019-05-09 11:24:29.917 Protocol TRACE afg  Peer QmXyqPw58TRRfUj9uWhDZtDKEPGwVoeLXS39oAWiP47c5k updated view. Now at Round(667), SetId(1)
2019-05-09 11:24:30.114 tokio-runtime-worker-1 INFO substrate_basic_authorship::basic_authorship  Starting consensus session on top of parent 0x508b0331dbb45e6dc20770aecac137f4b1af77b30d6af4a4a60f64b05ebf1a7d
2019-05-09 11:24:30.197 Protocol TRACE afg  Peer QmfRsAGQjcebwdD6MG69uEvoRvsgq5NhgVRK7PYvBBEbPU updated view. Now at Round(667), SetId(1)
2019-05-09 11:24:30.697 Protocol TRACE afg  Peer QmfRsAGQjcebwdD6MG69uEvoRvsgq5NhgVRK7PYvBBEbPU updated view. Now at Round(667), SetId(1)
2019-05-09 11:24:30.799 tokio-runtime-worker-3 INFO substrate  Idle (1 peers), best: #1848 (0x508b…1a7d), finalized #1788 (0x02ed…0a9c), ⬇ 9.8kiB/s ⬆ 12.5kiB/s
2019-05-09 11:24:31.055 Protocol TRACE afg  Peer QmRDKCdjt6ZYEmNYUMhJnv9X5baACnvYspARst3fyyBerB updated view. Now at Round(668), SetId(1)
2019-05-09 11:24:31.354 tokio-runtime-worker-1 INFO substrate_basic_authorship::basic_authorship  Prepared block for proposing at 1849 [hash: 0xd781f57fbb1b55c22bcc006639a6c203c94357ae1fff44aa6d4be130af7e264b; parent_hash: 0x508b…1a7d; extrinsics: [0x812c…46c1]]
2019-05-09 11:24:31.354 tokio-runtime-worker-1 INFO substrate_consensus_aura  Pre-sealed block for proposal at 1849. Hash now 0x0e23b00ef323916da5a57ffefd6dde7d4176d391cee05344cb8a0c681f2a6b94, previously 0xd781f57fbb1b55c22bcc006639a6c203c94357ae1fff44aa6d4be130af7e264b.
2019-05-09 11:24:31.611 Protocol TRACE afg  Peer QmfRsAGQjcebwdD6MG69uEvoRvsgq5NhgVRK7PYvBBEbPU updated view. Now at Round(668), SetId(1)
2019-05-09 11:24:31.642 tokio-runtime-worker-3 TRACE afg  Polling round 666, state = State { prevote_ghost: None, finalized: None, estimate: None, completable: false }, step = Some(Prevoted)
2019-05-09 11:24:31.649 tokio-runtime-worker-3 INFO substrate_cli::informant  Reorg from #1802,0x74a4…ba6c to #1849,0x0e23…6b94, common ancestor #1792,0xb496…c665
2019-05-09 11:24:31.649 tokio-runtime-worker-3 INFO substrate  Imported #1849 (0x0e23…6b94)
2019-05-09 11:24:32.032 Protocol TRACE afg  Peer QmfRsAGQjcebwdD6MG69uEvoRvsgq5NhgVRK7PYvBBEbPU updated view. Now at Round(668), SetId(1)
2019-05-09 11:24:32.209 tokio-runtime-worker-0 TRACE afg  Polling round 666, state = State { prevote_ghost: None, finalized: None, estimate: None, completable: false }, step = Some(Prevoted)
2019-05-09 11:24:32.629 Protocol TRACE afg  Peer QmfRsAGQjcebwdD6MG69uEvoRvsgq5NhgVRK7PYvBBEbPU updated view. Now at Round(669), SetId(1)
2019-05-09 11:24:32.630 Protocol TRACE afg  Peer QmRDKCdjt6ZYEmNYUMhJnv9X5baACnvYspARst3fyyBerB updated view. Now at Round(669), SetId(1)
2019-05-09 11:24:33.110 Protocol TRACE afg  Peer QmfRsAGQjcebwdD6MG69uEvoRvsgq5NhgVRK7PYvBBEbPU updated view. Now at Round(669), SetId(1)
2019-05-09 11:24:33.237 Protocol TRACE afg  Peer QmRDKCdjt6ZYEmNYUMhJnv9X5baACnvYspARst3fyyBerB updated view. Now at Round(669), SetId(1)
2019-05-09 11:24:33.301 tokio-runtime-worker-1 TRACE afg  Got commit for round_number 668: target_number: 1823, target_hash: 0xa8c06f47a353faf1f3bcc2aff39b5fbb3445f385f52e867f3c09c2ae8093db09
2019-05-09 11:24:33.302 tokio-runtime-worker-1 DEBUG afg  Finalizing blocks up to (1823, 0xa8c0…db09)
2019-05-09 11:24:33.363 tokio-runtime-worker-1 TRACE afg  Imported commit for later round than current best 666, starting prospective round at 669
2019-05-09 11:24:33.363 tokio-runtime-worker-1 DEBUG afg  Voter Alice noting beginning of round (Round(669), SetId(1)) to network.
2019-05-09 11:24:33.363 tokio-runtime-worker-1 TRACE afg  Polling round 669, state = State { prevote_ghost: None, finalized: None, estimate: None, completable: false }, step = Some(Start)
2019-05-09 11:24:33.363 tokio-runtime-worker-1 TRACE afg  Polling round 666, state = State { prevote_ghost: None, finalized: None, estimate: None, completable: false }, step = Some(Prevoted)
2019-05-09 11:24:33.390 tokio-runtime-worker-0 TRACE afg  Polling round 669, state = State { prevote_ghost: None, finalized: None, estimate: None, completable: false }, step = Some(Start)
2019-05-09 11:24:33.391 tokio-runtime-worker-0 TRACE afg  Polling round 666, state = State { prevote_ghost: None, finalized: None, estimate: None, completable: false }, step = Some(Prevoted)
2019-05-09 11:24:33.657 Protocol TRACE afg  Peer QmfRsAGQjcebwdD6MG69uEvoRvsgq5NhgVRK7PYvBBEbPU updated view. Now at Round(669), SetId(1)
2019-05-09 11:24:33.713 tokio-runtime-worker-1 TRACE afg  Polling round 669, state = State { prevote_ghost: None, finalized: None, estimate: None, completable: false }, step = Some(Start)
2019-05-09 11:24:33.713 tokio-runtime-worker-1 TRACE afg  Polling round 666, state = State { prevote_ghost: None, finalized: None, estimate: None, completable: false }, step = Some(Prevoted)
2019-05-09 11:24:33.714 tokio-runtime-worker-1 DEBUG afg  Waiting to import block 0xff2f…8875 before 1 votes can be imported. Possible fork?
2019-05-09 11:24:33.714 tokio-runtime-worker-1 DEBUG afg  Waiting to import block 0xccf0…06c5 before 1 votes can be imported. Possible fork?
2019-05-09 11:24:34.161 tokio-runtime-worker-0 TRACE afg  Polling round 669, state = State { prevote_ghost: None, finalized: None, estimate: None, completable: false }, step = Some(Start)
2019-05-09 11:24:34.161 tokio-runtime-worker-0 TRACE afg  Got incoming message
2019-05-09 11:24:34.171 tokio-runtime-worker-0 TRACE afg  Got incoming message
2019-05-09 11:24:34.176 tokio-runtime-worker-0 TRACE afg  Polling round 666, state = State { prevote_ghost: None, finalized: None, estimate: None, completable: false }, step = Some(Prevoted)
2019-05-09 11:24:34.177 tokio-runtime-worker-0 TRACE afg  Polling round 669, state = State { prevote_ghost: None, finalized: None, estimate: None, completable: false }, step = Some(Start)
2019-05-09 11:24:34.177 tokio-runtime-worker-0 TRACE afg  Polling round 666, state = State { prevote_ghost: None, finalized: None, estimate: None, completable: false }, step = Some(Prevoted)
2019-05-09 11:24:34.194 tokio-runtime-worker-0 TRACE afg  Polling round 669, state = State { prevote_ghost: None, finalized: None, estimate: None, completable: false }, step = Some(Start)
2019-05-09 11:24:34.194 tokio-runtime-worker-0 TRACE afg  Got incoming message
2019-05-09 11:24:34.199 tokio-runtime-worker-0 TRACE afg  Polling round 666, state = State { prevote_ghost: None, finalized: None, estimate: None, completable: false }, step = Some(Prevoted)
2019-05-09 11:24:34.230 tokio-runtime-worker-0 TRACE afg  Polling round 669, state = State { prevote_ghost: Some((0xb4eb3cad8684423bacc7e9a23bae525f525b5228e58340e620bcd0726bdff466, 1834)), finalized: None, estimate: Some((0xb4eb3cad8684423bacc7e9a23bae525f525b5228e58340e620bcd0726bdff466, 1834)), completable: false }, step = Some(Start)
2019-05-09 11:24:34.231 tokio-runtime-worker-0 TRACE afg  Got incoming message
2019-05-09 11:24:34.240 tokio-runtime-worker-0 TRACE afg  Polling round 666, state = State { prevote_ghost: None, finalized: None, estimate: None, completable: false }, step = Some(Prevoted)
2019-05-09 11:24:34.260 tokio-runtime-worker-2 TRACE afg  Polling round 669, state = State { prevote_ghost: Some((0xb4eb3cad8684423bacc7e9a23bae525f525b5228e58340e620bcd0726bdff466, 1834)), finalized: None, estimate: Some((0xb4eb3cad8684423bacc7e9a23bae525f525b5228e58340e620bcd0726bdff466, 1834)), completable: false }, step = Some(Start)
2019-05-09 11:24:34.261 tokio-runtime-worker-2 TRACE afg  Got incoming message
2019-05-09 11:24:34.266 tokio-runtime-worker-2 TRACE afg  Polling round 666, state = State { prevote_ghost: None, finalized: None, estimate: None, completable: false }, step = Some(Prevoted)
2019-05-09 11:24:35.782 tokio-runtime-worker-2 INFO substrate  Idle (1 peers), best: #1849 (0x0e23…6b94), finalized #1823 (0xa8c0…db09), ⬇ 21.3kiB/s ⬆ 3.7kiB/s
2019-05-09 11:24:37.210 tokio-runtime-worker-2 TRACE afg  Polling round 669, state = State { prevote_ghost: Some((0xb4eb3cad8684423bacc7e9a23bae525f525b5228e58340e620bcd0726bdff466, 1834)), finalized: None, estimate: Some((0xb4eb3cad8684423bacc7e9a23bae525f525b5228e58340e620bcd0726bdff466, 1834)), completable: false }, step = Some(Start)
2019-05-09 11:24:37.210 tokio-runtime-worker-2 TRACE afg  Polling round 666, state = State { prevote_ghost: None, finalized: None, estimate: None, completable: false }, step = Some(Prevoted)

====================

stack backtrace:
   0: substrate_panic_handler::panic_hook::hdeb7b913bef10aa5 (0x10dfc22bb)
             at .cargo/git/checkouts/substrate-7e08433d4c370a21/2e2bcab/core/panic-handler/src/lib.rs:82
   1: substrate_panic_handler::set::{{closure}}::hc0a192efc94fa650 (0x10dfc1ec6)
             at .cargo/git/checkouts/substrate-7e08433d4c370a21/2e2bcab/core/panic-handler/src/lib.rs:31
   2: std::panicking::rust_panic_with_hook::h0c3c38b074f5c6b2 (0x10e4541b0)
             at src/libstd/panicking.rs:478
   3: std::panicking::continue_panic_fmt::h9b94c5dc7d74db71 (0x10e453bfc)
             at src/libstd/panicking.rs:381
   4: _rust_begin_unwind (0x10e453ae8)
             at src/libstd/panicking.rs:308
   5: core::panicking::panic_fmt::hc9cc9f057d27d1cd (0x10e471091)
             at src/libcore/panicking.rs:85
   6: core::result::unwrap_failed::h99438905fcf64bec (0x10beffe5e)
             at /rustc/d628c2e642c6f8f85f24dd5d7f49de89b95bf682/src/libcore/macros.rs:18
   7: core::result::Result<T,E>::expect::hc5a428b7f8e14afb (0x10bc78229)
             at /rustc/d628c2e642c6f8f85f24dd5d7f49de89b95bf682/src/libcore/result.rs:827
   8: <substrate_state_machine::ext::Ext<H,B,T,O> as substrate_state_machine::Externalities<H>>::storage::{{closure}}::h1d995fde0a20a526 (0x10b34ccb3)
             at .cargo/git/checkouts/substrate-7e08433d4c370a21/2e2bcab/core/state-machine/src/ext.rs:197
   9: core::option::Option<T>::unwrap_or_else::hc7677830174aafbc (0x10b882e4b)
             at /rustc/d628c2e642c6f8f85f24dd5d7f49de89b95bf682/src/libcore/option.rs:388
  10: <substrate_state_machine::ext::Ext<H,B,T,O> as substrate_state_machine::Externalities<H>>::storage::hd1ff88bf2d5e66a2 (0x10b34c973)
             at .cargo/git/checkouts/substrate-7e08433d4c370a21/2e2bcab/core/state-machine/src/ext.rs:196
  11: <substrate_executor::wasm_executor::FunctionExecutor<E> as wasmi::host::Externals>::invoke_index::{{closure}}::hc67361fceb25c349 (0x10af8c27c)
             at .cargo/git/checkouts/substrate-7e08433d4c370a21/2e2bcab/core/executor/src/wasm_executor.rs:332
  12: <substrate_executor::wasm_executor::FunctionExecutor<E> as wasmi::host::Externals>::invoke_index::hb749f7b2e81facb3 (0x10aeffc38)
             at .cargo/git/checkouts/substrate-7e08433d4c370a21/2e2bcab/core/executor/src/wasm_utils.rs:135
  13: wasmi::func::FuncInstance::invoke::h382998e1a3468038 (0x10b3d4a14)
             at .cargo/registry/src/github.com-1ecc6299db9ec823/wasmi-0.4.4/src/func.rs:149
  14: wasmi::runner::Interpreter::run_interpreter_loop::h210731c973ae6162 (0x10b321a06)
             at .cargo/registry/src/github.com-1ecc6299db9ec823/wasmi-0.4.4/src/runner.rs:304
  15: wasmi::runner::Interpreter::start_execution::hdd2d4e8d98bbeef7 (0x10b31c585)
             at .cargo/registry/src/github.com-1ecc6299db9ec823/wasmi-0.4.4/src/runner.rs:212
  16: wasmi::func::FuncInstance::invoke::h382998e1a3468038 (0x10b3d4a8b)
             at .cargo/registry/src/github.com-1ecc6299db9ec823/wasmi-0.4.4/src/func.rs:144
  17: wasmi::module::ModuleInstance::invoke_export::hd5d3876bc2ff9048 (0x10be71fd8)
             at .cargo/registry/src/github.com-1ecc6299db9ec823/wasmi-0.4.4/src/module.rs:642
  18: substrate_executor::wasm_executor::WasmExecutor::call_in_wasm_module_with_custom_signature::h57ff13f301d0bacc (0x10afc83b6)
             at .cargo/git/checkouts/substrate-7e08433d4c370a21/2e2bcab/core/executor/src/wasm_executor.rs:836
  19: substrate_executor::wasm_executor::WasmExecutor::call_in_wasm_module::h4434c5b61255bccc (0x10afc28eb)
             at .cargo/git/checkouts/substrate-7e08433d4c370a21/2e2bcab/core/executor/src/wasm_executor.rs:786
  20: <substrate_executor::native_executor::NativeExecutor<D> as substrate_state_machine::CodeExecutor<substrate_primitives::hasher::blake2::Blake2Hasher>>::call::{{closure}}::h82d59d69836a9497 (0x10b36df3d)
             at .cargo/git/checkouts/substrate-7e08433d4c370a21/2e2bcab/core/executor/src/native_executor.rs:234
  21: std::thread::local::LocalKey<T>::try_with::h910a963bbe723fdf (0x10b65e929)
             at /rustc/d628c2e642c6f8f85f24dd5d7f49de89b95bf682/src/libstd/thread/local.rs:299
  22: std::thread::local::LocalKey<T>::with::h984d3ac854d33f31 (0x10b64e33b)
             at /rustc/d628c2e642c6f8f85f24dd5d7f49de89b95bf682/src/libstd/thread/local.rs:245
  23: <substrate_executor::native_executor::NativeExecutor<D> as substrate_state_machine::CodeExecutor<substrate_primitives::hasher::blake2::Blake2Hasher>>::call::hd1cd80f71b1d017f (0x10b35626c)
             at .cargo/git/checkouts/substrate-7e08433d4c370a21/2e2bcab/core/executor/src/native_executor.rs:202
  24: substrate_state_machine::StateMachine<H,B,T,O,Exec>::execute_aux::h8fc6e1c9f17555ce (0x10b2274bf)
             at .cargo/git/checkouts/substrate-7e08433d4c370a21/2e2bcab/core/state-machine/src/lib.rs:424
  25: substrate_state_machine::StateMachine<H,B,T,O,Exec>::execute_using_consensus_failure_handler::h90af8ce60ba61a1a (0x10b26d76b)
             at .cargo/git/checkouts/substrate-7e08433d4c370a21/2e2bcab/core/state-machine/src/lib.rs:540
  26: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call::h0122a8f4ff8ae8a9 (0x10b7ae997)
             at .cargo/git/checkouts/substrate-7e08433d4c370a21/2e2bcab/core/client/src/call_executor.rs:276
  27: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at::h408fc941d58ceea8 (0x10be8e5c2)
             at .cargo/git/checkouts/substrate-7e08433d4c370a21/2e2bcab/core/client/src/client.rs:1406
  28: substrate_client::block_builder::api::runtime_decl_for_BlockBuilder::check_inherents_call_api_at::hbf8ced3647526ded (0x10b03e9af)
             at .cargo/git/checkouts/substrate-7e08433d4c370a21/2e2bcab/core/client/src/block_builder/api.rs:24
  29: <mychain_runtime::RuntimeApiImpl<RuntimeApiImplCall> as substrate_client::block_builder::api::BlockBuilder<<mychain_runtime::Runtime as sr_primitives::traits::GetNodeBlockType>::NodeBlock>>::BlockBuilder_check_inherents_runtime_api_impl::{{closure}}::h8f597b2b11bfe61e (0x10bd610a0)
             at projects/mychain/mychain/runtime/src/lib.rs:395
  30: mychain_runtime::RuntimeApiImpl<C>::call_api_at::h95f930bf00704208 (0x10bd4fb77)
             at projects/mychain/mychain/runtime/src/lib.rs:291
  31: <mychain_runtime::RuntimeApiImpl<RuntimeApiImplCall> as substrate_client::block_builder::api::BlockBuilder<<mychain_runtime::Runtime as sr_primitives::traits::GetNodeBlockType>::NodeBlock>>::BlockBuilder_check_inherents_runtime_api_impl::h2537c98c2aebfd08 (0x10bd60e1d)
             at projects/mychain/mychain/runtime/src/lib.rs:291
  32: substrate_client::block_builder::api::BlockBuilder::check_inherents::ha5de9c071cb1eb1a (0x10bd53cac)
             at .cargo/git/checkouts/substrate-7e08433d4c370a21/2e2bcab/core/client/src/block_builder/api.rs:24
  33: substrate_consensus_aura::AuraVerifier<C,E,P>::check_inherents::h7c24e1c7d2a09cb5 (0x10b9747db)
             at .cargo/git/checkouts/substrate-7e08433d4c370a21/2e2bcab/core/consensus/aura/src/lib.rs:529
  34: <substrate_consensus_aura::AuraVerifier<C,E,P> as substrate_consensus_common::import_queue::Verifier<B>>::verify::hd5fa2de460a9230a (0x10b96f568)
             at .cargo/git/checkouts/substrate-7e08433d4c370a21/2e2bcab/core/consensus/aura/src/lib.rs:637
  35: substrate_consensus_common::import_queue::import_single_block::h782efa56af0fb01a (0x10b0cb5be)
             at .cargo/git/checkouts/substrate-7e08433d4c370a21/2e2bcab/core/consensus/common/src/import_queue.rs:619
  36: substrate_consensus_common::import_queue::BlockImportWorker<B,V>::import_a_batch_of_blocks::h1989c15e8c807a5e (0x10b0d2ab3)
             at .cargo/git/checkouts/substrate-7e08433d4c370a21/2e2bcab/core/consensus/common/src/import_queue.rs:497
  37: substrate_consensus_common::import_queue::BlockImportWorker<B,V>::new::{{closure}}::hddb7d0e917bfca4a (0x10b0d472e)
             at .cargo/git/checkouts/substrate-7e08433d4c370a21/2e2bcab/core/consensus/common/src/import_queue.rs:458
  38: std::sys_common::backtrace::__rust_begin_short_backtrace::hbd1a64295193897f (0x10aec5ea0)
             at /rustc/d628c2e642c6f8f85f24dd5d7f49de89b95bf682/src/libstd/sys_common/backtrace.rs:136
  39: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h2828c62d3270bd42 (0x10bb014c0)
             at /rustc/d628c2e642c6f8f85f24dd5d7f49de89b95bf682/src/libstd/thread/mod.rs:469
  40: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h864a20a96d4fe990 (0x10b69c5f0)
             at /rustc/d628c2e642c6f8f85f24dd5d7f49de89b95bf682/src/libstd/panic.rs:309
  41: std::panicking::try::do_call::h5ed64f5d4f0ee1ab (0x10b3b4010)
             at /rustc/d628c2e642c6f8f85f24dd5d7f49de89b95bf682/src/libstd/panicking.rs:293
  42: ___rust_maybe_catch_panic (0x10e45cfde)
             at src/libpanic_unwind/lib.rs:85
  43: std::panicking::try::h6c6f381a60f1efca (0x10b3b0841)
             at /rustc/d628c2e642c6f8f85f24dd5d7f49de89b95bf682/src/libstd/panicking.rs:272
  44: std::panic::catch_unwind::ha99041b2893b09b3 (0x10b69cef0)
             at /rustc/d628c2e642c6f8f85f24dd5d7f49de89b95bf682/src/libstd/panic.rs:388
  45: std::thread::Builder::spawn_unchecked::{{closure}}::hebe87182dc8c6816 (0x10bb0100c)
             at /rustc/d628c2e642c6f8f85f24dd5d7f49de89b95bf682/src/libstd/thread/mod.rs:468
  46: core::ops::function::FnOnce::call_once{{vtable.shim}}::h1d0761def7ea30ac (0x10bb660d4)
             at /rustc/d628c2e642c6f8f85f24dd5d7f49de89b95bf682/src/libcore/ops/function.rs:231
  47: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hb1a81ed5f81e9aa8 (0x10e44064d)
             at /rustc/d628c2e642c6f8f85f24dd5d7f49de89b95bf682/src/liballoc/boxed.rs:704
  48: std::sys::unix::thread::Thread::new::thread_start::h56350991b625b32a (0x10e45c4fd)
             at /rustc/d628c2e642c6f8f85f24dd5d7f49de89b95bf682/src/liballoc/boxed.rs:704
  49: __pthread_body (0x7fff65fd86c0)
  50: __pthread_start (0x7fff65fd856c)

Thread 'ImportQueueWorker' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Invalid state root: 0xb00279a52278e1609d5df5633fe4cc5f5cc6200e0a585784a21f10d132302ed6"', src/libcore/result.rs:999
```

**Comment by bkchr** [comment]
Do you still have this problem?

**Comment by philipstanislaus** [comment]
@bkchr is this still an issue? Trying to determine if there are any red flags to launching Centrifuge's mainnet shortly. Thanks!

**Comment by bkchr** [comment]
I don't think so, do you have encountered this?
