### ISSUE TITLE
Thread 'main-tokio-3' panicked at 'attempt to negate with overflow'

### ISSUE THREAD

**Issue by kwingram25** [paritytech/substrate#2535]
```
stack backtrace:
   0: substrate_panic_handler::panic_hook::hfc21cef1e505c2bc (0x55a95ce36273)
             at core/panic-handler/src/lib.rs:82
   1: substrate_panic_handler::set::{{closure}}::h099e56d97f5fe427 (0x55a95ce36ee6)
             at core/panic-handler/src/lib.rs:31
   2: rust_panic_with_hook (0x55a95d4fa178)
             at src/libstd/panicking.rs:482
   3: continue_panic_fmt (0x55a95d4f9c11)
             at src/libstd/panicking.rs:385
   4: rust_begin_unwind (0x55a95d4f9af5)
   5: panic_fmt (0x55a95d5147ec)
             at src/libcore/panicking.rs:85
   6: panic (0x55a95d51472b)
             at src/libcore/panicking.rs:49
   7: substrate_peerset::Peerset::update_time::reput_tick::h9f1c2a4cb69fff6e (0x55a95bedc806)
             at core/peerset/src/lib.rs:263
   8: substrate_peerset::Peerset::update_time::h09ed151df2f7fbeb (0x55a95bedc364)
             at core/peerset/src/lib.rs:275
   9: substrate_peerset::Peerset::debug_info::hc6bdf12079a44818 (0x55a95bedd98d)
             at core/peerset/src/lib.rs:381
  10: <substrate_network_libp2p::custom_proto::behaviour::CustomProto<TMessage, TSubstream>>::peerset_debug_info::h2cb87ca4576c2090 (0x55a95abcb6cf)
             at /media/storage/Documents/substrate/core/network-libp2p/src/custom_proto/behaviour.rs:361
  11: <substrate_network_libp2p::behaviour::Behaviour<TMessage, TSubstream>>::peerset_debug_info::hbf2e8513f285351e (0x55a95af62b6f)
             at /media/storage/Documents/substrate/core/network-libp2p/src/behaviour.rs:163
  12: <substrate_network_libp2p::service_task::Service<TMessage>>::state::h8808aa78856ba541 (0x55a95ac10b42)
             at /media/storage/Documents/substrate/core/network-libp2p/src/service_task.rs:225
  13: <substrate_network::service::Service<B, S> as substrate_network::service::SyncProvider<B>>::network_state::h6e7578617ef0a56a (0x55a95a4d7a52)
             at /media/storage/Documents/substrate/core/network/src/service.rs:345
  14: substrate_cli::informant::start::{{closure}}::h6b45a8f7a75dcbad (0x55a95a1bad44)
             at /media/storage/Documents/substrate/core/cli/src/informant.rs:91
  15: <futures::stream::for_each::ForEach<S, F, U> as futures::future::Future>::poll::h003e0f6ba4117a7e (0x55a95a1499d8)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/stream/for_each.rs:46
  16: <futures::future::join::MaybeDone<A>>::poll::h6688fc090b0634a0 (0x55a95a1766a1)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/join.rs:153
  17: <futures::future::join::Join3<A, B, C> as futures::future::Future>::poll::h95a4c2c0c09ba2af (0x55a95a177d45)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/join.rs:67
  18: <exit_future::UntilExit<F> as futures::future::Future>::poll::hbf5dd3dd41b36485 (0x55a95a1b5f16)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/exit-future-0.1.4/src/lib.rs:25
  19: <futures::future::map::Map<A, F> as futures::future::Future>::poll::h4eacd1b4471cc0db (0x55a95a1aaf10)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/map.rs:30
  20: <alloc::boxed::Box<F> as futures::future::Future>::poll::hb939a7d89258df17 (0x55a95cd4d3d4)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/mod.rs:113
  21: <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}::hd4187b53784424c4 (0x55a95c8c75b3)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/task_impl/mod.rs:329
  22: <futures::task_impl::Spawn<T>>::enter::{{closure}}::haff00c35d29f5728 (0x55a95c8c7860)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/task_impl/mod.rs:399
  23: futures::task_impl::std::set::h297fd7ba6b4360ee (0x55a95c8f70f6)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/task_impl/std/mod.rs:78
  24: <futures::task_impl::Spawn<T>>::enter::h12ecdf480d371a98 (0x55a95c8c76ae)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/task_impl/mod.rs:399
  25: <futures::task_impl::Spawn<T>>::poll_fn_notify::hc6b5f9cc425bb3c5 (0x55a95c8c7417)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/task_impl/mod.rs:291
  26: <futures::task_impl::Spawn<T>>::poll_future_notify::h4a1023996281e785 (0x55a95c8c7557)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/task_impl/mod.rs:329
  27: tokio_threadpool::task::Task::run::{{closure}}::h6cdb3beb766b42e1 (0x55a95c8cca31)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/task/mod.rs:145
  28: core::ops::function::FnOnce::call_once::h188c1c4a76552975 (0x55a95c8dcd78)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libcore/ops/function.rs:231
  29: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hc4bc9dee1b2b059a (0x55a95c8c6628)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:309
  30: std::panicking::try::do_call::h6725a35248a9b05f (0x55a95c8c71d2)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:297
  31: __rust_maybe_catch_panic (0x55a95d500389)
             at src/libpanic_unwind/lib.rs:87
  32: std::panicking::try::h59808f572524b0de (0x55a95c8c6f0f)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:276
  33: std::panic::catch_unwind::h90b66d986173234e (0x55a95c8c6e30)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:388
  34: tokio_threadpool::task::Task::run::h44390cfe33def6ce (0x55a95c8cc24d)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/task/mod.rs:130
  35: tokio_threadpool::worker::Worker::run_task2::h11853f9b0b977883 (0x55a95c8ed19e)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:567
  36: tokio_threadpool::worker::Worker::run_task::h19f824855208ef7b (0x55a95c8eca63)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:459
  37: tokio_threadpool::worker::Worker::try_run_owned_task::hb7bf3e55302ad76c (0x55a95c8ec0e2)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:390
  38: tokio_threadpool::worker::Worker::try_run_task::ha1028c469627826c (0x55a95c8ebb1c)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:297
  39: tokio_threadpool::worker::Worker::run::h5f393b1b2e050fc5 (0x55a95c8eb975)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:241
  40: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}::{{closure}}::h391748e28190687a (0x55a95c87d931)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.19/src/runtime/threadpool/builder.rs:349
  41: tokio_trace_core::dispatcher::with_default::h109e5e68d1ed8e4d (0x55a95c87adfb)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-trace-core-0.1.0/src/dispatcher.rs:54
  42: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}::he081c71f81a2a4c0 (0x55a95c87d96c)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.19/src/runtime/threadpool/builder.rs:348
  43: tokio_timer::timer::handle::with_default::{{closure}}::ha35ba39eb888a3b1 (0x55a95c87fe14)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.10/src/timer/handle.rs:94
  44: <std::thread::local::LocalKey<T>>::try_with::h015d9ffbd19a4380 (0x55a95c87dfa6)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/thread/local.rs:300
  45: <std::thread::local::LocalKey<T>>::with::h3b3bf054e7cfa129 (0x55a95c87dc7b)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/thread/local.rs:246
  46: tokio_timer::timer::handle::with_default::hef7e55ee13347a82 (0x55a95c87fc51)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.10/src/timer/handle.rs:81
  47: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::hf0e1aedd6009cbfc (0x55a95c87d9d7)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.19/src/runtime/threadpool/builder.rs:347
  48: tokio_timer::clock::clock::with_default::{{closure}}::h5224723d7c156985 (0x55a95c8898a9)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.10/src/clock/clock.rs:141
  49: <std::thread::local::LocalKey<T>>::try_with::h6ba85419ac98ec48 (0x55a95c87e4fa)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/thread/local.rs:300
  50: <std::thread::local::LocalKey<T>>::with::h5b1be780b599ada1 (0x55a95c87dcfc)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/thread/local.rs:246
  51: tokio_timer::clock::clock::with_default::hf42d5c9f8e92e2d0 (0x55a95c889799)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.10/src/clock/clock.rs:124
  52: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::hc330a6b811df95af (0x55a95c87da23)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.19/src/runtime/threadpool/builder.rs:346
  53: tokio_reactor::with_default::{{closure}}::hacec6c83860b74c2 (0x55a95c87ef6a)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.9/src/lib.rs:237
  54: <std::thread::local::LocalKey<T>>::try_with::hf41c1e92e565b28e (0x55a95c87ec5e)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/thread/local.rs:300
  55: <std::thread::local::LocalKey<T>>::with::hfa6929e949488e61 (0x55a95c87dd7c)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/thread/local.rs:246
  56: tokio_reactor::with_default::ha55155e039a4f717 (0x55a95c87ed20)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.9/src/lib.rs:217
  57: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h15bd479eae20ed0c (0x55a95c87dacb)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.19/src/runtime/threadpool/builder.rs:345
  58: tokio_threadpool::callback::Callback::call::h05617c34d516dfe8 (0x55a95c8d1842)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/callback.rs:22
  59: tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}}::hfe9b0bed5bf9d228 (0x55a95c8eb5fe)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:127
  60: tokio_executor::global::with_default::{{closure}}::h7ef0213321defe35 (0x55a95c8e679a)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.7/src/global.rs:209
  61: <std::thread::local::LocalKey<T>>::try_with::h664247fa3b73d7c5 (0x55a95c8e7c0e)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/thread/local.rs:300
  62: <std::thread::local::LocalKey<T>>::with::hd133d81f9d5a1ab0 (0x55a95c8e71b2)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/thread/local.rs:246
  63: tokio_executor::global::with_default::h494fc3a448c22c73 (0x55a95c8e6675)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.7/src/global.rs:178
  64: tokio_threadpool::worker::Worker::do_run::{{closure}}::h4d67a4233c219f36 (0x55a95c8eb6bc)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:125
  65: <std::thread::local::LocalKey<T>>::try_with::h4bcb85ce06101917 (0x55a95c8e79a9)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/thread/local.rs:300
  66: <std::thread::local::LocalKey<T>>::with::hf6b79f0b181d4e64 (0x55a95c8e72ed)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/thread/local.rs:246
  67: tokio_threadpool::worker::Worker::do_run::h80a187142fe81385 (0x55a95c8eb4e7)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:116
  68: tokio_threadpool::pool::Pool::spawn_thread::{{closure}}::hba0b1661db3b1338 (0x55a95c8f1664)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/pool/mod.rs:344
  69: std::sys_common::backtrace::__rust_begin_short_backtrace::h0a065efe1aa5bc69 (0x55a95c8e6c0d)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/sys_common/backtrace.rs:135
  70: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h6d1383ed12d33ece (0x55a95c8d6211)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/thread/mod.rs:469
  71: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h496a37eb23161265 (0x55a95c8c65f1)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:309
  72: std::panicking::try::do_call::h163234a88c9e316a (0x55a95c8c715b)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:297
  73: __rust_maybe_catch_panic (0x55a95d500389)
             at src/libpanic_unwind/lib.rs:87
  74: std::panicking::try::hb9c39811c6dc6af5 (0x55a95c8c7045)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:276
  75: std::panic::catch_unwind::hb3b92edb310acfd5 (0x55a95c8c6e71)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:388
  76: std::thread::Builder::spawn_unchecked::{{closure}}::h799d3d2d2bf4b8e8 (0x55a95c8d5ff5)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/thread/mod.rs:468
  77: <F as alloc::boxed::FnBox<A>>::call_box::he0be002470ac4fc9 (0x55a95c8d8832)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/liballoc/boxed.rs:749
  78: call_once<(),()> (0x55a95d4ff6cd)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/liballoc/boxed.rs:759
      start_thread
             at src/libstd/sys_common/thread.rs:14
      thread_start
             at src/libstd/sys/unix/thread.rs:81
  79: start_thread (0x7f4b1b2836da)
  80: __clone (0x7f4b1ad9488e)
  81: <unknown> (0x0)

Thread 'main-tokio-3' panicked at 'attempt to negate with overflow', core/peerset/src/lib.rs:263

This is a bug. Please report it at:

	https://github.com/paritytech/substrate/issues/new
```

This has begun happening about every 15 minutes, running via `cargo run \-- --dev`

**Comment by pepyakin** [comment]
There are a few keywords that suggest that @tomaka might know what happens there.
