### ISSUE TITLE
Thread 'main-tokio-0' panicked

### ISSUE THREAD

**Issue by YaaMe** [paritytech/substrate#2893]
```
stack backtrace:
   0: substrate_panic_handler::panic_hook::hf07090ba21ef6216 (0x55a2f7a9c364)
             at core/panic-handler/src/lib.rs:82
   1: substrate_panic_handler::set::{{closure}}::h90ddf6b6982d8c1f (0x55a2f7a9cfb7)
             at core/panic-handler/src/lib.rs:31
   2: rust_panic_with_hook (0x55a2f81a7ba9)
             at src/libstd/panicking.rs:478
   3: continue_panic_fmt (0x55a2f81a7642)
             at src/libstd/panicking.rs:381
   4: begin_panic_fmt (0x55a2f81a758f)
             at src/libstd/panicking.rs:336
   5: finality_grandpa::voter::voting_round::VotingRound<H,N,E>::construct_prevote::h3d013614c7b23f0e (0x55a2f6085c6d)
             at /home/jie.zhu/workspace/substrate/<::std::macros::panic macros>:8
   6: finality_grandpa::voter::voting_round::VotingRound<H,N,E>::prevote::{{closure}}::hcd2dee0595b3acde (0x55a2f608a75a)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/finality-grandpa-0.7.2/src/voter/voting_round.rs:372
   7: finality_grandpa::voter::voting_round::VotingRound<H,N,E>::prevote::hb07065f0d3f86ca2 (0x55a2f6089901)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/finality-grandpa-0.7.2/src/voter/voting_round.rs:392
   8: finality_grandpa::voter::voting_round::VotingRound<H,N,E>::poll::h4f154a09cfd128af (0x55a2f6087fc9)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/finality-grandpa-0.7.2/src/voter/voting_round.rs:163
   9: finality_grandpa::voter::Voter<H,N,E,GlobalIn,GlobalOut>::process_best_round::h9bb1efe8d83ed136 (0x55a2f54ff3cd)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/finality-grandpa-0.7.2/src/voter/mod.rs:635
  10: <finality_grandpa::voter::Voter<H,N,E,GlobalIn,GlobalOut> as futures::future::Future>::poll::h10da771ee2f7d5f8 (0x55a2f54fc2cd)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/finality-grandpa-0.7.2/src/voter/mod.rs:740
  11: substrate_finality_grandpa::run_grandpa_voter::{{closure}}::{{closure}}::ha156ddf8df33eac4 (0x55a2f4de261b)
             at /home/jie.zhu/workspace/substrate/core/finality-grandpa/src/lib.rs:609
  12: <futures::future::poll_fn::PollFn<F> as futures::future::Future>::poll::hf2f4573e03e9911c (0x55a2f558815b)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/future/poll_fn.rs:43
  13: <futures::future::select2::Select2<A,B> as futures::future::Future>::poll::h5e88d7a893fbbf8a (0x55a2f4e4ac01)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/future/select2.rs:26
  14: futures::future::chain::Chain<A,B,C>::poll::h59d9234e1bb88246 (0x55a2f6065a80)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/future/chain.rs:26
  15: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll::h616377d9fa4e63d9 (0x55a2f568c76b)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/future/then.rs:32
  16: <futures::future::loop_fn::LoopFn<A,F> as futures::future::Future>::poll::h9fa3b4e76e6be7d7 (0x55a2f4fcb70b)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/future/loop_fn.rs:93
  17: <futures::future::map::Map<A,F> as futures::future::Future>::poll::h165d74bdbfa9b53d (0x55a2f5cbf7df)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/future/map.rs:30
  18: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::h2a7119600275cf3a (0x55a2f5084254)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/future/map_err.rs:30
  19: futures::future::chain::Chain<A,B,C>::poll::h3d01ef6485a175cf (0x55a2f6063c77)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/future/chain.rs:32
  20: <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll::h449412cb92db94fc (0x55a2f5f47514)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/future/and_then.rs:32
  21: <futures::future::select::Select<A,B> as futures::future::Future>::poll::hbd4cb06a062189cd (0x55a2f53e89e5)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/future/select.rs:48
  22: futures::future::chain::Chain<A,B,C>::poll::h456fe7d19a4e14f7 (0x55a2f60645af)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/future/chain.rs:26
  23: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll::hca45e4c105275ff2 (0x55a2f568c914)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/future/then.rs:32
  24: <alloc::boxed::Box<F> as futures::future::Future>::poll::h38d4135823dcb5d7 (0x55a2f799d5d5)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/future/mod.rs:113
  25: futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}::hf7ef39742acb444b (0x55a2f7432204)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/task_impl/mod.rs:329
  26: futures::task_impl::Spawn<T>::enter::{{closure}}::hb299345ea97f3d17 (0x55a2f7432481)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/task_impl/mod.rs:399
  27: futures::task_impl::std::set::h5d7716c8298e47fc (0x55a2f7461c57)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/task_impl/std/mod.rs:83
  28: futures::task_impl::Spawn<T>::enter::h488ce74c0f9ec40f (0x55a2f74322ff)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/task_impl/mod.rs:399
  29: futures::task_impl::Spawn<T>::poll_fn_notify::hb17d110b4bc086b4 (0x55a2f7432068)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/task_impl/mod.rs:291
  30: futures::task_impl::Spawn<T>::poll_future_notify::h4b1ce727f873fbcf (0x55a2f74321a8)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/task_impl/mod.rs:329
  31: tokio_threadpool::task::Task::run::{{closure}}::hdefb8d611e145d1f (0x55a2f7437442)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/task/mod.rs:145
  32: core::ops::function::FnOnce::call_once::hcde9fc90d1a8b983 (0x55a2f7447969)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/ops/function.rs:231
  33: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h34004a97e64351a2 (0x55a2f7431039)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panic.rs:309
  34: std::panicking::try::do_call::h41cb663902e91252 (0x55a2f7431d73)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panicking.rs:293
  35: __rust_maybe_catch_panic (0x55a2f81aceea)
             at src/libpanic_unwind/lib.rs:87
  36: std::panicking::try::h7b73f2947d66d4aa (0x55a2f7431be0)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panicking.rs:272
  37: std::panic::catch_unwind::hd1bad508b88a43cc (0x55a2f74319d1)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panic.rs:388
  38: tokio_threadpool::task::Task::run::h8aaf0c16f9bdbd0a (0x55a2f7436c9e)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/task/mod.rs:130
  39: tokio_threadpool::worker::Worker::run_task2::hc17c15964e850a0f (0x55a2f7457cff)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:567
  40: tokio_threadpool::worker::Worker::run_task::h14f4d9ae18385473 (0x55a2f74575c4)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:459
  41: tokio_threadpool::worker::Worker::try_run_owned_task::h5b9b35a6a6c1a60f (0x55a2f7456c43)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:390
  42: tokio_threadpool::worker::Worker::try_run_task::h8ad300200db971dd (0x55a2f745667d)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:297
  43: tokio_threadpool::worker::Worker::run::h82f66cf55e7de06a (0x55a2f74564d6)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:241
  44: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}::{{closure}}::hf8c123a971db70b0 (0x55a2f73ed1b2)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.21/src/runtime/threadpool/builder.rs:381
  45: tokio_trace_core::dispatcher::with_default::h944ab4eda29922f7 (0x55a2f73ef296)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-trace-core-0.2.0/src/dispatcher.rs:64
  46: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}::heb6bf5553b0f86c0 (0x55a2f73ed1ed)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.21/src/runtime/threadpool/builder.rs:380
  47: tokio_timer::timer::handle::with_default::{{closure}}::h692640311acb7aac (0x55a2f73ed685)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/timer/handle.rs:101
  48: std::thread::local::LocalKey<T>::try_with::h4c627eb4e731f569 (0x55a2f73fafc7)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/thread/local.rs:299
  49: std::thread::local::LocalKey<T>::with::hb4d22b85ac370c36 (0x55a2f73fab4c)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/thread/local.rs:245
  50: tokio_timer::timer::handle::with_default::h4ca6687f1c9e9e12 (0x55a2f73ed4c2)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/timer/handle.rs:84
  51: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::h02ca26a02f83282a (0x55a2f73ed258)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.21/src/runtime/threadpool/builder.rs:379
  52: tokio_timer::clock::clock::with_default::{{closure}}::hccaf6491dcbe8394 (0x55a2f73f98ea)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/clock/clock.rs:137
  53: std::thread::local::LocalKey<T>::try_with::h88e89db33e24a11f (0x55a2f73fb23b)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/thread/local.rs:299
  54: std::thread::local::LocalKey<T>::with::h150bcaddb4385490 (0x55a2f73fa9fd)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/thread/local.rs:245
  55: tokio_timer::clock::clock::with_default::ha3656fb37a45d3fd (0x55a2f73f97da)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/clock/clock.rs:117
  56: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::hac982f4b9ab7ae81 (0x55a2f73ed2a4)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.21/src/runtime/threadpool/builder.rs:378
  57: tokio_reactor::with_default::{{closure}}::hcd726c790946bc01 (0x55a2f73eda4b)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.9/src/lib.rs:237
  58: std::thread::local::LocalKey<T>::try_with::hbb26a82354cd140c (0x55a2f73fb74f)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/thread/local.rs:299
  59: std::thread::local::LocalKey<T>::with::h1daedb7e08925e24 (0x55a2f73faa7d)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/thread/local.rs:245
  60: tokio_reactor::with_default::h4a14fe18c610ce1a (0x55a2f73ed801)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.9/src/lib.rs:217
  61: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h7b8789327a1ece9f (0x55a2f73ed34c)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.21/src/runtime/threadpool/builder.rs:377
  62: tokio_threadpool::callback::Callback::call::hae32e6c23942fc0a (0x55a2f743c2c3)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/callback.rs:22
  63: tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}}::hb98ab0e33a3d05fb (0x55a2f745615f)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:127
  64: tokio_executor::global::with_default::{{closure}}::hd7d0aaab16e0ff2b (0x55a2f745104b)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.7/src/global.rs:209
  65: std::thread::local::LocalKey<T>::try_with::hee2daa33b99161cb (0x55a2f745305f)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/thread/local.rs:299
  66: std::thread::local::LocalKey<T>::with::hdf2dac596fe01e18 (0x55a2f7451fc3)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/thread/local.rs:245
  67: tokio_executor::global::with_default::h33736047c4e792b1 (0x55a2f7450f26)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.7/src/global.rs:178
  68: tokio_threadpool::worker::Worker::do_run::{{closure}}::h650543fd19fbce2b (0x55a2f745621d)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:125
  69: std::thread::local::LocalKey<T>::try_with::h1134e9b805c75ebd (0x55a2f74521ea)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/thread/local.rs:299
  70: std::thread::local::LocalKey<T>::with::h6f658f2c57c6ce93 (0x55a2f7451e7e)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/thread/local.rs:245
  71: tokio_threadpool::worker::Worker::do_run::h4045b279e8f01151 (0x55a2f7456048)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:116
  72: tokio_threadpool::pool::Pool::spawn_thread::{{closure}}::hc9065099e797f4ee (0x55a2f745c1c5)
             at /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/pool/mod.rs:344
  73: std::sys_common::backtrace::__rust_begin_short_backtrace::h3ef506f30a517da6 (0x55a2f745187e)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/sys_common/backtrace.rs:136
  74: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hae9d9cf422657c3a (0x55a2f74469d2)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/thread/mod.rs:470
  75: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h6a062aa466be3d64 (0x55a2f7431082)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panic.rs:309
  76: std::panicking::try::do_call::h3d8fb99a89ad715e (0x55a2f7431cfc)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panicking.rs:293
  77: __rust_maybe_catch_panic (0x55a2f81aceea)
             at src/libpanic_unwind/lib.rs:87
  78: std::panicking::try::h4f0966ca25feaba9 (0x55a2f7431ab6)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panicking.rs:272
  79: std::panic::catch_unwind::hd217e75cdfa22f29 (0x55a2f7431a12)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panic.rs:388
  80: std::thread::Builder::spawn_unchecked::{{closure}}::he5ba15e9e6214fd7 (0x55a2f74467c6)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/thread/mod.rs:469
  81: core::ops::function::FnOnce::call_once{{vtable.shim}}::he56a668fc9e248e4 (0x55a2f74477c4)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/ops/function.rs:231
  82: call_once<(),FnBox<()>> (0x55a2f819526f)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/liballoc/boxed.rs:702
  83: call_once<(),alloc::boxed::Box<FnBox<()>>> (0x55a2f81ac250)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/liballoc/boxed.rs:702
      start_thread
             at src/libstd/sys_common/thread.rs:14
      thread_start
             at src/libstd/sys/unix/thread.rs:80
  84: start_thread (0x7fe65ed1e6db)
  85: __clone (0x7fe65e82f88f)
  86: <unknown> (0x0)

Thread 'main-tokio-0' panicked at 'Previously known block 0x8c1ea2229e9888e3b305264f76ce41a05bb89e2678b6c68794fac99427ef90bc has disappeared from chain', /home/jie.zhu/.cargo/registry/src/github.com-1ecc6299db9ec823/finality-grandpa-0.7.2/src/voter/voting_round.rs:492

This is a bug. Please report it at:

	https://github.com/paritytech/substrate/issues/new

```

**Comment by bkchr** [comment]
What have you done? A more detailed error description would be nice.

**Comment by YaaMe** [comment]
`clone REPO` & Follow the `README.md`(Linux) & run `cargo run \-- --dev`
I'm sure commit `bdb87ddab9062cf2d1269e90736cab633d28fe52` is worked.So problem may appear in the last week commit.

**Comment by bkchr** [comment]
Did you tried to purge your chain?

**Comment by YaaMe** [comment]
got it `cargo run purge-chain dev`.
