### ISSUE TITLE
Storage root must match that calculated

### ISSUE THREAD

**Issue by zhang-dong-dong** [paritytech/substrate#4008]
#3989  The fix problem is here again，no stop just bucle logs, after stop and start , works well。
Startup script：
```
./polkadot --rpc-cors=all --pruning=archive  --validator
```

```
2019-11-04 07:21:58 Polling the network future took 2.608427841s
2019-11-04 07:22:01 Polling the network future took 1.685406482s
2019-11-04 07:22:02 Syncing  0.0 bps, target=#529139 (6 peers), best: #525501 (0x08ef…8a4a), finalized #525501 (0x08ef…8a4a), ⬇ 26.0kiB/s ⬆ 2.1kiB/s
Hash: given=a6b7f2b73433a191459367d8a4c7ab6e8e8ff9e7e91d9edbfae5ca3a399a8c83, expected=ccbf281d09ad89cffe5b1ed0b933c91d735b41eb9d8f42901637307a171585e1

====================

Version: 0.6.6-ccd1c6eb-x86_64-linux-gnu

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
   2: std::panicking::begin_panic
   3: srml_executive::Executive<System,Block,Context,UnsignedValidator,AllModules>::execute_block
   4: polkadot_runtime::api::dispatch
   5: std::panicking::try::do_call
   6: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
   7: substrate_executor::native_executor::safe_call
   8: std::thread::local::LocalKey<T>::with
   9: <polkadot_executor::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch
  10: std::thread::local::LocalKey<T>::with
  11: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_aux
  12: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_call_with_native_else_wasm_strategy
  13: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_using_consensus_failure_handler
  14: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state
  15: <&substrate_client::client::Client<B,E,Block,RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
  16: <substrate_finality_grandpa::import::GrandpaBlockImport<B,E,Block,RA,SC> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
  17: <substrate_consensus_babe::BabeBlockImport<B,E,Block,I,RA,PRA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
  18: substrate_consensus_common::import_queue::import_single_block
  19: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  20: <futures_util::future::then::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
  21: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  22: futures_executor::thread_pool::PoolState::work
  23: std::sys_common::backtrace::__rust_begin_short_backtrace
  24: std::panicking::try::do_call
  25: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  26: core::ops::function::FnOnce::call_once{{vtable.shim}}
  27: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  28: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:79
  29: start_thread
  30: __clone


Thread 'import-queue-worker-0' panicked at 'Storage root must match that calculated.', /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/595f18e/srml/executive/src/lib.rs:271

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new

Hash not equal
a6b7f2b73433a191459367d8a4c7ab6e8e8ff9e7e91d9edbfae5ca3a399a8c83
ccbf281d09ad89cffe5b1ed0b933c91d735b41eb9d8f42901637307a171585e1
panicked at 'Storage root must match that calculated.', /Users/gav/.cargo/git/checkouts/substrate-7e08433d4c370a21/595f18e/srml/executive/src/lib.rs:271:3
2019-11-04 07:22:05 Block import error:
Execution(Wasmi(Trap(Trap { kind: Unreachable })))
2019-11-04 07:22:05 Polling the network future took 3.215362915s
2019-11-04 07:22:09 Polling the network future took 2.293160164s
2019-11-04 07:22:10 Syncing  0.0 bps, target=#529139 (5 peers), best: #525501 (0x08ef…8a4a), finalized #525501 (0x08ef…8a4a), ⬇ 21.9kiB/s ⬆ 1.3kiB/s
2019-11-04 07:22:12 Libp2p => Query for [18, 32, 236, 236, 2, 232, 31, 46, 63, 98, 32, 80, 91, 95, 231, 198, 233, 103, 218, 189, 217, 11, 141, 24, 75, 227, 93, 155, 193, 187, 197, 103, 118, 19] timed out with 4 results
2019-11-04 07:22:13 Polling the network future took 2.917068732s
```

**Comment by marcio-diaz** [comment]
We forgot to include the fix in version `0.6.6`. Now, it should be fixed at `0.6` (and starting from the upcoming release `0.6.7`).

Please open a new issue if the problem persist in those versions.

**Comment by bkchr** [comment]
The used version is from yesterday: https://github.com/paritytech/polkadot/commit/ccd1c6ebce4b396e7ee202f7f011cdbb937349ab

It should already contain the fix. I think there are maybe more bugs in the code.

**Comment by marcio-diaz** [comment]
But substrate hash is `595f18e` right? And doesn't include the fix.

**Comment by bkchr** [comment]
@marcio-diaz ahh! Good catch! :) I didn't checked this at 4am on my mobile. Will close again.
