### ISSUE TITLE
Block import error: 'Storage root must match that claculated' from V0.6.17

### ISSUE THREAD

**Issue by plumex** [paritytech/substrate#4098]
This block import error looks happen again on v0.6.17, with different error msg.
the validator stop syncing blocks and keeping throw out exactly same msg below.

running inside docker, v0.6.17

> 2019-11-13 13:54:27 Block import error:\n
Execution(Wasmi(Trap(Trap { kind: Unreachable })))\n
Hash: given=f8ae12d38f450c6c8b7817f06ac57db63db9bb3cb835d9542eea50c65280841c, expected=1394e74969198de9ce408e0b2ec603dc3e919ef50093ed941b6d1d695c562998\n
\n
====================\n
\n
Version: 0.6.17-0929fe24-x86_64-linux-gnu\n
\n
stack backtrace:\n
   0: substrate_panic_handler::set::{{closure}}\n
   1: std::panicking::rust_panic_with_hook\n
             at src/libstd/panicking.rs:477\n
   2: std::panicking::begin_panic\n
   3: srml_executive::Executive\u003cSystem,Block,Context,UnsignedValidator,AllModules\u003e::execute_block\n
   4: polkadot_runtime::api::dispatch\n
   5: std::panicking::try::do_call\n
   6: __rust_maybe_catch_panic\n
             at src/libpanic_unwind/lib.rs:80\n
   7: substrate_executor::native_executor::safe_call\n
   8: std::thread::local::LocalKey\u003cT\u003e::with\n
   9: \u003cpolkadot_executor::Executor as substrate_executor::native_executor::NativeExecutionDispatch\u003e::dispatch\n
  10: std::thread::local::LocalKey\u003cT\u003e::with\n
  11: substrate_state_machine::StateMachine\u003cB,H,N,T,Exec\u003e::execute_aux\n
  12: substrate_state_machine::StateMachine\u003cB,H,N,T,Exec\u003e::execute_call_with_native_else_wasm_strategy\n
  13: substrate_state_machine::StateMachine\u003cB,H,N,T,Exec\u003e::execute_using_consensus_failure_handler\n
  14: \u003csubstrate_client::call_executor::LocalCallExecutor\u003cB,E\u003e as substrate_client::call_executor::CallExecutor\u003cBlock,substrate_primitives::hasher::blake2::Blake2Hasher\u003e\u003e::call_at_state\n
  15: \u003c\u0026substrate_client::client::Client\u003cB,E,Block,RA\u003e as substrate_consensus_common::block_import::BlockImport\u003cBlock\u003e\u003e::import_block\n
  16: \u003csubstrate_finality_grandpa::import::GrandpaBlockImport\u003cB,E,Block,RA,SC\u003e as substrate_consensus_common::block_import::BlockImport\u003cBlock\u003e\u003e::import_block\n
  17: \u003csubstrate_consensus_babe::BabeBlockImport\u003cB,E,Block,I,RA,PRA\u003e as substrate_consensus_common::block_import::BlockImport\u003cBlock\u003e\u003e::import_block\n
  18: substrate_consensus_common::import_queue::import_single_block\n
  19: \u003cfutures_util::future::poll_fn::PollFn\u003cF\u003e as core::future::future::Future\u003e::poll\n
  20: \u003cfutures_util::future::then::Then\u003cFut1,Fut2,F\u003e as core::future::future::Future\u003e::poll\n
  21: \u003cfutures_util::future::poll_fn::PollFn\u003cF\u003e as core::future::future::Future\u003e::poll\n
  22: futures_executor::thread_pool::PoolState::work\n
  23: std::sys_common::backtrace::__rust_begin_short_backtrace\n
  24: std::panicking::try::do_call\n
  25: __rust_maybe_catch_panic\n
             at src/libpanic_unwind/lib.rs:80\n
  26: core::ops::function::FnOnce::call_once{{vtable.shim}}\n
  27: \u003calloc::boxed::Box\u003cF\u003e as core::ops::function::FnOnce\u003cA\u003e\u003e::call_once\n
             at rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922\n
  28: \u003calloc::boxed::Box\u003cF\u003e as core::ops::function::FnOnce\u003cA\u003e\u003e::call_once\n
             at rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922\n
      std::sys_common::thread::start_thread\n
             at src/libstd/sys_common/thread.rs:13\n
      std::sys::unix::thread::Thread::new::thread_start\n
             at src/libstd/sys/unix/thread.rs:79\n
  29: start_thread\n
  30: __clone\n
\n
\n
Thread 'import-queue-worker-0' panicked at 'Storage root must match that calculated.', /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/aa937d9/srml/executive/src/lib.rs:292\n
\n
This is a bug. Please report it at:\n
\n
\u0009https://github.com/paritytech/polkadot/issues/new\n

Edit: add log for where is happen
> 2019-11-13 08:37:11 Idle (45 peers), best: #647563 (0xd656…fd6f), finalized #647562 (0x3cf9…a5dc), ⬇ 357.1kiB/s ⬆ 527.3kiB/s\n
2019-11-13 08:37:12 Imported #647564 (0x6779…7c4b)\n
2019-11-13 08:37:12 Starting parachain attestation session on top of parent 0x67797bec043a861f39d825b50c705ec742a6dfe2497c754bbd8ebc6cd8af7c4b. Local parachain duty is Some(LocalDuty { validation: Relay })\n
2019-11-13 08:37:16 Idle (45 peers), best: #647564 (0x6779…7c4b), finalized #647562 (0x3cf9…a5dc), ⬇ 229.5kiB/s ⬆ 279.1kiB/s\n
2019-11-13 08:37:19 Potential safety failure: reverting finalized block (647563, 0xb639899ca6eed2d1d57f05bd5908b7b09698a6efa6caff3ffd23337f558bedc4)\n

**Comment by plumex** [comment]
sorry, wrong repo. move to https://github.com/paritytech/polkadot/issues/582
