### ISSUE TITLE
"Address already in use" should be handled gracefully

### ISSUE THREAD

**Issue by iammelea** [paritytech/substrate#4233]
after update to 0.6.18 node crash, stop and start no solved
```
kusasentry  | 2019-11-27 13:20:13 ----------------------------
0|kusasentry  | 2019-11-27 13:20:13 This chain is not in any way
0|kusasentry  | 2019-11-27 13:20:13       endorsed by the       
0|kusasentry  | 2019-11-27 13:20:13      KUSAMA FOUNDATION      
0|kusasentry  | 2019-11-27 13:20:13 ----------------------------
0|kusasentry  | 2019-11-27 13:20:13 Node name: melea-◮👁◭ Vali→ [CdEm1E_5Yb9dr]
0|kusasentry  | 2019-11-27 13:20:13 Roles: SENTRY
0|kusasentry  | 2019-11-27 13:20:13 Highest known block at #850155
0|kusasentry  | 2019-11-27 13:20:13 Local node identity is: QmW7AsPownc6ZS7smc3SbMKioUuUk4ch7xxr7az1ajzxjH
0|kusasentry  | 2019-11-27 13:20:13 Unable to bind server to 127.0.0.1:9944. Trying random port.
0|kusasentry  | ====================
0|kusasentry  | Version: 
0|kusasentry  | 0.6.18-63d2c0e3-x86_64-linux-gnu
0|kusasentry  | stack backtrace:
0|kusasentry  |    0: substrate_panic_handler::set::{{closure}}
0|kusasentry  |    1: std::panicking::rust_panic_with_hook
0|kusasentry  |              at src/libstd/panicking.rs:477
0|kusasentry  |    2: std::panicking::continue_panic_fmt
0|kusasentry  |              at src/libstd/panicking.rs:380
0|kusasentry  |    3: rust_begin_unwind
0|kusasentry  |              at src/libstd/panicking.rs:307
0|kusasentry  |    4: core::panicking::panic_fmt
0|kusasentry  |              at src/libcore/panicking.rs:85
0|kusasentry  |    5: core::result::unwrap_failed
0|kusasentry  |              at src/libcore/result.rs:1165
0|kusasentry  |    6: <std::future::GenFuture<T> as core::future::future::Future>::poll
0|kusasentry  |    7: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
0|kusasentry  |    8: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll
0|kusasentry  |    9: futures::task_impl::std::set
0|kusasentry  |   10: std::panicking::try::do_call
0|kusasentry  |   11: __rust_maybe_catch_panic
0|kusasentry  |              at src/libpanic_unwind/lib.rs:80
0|kusasentry  |   12: tokio_threadpool::task::Task::run
0|kusasentry  |   13: tokio_threadpool::worker::Worker::run_task
0|kusasentry  |   14: tokio_threadpool::worker::Worker::run
0|kusasentry  |   15: std::thread::local::LocalKey<T>::with
0|kusasentry  |   
0|kusasentry  | 16: std::thread::local::LocalKey<T>::with
0|kusasentry  |   17: std::thread::local::LocalKey<T>::with
0|kusasentry  |   18: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
0|kusasentry  |   19: std::thread::local::LocalKey<T>::with
0|kusasentry  |   20: std::thread::local::LocalKey<T>::with
0|kusasentry  |   21: std::sys_common::backtrace::__rust_begin_short_backtrace
0|kusasentry  |   22: std::panicking::try::do_call
0|kusasentry  |   23: __rust_maybe_catch_panic
0|kusasentry  |              at src/libpanic_unwind/lib.rs:80
0|kusasentry  |   24: core::ops::function::FnOnce::call_once{{vtable.shim}}
0|kusasentry  |   25: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
0|kusasentry  |              at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
0|kusasentry  |   26: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
0|kusasentry  |              at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
0|kusasentry  |       std::sys_common::thread::start_thread
0|kusasentry  |              at src/libstd/sys_common/thread.rs:13
0|kusasentry  |       std::sys::unix::thread::Thread::new::thread_start
0|kusasentry  |              at src/libstd/sys/unix/thread.rs:79
0|kusasentry  |   27: start_thread
0|kusasentry  |   28: __clone
0|kusasentry  | Thread 'tokio-runtime-worker-1' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 98, kind: AddrInUse, message: "Address already in use" }', src/libcore/result.rs:1165
0|kusasentry  | This is a bug. Please report it at:
0|kusasentry  | 	https://github.com/paritytech/polkadot/issues/new
```

**Comment by tomaka** [comment]
I think that's the grafana server: https://github.com/paritytech/substrate/blob/d9ca9750dba018463d59459a3ee1c03b71ea2d46/client/grafana-data-source/src/server.rs#L118
