### ISSUE TITLE
Broken Pipe

### ISSUE THREAD

**Issue by damianoazzolini** [paritytech/substrate#4248]
I was looking into `substrate --help` using the `grep` command. I erroneously typed `substrate --help | grep` and this happened:
```
Version: 2.0.0-958c28824-x86_64-linux-gnu

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
   2: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   3: rust_begin_unwind
             at src/libstd/panicking.rs:311
   4: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed
             at src/libcore/result.rs:1084
   6: clap::errors::Error::exit
   7: clap::app::App::get_matches_from
   8: node_cli::run
   9: substrate::main
  10: std::rt::lang_start::{{closure}}
  11: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
      std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  12: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  13: std::panicking::try
             at src/libstd/panicking.rs:275
      std::panic::catch_unwind
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  14: main
  15: __libc_start_main
  16: _start


Thread 'main' panicked at 'Error writing Error to stdout: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', src/libcore/result.rs:1084

This is a bug. Please report it at:

        https://github.com/paritytech/substrate/issues/new
```

**Comment by pscott** [comment]
So the issue comes from the `println!` macro (in this particular case, a `println!` inside of Clap's codebase).
SIGPIPE gets silently ignored by Rust, and then when `println!` tries to `write()` it just crashes because it errors. There is an ongoing discussion as to whether Rust should or should not ignore SIGPIPE signal, or add an `unignore_sigpipe()` function... but nothing final as of now.

For reference, see this issue: https://github.com/rust-lang/rust/issues/46016

I think it's safe to say we can close this issue, but would prefer confirmation from @gnunicorn :)
