### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by marcio-diaz** [paritytech/substrate#4270]
I have a lot of free space on my disk, however a got this:

```
2019-12-02 16:00:42 Block import error:
Backend("IO error: No space left on deviceWhile appending to file: /home/marcio/.local/share/substrate/chains/dev/db/003249.log: No space left on device")

====================

Version: 2.0.0-1903f36f7-x86_64-linux-gnu

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
   2: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:375
   3: rust_begin_unwind
             at src/libstd/panicking.rs:304
   4: core::panicking::panic_fmt
             at src/libcore/panicking.rs:81
   5: core::result::unwrap_failed
             at src/libcore/result.rs:1189
   6: node_cli::cli::run
   7: substrate::main
   8: std::rt::lang_start::{{closure}}
   9: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
      std::panicking::try::do_call
             at src/libstd/panicking.rs:289
  10: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:81
  11: std::panicking::try
             at src/libstd/panicking.rs:267
      std::panic::catch_unwind
             at src/libstd/panic.rs:395
      std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  12: main
  13: __libc_start_main
  14: _start


Thread 'main' panicked at 'Failed to import block: ClientImport("Backend error: IO error: No space left on deviceWhile appending to file: /home/marcio/.local/share/substrate/chains/dev/db/003249.log: No space left on device")', src/libcore/result.rs:1189
```

**Comment by joshua-mir** [comment]
there's a chance that you have space remaining but you have no remaining inodes. what's the output of `df -i`?

**Comment by marcio-diaz** [comment]
It doesn't seems the case: `2022682` free.

**Comment by arkpar** [comment]
No error reported by `fsck` ?
