### ISSUE TITLE
Panic raised when syncing flamir fir 

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#4702]
I was running a substrate node built cfbb24cbd syncing flamir fir. At some point I had this:

```
2020-01-21 20:08:34 Syncing  4.5 bps, target=#933886 (4 peers), best: #1901 (0x8ec2…7c16), finalized #1536 (0xe729…c768), ⬇ 2.9kiB/s ⬆ 2.6kiB/s
2020-01-21 20:08:39 Syncing  3.7 bps, target=#933887 (4 peers), best: #1920 (0xfa9a…7465), finalized #1536 (0xe729…c768), ⬇ 10.8kiB/s ⬆ 7.8kiB/s

====================

Version: 2.0.0-cfbb24cbd-arm-linux-gnu

stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: sp_panic_handler::set::{{closure}}
   3: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:468
   4: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
   5: rust_begin_unwind
             at src/libstd/panicking.rs:302
   6: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
   7: soketto::base::Codec::encode_header
   8: std::future::poll_with_tls_context
   9: std::future::poll_with_tls_context
  10: <std::future::GenFuture<T> as core::future::future::Future>::poll
  11: <quicksink::SinkImpl<S,F,T,A,E> as futures_sink::Sink<A>>::poll_flush
  12: <futures_util::sink::with::With<Si,Item,U,Fut,F> as futures_sink::Sink<U>>::poll_flush
  13: <libp2p_core::either::EitherOutput<A,B> as futures_sink::Sink<I>>::poll_flush
  14: <futures_util::sink::map_err::SinkMapErr<Si,F> as futures_sink::Sink<Item>>::poll_flush
  15: sc_telemetry::worker::node::Node<TTrans>::poll
  16: sc_telemetry::worker::TelemetryWorker::poll
  17: <sc_telemetry::Telemetry as futures_core::stream::Stream>::poll_next
  18: futures_util::future::future::FutureExt::poll_unpin
  19: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  20: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  21: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll
  22: futures::task_impl::std::set
  23: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  24: futures_util::future::future::FutureExt::poll_unpin
  25: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  26: tokio::runtime::enter::Enter::block_on
  27: std::thread::local::LocalKey<T>::with
  28: std::thread::local::LocalKey<T>::with
  29: tokio::runtime::spawner::Spawner::enter
  30: std::thread::local::LocalKey<T>::with
  31: node_cli::cli::run_until_exit
  32: sc_cli::ParseAndPrepareRun<RP>::run
  33: node_cli::cli::run
  34: substrate::main
  35: std::rt::lang_start::{{closure}}
  36: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
      std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  37: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  38: std::panicking::try
             at src/libstd/panicking.rs:265
      std::panic::catch_unwind
             at src/libstd/panic.rs:396
      std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  39: main
  40: __libc_start_main


Thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `8`,
 right: `4`: destination and source slices have different lengths', src/libcore/slice/mod.rs:2217
```

cc @twittner because the panic is coming from soketto.

**Comment by twittner** [comment]
Soketto v0.3.2 which fixes this bug has been published to crates.io. See https://github.com/paritytech/soketto/pull/18 for details. Thanks @pepyakin for filing this issue!
