### ISSUE TITLE
Running the light client with --dev causes a crash

### ISSUE THREAD

**Issue by adilimroz** [paritytech/substrate#4758]
Built with `17aae385e16ae4ac9591db910d7b3258e44ec592`

**To reproduce**
substrate --dev --base-path /substrate-base-l/ --light

2020-01-29 12:56:27 Running in --dev mode, RPC CORS has been disabled.
2020-01-29 12:56:27 Substrate Node
2020-01-29 12:56:27   version 2.0.0-ff509dab2-x86_64-linux-gnu
2020-01-29 12:56:27   by Parity Technologies, 2017-2019
2020-01-29 12:56:27 Chain specification: Development
2020-01-29 12:56:27 Node name: imaginary-believe-0277
2020-01-29 12:56:27 Roles: LIGHT
2020-01-29 12:56:32 Initializing Genesis block/state (state: 0xd332…04a7, header-hash: 0xb105…8581)
2020-01-29 12:56:32 Loading GRANDPA authorities from genesis on what appears to be first startup.
2020-01-29 12:56:41 Loaded block-time = BabeConfiguration { slot_duration: 3000, epoch_length: 200, c: (1, 4), genesis_authorities: [(Public(d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d (5GrwvaEF...)), 1)], randomness: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], secondary_slots: true } milliseconds from genesis on first-launch
2020-01-29 12:56:41 Creating empty BABE epoch changes on what appears to be first startup.
 
====================
 
Version: 2.0.0-ff509dab2-x86_64-linux-gnu
 
stack backtrace:
   0: sp_panic_handler::panic_hook
             at primitives/panic-handler/src/lib.rs:148
   1: sp_panic_handler::set::{{closure}}
             at primitives/panic-handler/src/lib.rs:58
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
   3: rust_begin_unwind
             at src/libstd/panicking.rs:375
   4: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
   5: core::option::expect_failed
             at src/libcore/option.rs:1188
   6: core::option::Option<T>::expect
             at /rustc/19bd93467617a447c22ec32cc1cf14d40cb84ccf/src/libcore/option.rs:348
   7: <&mut dyn sp_externalities::Externalities as sp_io::crypto::Crypto>::ed25519_generate
             at primitives/io/src/lib.rs:375
   8: sp_io::crypto::ed25519_generate::{{closure}}
             at primitives/io/src/lib.rs:357
   9: sp_externalities::scope_limited::ext::with::{{closure}}
             at <::environmental::environmental macros>:32
  10: environmental::with::{{closure}}
             at /home/adilimroz/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.0.2/src/lib.rs:103
  11: std::thread::local::LocalKey<T>::try_with
             at /rustc/19bd93467617a447c22ec32cc1cf14d40cb84ccf/src/libstd/thread/local.rs:262
  12: std::thread::local::LocalKey<T>::with
             at /rustc/19bd93467617a447c22ec32cc1cf14d40cb84ccf/src/libstd/thread/local.rs:239
  13: environmental::with
             at /home/adilimroz/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.0.2/src/lib.rs:97
  14: sp_externalities::scope_limited::ext::with
             at <::environmental::environmental macros>:32
  15: sp_externalities::scope_limited::with_externalities
             at primitives/externalities/src/scope_limited.rs:36
  16: sp_io::crypto::ed25519_generate
             at primitives/io/src/lib.rs:357
  17: sp_application_crypto::ed25519::<impl sp_application_crypto::traits::RuntimePublic for sp_core::ed25519::Public>::generate_pair
             at primitives/application-crypto/src/ed25519.rs:46
  18: <sp_finality_grandpa::app::Public as sp_application_crypto::traits::RuntimeAppPublic>::generate_pair
             at <::sp_application_crypto::app_crypto_public_common macros>:55
  19: node_runtime::SessionKeys::generate
             at <::sp_runtime::traits::impl_opaque_keys macros>:29
  20: <node_runtime::Runtime as sp_session::runtime_decl_for_SessionKeys::SessionKeys<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<<pallet_indices::Module<node_runtime::Runtime> as sp_runtime::traits::StaticLookup>::Source,node_runtime::Call,sp_runtime::MultiSignature,(frame_system::CheckVersion<node_runtime::Runtime>, frame_system::CheckGenesis<node_runtime::Runtime>, frame_system::CheckEra<node_runtime::Runtime>, frame_system::CheckNonce<node_runtime::Runtime>, frame_system::CheckWeight<node_runtime::Runtime>, pallet_transaction_payment::ChargeTransactionPayment<node_runtime::Runtime>, pallet_contracts::CheckBlockGasLimit<node_runtime::Runtime>)>>>>::generate_session_keys
             at bin/node/runtime/src/lib.rs:733
  21: sp_session::runtime_decl_for_SessionKeys::generate_session_keys_native_call_generator::{{closure}}
             at primitives/session/src/lib.rs:26
  22: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call::{{closure}}::{{closure}}
             at client/executor/src/native_executor.rs:233
  23: std::panicking::try::do_call
             at /rustc/19bd93467617a447c22ec32cc1cf14d40cb84ccf/src/libstd/panicking.rs:292
  24: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  25: std::panicking::try
             at /rustc/19bd93467617a447c22ec32cc1cf14d40cb84ccf/src/libstd/panicking.rs:270
  26: std::panic::catch_unwind
             at /rustc/19bd93467617a447c22ec32cc1cf14d40cb84ccf/src/libstd/panic.rs:394
  27: sc_executor::native_executor::safe_call
             at client/executor/src/native_executor.rs:42
  28: sc_executor::native_executor::with_native_environment::{{closure}}
             at client/executor/src/native_executor.rs:51
  29: environmental::using::{{closure}}
             at /home/adilimroz/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.0.2/src/lib.rs:88
  30: std::thread::local::LocalKey<T>::try_with
             at /rustc/19bd93467617a447c22ec32cc1cf14d40cb84ccf/src/libstd/thread/local.rs:262
  31: std::thread::local::LocalKey<T>::with
             at /rustc/19bd93467617a447c22ec32cc1cf14d40cb84ccf/src/libstd/thread/local.rs:239
  32: environmental::using
             at /home/adilimroz/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.0.2/src/lib.rs:65
  33: sp_externalities::scope_limited::ext::using
             at <::environmental::environmental macros>:29
  34: sp_externalities::scope_limited::set_and_run_with_externalities
             at primitives/externalities/src/scope_limited.rs:29
  35: sc_executor::native_executor::with_native_environment
             at client/executor/src/native_executor.rs:51
  36: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call::{{closure}}
             at client/executor/src/native_executor.rs:233
  37: sc_executor::native_executor::NativeExecutor<D>::with_runtime::{{closure}}
             at client/executor/src/native_executor.rs:148
  38: std::thread::local::LocalKey<T>::try_with
             at /rustc/19bd93467617a447c22ec32cc1cf14d40cb84ccf/src/libstd/thread/local.rs:262
  39: std::thread::local::LocalKey<T>::with
             at /rustc/19bd93467617a447c22ec32cc1cf14d40cb84ccf/src/libstd/thread/local.rs:239
  40: sc_executor::native_executor::NativeExecutor<D>::with_runtime
             at client/executor/src/native_executor.rs:136
  41: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
             at client/executor/src/native_executor.rs:201
  42: sp_state_machine::StateMachine<B,H,N,T,Exec>::execute_aux
             at primitives/state-machine/src/lib.rs:263
  43: sp_state_machine::StateMachine<B,H,N,T,Exec>::execute_using_consensus_failure_handler
             at primitives/state-machine/src/lib.rs:433
  44: <sc_client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block,sp_core::hasher::blake2::Blake2Hasher>>::contextual_call
             at client/src/call_executor.rs:167
  45: <sc_client::light::call_executor::GenesisCallExecutor<B,Local> as sc_client_api::call_executor::CallExecutor<Block,sp_core::hasher::blake2::Blake2Hasher>>::contextual_call
             at client/src/light/call_executor.rs:123
  46: <sc_client::client::Client<B,E,Block,RA> as sp_api::CallRuntimeAt<Block>>::call_api_at
             at client/src/client.rs:1441
  47: sp_session::runtime_decl_for_SessionKeys::generate_session_keys_call_api_at
             at primitives/session/src/lib.rs:26
  48: <node_runtime::RuntimeApiImpl<RuntimeApiImplCall> as sp_session::SessionKeys<<node_runtime::Runtime as sp_runtime::traits::GetNodeBlockType>::NodeBlock>>::SessionKeys_generate_session_keys_runtime_api_impl::{{closure}}
             at bin/node/runtime/src/lib.rs:590
  49: node_runtime::RuntimeApiImpl<C>::call_api_at
             at bin/node/runtime/src/lib.rs:590
  50: <node_runtime::RuntimeApiImpl<RuntimeApiImplCall> as sp_session::SessionKeys<<node_runtime::Runtime as sp_runtime::traits::GetNodeBlockType>::NodeBlock>>::SessionKeys_generate_session_keys_runtime_api_impl
             at bin/node/runtime/src/lib.rs:590
  51: sp_session::SessionKeys::generate_session_keys
             at primitives/session/src/lib.rs:26
  52: sp_session::generate_initial_session_keys
             at primitives/session/src/lib.rs:56
  53: sc_service::builder::ServiceBuilder<TBl,TRtApi,TCfg,TGen,TCSExt,sc_client::client::Client<TBackend,TExec,TBl,TRtApi>,alloc::sync::Arc<sc_network::on_demand_layer::OnDemand<TBl>>,TSc,TImpQu,alloc::boxed::Box<dyn sc_network::config::FinalityProofRequestBuilder<TBl>+core::marker::Send+core::marker::Sync>,alloc::sync::Arc<dyn sc_network::chain::FinalityProofProvider<TBl>>,TNetP,TExPool,TRpc,TBackend>::build
             at client/service/src/builder.rs:774
  54: node_cli::service::new_light
             at bin/node/cli/src/service.rs:322
  55: node_cli::cli::run::{{closure}}
             at bin/node/cli/src/cli.rs:113
  56: sc_cli::ParseAndPrepareRun<RP>::run
             at client/cli/src/lib.rs:327
  57: node_cli::cli::run
             at bin/node/cli/src/cli.rs:100
  58: substrate::main
             at bin/node/cli/bin/main.rs:57
  59: std::rt::lang_start::{{closure}}
             at /rustc/19bd93467617a447c22ec32cc1cf14d40cb84ccf/src/libstd/rt.rs:67
  60: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
      std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  61: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  62: std::panicking::try
             at src/libstd/panicking.rs:270
      std::panic::catch_unwind
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  63: std::rt::lang_start
             at /rustc/19bd93467617a447c22ec32cc1cf14d40cb84ccf/src/libstd/rt.rs:67
  64: main
  65: __libc_start_main
  66: _start
 
 
Thread 'main' panicked at 'No `keystore` associated for the current context!', src/libcore/option.rs:1188
 
This is a bug. Please report it at:
 
    https://github.com/paritytech/substrate/issues/new
 
Error: Service(Client(Execution("Execution: Runtime error")))

**Comment by adilimroz** [comment]
Should be fixed with https://github.com/paritytech/substrate/pull/4757
Also, full node needs to be manually specified as `--bootnode`
