### ISSUE TITLE
Possible Allocation Error: `AllocatorOutOfSpace`

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#4826]
When I was trying to benchmark the runtime, I ran into an issue where a loop was causing `AllocatorOutOfSpace` errors.

You can reproduce this error by checking out this commit of Substrate:

https://github.com/paritytech/substrate/tree/7bd0ae11cdff291b805c9633f184e59f49d17e43

Run a node with `./target/release/substrate --dev --execution=Wasm --wasm-execution=Compiled`

Then call the RPC `state_call` with `IdentityBenchmarks_run_benchmarks`

You will notice that the processes starts, completes a few loops, then returns the alocator out of space error.

We added some print statements around these error points and noticed a consistent growth in `item_size` which ultimately causes this error.

To solve this problem, we can reduce the size of the loop (before we hit a memory error), or we can use `native` execution.

Let me know if I can provide any more details.

**Comment by shawntabrizi** [comment]
Still facing this issue actually on the latest stuff. Large loops do not seem to be good here:

```
====================

Version: 2.0.0-5ee888f90-x86_64-macos

stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: sp_panic_handler::set::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::continue_panic_fmt
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::result::unwrap_failed
   8: <<sp_io::allocator::HostFunctions as sp_wasm_interface::HostFunctions>::host_functions::ExtAllocatorMallocVersion1 as sp_wasm_interface::Function>::execute
   9: std::panicking::try::do_call
  10: __rust_maybe_catch_panic
  11: sc_executor_wasmtime::trampoline::stub_fn


Thread 'main' panicked at 'Failed to allocate memory: "Allocator ran out of space"', src/libcore/result.rs:1165

This is a bug. Please report it at:

        https://github.com/paritytech/substrate/issues/new

Error: Service(Other("Error executing runtime benchmark: FunctionExecution(\"ext_allocator_malloc_version_1\", \"Failed to allocate memory: \\\"Allocator ran out of space\\\"\")"))

**Comment by kianenigma** [comment]
Similar issue:

```
====================

Version: 2.0.0-2ed0a1d90-x86_64-macos

stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: sp_panic_handler::set::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::continue_panic_fmt
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::result::unwrap_failed
   8: <<sp_io::allocator::HostFunctions as sp_wasm_interface::HostFunctions>::host_functions::ExtAllocatorMallocVersion1 as sp_wasm_interface::Function>::execute
   9: std::panicking::try::do_call
  10: __rust_maybe_catch_panic
  11: sc_executor_wasmtime::trampoline::stub_fn


Thread 'event.loop0' panicked at 'Failed to allocate memory: "Allocator ran out of space"', src/libcore/result.rs:1165

```

**Comment by kianenigma** [comment]
> @shawntabrizi shawntabrizi assigned pepyakin 1 hour ago

maybe @cmichi can also help.
