### ISSUE TITLE
Telemetry being used after finalisation takedown

### ISSUE THREAD

**Issue by phillux** [paritytech/substrate#490]
```
stack backtrace:
   0:     0x55ae56cee15c - backtrace::backtrace::trace::h9ffedbc1a03a0b56
   1:     0x55ae56ced722 - backtrace::capture::Backtrace::new::h7733a389fd8dd5ff
   2:     0x55ae5654af40 - substrate_cli::panic_hook::panic_hook::hbdbe874002aae473
   3:     0x55ae5654ac58 - core::ops::function::Fn::call::h2041fd09a0b7a800
   4:     0x55ae56e21135 - std::panicking::rust_panic_with_hook::h55e258944e31bc6d
                        at libstd/panicking.rs:467
   5:     0x55ae56c084a6 - std::panicking::begin_panic::h8c046d364a3ce1b1
   6:     0x55ae56c07b78 - <slog_scope::NoGlobalLoggerSet as slog::Drain>::log::h1c9297901e35c8f5
   7:     0x55ae562ac99c - <substrate_service::Service<Components>>::new::{{closure}}::{{closure}}::hcfed55df2f9e9dfa
   8:     0x55ae562a1309 - <std::thread::local::LocalKey<T>>::with::h02bae4ff600d856d
   9:     0x55ae5628cf04 - <substrate_service::Service<Components>>::new::{{closure}}::he6335c5ab77930c2
  10:     0x55ae56befb46 - <substrate_telemetry::TelemetryWriter as std::io::Write>::flush::h4be73b4ac7bb3d06
  11:     0x55ae56bef449 - <substrate_telemetry::TelemetryWriter as std::io::Write>::write::h811464c88f7aade1
  12:     0x55ae56bee410 - std::io::Write::write_all::h3c6409a0c6c2a74d
  13:     0x55ae56bfd527 - <slog_json::Json<W> as slog::Drain>::log::h1f1f725c158edb10
  14:     0x55ae56bf0a02 - std::sys_common::backtrace::__rust_begin_short_backtrace::hdec45496ac7fd38a
  15:     0x55ae56c053c5 - std::panicking::try::do_call::h58c515c077c694ce
  16:     0x55ae56e42c79 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:105
  17:     0x55ae56bf7210 - <F as alloc::boxed::FnBox<A>>::call_box::ha3ef0333c1bc3a0e
  18:     0x55ae56e371fa - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h9ad6846d840ae36b
                        at /checkout/src/liballoc/boxed.rs:648
                         - std::sys_common::thread::start_thread::h2698ca233d3cb229
                        at libstd/sys_common/thread.rs:24
  19:     0x55ae56e21745 - std::sys::unix::thread::Thread::new::thread_start::h80e954ec963e7e56
                        at libstd/sys/unix/thread.rs:90
  20:     0x7fcccdf62074 - start_thread
  21:     0x7fcccda7f53e - clone
  22:                0x0 - <unknown>

Thread '<unnamed>' panicked at 'slog-scope: No logger set. Use `slog_scope::set_global_logger` or `slog_scope::scope`.', /home/XXXX/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-scope-4.0.1/lib.rs:123
```

When I quit Polkadot (ctrl+C), I received this error

**Comment by gavofyork** [comment]
haven't seen this in a long while. reopen if it comes back.
