### ISSUE TITLE
Bug starting a staging network

### ISSUE THREAD

**Issue by avalverdero** [paritytech/substrate#4901]
Hi!

I am trying to start a Staging chain network using substrate parity repository, The compilation works fine but I received this error when I am starting the node :

```
./target/release/substrate --chain staging --base-path /tmp/a
2020-02-12 10:08:12 Substrate Node
2020-02-12 10:08:12   version 2.0.0-00a400f82-x86_64-linux-gnu
2020-02-12 10:08:12   by Parity Technologies <admin@parity.io>, 2017-2020
2020-02-12 10:08:12 Chain specification: Staging Testnet
2020-02-12 10:08:12 Node name: addicted-plants-5259
2020-02-12 10:08:12 Roles: FULL

====================

Version: 2.0.0-00a400f82-x86_64-linux-gnu

stack backtrace:
   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
   2: rust_begin_unwind
             at src/libstd/panicking.rs:375
   3: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
   4: core::slice::slice_index_len_fail
             at src/libcore/slice/mod.rs:2674
   5: node_cli::chain_spec::testnet_genesis
   6: node_cli::chain_spec::staging_testnet_config_genesis
   7: core::ops::function::Fn::call
   8: <sc_chain_spec::chain_spec::ChainSpec<G,E> as sp_runtime::BuildStorage>::build_storage
   9: sc_client::client::Client<B,E,Block,RA>::new
  10: sc_client_db::new_client
  11: sc_service::builder::ServiceBuilder<(),(),TGen,TCSExt,(),(),(),(),(),(),(),(),(),()>::new_full
  12: node_cli::service::new_full
  13: sc_cli::runtime::run_service_until_exit
  14: sc_cli::run_node
  15: sc_cli::params::RunCmd::run
  16: sc_cli::run
  17: node_cli::command::run
  18: substrate::main
  19: std::rt::lang_start::{{closure}}
  20: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
      std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  21: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  22: std::panicking::try
             at src/libstd/panicking.rs:270
      std::panic::catch_unwind
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  23: main
  24: __libc_start_main
  25: _start


Thread 'main' panicked at 'index 3 out of range for slice of length 1', src/libcore/slice/mod.rs:2674

This is a bug. Please report it at:

	https://github.com/paritytech/substrate/issues/new

```

I'm not sure if is a substrate problem but probably we can fix it modifying substrate code.

Thanks in advance and kind regards.

**Comment by avalverdero** [comment]
Duplicated #4899
