### ISSUE TITLE
Version: 2.0.0-alpha.1 - Storage root must match that calculated

### ISSUE THREAD

**Issue by avalverdero** [paritytech/substrate#5437]
Hi!

I have problems using substrate to create our own blockchain. I receive this error:

```
Version: 2.0.0-alpha.1-cf1d632-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:476
   2: std::panicking::begin_panic
   3: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules>::execute_block
   4: <node_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<<pallet_indices::Module<node_runtime::Runtime> as sp_runtime::traits::StaticLookup>::Source,node_runtime::Call,sp_runtime::MultiSignature,(frame_system::CheckVersion<node_runtime::Runtime>, frame_system::CheckGenesis<node_runtime::Runtime>, frame_system::CheckEra<node_runtime::Runtime>, frame_system::CheckNonce<node_runtime::Runtime>, frame_system::CheckWeight<node_runtime::Runtime>, pallet_transaction_payment::ChargeTransactionPayment<node_runtime::Runtime>, pallet_contracts::CheckBlockGasLimit<node_runtime::Runtime>)>>>>::execute_block
   5: sp_api::runtime_decl_for_Core::execute_block_native_call_generator::{{closure}}
   6: std::panicking::try::do_call
   7: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
   8: std::thread::local::LocalKey<T>::with
   9: std::thread::local::LocalKey<T>::with
  10: sp_state_machine::StateMachine<B,H,N,Exec>::execute_aux
  11: sp_state_machine::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
  12: <sc_client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
  13: <sc_client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  14: sp_api::runtime_decl_for_Core::execute_block_call_api_at
  15: sp_api::Core::execute_block
  16: <&sc_client::client::Client<B,E,Block,RA> as sp_consensus::block_import::BlockImport<Block>>::import_block
  17: <sc_finality_grandpa::import::GrandpaBlockImport<B,E,Block,RA,SC> as sp_consensus::block_import::BlockImport<Block>>::import_block
  18: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sp_consensus::block_import::BlockImport<Block>>::import_block
  19: sp_consensus::import_queue::import_single_block
  20: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  21: futures_util::future::future::chain::Chain<Fut1,Fut2,Data>::poll
  22: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  23: futures_executor::thread_pool::PoolState::work
  24: std::sys_common::backtrace::__rust_begin_short_backtrace
  25: std::panicking::try::do_call
  26: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  27: core::ops::function::FnOnce::call_once{{vtable.shim}}
  28: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
  29: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:80
  30: start_thread
  31: __clone


Thread 'import-queue-worker-0' panicked at 'Storage root must match that calculated.', <::std::macros::panic macros>:2

This is a bug. Please report it at:

	https://github.com/paritytech/substrate/issues/new

```

I am using chain parameter in staging mode.

Do you can help me?

Many thanks!

**Comment by bkchr** [comment]
Please update to the latest alpha and if that does not help, we need to know what you are doing. (please post a link to your runtime and a description on how to reproduce)

**Comment by avalverdero** [comment]
OK @bkchr, Monday I will upgrade to latest versión and come back with more feedback.

Many thanks!

**Comment by bkchr** [comment]
ANy update?

**Comment by avalverdero** [comment]
Sorry for late response, with the latest alpha and starting the network from zero, the problem has not arisen again.

Many thanks!
