### ISSUE TITLE
Thread 'event.loop0' panicked at 'Expected always-serializable type; qed: Error("u128 is not supported", line: 0, column: 0)', src/libcore/result.rs:1165

### ISSUE THREAD

**Issue by IPSE-TEAM** [paritytech/substrate#5450]
```bash
Version: 2.0.0-f72015c-x86_64-linux-gnu

stack backtrace:
   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   2: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
   3: rust_begin_unwind
             at src/libstd/panicking.rs:307
   4: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed
             at src/libcore/result.rs:1165
   6: <futures::future::map::Map<A,F> as futures::future::Future>::poll
   7: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
   8: <futures::future::either::Either<A,B> as futures::future::Future>::poll
   9: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  10: futures::future::chain::Chain<A,B,C>::poll
  11: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  12: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  13: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  14: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  15: <futures::future::select::Select<A,B> as futures::future::Future>::poll
  16: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  17: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  18: futures::task_impl::std::set
  19: std::panicking::try::do_call
  20: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  21: tokio_threadpool::task::Task::run
  22: tokio_threadpool::worker::Worker::run_task
  23: tokio_threadpool::worker::Worker::run
  24: tokio_reactor::with_default
  25: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  26: std::thread::local::LocalKey<T>::with
  27: std::thread::local::LocalKey<T>::with
  28: std::sys_common::backtrace::__rust_begin_short_backtrace
  29: std::panicking::try::do_call
  30: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  31: core::ops::function::FnOnce::call_once{{vtable.shim}}
  32: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
  33: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:79
  34: start_thread
  35: __clone


Thread 'event.loop0' panicked at 'Expected always-serializable type; qed: Error("u128 is not supported", line: 0, column: 0)', src/libcore/result.rs:1165
```

**Comment by bkchr** [comment]
I assume you call some RPC method?

**Comment by Irish-bee** [comment]
> I assume you call some RPC method?

yes, i call my custom RPC method, And the error occur. 
```
impl<C, AccountId, CurrencyId, Index, Balance, Block> IcoApi<AccountId, CurrencyId, Index, Balance> for FullIco<C, Block> 
where
    C: sp_api::ProvideRuntimeApi<Block>,
    C: HeaderBackend<Block>,
    C: Send + Sync + 'static,
    C::Api: IcoAmountApi<Block, AccountId, CurrencyId, Index, Balance>,
    Block: traits::Block,
    AccountId: Clone + std::fmt::Display + Codec,
    Index: Clone + std::fmt::Display + Codec + Send + traits::AtLeast32Bit + 'static,
    CurrencyId: Clone + std::fmt::Display + Codec,
    Balance: Clone + std::fmt::Display + Codec + Send + traits::AtLeast32Bit + 'static,
{
    fn can_release_amount(&self, account: AccountId, currency_id: CurrencyId, index: Index) -> FutureResult<Balance> {
        let get_release_amount = || {
            let api = self.client.runtime_api();
            let best = self.client.info().best_hash;
            let at = BlockId::hash(best);

            let amount = api.can_release_amount(&at, account, currency_id, index).map_err(|e| RpcError {
                code: ErrorCode::ServerError(Error::RuntimeError.into()),
                message: "Unable to dry run extrinsic.".into(),
                data: Some(format!("{:?}", e).into()),
            })?;
            Ok(amount)

        };

        Box::new(result(get_release_amount()))
    }
```
