### ISSUE TITLE
Crash on first invocation of Polkadot

### ISSUE THREAD

**Issue by samskiter** [paritytech/substrate#567]
```
stack backtrace:
   0:        0x105a1904e - backtrace::backtrace::trace::h1e5a0011abbb33b2
   1:        0x105a1824c - _$LT$backtrace..capture..Backtrace$u20$as$u20$core..default..Default$GT$::default::h28a561f1033dc8f5
   2:        0x105a182cd - backtrace::capture::Backtrace::new::h1c3fc463634bb61e
   3:        0x104fd9959 - substrate_cli::panic_hook::panic_hook::h3e0135909b42f5ad
   4:        0x104fd966b - core::ops::function::Fn::call::hbc83727544cc1030
   5:        0x105b5e69e - std::panicking::rust_panic_with_hook::h81c4f3add25e6667
   6:        0x105b5e41e - std::panicking::continue_panic_fmt::hfa057b7c1de88179
   7:        0x105b5e0a8 - rust_begin_unwind
   8:        0x105ba1cc1 - core::panicking::panic_fmt::h4c82aa4e615d52a2
   9:        0x104dc9f3d - core::result::unwrap_failed::h6a50694e03336876
  10:        0x104cfc409 - _$LT$substrate_state_machine..ext..Ext$LT$$u27$a$C$$u20$B$GT$$u20$as$u20$substrate_state_machine..Externalities$GT$::storage::h6da9f575fd704709
  11:        0x104d2e5f3 - _$LT$substrate_client..call_executor..LocalCallExecutor$LT$B$C$$u20$E$GT$$u20$as$u20$substrate_client..call_executor..CallExecutor$LT$Block$GT$$GT$::runtime_version::h27ca822e60b85806
  12:        0x104eb8d0e - _$LT$substrate_client..client..Client$LT$B$C$$u20$E$C$$u20$Block$GT$$u20$as$u20$substrate_bft..Authorities$LT$Block$GT$$GT$::authorities::hee19fe9c255ed822
  13:        0x104d14d49 - _$LT$substrate_bft..BftService$LT$B$C$$u20$P$C$$u20$I$GT$$GT$::build_upon::hda7d5a94f7d4765b
  14:        0x104dd4152 - _$LT$futures..future..chain..Chain$LT$A$C$$u20$B$C$$u20$C$GT$$GT$::poll::h613355c16488b302
  15:        0x104d1fccd - _$LT$futures..future..map..Map$LT$A$C$$u20$F$GT$$u20$as$u20$futures..future..Future$GT$::poll::hb612c921c88fee92
  16:        0x104d8feac - futures::task_impl::std::set::hb4d29f5f842a32a0
  17:        0x104d14b6a - tokio::executor::current_thread::CurrentRunner::set_spawn::h272462496b533c0d
  18:        0x104dd883b - _$LT$tokio..executor..current_thread..scheduler..Scheduler$LT$U$GT$$GT$::tick::he3cb5726c90ec545
  19:        0x104d16172 - _$LT$tokio..executor..current_thread..Entered$LT$$u27$a$C$$u20$P$GT$$GT$::block_on::h151312e497c101cd
  20:        0x104d5d146 - _$LT$std..thread..local..LocalKey$LT$T$GT$$GT$::with::h8dff734156799729
  21:        0x104d5e315 - _$LT$std..thread..local..LocalKey$LT$T$GT$$GT$::with::hbf726c58fdc80de1
  22:        0x104d5ad4d - _$LT$std..thread..local..LocalKey$LT$T$GT$$GT$::with::h1c1ba68f4bf11b1a
  23:        0x104d5a9a8 - _$LT$std..thread..local..LocalKey$LT$T$GT$$GT$::with::h0103d5636f942a67
  24:        0x104d85708 - tokio::runtime::current_thread::runtime::Runtime::block_on::h4d94dce5758d231b
  25:        0x104dbba22 - std::sys_common::backtrace::__rust_begin_short_backtrace::h40b74f03cf330f6d
  26:        0x104d07d9d - std::panicking::try::do_call::haa94bc952087aeee (.llvm.12774340002830960411)
  27:        0x105b6a7ae - __rust_maybe_catch_panic
  28:        0x104dcaa26 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h5c97992cbadc038a
  29:        0x105b5d4f7 - std::sys_common::thread::start_thread::h78b1dd404be976ad
  30:        0x105b44a68 - std::sys::unix::thread::Thread::new::thread_start::h27c6becca8cf44e0
  31:     0x7fff69053660 - _pthread_body
  32:     0x7fff6905350c - _pthread_start

Thread '<unnamed>' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Invalid state root: 0x1ae8…aa2d"', libcore/result.rs:945

```

Full output:

```
$ polkadot --validator --key hello123
2018-08-14 21:18:20 Parity ·:· Polkadot
2018-08-14 21:18:20   version 0.2.4-f4f82af6-x86_64-macos
2018-08-14 21:18:20   by Parity Technologies, 2017, 2018
2018-08-14 21:18:20 Chain specification: Krumme Lanke
2018-08-14 21:18:20 Node name: faded-camp-4755
2018-08-14 21:18:20 Roles: AUTHORITY
2018-08-14 21:18:20 Initialising Genesis block/state (state: 609a…3f5a, header-hash: 6c5a…71cc)
2018-08-14 21:18:20 Best block: #0
2018-08-14 21:18:20 Local node address is: /ip4/0.0.0.0/tcp/30333/p2p/QmTYH3vgEiZgZbT3jHQcej4mzHjtS5BxJnzK8JJBsNsacJ
2018-08-14 21:18:21 New external node address: /ip4/<REDACTED>/tcp/30333/p2p/QmTYH3vgEiZgZbT3jHQcej4mzHjtS5BxJnzK8JJBsNsacJ
2018-08-14 21:18:21 Using authority key 5FB7JBJf7J9xngNkdiAzU2vTsvmWmmijtZZzpMwwhS3HLL3r
2018-08-14 21:18:21 Idle (0 peers), best: #0 (6c5a…71cc)
2018-08-14 21:18:21 Reconnected to telemetry server: wss://telemetry.polkadot.io/submit/
2018-08-14 21:18:21 Finishing future for proto [100, 111, 116] with PeerId(QmWCnXrhM1in1qPqVT3rDXQEJHedAzbPDMimdjqy2P9fGn) => Err(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })
2018-08-14 21:18:21 Node PeerId(QmWCnXrhM1in1qPqVT3rDXQEJHedAzbPDMimdjqy2P9fGn) with peer ID 1 through protocol [100, 111, 116] disconnected
2018-08-14 21:18:21 Finishing future for proto [100, 111, 116] with PeerId(QmWzYU5X1NpFrprD1YZF5Lcj9aE5WF4QEg5FpvQx5XGWG7) => Err(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })
2018-08-14 21:18:21 Node PeerId(QmWzYU5X1NpFrprD1YZF5Lcj9aE5WF4QEg5FpvQx5XGWG7) with peer ID 3 through protocol [100, 111, 116] disconnected
2018-08-14 21:18:26 Syncing, target=#1077215 (3 peers), best: #308 (9023…6ffc)
2018-08-14 21:18:31 Syncing, target=#1077216 (3 peers), best: #512 (c2cc…7458)
2018-08-14 21:18:35 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-14 21:18:35 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-14 21:18:36 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-14 21:18:36 Syncing, target=#1077217 (3 peers), best: #512 (c2cc…7458)
2018-08-14 21:18:36 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-14 21:18:37 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-14 21:18:37 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-14 21:18:38 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-14 21:18:38 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-14 21:18:39 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-14 21:18:39 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-14 21:18:40 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-14 21:18:40 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-14 21:18:41 Syncing, target=#1077218 (3 peers), best: #512 (c2cc…7458)
2018-08-14 21:18:41 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-14 21:18:41 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-14 21:18:42 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-14 21:18:42 Finishing future for proto [100, 111, 116] with PeerId(QmY33GW69TnTsdQWjAkxJR1GrWTdeV1PmzzcSmUay4HvAB) => Err(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })
2018-08-14 21:18:42 Node PeerId(QmY33GW69TnTsdQWjAkxJR1GrWTdeV1PmzzcSmUay4HvAB) with peer ID 2 through protocol [100, 111, 116] disconnected
2018-08-14 21:18:42 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-14 21:18:43 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-14 21:18:43 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-14 21:18:44 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-14 21:18:44 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-14 21:18:45 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-14 21:18:45 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-14 21:18:46 Syncing, target=#1077218 (2 peers), best: #721 (6331…4314)
2018-08-14 21:18:46 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-14 21:18:46 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-14 21:18:47 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-14 21:18:51 Syncing, target=#1077219 (2 peers), best: #1050 (a925…6412)
2018-08-14 21:18:56 Syncing, target=#1077220 (2 peers), best: #1339 (4c06…206a)
2018-08-14 21:18:58 New external node address: /ip4/127.0.0.1/tcp/30333/p2p/QmTYH3vgEiZgZbT3jHQcej4mzHjtS5BxJnzK8JJBsNsacJ
2018-08-14 21:19:00 Finishing future for proto [100, 111, 116] with PeerId(Qmbiafvoy3WmEDMixvx4t7tjDLnaJ7S8rDKFs4auxWbVpQ) => Err(Custom { kind: UnexpectedEof, error: StringError("unexpected end of file") })
2018-08-14 21:19:00 Node PeerId(Qmbiafvoy3WmEDMixvx4t7tjDLnaJ7S8rDKFs4auxWbVpQ) with peer ID 27 through protocol [100, 111, 116] disconnected
2018-08-14 21:19:01 Syncing, target=#1077221 (2 peers), best: #1642 (4ad4…942d)
2018-08-14 21:19:06 Syncing, target=#1077222 (2 peers), best: #1967 (44c2…26d1)
2018-08-14 21:19:11 Syncing, target=#1077223 (2 peers), best: #2285 (ceaf…d001)
2018-08-14 21:19:16 Syncing, target=#1077224 (2 peers), best: #2573 (7553…f6dc)
2018-08-14 21:19:21 Syncing, target=#1077224 (2 peers), best: #2879 (491d…b586)
2018-08-14 21:19:26 Syncing, target=#1077225 (2 peers), best: #3175 (58c1…b059)
2018-08-14 21:19:31 Syncing, target=#1077226 (3 peers), best: #3475 (ca37…61ba)
2018-08-14 21:19:36 Syncing, target=#1077227 (3 peers), best: #3793 (9d27…383d)
2018-08-14 21:19:41 Syncing, target=#1077227 (3 peers), best: #4092 (fc23…164f)
2018-08-14 21:19:46 Syncing, target=#1077228 (3 peers), best: #4313 (b43d…a375)
2018-08-14 21:19:49 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-14 21:19:50 Finishing future for proto [100, 111, 116] with PeerId(QmY33GW69TnTsdQWjAkxJR1GrWTdeV1PmzzcSmUay4HvAB) => Ok(())
2018-08-14 21:19:50 Node PeerId(QmY33GW69TnTsdQWjAkxJR1GrWTdeV1PmzzcSmUay4HvAB) with peer ID 53 through protocol [100, 111, 116] disconnected
2018-08-14 21:19:51 Syncing, target=#1077229 (3 peers), best: #4623 (627b…4b1b)

====================

stack backtrace:
   0:        0x105a1904e - backtrace::backtrace::trace::h1e5a0011abbb33b2
   1:        0x105a1824c - _$LT$backtrace..capture..Backtrace$u20$as$u20$core..default..Default$GT$::default::h28a561f1033dc8f5
   2:        0x105a182cd - backtrace::capture::Backtrace::new::h1c3fc463634bb61e
   3:        0x104fd9959 - substrate_cli::panic_hook::panic_hook::h3e0135909b42f5ad
   4:        0x104fd966b - core::ops::function::Fn::call::hbc83727544cc1030
   5:        0x105b5e69e - std::panicking::rust_panic_with_hook::h81c4f3add25e6667
   6:        0x105b5e41e - std::panicking::continue_panic_fmt::hfa057b7c1de88179
   7:        0x105b5e0a8 - rust_begin_unwind
   8:        0x105ba1cc1 - core::panicking::panic_fmt::h4c82aa4e615d52a2
   9:        0x104dc9f3d - core::result::unwrap_failed::h6a50694e03336876
  10:        0x104cfc409 - _$LT$substrate_state_machine..ext..Ext$LT$$u27$a$C$$u20$B$GT$$u20$as$u20$substrate_state_machine..Externalities$GT$::storage::h6da9f575fd704709
  11:        0x104d2e5f3 - _$LT$substrate_client..call_executor..LocalCallExecutor$LT$B$C$$u20$E$GT$$u20$as$u20$substrate_client..call_executor..CallExecutor$LT$Block$GT$$GT$::runtime_version::h27ca822e60b85806
  12:        0x104eb8d0e - _$LT$substrate_client..client..Client$LT$B$C$$u20$E$C$$u20$Block$GT$$u20$as$u20$substrate_bft..Authorities$LT$Block$GT$$GT$::authorities::hee19fe9c255ed822
  13:        0x104d14d49 - _$LT$substrate_bft..BftService$LT$B$C$$u20$P$C$$u20$I$GT$$GT$::build_upon::hda7d5a94f7d4765b
  14:        0x104dd4152 - _$LT$futures..future..chain..Chain$LT$A$C$$u20$B$C$$u20$C$GT$$GT$::poll::h613355c16488b302
  15:        0x104d1fccd - _$LT$futures..future..map..Map$LT$A$C$$u20$F$GT$$u20$as$u20$futures..future..Future$GT$::poll::hb612c921c88fee92
  16:        0x104d8feac - futures::task_impl::std::set::hb4d29f5f842a32a0
  17:        0x104d14b6a - tokio::executor::current_thread::CurrentRunner::set_spawn::h272462496b533c0d
  18:        0x104dd883b - _$LT$tokio..executor..current_thread..scheduler..Scheduler$LT$U$GT$$GT$::tick::he3cb5726c90ec545
  19:        0x104d16172 - _$LT$tokio..executor..current_thread..Entered$LT$$u27$a$C$$u20$P$GT$$GT$::block_on::h151312e497c101cd
  20:        0x104d5d146 - _$LT$std..thread..local..LocalKey$LT$T$GT$$GT$::with::h8dff734156799729
  21:        0x104d5e315 - _$LT$std..thread..local..LocalKey$LT$T$GT$$GT$::with::hbf726c58fdc80de1
  22:        0x104d5ad4d - _$LT$std..thread..local..LocalKey$LT$T$GT$$GT$::with::h1c1ba68f4bf11b1a
  23:        0x104d5a9a8 - _$LT$std..thread..local..LocalKey$LT$T$GT$$GT$::with::h0103d5636f942a67
  24:        0x104d85708 - tokio::runtime::current_thread::runtime::Runtime::block_on::h4d94dce5758d231b
  25:        0x104dbba22 - std::sys_common::backtrace::__rust_begin_short_backtrace::h40b74f03cf330f6d
  26:        0x104d07d9d - std::panicking::try::do_call::haa94bc952087aeee (.llvm.12774340002830960411)
  27:        0x105b6a7ae - __rust_maybe_catch_panic
  28:        0x104dcaa26 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h5c97992cbadc038a
  29:        0x105b5d4f7 - std::sys_common::thread::start_thread::h78b1dd404be976ad
  30:        0x105b44a68 - std::sys::unix::thread::Thread::new::thread_start::h27c6becca8cf44e0
  31:     0x7fff69053660 - _pthread_body
  32:     0x7fff6905350c - _pthread_start

Thread '<unnamed>' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Invalid state root: 0x1ae8…aa2d"', libcore/result.rs:945

This is a bug. Please report it at:

    https://github.com/paritytech/polkadot/issues/new
```

**Comment by samskiter** [comment]
On retry with just `polkadot` it is successfully proceeding with a full sync

**Comment by gavofyork** [comment]
(duplicate of #487)
