### ISSUE TITLE
Librocksdb fails to build on Windows

### ISSUE THREAD

**Issue by Swader** [paritytech/substrate#5682]
Related to #5681 

Rocksdb now needs `llvm-config` which is not included in the ready-made installations of LLVM. One has to compile it manually in Debug mode to get that binary. Once past this hurdle, the following error stops compilation of rocksdb:

```bash
   Compiling parity-multiaddr v0.7.3
error: failed to run custom build command for `librocksdb-sys v6.6.4`

Caused by:
  process didn't exit successfully: `C:\Users\Swader\repos\polkadot\target\release\build\librocksdb-sys-7252674dc0acc032\build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=rocksdb/
cargo:rerun-if-changed=snappy/
cargo:rerun-if-changed=lz4/
cargo:rerun-if-changed=zstd/
cargo:rerun-if-changed=zlib/
cargo:rerun-if-changed=bzip2/

--- stderr
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include\vadefs.h:61:33: error: expected ';' after top level declarator
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:96:1: error: expected identifier
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:96:20: error: expected ';' after top level declarator
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:193:29: error: expected ';' after top level declarator
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:194:30: error: typedef redefinition with different types ('__int64' (aka 'unsigned int') vs 'long long')
C:\Program Files\LLVM\lib\clang\11.0.0\include\stddef.h:35:26: note: previous definition is here
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:344:51: error: unknown type name 'uintptr_t'
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:345:67: error: unknown type name 'uintptr_t'
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:349:8: error: unknown type name 'uintptr_t'
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:357:1: error: a parameter list without types is only allowed in a function definition
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:357:18: error: expected ';' after top level declarator
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include\vadefs.h:61:33: error: expected ';' after top level declarator, err: true
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:96:1: error: expected identifier, err: true
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:96:20: error: expected ';' after top level declarator, err: true
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:193:29: error: expected ';' after top level declarator, err: true
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:194:30: error: typedef redefinition with different types ('__int64' (aka 'unsigned int') vs 'long long'), err: true
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:344:51: error: unknown type name 'uintptr_t', err: true
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:345:67: error: unknown type name 'uintptr_t', err: true
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:349:8: error: unknown type name 'uintptr_t', err: true
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:357:1: error: a parameter list without types is only allowed in a function definition, err: true
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include\vcruntime.h:357:18: error: expected ';' after top level declarator, err: true
thread 'main' panicked at 'unable to generate rocksdb bindings: ()', C:\Users\Swader\.cargo\registry\src\github.com-1ecc6299db9ec823\librocksdb-sys-6.6.4\build.rs:30:20

stack backtrace:
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace/dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src\libstd\sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src\libstd\sys_common/backtrace.rs:59
   4: core::fmt::write
             at src\libcore\fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src\libstd\io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src\libstd\sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src\libstd\sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src\libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src\libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src\libstd/panicking.rs:472
  11: rust_begin_unwind
             at src\libstd/panicking.rs:380
  12: core::panicking::panic_fmt
             at src\libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src\libcore/option.rs:1199
  14: build_script_build::main
  15: std::rt::lang_start::{{closure}}
  16: std::rt::lang_start_internal::{{closure}}
             at src\libstd/rt.rs:52
  17: std::panicking::try::do_call
             at src\libstd/panicking.rs:305
  18: __rust_maybe_catch_panic
             at src\libpanic_unwind/lib.rs:86
  19: std::panicking::try
             at src\libstd/panicking.rs:281
  20: std::panic::catch_unwind
             at src\libstd/panic.rs:394
  21: std::rt::lang_start_internal
             at src\libstd/rt.rs:51
  22: main
  23: _tmainCRTStartup
  24: mainCRTStartup
  25: unit_addrs_search
  26: unit_addrs_search
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

A recommended solution is providing pre-built binaries of librocksdb which get downloaded by a pre-compile script on `cargo build --release`, similar to [this approach](https://github.com/status-im/nimbus) (see fetch-dlls). So on Windows, users would run something like `./fetch-dlls.sh & cargo build --release`.

**Comment by bkchr** [comment]
This is an upstream issue in a crate that we don't control. Please report your build problems to the rocksdb issue tracker.

**Comment by General-Beck** [comment]
`choco install llvm` like https://github.com/openethereum/openethereum/blob/master/.github/workflows/build.yml#L71

**Comment by Swader** [comment]
@General-Beck are you saying choco-installed LLVM makes rocksdb compile for you? To me it still fails.
