### ISSUE TITLE
wasm trap: call stack exhausted

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#5751]
While syncing from scratch with `--wasm-execution compiled`, I got this in my logs:

```
2020-04-23 11:41:01 panicked at 'Transaction trie root must be valid.', /home/volt/.cargo/git/checkouts/substrate-7e08433d4c370a21/d9fca7e/frame/executive/src/lib.rs:192:3
2020-04-23 11:41:01 Block prepare storage changes error:
Execution(Other("Wasm execution trapped: wasm trap: call stack exhausted, source location: @-"))
2020-04-23 11:41:01 💔 Error importing block 0xd1f838d9ed7a691b6cce3fd9dd1feb8dcb5e2ade751c99958041a3b71b3cfeba: Err(Other(ClientImport("Import failed: Execution: Wasm execution trapped: wasm trap: call stack exhausted, source location: @-")))
2020-04-23 11:41:01 💔 Error importing block 0x82e536269dbd6ef531f7edc351788b83022b1f20e18f99740353f789329a636a: Err(UnknownParent)
2020-04-23 11:41:01 💔 Error importing block 0x356ce31fce084b8c68c76147917842e67e322ee67a8b9596689f35303ffcd3c9: Err(UnknownParent)
```

After which my node started force-closing all the connections, and I lost all my peers.

**Comment by tomaka** [comment]
After that, the sync is stalled with messages such as:

```
2020-04-23 11:47:59.86 tokio-runtime-worker TRACE sync  Too far ahead for peer QmWcQhEHEyt1fxgRkBYWZJhZjh899nhYxz5h7xwLCQ5EwM (28828)
```

**Comment by bkchr** [comment]
So, this can be closed?

**Comment by arkpar** [comment]
All runtime errors (such as e.g. invalid state root) now show as "wasm trap: call stack exhausted", which is misleading.

**Comment by bkchr** [comment]
`panic!` resolves to a trap inside WASM. That is the reason we see this output. 

The real panic message was printed before:
```
2020-04-23 11:41:01 panicked at 'Transaction trie root must be valid.', /home/volt/.cargo/git/checkouts/substrate-7e08433d4c370a21/d9fca7e/frame/executive/src/lib.rs:192:3
```

But yeah, we could improve on this ;)
