### ISSUE TITLE
Caught panic "Receiver::next_message called after `None`"

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#6443]
Got a panic while running the testsuite which seems to be unrelated to my changes (i.e. runtime).

```

====================

Version: 2.0.0-rc3-unknown-commit-x86_64-linux-gnu

   0: sp_panic_handler::panic_hook
             at primitives/panic-handler/src/lib.rs:149
   1: sp_panic_handler::set::{{closure}}
             at primitives/panic-handler/src/lib.rs:59
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:515
   3: rust_begin_unwind
             at src/libstd/panicking.rs:419
   4: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
   5: core::option::expect_failed
             at src/libcore/option.rs:1260
   6: core::option::Option<T>::expect
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/option.rs:347
   7: futures_channel::mpsc::UnboundedReceiver<T>::next_message
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-channel-0.3.4/src/mpsc/mod.rs:1141
   8: <futures_channel::mpsc::UnboundedReceiver<T> as futures_core::stream::Stream>::poll_next
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-channel-0.3.4/src/mpsc/mod.rs:1195
   9: <sc_network::service::out_events::Receiver as futures_core::stream::Stream>::poll_next
             at client/network/src/service/out_events.rs:100
  10: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/stream/stream/mod.rs:1184
  11: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/stream/stream/next.rs:35
  12: futures_util::future::future::FutureExt::now_or_never
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/future/mod.rs:553
  13: <sc_network::service::out_events::Receiver as core::ops::drop::Drop>::drop
             at client/network/src/service/out_events.rs:123
  14: core::ptr::drop_in_place
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:177
  15: core::ptr::drop_in_place
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:177
  16: core::ptr::drop_in_place
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:177
  17: core::ptr::drop_in_place
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:177
  18: core::ptr::drop_in_place
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:177
  19: core::ptr::drop_in_place
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:177
  20: alloc::sync::Arc<T>::drop_slow
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/sync.rs:793
  21: <alloc::sync::Arc<T> as core::ops::drop::Drop>::drop
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/sync.rs:1305
  22: core::ptr::drop_in_place
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:177
  23: core::ptr::drop_in_place
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:177
  24: core::ptr::drop_in_place
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:177
  25: core::ptr::drop_in_place
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:177
  26: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/select.rs:72
  27: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/future/map.rs:40
  28: <std::panic::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:335
  29: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::{{closure}}
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/future/catch_unwind.rs:29
  30: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:318
  31: std::panicking::try::do_call
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:331
  32: __rust_try
  33: std::panicking::try
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:274
  34: std::panic::catch_unwind
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:394
  35: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/future/catch_unwind.rs:29
  36: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/future/map.rs:40
  37: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
             at /home/lilpep/remote-builds/substrate/client/service/src/task_manager/prometheus_future.rs:56
  38: <std::panic::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:335
  39: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::{{closure}}
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/future/catch_unwind.rs:29
  40: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:318
  41: std::panicking::try::do_call
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:331
  42: __rust_try
  43: std::panicking::try
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:274
  44: std::panic::catch_unwind
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:394
  45: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/future/catch_unwind.rs:29
  46: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/future/future.rs:118
  47: futures_util::future::future::FutureExt::poll_unpin
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/future/mod.rs:507
  48: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/select.rs:64
  49: sc_service::task_manager::SpawnTaskHandle::spawn_inner::{{closure}}
             at /home/lilpep/remote-builds/substrate/client/service/src/task_manager.rs:95
  50: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/future/mod.rs:66
  51: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/future/future.rs:118
  52: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/task/core.rs:163
  53: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/loom/std/unsafe_cell.rs:14
  54: tokio::runtime::task::core::Core<T,S>::poll
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/task/core.rs:148
  55: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/task/harness.rs:108
  56: core::ops::function::FnOnce::call_once
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ops/function.rs:232
  57: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:318
  58: std::panicking::try::do_call
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:331
  59: __rust_try
  60: std::panicking::try
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:274
  61: std::panic::catch_unwind
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:394
  62: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/task/harness.rs:84
  63: tokio::runtime::task::raw::poll
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/task/raw.rs:104
  64: tokio::runtime::task::raw::RawTask::poll
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/task/raw.rs:66
  65: tokio::runtime::task::Notified<S>::run
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/task/mod.rs:169
  66: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/thread_pool/worker.rs:308
  67: tokio::coop::budget::{{closure}}
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/coop.rs:97
  68: std::thread::local::LocalKey<T>::try_with
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:263
  69: std::thread::local::LocalKey<T>::with
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:239
  70: tokio::coop::budget
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/coop.rs:79
      tokio::runtime::thread_pool::worker::Context::run_task
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/thread_pool/worker.rs:307
  71: tokio::runtime::thread_pool::worker::Context::run
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/thread_pool/worker.rs:279
  72: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/thread_pool/worker.rs:264
  73: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/macros/scoped_tls.rs:64
  74: tokio::runtime::thread_pool::worker::run
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/thread_pool/worker.rs:261
  75: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/thread_pool/worker.rs:240
  76: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/blocking/task.rs:38
  77: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/task/core.rs:163
  78: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/loom/std/unsafe_cell.rs:14
  79: tokio::runtime::task::core::Core<T,S>::poll
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/task/core.rs:148
  80: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/task/harness.rs:108
  81: core::ops::function::FnOnce::call_once
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ops/function.rs:232
  82: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:318
  83: std::panicking::try::do_call
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:331
  84: __rust_try
  85: std::panicking::try
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:274
  86: std::panic::catch_unwind
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:394
  87: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/task/harness.rs:84
  88: tokio::runtime::task::raw::poll
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/task/raw.rs:104
  89: tokio::runtime::task::raw::RawTask::poll
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/task/raw.rs:66
  90: tokio::runtime::task::Notified<S>::run
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/task/mod.rs:169
  91: tokio::runtime::blocking::pool::Inner::run
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/blocking/pool.rs:230
  92: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::{{closure}}
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/blocking/pool.rs:210
  93: tokio::runtime::context::enter
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/context.rs:72
  94: tokio::runtime::handle::Handle::enter
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/handle.rs:39
  95: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.18/src/runtime/blocking/pool.rs:209
  96: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/sys_common/backtrace.rs:130
  97: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/mod.rs:475
  98: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:318
  99: std::panicking::try::do_call
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:331
 100: __rust_try
 101: std::panicking::try
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:274
 102: std::panic::catch_unwind
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:394
 103: std::thread::Builder::spawn_unchecked::{{closure}}
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/mod.rs:474
 104: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ops/function.rs:232
 105: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:87
 106: start_thread
 107: __clone


Thread 'tokio-runtime-worker' panicked at 'Receiver::next_message called after `None`', /home/lilpep/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-channel-0.3.4/src/mpsc/mod.rs:1141

This is a bug. Please report it at:

	https://github.com/paritytech/substrate/issues/new

test inspect_works ... FAILED

failures:

---- inspect_works stdout ----
thread 'inspect_works' panicked at 'assertion failed: wait_for(&mut cmd, 40).map(|x| x.success()).unwrap_or_default()', bin/node/cli/tests/common.rs:66:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/io/mod.rs:1504
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:156
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:215
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  12: std::panicking::begin_panic
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:438
  13: inspect_works::common::run_dev_node_for_a_while
             at bin/node/cli/tests/common.rs:66
  14: inspect_works::inspect_works
             at bin/node/cli/tests/inspect_works.rs:31
  15: inspect_works::inspect_works::{{closure}}
             at bin/node/cli/tests/inspect_works.rs:28
  16: core::ops::function::FnOnce::call_once
             at /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ops/function.rs:232
  17: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
  18: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic.rs:318
  19: std::panicking::try::do_call
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:331
  20: std::panicking::try
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:274
  21: std::panic::catch_unwind
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic.rs:394
  22: test::run_test_in_process
             at src/libtest/lib.rs:541
  23: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:450
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    inspect_works

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '-p node-cli --test inspect_works'
```

I am not sure who I should ping about this one, but let's start with @tomaka 

To give more info: the fork point is this commit f8935061c86b42f1018988166156ba792b0aa1a0 and I am running on `cargo remote test` on the beast.

**Comment by tomaka** [comment]
I remember seeing an open pull request that fixes this problem, but I can't find which.

**Comment by bkchr** [comment]
Fixed by: https://github.com/paritytech/substrate/pull/6458
