### ISSUE TITLE
build macro in pallet-staking-reward-curve compile error

### ISSUE THREAD

**Issue by kaichaosun** [paritytech/substrate#6492]
Build failed when using `staking-reward-curve` (without prefix pallet) in cargo.toml and runtime/lib.rs, can be reproduced [here](https://github.com/kaichaosun/tao/tree/curve-macro)
```
[dependencies.pallet-staking-reward-curve]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-staking-reward-curve'
tag = 'v2.0.0-rc3'
version = '2.0.0-rc3'
```

Error info:
```
hread 'rustc' panicked at 'src/librustc_resolve/macros.rs:883: inconsistent resolution for a macro', /rustc/feb3536eba10c2e4585d066629598f03d5ddc7c6/src/li
bstd/macros.rs:13:23
stack backtrace:
   0:     0x7fb322985925 - backtrace::backtrace::libunwind::trace::hc3f32ba24d88242a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x7fb322985925 - backtrace::backtrace::trace_unsynchronized::h1f075597100358e7
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x7fb322985925 - std::sys_common::backtrace::_print_fmt::h4397782fec59f199
                               at src/libstd/sys_common/backtrace.rs:78
...
```

Build successfully when using `pallet-staking-reward-curve` in cargo.toml and runtime/lib.rs: 
```
[dependencies.pallet-staking-reward-curve]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-staking-reward-curve'
tag = 'v2.0.0-rc3'
version = '2.0.0-rc3'
```

**Comment by bkchr** [comment]
This is a rustc bug: https://github.com/rust-lang/rust/issues/56935

Solution is: Don't rename the crate in `Cargo.toml`
