### ISSUE TITLE
Panic on importing block with (maybe) tx signature verification

### ISSUE THREAD

**Issue by zikunfan** [paritytech/substrate#6889]
### Version
`rc4`

### Context
1. Wasm already be forkless upgraded;
2. Binary client(native) using the old runtime wasm code;
3. Client started with args `--base-path /crust/chain --chain maxwell --validator --port 30333 --name vnode --rpc-port 9933 --ws-port 9944 --pruning archive`

### Error
Panic errors:
```shell
{"log":"Thread 'tokio-runtime-worker' panicked at 'Signature verification has not been called before `SignatureBatching::drop`', /opt/cache/registry/src/github.com-1ecc6299db9ec823/sp-runtime-2.0.0-rc4/src/lib.rs:792\n","stream":"stderr","time":"2020-08-14T01:27:19.930625039Z"}
```
```shell
{"log":"   2: std::panicking::begin_panic\n","stream":"stderr","time":"2020-08-14T01:27:19.929452095Z"}
```
```shell
{"log":"   0: sp_panic_handler::set::{{closure}}\n","stream":"stderr","time":"2020-08-14T01:27:19.929420478Z"}
{"log":"   1: std::panicking::rust_panic_with_hook\n","stream":"stderr","time":"2020-08-14T01:27:19.929434224Z"}
```
```shell
{"log":"  31: \u003cstd::panic::AssertUnwindSafe\u003cF\u003e as core::ops::function::FnOnce\u003c()\u003e\u003e::call_once\n","stream":"stderr","time":"2020-08-14T01:27:19.928993885Z"}
```

### Whole error log, TL;DR

```shell
{"log":"Starting crust using args: --base-path /crust/chain --chain maxwell --validator --port 30333 --name vnode --rpc-port 9933 --ws-port 9944 --pruning archive\n","stream":"stdout","time":"2020-08-14T01:27:17.407435398Z"}
{"log":"2020-08-14 01:27:17 Crust Node\n","stream":"stderr","time":"2020-08-14T01:27:17.41357637Z"}
{"log":"2020-08-14 01:27:17 ✌️  version 0.7.0-fa66cad-x86_64-linux-gnu\n","stream":"stderr","time":"2020-08-14T01:27:17.413594609Z"}
{"log":"2020-08-14 01:27:17 ❤️  by crustio, 2019-2020\n","stream":"stderr","time":"2020-08-14T01:27:17.413598036Z"}
{"log":"2020-08-14 01:27:17 📋 Chain specification: Maxwell\n","stream":"stderr","time":"2020-08-14T01:27:17.413600474Z"}
{"log":"2020-08-14 01:27:17 🏷  Node name: vnode\n","stream":"stderr","time":"2020-08-14T01:27:17.413602874Z"}
{"log":"2020-08-14 01:27:17 👤 Role: AUTHORITY\n","stream":"stderr","time":"2020-08-14T01:27:17.413605106Z"}
{"log":"2020-08-14 01:27:17 💾 Database: RocksDb at /crust/chain/chains/maxwell1/db\n","stream":"stderr","time":"2020-08-14T01:27:17.413607356Z"}
{"log":"2020-08-14 01:27:17 ⛓  Native runtime: crust-4 (crustio-crust-1.tx1.au1)\n","stream":"stderr","time":"2020-08-14T01:27:17.413610938Z"}
{"log":"2020-08-14 01:27:17 📦 Highest known block at #238815\n","stream":"stderr","time":"2020-08-14T01:27:17.88565109Z"}
{"log":"2020-08-14 01:27:17 🏷  Local node identity is: 12D3KooWF3TdhEmobLK2cX8ir1BcBfhVreiK9eQ9HGXzufJ8QX5c (legacy representation: QmTtCVr1cuo3QLciv9BZjh98TCFKCNpPhPVRpSijk18uXU)\n","stream":"stderr","time":"2020-08-14T01:27:17.885793183Z"}
{"log":"2020-08-14 01:27:17 〽️ Prometheus server started at 127.0.0.1:9615\n","stream":"stderr","time":"2020-08-14T01:27:17.888508772Z"}
{"log":"2020-08-14 01:27:17 👶 Starting BABE Authorship worker\n","stream":"stderr","time":"2020-08-14T01:27:17.891306537Z"}
{"log":"2020-08-14 01:27:18 🔍 Discovered new external address for our node: /ip4/192.168.50.1/tcp/30333/p2p/12D3KooWF3TdhEmobLK2cX8ir1BcBfhVreiK9eQ9HGXzufJ8QX5c\n","stream":"stderr","time":"2020-08-14T01:27:18.49219908Z"}
{"log":"2020-08-14 01:27:18 🔍 Discovered new external address for our node: /ip4/182.148.7.157/tcp/30333/p2p/12D3KooWF3TdhEmobLK2cX8ir1BcBfhVreiK9eQ9HGXzufJ8QX5c\n","stream":"stderr","time":"2020-08-14T01:27:18.653000039Z"}
{"log":"2020-08-14 01:27:19 🔍 Discovered new external address for our node: /ip4/192.168.50.163/tcp/30333/p2p/12D3KooWF3TdhEmobLK2cX8ir1BcBfhVreiK9eQ9HGXzufJ8QX5c\n","stream":"stderr","time":"2020-08-14T01:27:19.415313266Z"}
{"log":"\n","stream":"stderr","time":"2020-08-14T01:27:19.928050737Z"}
{"log":"====================\n","stream":"stderr","time":"2020-08-14T01:27:19.928068342Z"}
{"log":"\n","stream":"stderr","time":"2020-08-14T01:27:19.928070954Z"}
{"log":"Version: 0.7.0-fa66cad-x86_64-linux-gnu\n","stream":"stderr","time":"2020-08-14T01:27:19.928073054Z"}
{"log":"\n","stream":"stderr","time":"2020-08-14T01:27:19.928075213Z"}
{"log":"   0: sp_panic_handler::set::{{closure}}\n","stream":"stderr","time":"2020-08-14T01:27:19.928077188Z"}
{"log":"   1: std::panicking::rust_panic_with_hook\n","stream":"stderr","time":"2020-08-14T01:27:19.928079199Z"}
{"log":"             at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/panicking.rs:530\n","stream":"stderr","time":"2020-08-14T01:27:19.928081787Z"}
{"log":"   2: std::panicking::begin_panic\n","stream":"stderr","time":"2020-08-14T01:27:19.928085226Z"}
{"log":"   3: frame_executive::Executive\u003cSystem,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade\u003e::execute_block\n","stream":"stderr","time":"2020-08-14T01:27:19.928088263Z"}
{"log":"   4: \u003ccrust_runtime::Runtime as sp_api::runtime_decl_for_Core::Core\u003csp_runtime::generic::block::Block\u003csp_runtime::generic::header::Header\u003cu32,sp_runtime::traits::BlakeTwo256\u003e,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic\u003c\u003c\u003csp_runtime::MultiSignature as sp_runtime::traits::Verify\u003e::Signer as sp_runtime::traits::IdentifyAccount\u003e::AccountId,crust_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion\u003ccrust_runtime::Runtime\u003e,frame_system::extensions::check_tx_version::CheckTxVersion\u003ccrust_runtime::Runtime\u003e,frame_system::extensions::check_genesis::CheckGenesis\u003ccrust_runtime::Runtime\u003e,frame_system::extensions::check_mortality::CheckMortality\u003ccrust_runtime::Runtime\u003e,frame_system::extensions::check_nonce::CheckNonce\u003ccrust_runtime::Runtime\u003e,frame_system::extensions::check_weight::CheckWeight\u003ccrust_runtime::Runtime\u003e,pallet_transaction_payment::ChargeTransactionPayment\u003ccrust_runtime::Runtime\u003e)\u003e\u003e\u003e\u003e::execute_block\n","stream":"stderr","time":"2020-08-14T01:27:19.928273098Z"}
{"log":"   5: sp_api::runtime_decl_for_Core::execute_block_native_call_generator::{{closure}}\n","stream":"stderr","time":"2020-08-14T01:27:19.928293003Z"}
{"log":"   6: std::thread::local::LocalKey\u003cT\u003e::with\n","stream":"stderr","time":"2020-08-14T01:27:19.928318124Z"}
{"log":"   7: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}\n","stream":"stderr","time":"2020-08-14T01:27:19.928341886Z"}
{"log":"   8: sc_executor::wasm_runtime::RuntimeCache::with_instance\n","stream":"stderr","time":"2020-08-14T01:27:19.928350736Z"}
{"log":"   9: \u003csc_executor::native_executor::NativeExecutor\u003cD\u003e as sp_core::traits::CodeExecutor\u003e::call\n","stream":"stderr","time":"2020-08-14T01:27:19.92838179Z"}
{"log":"  10: sp_state_machine::StateMachine\u003cB,H,N,Exec\u003e::execute_aux\n","stream":"stderr","time":"2020-08-14T01:27:19.92840196Z"}
{"log":"  11: sp_state_machine::StateMachine\u003cB,H,N,Exec\u003e::execute_using_consensus_failure_handler\n","stream":"stderr","time":"2020-08-14T01:27:19.92842286Z"}
{"log":"  12: \u003csc_service::client::call_executor::LocalCallExecutor\u003cB,E\u003e as sc_client_api::call_executor::CallExecutor\u003cBlock\u003e\u003e::contextual_call\n","stream":"stderr","time":"2020-08-14T01:27:19.928458918Z"}
{"log":"  13: \u003csc_service::client::client::Client\u003cB,E,Block,RA\u003e as sp_api::CallApiAt\u003cBlock\u003e\u003e::call_api_at\n","stream":"stderr","time":"2020-08-14T01:27:19.928493359Z"}
{"log":"  14: sp_api::runtime_decl_for_Core::execute_block_call_api_at\n","stream":"stderr","time":"2020-08-14T01:27:19.928504845Z"}
{"log":"  15: sp_api::Core::execute_block_with_context\n","stream":"stderr","time":"2020-08-14T01:27:19.92852286Z"}
{"log":"  16: \u003c\u0026sc_service::client::client::Client\u003cB,E,Block,RA\u003e as sp_consensus::block_import::BlockImport\u003cBlock\u003e\u003e::import_block\n","stream":"stderr","time":"2020-08-14T01:27:19.928555843Z"}
{"log":"  17: \u003csc_finality_grandpa::import::GrandpaBlockImport\u003cBE,Block,Client,SC\u003e as sp_consensus::block_import::BlockImport\u003cBlock\u003e\u003e::import_block\n","stream":"stderr","time":"2020-08-14T01:27:19.928593959Z"}
{"log":"  18: \u003csc_consensus_babe::BabeBlockImport\u003cBlock,Client,Inner\u003e as sp_consensus::block_import::BlockImport\u003cBlock\u003e\u003e::import_block\n","stream":"stderr","time":"2020-08-14T01:27:19.928626516Z"}
{"log":"  19: sp_consensus::import_queue::import_single_block_metered\n","stream":"stderr","time":"2020-08-14T01:27:19.928637824Z"}
{"log":"  20: \u003cfutures_util::future::poll_fn::PollFn\u003cF\u003e as core::future::future::Future\u003e::poll\n","stream":"stderr","time":"2020-08-14T01:27:19.928678122Z"}
{"log":"  21: \u003cfutures_util::future::future::map::Map\u003cFut,F\u003e as core::future::future::Future\u003e::poll\n","stream":"stderr","time":"2020-08-14T01:27:19.928711722Z"}
{"log":"  22: \u003cfutures_util::future::future::flatten::Flatten\u003cFut,\u003cFut as core::future::future::Future\u003e::Output\u003e as core::future::future::Future\u003e::poll\n","stream":"stderr","time":"2020-08-14T01:27:19.928760953Z"}
{"log":"  23: \u003cfutures_util::future::poll_fn::PollFn\u003cF\u003e as core::future::future::Future\u003e::poll\n","stream":"stderr","time":"2020-08-14T01:27:19.928788606Z"}
{"log":"  24: \u003csc_service::task_manager::prometheus_future::PrometheusFuture\u003cT\u003e as core::future::future::Future\u003e::poll\n","stream":"stderr","time":"2020-08-14T01:27:19.928824189Z"}
{"log":"  25: \u003cfutures_util::future::select::Select\u003cA,B\u003e as core::future::future::Future\u003e::poll\n","stream":"stderr","time":"2020-08-14T01:27:19.92885355Z"}
{"log":"  26: \u003ccore::future::from_generator::GenFuture\u003cT\u003e as core::future::future::Future\u003e::poll\n","stream":"stderr","time":"2020-08-14T01:27:19.928886165Z"}
{"log":"  27: std::thread::local::LocalKey\u003cT\u003e::with\n","stream":"stderr","time":"2020-08-14T01:27:19.928906029Z"}
{"log":"  28: futures_executor::local_pool::block_on\n","stream":"stderr","time":"2020-08-14T01:27:19.928915863Z"}
{"log":"  29: tokio::loom::std::unsafe_cell::UnsafeCell\u003cT\u003e::with_mut\n","stream":"stderr","time":"2020-08-14T01:27:19.928940656Z"}
{"log":"  30: tokio::runtime::task::core::Core\u003cT,S\u003e::poll\n","stream":"stderr","time":"2020-08-14T01:27:19.928959414Z"}
{"log":"  31: \u003cstd::panic::AssertUnwindSafe\u003cF\u003e as core::ops::function::FnOnce\u003c()\u003e\u003e::call_once\n","stream":"stderr","time":"2020-08-14T01:27:19.928993885Z"}
{"log":"  32: tokio::runtime::task::harness::Harness\u003cT,S\u003e::poll\n","stream":"stderr","time":"2020-08-14T01:27:19.929021037Z"}
{"log":"  33: tokio::runtime::blocking::pool::Inner::run\n","stream":"stderr","time":"2020-08-14T01:27:19.929050185Z"}
{"log":"  34: tokio::runtime::context::enter\n","stream":"stderr","time":"2020-08-14T01:27:19.929064587Z"}
{"log":"  35: std::sys_common::backtrace::__rust_begin_short_backtrace\n","stream":"stderr","time":"2020-08-14T01:27:19.929069992Z"}
{"log":"  36: core::ops::function::FnOnce::call_once{{vtable.shim}}\n","stream":"stderr","time":"2020-08-14T01:27:19.929093102Z"}
{"log":"  37: \u003calloc::boxed::Box\u003cF\u003e as core::ops::function::FnOnce\u003cA\u003e\u003e::call_once\n","stream":"stderr","time":"2020-08-14T01:27:19.929126693Z"}
{"log":"             at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/liballoc/boxed.rs:1081\n","stream":"stderr","time":"2020-08-14T01:27:19.929133927Z"}
{"log":"      \u003calloc::boxed::Box\u003cF\u003e as core::ops::function::FnOnce\u003cA\u003e\u003e::call_once\n","stream":"stderr","time":"2020-08-14T01:27:19.929165274Z"}
{"log":"             at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/liballoc/boxed.rs:1081\n","stream":"stderr","time":"2020-08-14T01:27:19.929171383Z"}
{"log":"      std::sys::unix::thread::Thread::new::thread_start\n","stream":"stderr","time":"2020-08-14T01:27:19.929190705Z"}
{"log":"             at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/sys/unix/thread.rs:87\n","stream":"stderr","time":"2020-08-14T01:27:19.929200317Z"}
{"log":"  38: start_thread\n","stream":"stderr","time":"2020-08-14T01:27:19.929202709Z"}
{"log":"  39: clone\n","stream":"stderr","time":"2020-08-14T01:27:19.929208894Z"}
{"log":"\n","stream":"stderr","time":"2020-08-14T01:27:19.929210967Z"}
{"log":"\n","stream":"stderr","time":"2020-08-14T01:27:19.929217408Z"}
{"log":"Thread 'tokio-runtime-worker' panicked at 'Transaction would exhausts the block limits', /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/macros.rs:13\n","stream":"stderr","time":"2020-08-14T01:27:19.929222711Z"}
{"log":"\n","stream":"stderr","time":"2020-08-14T01:27:19.929225119Z"}
{"log":"This is a bug. Please report it at:\n","stream":"stderr","time":"2020-08-14T01:27:19.92922708Z"}
{"log":"\n","stream":"stderr","time":"2020-08-14T01:27:19.929229451Z"}
{"log":"\u0009https://github.com/crustio/crust/issues/new\n","stream":"stderr","time":"2020-08-14T01:27:19.929237881Z"}
{"log":"\n","stream":"stderr","time":"2020-08-14T01:27:19.929240206Z"}
{"log":"\n","stream":"stderr","time":"2020-08-14T01:27:19.929408518Z"}
{"log":"====================\n","stream":"stderr","time":"2020-08-14T01:27:19.929412167Z"}
{"log":"\n","stream":"stderr","time":"2020-08-14T01:27:19.929414277Z"}
{"log":"Version: 0.7.0-fa66cad-x86_64-linux-gnu\n","stream":"stderr","time":"2020-08-14T01:27:19.929416227Z"}
{"log":"\n","stream":"stderr","time":"2020-08-14T01:27:19.929418284Z"}
{"log":"   0: sp_panic_handler::set::{{closure}}\n","stream":"stderr","time":"2020-08-14T01:27:19.929420478Z"}
{"log":"   1: std::panicking::rust_panic_with_hook\n","stream":"stderr","time":"2020-08-14T01:27:19.929434224Z"}
{"log":"             at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/panicking.rs:530\n","stream":"stderr","time":"2020-08-14T01:27:19.929438133Z"}
{"log":"   2: std::panicking::begin_panic\n","stream":"stderr","time":"2020-08-14T01:27:19.929452095Z"}
{"log":"   3: \u003csp_runtime::SignatureBatching as core::ops::drop::Drop\u003e::drop\n","stream":"stderr","time":"2020-08-14T01:27:19.929471158Z"}
{"log":"   4: frame_executive::Executive\u003cSystem,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade\u003e::execute_block\n","stream":"stderr","time":"2020-08-14T01:27:19.929498334Z"}
{"log":"   5: \u003ccrust_runtime::Runtime as sp_api::runtime_decl_for_Core::Core\u003csp_runtime::generic::block::Block\u003csp_runtime::generic::header::Header\u003cu32,sp_runtime::traits::BlakeTwo256\u003e,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic\u003c\u003c\u003csp_runtime::MultiSignature as sp_runtime::traits::Verify\u003e::Signer as sp_runtime::traits::IdentifyAccount\u003e::AccountId,crust_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion\u003ccrust_runtime::Runtime\u003e,frame_system::extensions::check_tx_version::CheckTxVersion\u003ccrust_runtime::Runtime\u003e,frame_system::extensions::check_genesis::CheckGenesis\u003ccrust_runtime::Runtime\u003e,frame_system::extensions::check_mortality::CheckMortality\u003ccrust_runtime::Runtime\u003e,frame_system::extensions::check_nonce::CheckNonce\u003ccrust_runtime::Runtime\u003e,frame_system::extensions::check_weight::CheckWeight\u003ccrust_runtime::Runtime\u003e,pallet_transaction_payment::ChargeTransactionPayment\u003ccrust_runtime::Runtime\u003e)\u003e\u003e\u003e\u003e::execute_block\n","stream":"stderr","time":"2020-08-14T01:27:19.929701703Z"}
{"log":"   6: sp_api::runtime_decl_for_Core::execute_block_native_call_generator::{{closure}}\n","stream":"stderr","time":"2020-08-14T01:27:19.929713909Z"}
{"log":"   7: std::thread::local::LocalKey\u003cT\u003e::with\n","stream":"stderr","time":"2020-08-14T01:27:19.929733015Z"}
{"log":"   8: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}\n","stream":"stderr","time":"2020-08-14T01:27:19.929753054Z"}
{"log":"   9: sc_executor::wasm_runtime::RuntimeCache::with_instance\n","stream":"stderr","time":"2020-08-14T01:27:19.929779918Z"}
{"log":"  10: \u003csc_executor::native_executor::NativeExecutor\u003cD\u003e as sp_core::traits::CodeExecutor\u003e::call\n","stream":"stderr","time":"2020-08-14T01:27:19.929794707Z"}
{"log":"  11: sp_state_machine::StateMachine\u003cB,H,N,Exec\u003e::execute_aux\n","stream":"stderr","time":"2020-08-14T01:27:19.929815834Z"}
{"log":"  12: sp_state_machine::StateMachine\u003cB,H,N,Exec\u003e::execute_using_consensus_failure_handler\n","stream":"stderr","time":"2020-08-14T01:27:19.929838892Z"}
{"log":"  13: \u003csc_service::client::call_executor::LocalCallExecutor\u003cB,E\u003e as sc_client_api::call_executor::CallExecutor\u003cBlock\u003e\u003e::contextual_call\n","stream":"stderr","time":"2020-08-14T01:27:19.929880573Z"}
{"log":"  14: \u003csc_service::client::client::Client\u003cB,E,Block,RA\u003e as sp_api::CallApiAt\u003cBlock\u003e\u003e::call_api_at\n","stream":"stderr","time":"2020-08-14T01:27:19.929911876Z"}
{"log":"  15: sp_api::runtime_decl_for_Core::execute_block_call_api_at\n","stream":"stderr","time":"2020-08-14T01:27:19.929919906Z"}
{"log":"  16: sp_api::Core::execute_block_with_context\n","stream":"stderr","time":"2020-08-14T01:27:19.929931827Z"}
{"log":"  17: \u003c\u0026sc_service::client::client::Client\u003cB,E,Block,RA\u003e as sp_consensus::block_import::BlockImport\u003cBlock\u003e\u003e::import_block\n","stream":"stderr","time":"2020-08-14T01:27:19.929975865Z"}
{"log":"  18: \u003csc_finality_grandpa::import::GrandpaBlockImport\u003cBE,Block,Client,SC\u003e as sp_consensus::block_import::BlockImport\u003cBlock\u003e\u003e::import_block\n","stream":"stderr","time":"2020-08-14T01:27:19.93001455Z"}
{"log":"  19: \u003csc_consensus_babe::BabeBlockImport\u003cBlock,Client,Inner\u003e as sp_consensus::block_import::BlockImport\u003cBlock\u003e\u003e::import_block\n","stream":"stderr","time":"2020-08-14T01:27:19.930041174Z"}
{"log":"  20: sp_consensus::import_queue::import_single_block_metered\n","stream":"stderr","time":"2020-08-14T01:27:19.930052748Z"}
{"log":"  21: \u003cfutures_util::future::poll_fn::PollFn\u003cF\u003e as core::future::future::Future\u003e::poll\n","stream":"stderr","time":"2020-08-14T01:27:19.930086258Z"}
{"log":"  22: \u003cfutures_util::future::future::map::Map\u003cFut,F\u003e as core::future::future::Future\u003e::poll\n","stream":"stderr","time":"2020-08-14T01:27:19.930122855Z"}
{"log":"  23: \u003cfutures_util::future::future::flatten::Flatten\u003cFut,\u003cFut as core::future::future::Future\u003e::Output\u003e as core::future::future::Future\u003e::poll\n","stream":"stderr","time":"2020-08-14T01:27:19.930173752Z"}
{"log":"  24: \u003cfutures_util::future::poll_fn::PollFn\u003cF\u003e as core::future::future::Future\u003e::poll\n","stream":"stderr","time":"2020-08-14T01:27:19.930202168Z"}
{"log":"  25: \u003csc_service::task_manager::prometheus_future::PrometheusFuture\u003cT\u003e as core::future::future::Future\u003e::poll\n","stream":"stderr","time":"2020-08-14T01:27:19.930242999Z"}
{"log":"  26: \u003cfutures_util::future::select::Select\u003cA,B\u003e as core::future::future::Future\u003e::poll\n","stream":"stderr","time":"2020-08-14T01:27:19.930268288Z"}
{"log":"  27: \u003ccore::future::from_generator::GenFuture\u003cT\u003e as core::future::future::Future\u003e::poll\n","stream":"stderr","time":"2020-08-14T01:27:19.930308072Z"}
{"log":"  28: std::thread::local::LocalKey\u003cT\u003e::with\n","stream":"stderr","time":"2020-08-14T01:27:19.930325Z"}
{"log":"  29: futures_executor::local_pool::block_on\n","stream":"stderr","time":"2020-08-14T01:27:19.930332582Z"}
{"log":"  30: tokio::loom::std::unsafe_cell::UnsafeCell\u003cT\u003e::with_mut\n","stream":"stderr","time":"2020-08-14T01:27:19.930360546Z"}
{"log":"  31: tokio::runtime::task::core::Core\u003cT,S\u003e::poll\n","stream":"stderr","time":"2020-08-14T01:27:19.93037748Z"}
{"log":"  32: \u003cstd::panic::AssertUnwindSafe\u003cF\u003e as core::ops::function::FnOnce\u003c()\u003e\u003e::call_once\n","stream":"stderr","time":"2020-08-14T01:27:19.930407568Z"}
{"log":"  33: tokio::runtime::task::harness::Harness\u003cT,S\u003e::poll\n","stream":"stderr","time":"2020-08-14T01:27:19.930435088Z"}
{"log":"  34: tokio::runtime::blocking::pool::Inner::run\n","stream":"stderr","time":"2020-08-14T01:27:19.930448145Z"}
{"log":"  35: tokio::runtime::context::enter\n","stream":"stderr","time":"2020-08-14T01:27:19.930460808Z"}
{"log":"  36: std::sys_common::backtrace::__rust_begin_short_backtrace\n","stream":"stderr","time":"2020-08-14T01:27:19.930473728Z"}
{"log":"  37: core::ops::function::FnOnce::call_once{{vtable.shim}}\n","stream":"stderr","time":"2020-08-14T01:27:19.930500075Z"}
{"log":"  38: \u003calloc::boxed::Box\u003cF\u003e as core::ops::function::FnOnce\u003cA\u003e\u003e::call_once\n","stream":"stderr","time":"2020-08-14T01:27:19.930534169Z"}
{"log":"             at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/liballoc/boxed.rs:1081\n","stream":"stderr","time":"2020-08-14T01:27:19.930542173Z"}
{"log":"      \u003calloc::boxed::Box\u003cF\u003e as core::ops::function::FnOnce\u003cA\u003e\u003e::call_once\n","stream":"stderr","time":"2020-08-14T01:27:19.930564302Z"}
{"log":"             at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/liballoc/boxed.rs:1081\n","stream":"stderr","time":"2020-08-14T01:27:19.930577797Z"}
{"log":"      std::sys::unix::thread::Thread::new::thread_start\n","stream":"stderr","time":"2020-08-14T01:27:19.930600855Z"}
{"log":"             at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/sys/unix/thread.rs:87\n","stream":"stderr","time":"2020-08-14T01:27:19.930605491Z"}
{"log":"  39: start_thread\n","stream":"stderr","time":"2020-08-14T01:27:19.930607759Z"}
{"log":"  40: clone\n","stream":"stderr","time":"2020-08-14T01:27:19.930610085Z"}
{"log":"\n","stream":"stderr","time":"2020-08-14T01:27:19.93061208Z"}
{"log":"\n","stream":"stderr","time":"2020-08-14T01:27:19.930614068Z"}
{"log":"Thread 'tokio-runtime-worker' panicked at 'Signature verification has not been called before `SignatureBatching::drop`', /opt/cache/registry/src/github.com-1ecc6299db9ec823/sp-runtime-2.0.0-rc4/src/lib.rs:792\n","stream":"stderr","time":"2020-08-14T01:27:19.930625039Z"}
{"log":"\n","stream":"stderr","time":"2020-08-14T01:27:19.930629848Z"}
{"log":"This is a bug. Please report it at:\n","stream":"stderr","time":"2020-08-14T01:27:19.930632959Z"}
{"log":"\n","stream":"stderr","time":"2020-08-14T01:27:19.930635886Z"}
{"log":"\u0009https://github.com/crustio/crust/issues/new\n","stream":"stderr","time":"2020-08-14T01:27:19.930639374Z"}
{"log":"\n","stream":"stderr","time":"2020-08-14T01:27:19.930642905Z"}
{"log":"thread panicked while panicking. aborting.\n","stream":"stderr","time":"2020-08-14T01:27:19.930646627Z"}
{"log":"/opt/run.sh: line 6:     8 Illegal instruction     (core dumped) /opt/crust/crust ${ARGS}\n","stream":"stderr","time":"2020-08-14T01:27:20.020447459Z"}
```

**Comment by bkchr** [comment]
Is this reproducible? If yes, could you give the git commit which I could use to reproduce this?

**Comment by zikunfan** [comment]
> Is this reproducible? If yes, could you give the git commit which I could use to reproduce this?

Not all nodes and 100% possibility can reproduce. And we are using crust(https://github.com/crustio/crust/tree/release/0.7.0) to build and test.

**Comment by bkchr** [comment]
Can you please post a readable log?
