### ISSUE TITLE
thread 'rustc' panicked at 'explicit panic', compiler/rustc_middle/src/lint.rs:287:37

### ISSUE THREAD

**Issue by TriplEight** [paritytech/substrate#7481]
[`build-rust-doc`](https://gitlab.parity.io/parity/substrate/-/jobs/702260#L1084) and [another](https://gitlab.parity.io/parity/substrate/-/jobs/702610) CI job fails with

<details>
<summary>explicit panic</summary>

```
Running `sccache rustc --crate-name prost --edition=2018 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/prost-0.6.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="prost-derive"' -C metadata=e6a7230de5815c74 -C extra-filename=-e6a7230de5815c74 --out-dir /builds/parity/substrate/target/debug/deps -L dependency=/builds/parity/substrate/target/debug/deps --extern bytes=/builds/parity/substrate/target/debug/deps/libbytes-cbac4f3e335ed5e3.rmeta --extern prost_derive=/builds/parity/substrate/target/debug/deps/libprost_derive-e3a64b6e8783083c.so --cap-lints allow -Dwarnings`
thread 'rustc' panicked at 'explicit panic', compiler/rustc_middle/src/lint.rs:287:37
stack backtrace:
   0: std::panicking::begin_panic
   1: rustc_middle::lint::struct_lint_level::struct_lint_level_impl
   2: <rustc_lint::array_into_iter::ArrayIntoIter as rustc_lint::passes::LateLintPass>::check_expr
   3: <rustc_lint::BuiltinCombinedLateLintPass as rustc_lint::passes::LateLintPass>::check_expr
   4: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
   5: rustc_hir::intravisit::walk_expr
   6: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
   7: rustc_hir::intravisit::walk_expr
   8: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
   9: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  10: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_stmt
  11: rustc_hir::intravisit::walk_expr
  12: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  13: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_nested_body
  14: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_fn
  15: rustc_hir::intravisit::walk_impl_item
  16: rustc_hir::intravisit::Visitor::visit_nested_impl_item
  17: rustc_hir::intravisit::walk_item
  18: rustc_hir::intravisit::Visitor::visit_nested_item
  19: rustc_hir::intravisit::walk_crate
  20: rustc_lint::late::late_lint_crate
  21: rustc_data_structures::sync::join
  22: rustc_interface::passes::analysis
  23: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  24: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  25: rustc_data_structures::stack::ensure_sufficient_stack
  26: rustc_query_system::query::plumbing::get_query_impl
  27: rustc_interface::passes::QueryContext::enter
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
note: rustc 1.49.0-nightly (b20253260 2020-11-01) running on x86_64-unknown-linux-gnu
note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type rlib
note: some of the compiler flags provided by cargo are hidden
query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `raw-cpuid`
Caused by:
  process didn't exit successfully: `sccache rustc --crate-name raw_cpuid /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/raw-cpuid-7.0.3/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=067b749acfbb0975 -C extra-filename=-067b749acfbb0975 --out-dir /builds/parity/substrate/target/debug/deps -L dependency=/builds/parity/substrate/target/debug/deps --extern bitflags=/builds/parity/substrate/target/debug/deps/libbitflags-df474a8ca45884a8.rmeta --cap-lints allow -Dwarnings --cfg 'feature="use_arch"' --cfg 'feature="nightly"'` (exit code: 101)
warning: build failed, waiting for other jobs to finish...
thread 'rustc' panicked at 'explicit panic', compiler/rustc_middle/src/lint.rs:287:37
stack backtrace:
   0: std::panicking::begin_panic
   1: rustc_middle::lint::struct_lint_level::struct_lint_level_impl
   2: <rustc_lint::array_into_iter::ArrayIntoIter as rustc_lint::passes::LateLintPass>::check_expr
   3: <rustc_lint::BuiltinCombinedLateLintPass as rustc_lint::passes::LateLintPass>::check_expr
   4: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
   5: rustc_hir::intravisit::walk_expr
   6: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
   7: rustc_hir::intravisit::walk_expr
   8: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
   9: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  10: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_stmt
  11: rustc_hir::intravisit::walk_expr
  12: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  13: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_nested_body
  14: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_fn
  15: rustc_hir::intravisit::walk_impl_item
  16: rustc_hir::intravisit::Visitor::visit_nested_impl_item
  17: rustc_hir::intravisit::walk_item
  18: rustc_hir::intravisit::Visitor::visit_nested_item
  19: rustc_hir::intravisit::walk_crate
  20: rustc_lint::late::late_lint_crate
  21: rustc_data_structures::sync::join
  22: rustc_interface::passes::analysis
  23: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  24: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  25: rustc_data_structures::stack::ensure_sufficient_stack
  26: rustc_query_system::query::plumbing::get_query_impl
  27: rustc_interface::passes::QueryContext::enter
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
note: rustc 1.49.0-nightly (b20253260 2020-11-01) running on x86_64-unknown-linux-gnu
note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type rlib
note: some of the compiler flags provided by cargo are hidden
query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: build failed
Command exited with non-zero status 101
190.05user 51.46system 1:03.17elapsed 382%CPU (0avgtext+0avgdata 517320maxresident)k
47168inputs+3439832outputs (29major+5664274minor)pagefaults 0swaps
Running after_script
00:02
Uploading artifacts for failed job
00:01
ERROR: Job failed: exit code 1
```

</details>

The command is `time cargo +nightly doc --no-deps --workspace --all-features --verbose`
And the first nightly to introduce it was `rustc 1.49.0-nightly (b20253260 2020-11-01)`
Can be reproed with `paritytech/ci-linux:4cc65dc0-20201102` image

**Comment by bkchr** [comment]
We don't track rustc bugs in here.

And apparently it got fixed: https://github.com/rust-lang/rust/issues/78660

Should be working with the nightly from tomorrow.
