### ISSUE TITLE
Impossible to structure runtime

### ISSUE THREAD

**Issue by vporton** [paritytech/substrate#7562]
I apply this patch to `substrate` v2.0.0:

```patch
diff --git a/primitives/io/src/lib.rs b/primitives/io/src/lib.rs
index 382a0c4b3..a3fe0544b 100644
--- a/primitives/io/src/lib.rs
+++ b/primitives/io/src/lib.rs
@@ -89,12 +89,7 @@ pub trait Storage {
                self.storage(key).map(|s| s.to_vec())
        }

-       /// Get `key` from storage, placing the value into `value_out` and return the number of
-       /// bytes that the entry in storage has beyond the offset or `None` if the storage entry
-       /// doesn't exist at all.
-       /// If `value_out` length is smaller than the returned length, only `value_out` length bytes
-       /// are copied into `value_out`.
-       fn read(&self, key: &[u8], value_out: &mut [u8], value_offset: u32) -> Option<u32> {
+       fn read_impl(&self, key: &[u8], value_out: &mut [u8], value_offset: u32) -> Option<u32> {
                self.storage(key).map(|value| {
                        let value_offset = value_offset as usize;
                        let data = &value[value_offset.min(value.len())..];
@@ -102,6 +97,16 @@ pub trait Storage {
                        value_out[..written].copy_from_slice(&data[..written]);
                        data.len() as u32
                })
+
+       }
+
+       /// Get `key` from storage, placing the value into `value_out` and return the number of
+       /// bytes that the entry in storage has beyond the offset or `None` if the storage entry
+       /// doesn't exist at all.
+       /// If `value_out` length is smaller than the returned length, only `value_out` length bytes
+       /// are copied into `value_out`.
+       fn read(&self, key: &[u8], value_out: &mut [u8], value_offset: u32) -> Option<u32> {
+               self.read_impl(key, value_out, value_offset)
        }

        /// Set `key` to `value` in the storage.
```

After this it does not compile:

```
error[E0599]: no method named `read_impl` found for reference `&&mut dyn storage::proc_macro_runtime_interface::Externalities` in the current scope
   --> primitives/io/src/lib.rs:109:8
    |
109 |         self.read_impl(key, value_out, value_offset)
    |              ^^^^^^^^^ method not found in `&&mut dyn storage::proc_macro_runtime_interface::Externalities`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `sp-io`

To learn more, run the command again with --verbose.
```

Then I try another way:
```patch
diff --git a/primitives/io/src/lib.rs b/primitives/io/src/lib.rs
index 382a0c4b3..a3fe0544b 100644
--- a/primitives/io/src/lib.rs
+++ b/primitives/io/src/lib.rs
@@ -89,12 +89,7 @@ pub trait Storage {
                self.storage(key).map(|s| s.to_vec())
        }

-       /// Get `key` from storage, placing the value into `value_out` and return the number of
-       /// bytes that the entry in storage has beyond the offset or `None` if the storage entry
-       /// doesn't exist at all.
-       /// If `value_out` length is smaller than the returned length, only `value_out` length bytes
-       /// are copied into `value_out`.
-       fn read(&self, key: &[u8], value_out: &mut [u8], value_offset: u32) -> Option<u32> {
+       fn read_impl(&self, key: &[u8], value_out: &mut [u8], value_offset: u32) -> Option<u32> {
                self.storage(key).map(|value| {
                        let value_offset = value_offset as usize;
                        let data = &value[value_offset.min(value.len())..];
@@ -102,6 +97,16 @@ pub trait Storage {
                        value_out[..written].copy_from_slice(&data[..written]);
                        data.len() as u32
                })
+
+       }
+
+       /// Get `key` from storage, placing the value into `value_out` and return the number of
+       /// bytes that the entry in storage has beyond the offset or `None` if the storage entry
+       /// doesn't exist at all.
+       /// If `value_out` length is smaller than the returned length, only `value_out` length bytes
+       /// are copied into `value_out`.
+       fn read(&self, key: &[u8], value_out: &mut [u8], value_offset: u32) -> Option<u32> {
+               storage::read_impl(key, value_out, value_offset)
        }

        /// Set `key` to `value` in the storage.
```
It compiles but fails the tests:
```
---- storage::types::value::test::test stdout ----
thread 'storage::types::value::test::test' panicked at 'already borrowed: BorrowMutError', /home/porton/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.1.2/src/lib.rs:143:41

---- storage::types::map::test::test stdout ----
thread 'storage::types::map::test::test' panicked at 'already borrowed: BorrowMutError', /home/porton/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.1.2/src/lib.rs:143:41

---- storage::types::double_map::test::test stdout ----
thread 'storage::types::double_map::test::test' panicked at 'already borrowed: BorrowMutError', /home/porton/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.1.2/src/lib.rs:143:41
```

This example shows that there is no (at least obvious) way to extract a part of a runtime function into a separate function (what may be necessary to factor out code of two similar functions into a third function). That's bad. What to do now?

**Comment by bkchr** [comment]
Just create a free standing function that you call from your functions?

**Comment by vporton** [comment]
> Just create a free standing function that you call from your functions?

But what should be its type for the argument `self`?

Note `self.read_impl(key, value_out, value_offset)` in the original bug report given as an example.
