### ISSUE TITLE
Panic at "client/finality-grandpa/src/import.rs" 682 lines

### ISSUE THREAD

**Issue by MyronFanQiu** [paritytech/substrate#7668]
We met an error when the client runs. It suddenly shutdown. I search the code, looks like the panic is by design. I want to know the reason for this panic and how to avoid it? 

error log
```2020-12-03 08:37:09  💤 Idle (21 peers), best: #1325518 (0xe632…4d30), finalized #1325517 (0xcb0e…333a), ⬇ 12.7kiB/s ⬆ 6.8kiB/s
2020-12-03 08:37:14  💤 Idle (21 peers), best: #1325518 (0xe632…4d30), finalized #1325517 (0xcb0e…333a), ⬇ 3.4kiB/s ⬆ 5.0kiB/s
2020-12-03 08:37:19  💤 Idle (21 peers), best: #1325518 (0xe632…4d30), finalized #1325517 (0xcb0e…333a), ⬇ 4.3kiB/s ⬆ 13.7kiB/s
2020-12-03 08:37:23  💔 Error importing block 0xf57719e4ec5cb278bdd62c216e1eb5b9e22adbd557d18949c14e324adecd1407: Err(UnknownParent)
2020-12-03 08:37:24  💤 Idle (21 peers), best: #1325518 (0xe632…4d30), finalized #1325517 (0xcb0e…333a), ⬇ 3.0kiB/s ⬆ 2.7kiB/s
2020-12-03 08:37:29  💤 Idle (21 peers), best: #1325518 (0xe632…4d30), finalized #1325517 (0xcb0e…333a), ⬇ 5.6kiB/s ⬆ 3.6kiB/s
2020-12-03 08:37:35  ⚙️  Syncing  0.0 bps, target=#1325524 (21 peers), best: #1325518 (0xe632…4d30), finalized #1325517 (0xcb0e…333a), ⬇ 4.2kiB/s ⬆ 11.5kiB/s
2020-12-03 08:37:38  ♻️  Reorg on #1325518,0xe632…4d30 to #1325518,0x3a7e…5600, common ancestor #1325517,0xcb0e…333a
2020-12-03 08:37:38  ✨ Imported #1325518 (0x3a7e…5600)
2020-12-03 08:37:38  👴 Applying authority set change scheduled at block #1325518
2020-12-03 08:37:38  👴 Applying GRANDPA set change to new set with 60 authorities
2020-12-03 08:37:38  Writing a telemetry log took more than 50ms
2020-12-03 08:37:38  Re-finalized block #0x3a7e29135b9569edc4a92982e55134740fda0e5b301b7246d3e28b4867b55600 (1325518) in the canonical chain, current best finalized is #1325518

====================

Version: 0.10.2-26bf8bc-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/d9a105fdd46c926ae606777a46dd90e5b838f92f/library/std/src/panicking.rs:595
   2: std::panicking::begin_panic::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: std::panicking::begin_panic
   5: sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC>::import_justification
   6: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sp_consensus::block_import::BlockImport<Block>>::import_block
   7: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sp_consensus::block_import::BlockImport<Block>>::import_block
   8: sp_consensus::import_queue::import_single_block_metered
   9: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  10: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
  11: <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as core::future::future::Future>::poll
  12: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  13: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  14: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  16: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  17: std::thread::local::LocalKey<T>::with
  18: futures_executor::local_pool::block_on
  19: tokio::runtime::task::core::Core<T,S>::poll
  20: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  21: tokio::runtime::task::raw::poll
  22: tokio::runtime::blocking::pool::Inner::run
  23: tokio::runtime::context::enter
  24: std::sys_common::backtrace::__rust_begin_short_backtrace
  25: core::ops::function::FnOnce::call_once{{vtable.shim}}
  26: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/d9a105fdd46c926ae606777a46dd90e5b838f92f/library/alloc/src/boxed.rs:1318
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/d9a105fdd46c926ae606777a46dd90e5b838f92f/library/alloc/src/boxed.rs:1318
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/d9a105fdd46c926ae606777a46dd90e5b838f92f/library/std/src/sys/unix/thread.rs:71
  27: start_thread
  28: clone


Thread 'tokio-runtime-worker' panicked at 'returns Ok when no authority set change should be enacted; qed;', /opt/cache/git/checkouts/substrate-7e08433d4c370a21/668ecad/client/finality-grandpa/src/import.rs:682```

**Comment by MyronFanQiu** [comment]
Related issue https://github.com/crustio/crust/issues/344

**Comment by bkchr** [comment]
CC @andresilva

**Comment by andresilva** [comment]
The root cause here seems to be that we are trying to import this block twice, since this is a block that changes the authority set this leads to some consistency issues and hence the deliberate panic (https://github.com/paritytech/substrate/blob/master/client/finality-grandpa/src/import.rs#L424-L425). The weird thing is why we try to import the block twice (but that could be some sync bug or whatever), but most importantly why we don't detect this in `GrandpaBlockImport` since the first thing we do there is check block status and early exit if it is already in chain.

There is also this earlier in the log which is also suspicious:
`2020-12-03 08:37:23  💔 Error importing block 0xf57719e4ec5cb278bdd62c216e1eb5b9e22adbd557d18949c14e324adecd1407: Err(UnknownParent)`

**Comment by andresilva** [comment]
@MyronFanQiu Do you know if the node is running with state pruning disabled, i.e. it is running in archive mode? If the node is a validator this should be the default unless explicitly changed.

**Comment by MyronFanQiu** [comment]
@andresilva We met such errors `2020-12-03 08:37:23 💔 Error importing block 0xf57719e4ec5cb278bdd62c216e1eb5b9e22adbd557d18949c14e324adecd1407: Err(UnknownParent)` several times.

**Comment by MyronFanQiu** [comment]
@andresilva You can check this log as well. https://github.com/crustio/crust/issues/345

**Comment by MyronFanQiu** [comment]
@andresilva Hi. We met this error again. Is there any suggestion or solution?
