### ISSUE TITLE
Node panicking 

### ISSUE THREAD

**Issue by Gauthamastro** [paritytech/substrate#7794]
Steps to reproduce

1. Clone Substrate Master
2. cargo build
3. ./target/debug/substrate

Logs
```

2020-12-27 09:43:44  Substrate Node
2020-12-27 09:43:44  ✌️  version 2.0.0-281f81c97-x86_64-linux-gnu
2020-12-27 09:43:44  ❤️  by Parity Technologies <admin@parity.io>, 2017-2020
2020-12-27 09:43:44  📋 Chain specification: Flaming Fir
2020-12-27 09:43:44  🏷 Node name: dark-bun-7831
2020-12-27 09:43:44  👤 Role: FULL
2020-12-27 09:43:44  💾 Database: RocksDb at /home/gj/.local/share/substrate/chains/flamingfir9/db
2020-12-27 09:43:44  ⛓  Native runtime: node-261 (substrate-node-0.tx2.au10)
2020-12-27 09:43:45  🔨 Initializing Genesis block/state (state: 0x89b8…d3e7, header-hash: 0xe40f…ed39)
2020-12-27 09:43:45  👴 Loading GRANDPA authority set from genesis on what appears to be first startup.
2020-12-27 09:43:46  ⏱  Loaded block-time = 3000 milliseconds from genesis on first-launch
2020-12-27 09:43:46  👶 Creating empty BABE epoch changes on what appears to be first startup.
2020-12-27 09:43:46  🏷 Local node identity is: 12D3KooWPHEVTvAnFVaTM55fPdgzCKqU7JRxAQzVbJWQMu7RZ6pV
2020-12-27 09:43:46  📦 Highest known block at #0
2020-12-27 09:43:46  〽️ Prometheus server started at 127.0.0.1:9615
2020-12-27 09:43:46  Listening for new connections on 127.0.0.1:9944.

====================

Version: 2.0.0-281f81c97-x86_64-linux-gnu

   0: sp_panic_handler::panic_hook
             at primitives/panic-handler/src/lib.rs:150:18
   1: sp_panic_handler::set::{{closure}}
             at primitives/panic-handler/src/lib.rs:60:4
   2: std::panicking::rust_panic_with_hook
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:573:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:476:9
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:153:18
   5: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475:5
   6: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85:14
   7: core::option::expect_none_failed
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1221:5
   8: core::result::Result<T,E>::unwrap
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/result.rs:973:23
   9: if_watch::unix::linux::NetlinkSocket::send_getaddr::{{closure}}::{{closure}}
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/if-watch-0.1.7/src/unix/linux.rs:99:17
  10: async_io::Async<T>::write_with::{{closure}}
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/async-io-1.3.1/src/lib.rs:872:19
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/future/mod.rs:79:19
  12: if_watch::unix::linux::NetlinkSocket::send_getaddr::{{closure}}
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/if-watch-0.1.7/src/unix/linux.rs:95:9
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/future/mod.rs:79:19
  14: if_watch::unix::IfWatcher::new::{{closure}}
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/if-watch-0.1.7/src/unix.rs:74:9
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/future/mod.rs:79:19
  16: if_watch::IfWatcher::new::{{closure}}
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/if-watch-0.1.7/src/lib.rs:41:17
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/future/mod.rs:79:19
  18: libp2p_mdns::service::MdnsService::new_inner::{{closure}}
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-mdns-0.26.0/src/service.rs:169:24
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/future/mod.rs:79:19
  20: libp2p_mdns::service::MdnsService::new::{{closure}}
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-mdns-0.26.0/src/service.rs:139:9
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/future/mod.rs:79:19
  22: libp2p_mdns::behaviour::Mdns::new::{{closure}}
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-mdns-0.26.0/src/behaviour.rs:95:44
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/future/mod.rs:79:19
  24: sc_network::discovery::MdnsWrapper::poll
             at client/network/src/discovery.rs:807:36
  25: <sc_network::discovery::DiscoveryBehaviour as libp2p_swarm::behaviour::NetworkBehaviour>::poll
             at client/network/src/discovery.rs:739:31
  26: <sc_network::behaviour::Behaviour<B,H> as libp2p_swarm::behaviour::NetworkBehaviour>::poll
             at client/network/src/behaviour.rs:47:10
  27: libp2p_swarm::ExpandedSwarm<TBehaviour,TInEvent,TOutEvent,THandler>::poll_next_event
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-swarm-0.25.0/src/lib.rs:679:17
  28: libp2p_swarm::ExpandedSwarm<TBehaviour,TInEvent,TOutEvent,THandler>::next_event::{{closure}}::{{closure}}
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-swarm-0.25.0/src/lib.rs:470:35
  29: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/poll_fn.rs:54:9
  30: libp2p_swarm::ExpandedSwarm<TBehaviour,TInEvent,TOutEvent,THandler>::next_event::{{closure}}
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-swarm-0.25.0/src/lib.rs:470:9
  31: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/future/mod.rs:79:19
  32: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/future/future.rs:121:9
  33: futures_util::future::future::FutureExt::poll_unpin
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/future/mod.rs:561:9
  34: <sc_network::service::NetworkWorker<B,H> as core::future::future::Future>::poll
             at client/network/src/service.rs:1357:21
  35: <&mut F as core::future::future::Future>::poll
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/future/future.rs:109:9
  36: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/future/fuse.rs:81:37
  37: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/future/future.rs:121:9
  38: futures_util::future::future::FutureExt::poll_unpin
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/future/mod.rs:561:9
  39: sc_service::build_network_future::{{closure}}::{{closure}}::{{closure}}
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/async_await/select_mod.rs:326:13
  40: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:269:13
  41: sc_service::build_network_future::{{closure}}::{{closure}}
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/async_await/select_mod.rs:326:13
  42: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/poll_fn.rs:54:9
  43: sc_service::build_network_future::{{closure}}
             at client/service/src/lib.rs:239:3
  44: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/future/mod.rs:79:19
  45: sc_service::builder::build_network::{{closure}}
             at client/service/src/builder.rs:980:3
  46: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/future/mod.rs:79:19
  47: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
             at client/service/src/task_manager/prometheus_future.rs:56:3
  48: <std::panic::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:325:9
  49: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::{{closure}}
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/future/catch_unwind.rs:28:42
  50: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:308:9
  51: std::panicking::try::do_call
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:373:40
  52: __rust_try
  53: std::panicking::try
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:337:19
  54: std::panic::catch_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:379:14
  55: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/future/catch_unwind.rs:28:9
  56: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/future/future.rs:121:9
  57: futures_util::future::future::FutureExt::poll_unpin
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/future/mod.rs:561:9
  58: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/select.rs:92:36
  59: sc_service::task_manager::SpawnTaskHandle::spawn_inner::{{closure}}
             at client/service/src/task_manager/mod.rs:100:11
  60: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/future/mod.rs:79:19
  61: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-futures-0.2.4/src/lib.rs:258:9
  62: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/future/future.rs:121:9
  63: futures_executor::local_pool::block_on::{{closure}}
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.8/src/local_pool.rs:317:23
  64: futures_executor::local_pool::run_executor::{{closure}}
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.8/src/local_pool.rs:87:37
  65: std::thread::local::LocalKey<T>::try_with
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/thread/local.rs:265:16
  66: std::thread::local::LocalKey<T>::with
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/thread/local.rs:241:9
  67: futures_executor::local_pool::run_executor
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.8/src/local_pool.rs:83:5
  68: futures_executor::local_pool::block_on
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.8/src/local_pool.rs:317:5
  69: sc_cli::runner::Runner<C>::new::{{closure}}::{{closure}}
             at client/cli/src/runner.rs:128:44
  70: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/blocking/task.rs:41:21
  71: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/task/core.rs:173:17
  72: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/loom/std/unsafe_cell.rs:14:9
  73: tokio::runtime::task::core::Core<T,S>::poll
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/task/core.rs:158:13
  74: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/task/harness.rs:107:27
  75: core::ops::function::FnOnce::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227:5
  76: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:308:9
  77: std::panicking::try::do_call
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:373:40
  78: __rust_try
  79: std::panicking::try
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:337:19
  80: std::panic::catch_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:379:14
  81: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/task/harness.rs:89:19
  82: tokio::runtime::task::raw::poll
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/task/raw.rs:104:5
  83: tokio::runtime::task::raw::RawTask::poll
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/task/raw.rs:66:18
  84: tokio::runtime::task::Notified<S>::run
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/task/mod.rs:169:9
  85: tokio::runtime::blocking::pool::Inner::run
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/blocking/pool.rs:250:17
  86: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::{{closure}}
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/blocking/pool.rs:230:21
  87: tokio::runtime::context::enter
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/context.rs:72:5
  88: tokio::runtime::handle::Handle::enter
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/handle.rs:76:9
  89: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/blocking/pool.rs:229:17
  90: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:137:18
  91: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/thread/mod.rs:458:17
  92: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:308:9
  93: std::panicking::try::do_call
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:373:40
  94: __rust_try
  95: std::panicking::try
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:337:19
  96: std::panic::catch_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:379:14
  97: std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/thread/mod.rs:457:30
  98: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227:5
  99: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/boxed.rs:1042:9
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/boxed.rs:1042:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys/unix/thread.rs:87:17
 100: start_thread
 101: clone


Thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }', /home/gj/.cargo/registry/src/github.com-1ecc6299db9ec823/if-watch-0.1.7/src/unix/linux.rs:107
```

**Comment by bkchr** [comment]
CC @tomaka @mxinden @romanb

**Comment by mxinden** [comment]
@Gauthamastro thanks for reporting the issue.

The panic is happening in a new dependency of rust-libp2p (if-watch) introduced with https://github.com/libp2p/rust-libp2p/pull/1830, more particular the panic happens [here](https://github.com/dvc94ch/if-watch/blob/master/src/unix/linux.rs#L99).

To help debug the issue, would you mind posting the output of `ip link show` from your machine here? Feel free to elide any private information.

**Comment by rphmeier** [comment]
@mxinden There's a lot of `unwrap` in that code, which should have never made it to production. I think we should remove that crate as a dependency until it gains proper error handling.

**Comment by Gauthamastro** [comment]
@mxinden Here you go!

```
17: eth0: <> mtu 1500 group default qlen 1
    link/ether ############
16: eth1: <> mtu 1500 group default qlen 1
    link/ether ############
11: eth2: <> mtu 1500 group default qlen 1
    link/ether ############
7: eth3: <> mtu 1500 group default qlen 1
    link/ether ############
1: lo: <LOOPBACK,UP> mtu 1500 group default qlen 1
    link/loopback 00:00:00:00:00:00
12: eth4: <> mtu 1500 group default qlen 1
    link/ether ############
5: wifi0: <BROADCAST,MULTICAST,UP> mtu 1500 group default qlen 1
    link/ieee802.11 ############
13: wifi1: <> mtu 1500 group default qlen 1
    link/ieee802.11 ############
8: wifi2: <> mtu 1500 group default qlen 1
    link/ieee802.11 ############
```

**Comment by tomaka** [comment]
> I think we should remove that crate as a dependency until it gains proper error handling. Our general rule with panickers is "prove or remove" - prove it won't happen and write a string with expect, or don't write a panicker in the first place.

There are three `unwrap()` in the entire `if-watch` repository, and I believe that they can be straight-up replaced with `?`

**Comment by Gauthamastro** [comment]
Is there any update on this?

**Comment by mxinden** [comment]
@Gauthamastro none that I am aware of. I am back from holiday tomorrow. I will have a look at it then.

**Comment by Gauthamastro** [comment]
@mxinden thanks!

**Comment by mxinden** [comment]
@Gauthamastro in the meantime you should be able to prevent the panic above by running your node with `--no-mdns`.

**Comment by Gauthamastro** [comment]
> @Gauthamastro in the meantime you should be able to prevent the panic above by running your node with `--no-mdns`.

Thanks for that!! My projects are depending on Substrate main.

**Comment by dvc94ch** [comment]
Sorry about the unwraps, they seem to be a leftover of a debugging session

**Comment by dvc94ch** [comment]
However it would be useful to fix the actual problem, not the error handling strategy.

@Gauthamastro what kernel are you using? Can you post the output of `uname -a`? It would also be useful to know what the args are that are causing the issue. Can you use strace or println to determine the args that are causing the panics?

**Comment by Gauthamastro** [comment]
@dvc94ch Sure, I will post the logs here later today. I am using the Linux subsystem for windows
Here is the output of uname -a
Linux MSI 4.4.0-19041-Microsoft #488-Microsoft Mon Sep 01 13:43:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bkchr** [comment]
Could we please enforce the `if-watch` release `0.1.8` in libp2p?

**Comment by bkchr** [comment]
Created a polkadot pr to update it for now manually: https://github.com/paritytech/polkadot/pull/2436

**Comment by mxinden** [comment]
> Could we please enforce the `if-watch` release `0.1.8` in libp2p?

:+1: see https://github.com/libp2p/rust-libp2p/pull/1956.

**Comment by bkchr** [comment]
Ty
