### ISSUE TITLE
Difference between `--wasm-execution compiled` and without it?

### ISSUE THREAD

**Issue by MyronFanQiu** [paritytech/substrate#8024]
We encounter one weird issue on one of our machine. If we enable `--wasm-execution compiled`, we would meet the following error message. It seems like that this cpu is not compatible with `--wasm-execution wasm`. May I know the reason behind this error and how to avoid it in the future? Is there any limit for `--wasm-execution compiled`? 
```
Version: 0.11.1-1ce71bb-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/61f5a0092364061ec5649ca98d5e3e9b927880fe/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/61f5a0092364061ec5649ca98d5e3e9b927880fe/library/std/src/panicking.rs:495:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/61f5a0092364061ec5649ca98d5e3e9b927880fe/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/61f5a0092364061ec5649ca98d5e3e9b927880fe/library/std/src/panicking.rs:493:5
   5: core::panicking::panic_fmt
             at /rustc/61f5a0092364061ec5649ca98d5e3e9b927880fe/library/core/src/panicking.rs:92:14
   6: core::panicking::panic
             at /rustc/61f5a0092364061ec5649ca98d5e3e9b927880fe/library/core/src/panicking.rs:50:5
   7: raw_cpuid::CpuId::get_extended_feature_info
   8: cranelift_native::builder
   9: wasmtime_jit::native::builder
  10: wasmtime::runtime::Config::new
  11: sc_executor_wasmtime::runtime::create_runtime
  12: sc_executor::wasm_runtime::create_wasm_runtime_with_code
  13: sc_executor::wasm_runtime::create_versioned_wasm_runtime
  14: sc_executor::wasm_runtime::RuntimeCache::with_instance
  15: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
  16: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
  17: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
  18: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::call
  19: <alloc::sync::Arc<dyn sc_client_api::call_executor::ExecutorProvider<Block>+Executor = E> as sc_finality_grandpa::GenesisAuthoritySetProvider<Block>>::get
  20: sc_finality_grandpa::aux_schema::load_persistent
  21: crust::service::new_partial
  22: crust::service::new_full
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  24: std::thread::local::LocalKey<T>::with
  25: tokio::runtime::thread_pool::ThreadPool::block_on
  26: tokio::runtime::context::enter
  27: sc_cli::runner::Runner<C>::run_node_until_exit
  28: crust::command::run
  29: crust::main
  30: std::sys_common::backtrace::__rust_begin_short_backtrace
  31: std::rt::lang_start::{{closure}}
  32: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/61f5a0092364061ec5649ca98d5e3e9b927880fe/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/61f5a0092364061ec5649ca98d5e3e9b927880fe/library/std/src/panicking.rs:379:40
      std::panicking::try
             at /rustc/61f5a0092364061ec5649ca98d5e3e9b927880fe/library/std/src/panicking.rs:343:19
      std::panic::catch_unwind
             at /rustc/61f5a0092364061ec5649ca98d5e3e9b927880fe/library/std/src/panic.rs:396:14
      std::rt::lang_start_internal
             at /rustc/61f5a0092364061ec5649ca98d5e3e9b927880fe/library/std/src/rt.rs:51:25
  33: main
  34: __libc_start_main
  35: _start


Thread 'main' panicked at 'assertion failed: res.eax == 0', /home/crust/.cargo/registry/src/github.com-1ecc6299db9ec823/raw-cpuid-7.0.3/src/lib.rs:295

This is a bug. Please report it at:

	https://github.com/crustio/crust/issues/new
```

**Comment by MyronFanQiu** [comment]
The cpu information is 
```
^Croot@iZuf672zlth26rsefiw5ciZ:~# lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8369HB CPU @ 3.30GHz
Stepping:            11
CPU MHz:             3300.000
BogoMIPS:            6600.00
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            33792K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat avx512_vnni
```

**Comment by bkchr** [comment]
This looks like some bug in `wasmtime`. Wasmtime is the compiler we use for our compiled wasm execution. I know that there was some upstream bug in wasmtime related to `cpuid`. So, maybe this is fixed with the next update of wasmtime.

**Comment by bkchr** [comment]
We have now udpated to the latest `wasmtime`. It should hopefully fix your problem, otherwise please report it upstream.
