### ISSUE TITLE
Subkey verify panics with certain inputs

### ISSUE THREAD

**Issue by alexspurling** [paritytech/substrate#8026]
The following inputs cause subkey verify to panic:

```
$ echo -n "05008eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a480b00502a4d3b70050000001b0000000500000043f1e3e3b9703dcb11f0cdc66b0a01e34fd84301489efb5266840fab4ae6e91e43f1e3e3b9703dcb11f0cdc66b0a01e34fd84301489efb5266840fab4ae6e91e" | xxd -r -p | target/release/subkey verify c51d8eb929a19df585abaa9af5b8959cd5708e7d8d90db0c409c4e1c1116664fd4d820eb48be841f9c4f7755e727ed03cf176d395c3011adb486fbd05969c2a0 0x029152f0c143955b70ef185a597895b453d233f4502bf5c28780b30226d52855f9
thread 'main' panicked at 'source slice length (33) does not match destination slice length (32)', /home/alexs/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/mod.rs:2745:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
   2: core::slice::<impl [T]>::copy_from_slice::len_mismatch_fail
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/slice/mod.rs:2738:13
   3: <sp_core::sr25519::Public as sp_core::crypto::Public>::from_slice
   4: sc_cli::commands::verify::VerifyCmd::run
   5: subkey::run
   6: subkey::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I have compiled subkey from master with commit `2d5a75d762c0408e4c341fd55f0d55e20dc6c017`

**Comment by alexspurling** [comment]
The actual cause of this error is when trying to verify an ECDSA public key without using the `scheme=ecdsa` flag. I will close the bug for now.
