### ISSUE TITLE
Encountered consensus error: ClientImport("Timeout in the Slots proposer")

### ISSUE THREAD

**Issue by 2075** [paritytech/substrate#8304]
Hey there,
we have tried a migration from 2.0.1 to 3.0.0 and bricked our chain again it seems:

```
2021-03-09 13:29:27  🙌 Starting consensus session on top of parent 0x234f91645afba871cc0f1878d8b50ae64420569a907fbdb3dd3a9eb79a04776e
2021-03-09 13:29:32  Timeout fired waiting for transaction pool at block #890338. Proceeding with production.
2021-03-09 13:29:33  ♻️  Reorg on #890338,0x234f…776e to #890339,0x030f…8d0d, common ancestor #890337,0xe46f…7690
2021-03-09 13:29:33  ✨ Imported #890339 (0x030f…8d0d)
2021-03-09 13:29:37  🎁 Prepared block for proposing at 890339 [hash: 0x18513d164ab5ac07a7d9754d270c86d213b63b533000b03e7a450aa16097d1ad; parent_hash: 0x234f…776e; extrinsics (2): [0x5381…c02e, 0x2716…7644]]
2021-03-09 13:29:39  🔖 Pre-sealed block for proposal at 890339. Hash now 0xdf9b735baa3d6235b8ab550efd40665ec98f1984135223dbca6fc547089d6896, previously 0x18513d164ab5ac07a7d9754d270c86d213b63b533000b03e7a450aa16097d1ad.
2021-03-09 13:29:49  🙌 Starting consensus session on top of parent 0xdf9b735baa3d6235b8ab550efd40665ec98f1984135223dbca6fc547089d6896
2021-03-09 13:30:11  ⌛️ Discarding proposal for slot 538432194; block production took too long
2021-03-09 13:30:13  Encountered consensus error: ClientImport("Timeout in the Slots proposer")

====================

Version: 1.10.0-9c443094a-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at rustc/234781afe33d3f339b002f85f948046d8476cfc9/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic::{{closure}}
.
.
.
.


Thread 'tokio-runtime-worker' panicked at 'Unexpected Either::Right on enabled `inject_listen_upgrade_error`.', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-swarm-0.27.1/src/toggle.rs:288

This is a bug. Please report it at:

	https://github.com/paritytech/substrate/issues/new

pure virtual method called
```

There are no new pallets, just upgraded substrate. 
It seems the validators are very instable now, the log above is from one which just disappeared.
Also, there is some slashing happening due to the inconsistent uptimes.

We have first updated the wasm, later on pulled the new docker images and restarted the bootnodes and valdiators.

Is there a way out of this? It feels a little odd, that we brick the chain whenever we upgrade the node, already the third time or so since early 2020.

CPU usage seems over average, also for the crashing nodes: 
<img width="296" alt="image" src="https://user-images.githubusercontent.com/1140449/110488633-efe0f000-80ee-11eb-8d48-7245b51c819f.png">

thanks again for any pointers!

**Comment by bkchr** [comment]
CC @tomaka 

As the panic is coming from libp2p.

**Comment by tomaka** [comment]
Please run `cargo update -p libp2p-swarm`

**Comment by 2075** [comment]
Thx, will check and ping back

**Comment by 2075** [comment]
LGTM 4 nao. thx!

**Comment by 2075** [comment]
last signs of life before the node moves into the void:

```

**Comment by 2075** [comment]
But it seems like it is an aws issue, wowee:
![image](https://user-images.githubusercontent.com/1140449/110673660-58080280-81d1-11eb-825f-1bf85e283faf.png)

**Comment by bkchr** [comment]
So we can close this?

**Comment by 2075** [comment]
Not sure, we experience instability on some other nodes outside as well, prior to our 3.0.0 upgrade everything ran smooth. Some nodes are stable, but not validators. It seems somehow related to validator nodes, they lost their validator icon in telemetry, too. And we see this type of messages in log:

```
subzero    | 2021-03-10 20:13:54  ✨ Imported #912229 (0xf69b…7c28)
subzero    | 2021-03-10 20:13:57  💤 Idle (9 peers), best: #912229 (0xf69b…7c28), finalized #912227 (0x16e7…ac03), ⬇ 14.7kiB/s ⬆ 11.5kiB/s
subzero    | 2021-03-10 20:13:57  ✨ Imported #912230 (0x8022…f64b)
subzero    | 2021-03-10 20:14:06  ✨ Imported #912231 (0x0e7c…93db)
subzero    | 2021-03-10 20:14:06  🙌 Starting consensus session on top of parent 0x8022fe3a51a33b5790a41c091db79c700458fdb49b854d034dd065313206f64b
subzero    | 2021-03-10 20:14:09  ⌛️ Discarding proposal for slot 538469081; block production took too long
subzero    | 2021-03-10 20:14:09  Encountered consensus error: ClientImport("Timeout in the Slots proposer")
subzero    | 2021-03-10 20:14:11  Timeout fired waiting for transaction pool at block #912230. Proceeding with production.
subzero    | 2021-03-10 20:14:13  🎁 Prepared block for proposing at 912231 [hash: 0xfffb016d8c285b15a84526899585582861f98c82cf89d684bfa6cede2f25fb46; parent_hash: 0x8022…f64b; extrinsics (1): [0xb38d…bdb6]]
subzero    | 2021-03-10 20:14:18  ✨ Imported #912231 (0x3ebd…d8fb)
subzero    | 2021-03-10 20:14:19  🙌 Starting consensus session on top of parent 0x0e7c67f0a89998ec1b1769fc36d0e00a71fd36b804d6c250e0461c89fa7093db
subzero    | 2021-03-10 20:14:23  Timeout fired waiting for transaction pool at block #912231. Proceeding with production.
subzero    | 2021-03-10 20:14:26  🎁 Prepared block for proposing at 912232 [hash: 0x1a17451db4abc0d330f30206f063e198e5eedff7d37c8bf1717cb1607595599a; parent_hash: 0x0e7c…93db; extrinsics (2): [0xfcbb…2f9d, 0x6486…6a60]]
subzero    | 2021-03-10 20:14:27  🔖 Pre-sealed block for proposal at 912232. Hash now 0x7fa39dd1b95c128ed8fabd627feac7628f551ccca0a73b61114d1e85c72f7e45, previously 0x1a17451db4abc0d330f30206f063e198e5eedff7d37c8bf1717cb1607595599a.
```

**Comment by 2075** [comment]
![image](https://user-images.githubusercontent.com/1140449/110693607-eb4c3280-81e7-11eb-87cc-d41365f54871.png)

**Comment by 2075** [comment]
maybe also related to dotmogs finding, will check if it is related to thread_local.

**Comment by bkchr** [comment]
I don't know what your last Screenshot should tell us.

**Comment by 2075** [comment]
well, networking seems to be a general issue with all of the above mentioned logs, considering our instances across various datacenters are used since almost a year, continuously running recent builds of substrate and since 3.0.0 there seem to be network issues out of nowhere.

**Comment by 2075** [comment]
> maybe also related to dotmogs finding, will check if it is related to thread_local.

this seemed to do the trick. thanks @tomaka @darkfriend77
