### ISSUE TITLE
Collator panics in dev mode

### ISSUE THREAD

**Issue by mikiquantum** [paritytech/substrate#8318]
Noticed this error when running Acala collator in dev mode through polkadot-launch. 

The parachain produces and finalizes blocks for some time and then it panics with no apparent reason or trigger.
Already talked to Acala and suggested to open an issue here, since it seems that is more of a core substrate issue.

```
Version: 0.7.3-41e0550-x86_64-macos

   0: backtrace::backtrace::libunwind::trace
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/backtrace/libunwind.rs:90:5
      backtrace::backtrace::trace_unsynchronized
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/backtrace/mod.rs:66:5
   1: backtrace::backtrace::trace
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/backtrace/mod.rs:53:14
   2: backtrace::capture::Backtrace::create
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/capture.rs:176:9
   3: backtrace::capture::Backtrace::new
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/capture.rs:140:22
   4: sp_panic_handler::panic_hook
             at /Users/miguelhervas/.cargo/git/checkouts/substrate-7e08433d4c370a21/e03ca38/primitives/panic-handler/src/lib.rs:150:18
   5: sp_panic_handler::set::{{closure}}
             at /Users/miguelhervas/.cargo/git/checkouts/substrate-7e08433d4c370a21/e03ca38/primitives/panic-handler/src/lib.rs:60:4
   6: std::panicking::rust_panic_with_hook
             at /rustc/45b3c28518e4c45dfd12bc2c4400c0d0e9639927/library/std/src/panicking.rs:595:17
   7: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/45b3c28518e4c45dfd12bc2c4400c0d0e9639927/library/std/src/panicking.rs:495:13
   8: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/45b3c28518e4c45dfd12bc2c4400c0d0e9639927/library/std/src/sys_common/backtrace.rs:141:18
   9: rust_begin_unwind
             at /rustc/45b3c28518e4c45dfd12bc2c4400c0d0e9639927/library/std/src/panicking.rs:493:5
  10: core::panicking::panic_fmt
             at /rustc/45b3c28518e4c45dfd12bc2c4400c0d0e9639927/library/core/src/panicking.rs:92:14
  11: core::panicking::panic
             at /rustc/45b3c28518e4c45dfd12bc2c4400c0d0e9639927/library/core/src/panicking.rs:50:5
  12: <sc_network::protocol::generic_proto::behaviour::GenericProto as libp2p_swarm::behaviour::NetworkBehaviour>::inject_event
             at /Users/miguelhervas/.cargo/git/checkouts/substrate-7e08433d4c370a21/e03ca38/client/network/src/protocol/generic_proto/behaviour.rs:1550:9
  13: <sc_network::protocol::Protocol<B,H> as libp2p_swarm::behaviour::NetworkBehaviour>::inject_event
             at /Users/miguelhervas/.cargo/git/checkouts/substrate-7e08433d4c370a21/e03ca38/client/network/src/protocol.rs:1527:3
  14: <sc_network::behaviour::Behaviour<B,H> as libp2p_swarm::behaviour::NetworkBehaviour>::inject_event
             at /Users/miguelhervas/.cargo/git/checkouts/substrate-7e08433d4c370a21/e03ca38/client/network/src/behaviour.rs:55:10
  15: libp2p_swarm::ExpandedSwarm<TBehaviour,TInEvent,TOutEvent,THandler>::poll_next_event
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-swarm-0.27.2/src/lib.rs:509:21
  16: libp2p_swarm::ExpandedSwarm<TBehaviour,TInEvent,TOutEvent,THandler>::next_event::{{closure}}::{{closure}}
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-swarm-0.27.2/src/lib.rs:475:35
  17: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.12/src/future/poll_fn.rs:54:9
  18: libp2p_swarm::ExpandedSwarm<TBehaviour,TInEvent,TOutEvent,THandler>::next_event::{{closure}}
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-swarm-0.27.2/src/lib.rs:475:9
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  20: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  21: futures_util::future::future::FutureExt::poll_unpin
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.12/src/future/future/mod.rs:561:9
  22: <sc_network::service::NetworkWorker<B,H> as core::future::future::Future>::poll
             at /Users/miguelhervas/.cargo/git/checkouts/substrate-7e08433d4c370a21/e03ca38/client/network/src/service.rs:1423:21
  23: <&mut F as core::future::future::Future>::poll
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/future.rs:107:9
  24: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.12/src/future/future/fuse.rs:86:37
  25: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  26: futures_util::future::future::FutureExt::poll_unpin
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.12/src/future/future/mod.rs:561:9
  27: sc_service::build_network_future::{{closure}}::{{closure}}::{{closure}}
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.12/src/async_await/select_mod.rs:326:13
  28: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:269:13
  29: sc_service::build_network_future::{{closure}}::{{closure}}
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.12/src/async_await/select_mod.rs:326:13
  30: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.12/src/future/poll_fn.rs:54:9
  31: sc_service::build_network_future::{{closure}}
             at /Users/miguelhervas/.cargo/git/checkouts/substrate-7e08433d4c370a21/e03ca38/client/service/src/lib.rs:226:3
  32: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  33: sc_service::builder::build_network::{{closure}}
             at /Users/miguelhervas/.cargo/git/checkouts/substrate-7e08433d4c370a21/e03ca38/client/service/src/builder.rs:970:3
  34: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  35: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
             at /Users/miguelhervas/.cargo/git/checkouts/substrate-7e08433d4c370a21/e03ca38/client/service/src/task_manager/prometheus_future.rs:61:3
  36: <std::panic::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:361:9
  37: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::{{closure}}
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.12/src/future/future/catch_unwind.rs:32:42
  38: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  39: std::panicking::try::do_call
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  40: ___rust_try
  41: std::panicking::try
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  42: std::panic::catch_unwind
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  43: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.12/src/future/future/catch_unwind.rs:32:9
  44: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  45: futures_util::future::future::FutureExt::poll_unpin
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.12/src/future/future/mod.rs:561:9
  46: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.12/src/future/select.rs:92:36
  47: sc_service::task_manager::SpawnTaskHandle::spawn_inner::{{closure}}
             at /Users/miguelhervas/.cargo/git/checkouts/substrate-7e08433d4c370a21/e03ca38/client/service/src/task_manager/mod.rs:138:11
  48: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  49: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-futures-0.2.5/src/lib.rs:283:9
  50: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  51: <sc_service::task_manager::WithTelemetrySpan<T> as core::future::future::Future>::poll
             at /Users/miguelhervas/.cargo/git/checkouts/substrate-7e08433d4c370a21/e03ca38/client/service/src/task_manager/mod.rs:70:3
  52: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  53: futures_executor::local_pool::block_on::{{closure}}
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.12/src/local_pool.rs:317:23
  54: futures_executor::local_pool::run_executor::{{closure}}
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.12/src/local_pool.rs:87:37
  55: std::thread::local::LocalKey<T>::try_with
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  56: std::thread::local::LocalKey<T>::with
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  57: futures_executor::local_pool::run_executor
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.12/src/local_pool.rs:83:5
  58: futures_executor::local_pool::block_on
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.12/src/local_pool.rs:317:5
  59: sc_cli::runner::Runner<C>::new::{{closure}}::{{closure}}
             at /Users/miguelhervas/.cargo/git/checkouts/substrate-7e08433d4c370a21/e03ca38/client/cli/src/runner.rs:136:44
  60: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/task.rs:41:21
  61: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:173:17
  62: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/loom/std/unsafe_cell.rs:14:9
  63: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:158:13
  64: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:107:27
  65: core::ops::function::FnOnce::call_once
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  66: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  67: std::panicking::try::do_call
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  68: ___rust_try
  69: std::panicking::try
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  70: std::panic::catch_unwind
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  71: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:89:19
  72: tokio::runtime::task::raw::poll
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:104:5
  73: tokio::runtime::task::raw::RawTask::poll
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:66:18
  74: tokio::runtime::task::Notified<S>::run
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/mod.rs:169:9
  75: tokio::runtime::blocking::pool::Inner::run
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/pool.rs:250:17
  76: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::{{closure}}
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/pool.rs:230:21
  77: tokio::runtime::context::enter
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/context.rs:72:5
  78: tokio::runtime::handle::Handle::enter
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/handle.rs:76:9
  79: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/miguelhervas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/pool.rs:229:17
  80: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  81: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/mod.rs:474:17
  82: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  83: std::panicking::try::do_call
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  84: ___rust_try
  85: std::panicking::try
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  86: std::panic::catch_unwind
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  87: std::thread::Builder::spawn_unchecked::{{closure}}
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/mod.rs:473:30
  88: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /Users/miguelhervas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  89: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/45b3c28518e4c45dfd12bc2c4400c0d0e9639927/library/alloc/src/boxed.rs:1546:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/45b3c28518e4c45dfd12bc2c4400c0d0e9639927/library/alloc/src/boxed.rs:1546:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/45b3c28518e4c45dfd12bc2c4400c0d0e9639927/library/std/src/sys/unix/thread.rs:71:17
  90: __pthread_body
  91: __pthread_start


Thread 'tokio-runtime-worker' panicked at 'assertion failed: matches!(connec_state, ConnectionState :: OpeningThenClosing)', /Users/miguelhervas/.cargo/git/checkouts/substrate-7e08433d4c370a21/e03ca38/client/network/src/protocol/generic_proto/behaviour.rs:1550
```

**Comment by bkchr** [comment]
CC @tomaka

**Comment by tomaka** [comment]
Should have been fixed by this PR: https://github.com/paritytech/substrate/pull/8200

Please run `cargo update -p sc-network`

**Comment by shaunxw** [comment]
Acala has latest `sc-network` dependency which includes the fix. @mikiquantum please pull the latest Acala master branch and rebuild collator node.

**Comment by mikiquantum** [comment]
Awesome, thanks all, will test it out and close this issue if not reproducible.

**Comment by kianenigma** [comment]
@mikiquantum any updates?

**Comment by mikiquantum** [comment]
@kianenigma looks good so far, closing now! Thanks all.
