### ISSUE TITLE
Panic in sc_network after ^C

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#9146]
During a graceful termination there was a panic in `sc_network::transactions::TransactionsHandler`

```
parachain-2000-1_1    | ====================
parachain-2000-1_1    |
parachain-2000-1_1    | Version: 1.0.0-1.0.1-x86_64-linux-gnu
parachain-2000-1_1    |
parachain-2000-1_1    |    0: sp_panic_handler::set::{{closure}}
parachain-2000-1_1    |    1: std::panicking::rust_panic_with_hook
parachain-2000-1_1    |              at rustc/d6eaea1c8860adb5302d2fbaad409e36585ab217/library/std/src/panicking.rs:595:17
parachain-2000-1_1    |    2: std::panicking::begin_panic::{{closure}}
parachain-2000-1_1    |    3: std::sys_common::backtrace::__rust_end_short_backtrace
parachain-2000-1_1    |    4: std::panicking::begin_panic
parachain-2000-1_1    |    5: sc_network::transactions::TransactionsHandler<B,H>::run::{{closure}}::{{closure}}::{{closure}}
parachain-2000-1_1    |    6: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
parachain-2000-1_1    |    7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
parachain-2000-1_1    |    8: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
parachain-2000-1_1    |    9: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
parachain-2000-1_1    |   10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
parachain-2000-1_1    |   11: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
parachain-2000-1_1    |   12: tokio::runtime::task::core::Core<T,S>::poll
parachain-2000-1_1    |   13: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
parachain-2000-1_1    |   14: tokio::runtime::task::harness::Harness<T,S>::poll
parachain-2000-1_1    |   15: std::thread::local::LocalKey<T>::with
parachain-2000-1_1    |   16: tokio::runtime::thread_pool::worker::Context::run_task
parachain-2000-1_1    |   17: tokio::runtime::thread_pool::worker::Context::run
parachain-2000-1_1    |   18: tokio::macros::scoped_tls::ScopedKey<T>::set
parachain-2000-1_1    |   19: tokio::runtime::thread_pool::worker::run
parachain-2000-1_1    |   20: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
parachain-2000-1_1    |   21: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
parachain-2000-1_1    |   22: tokio::runtime::task::raw::poll
parachain-2000-1_1    |   23: tokio::runtime::blocking::pool::Inner::run
parachain-2000-1_1    |   24: tokio::runtime::context::enter
parachain-2000-1_1    |   25: std::sys_common::backtrace::__rust_begin_short_backtrace
parachain-2000-1_1    |   26: core::ops::function::FnOnce::call_once{{vtable.shim}}
parachain-2000-1_1    |   27: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
parachain-2000-1_1    |              at rustc/d6eaea1c8860adb5302d2fbaad409e36585ab217/library/alloc/src/boxed.rs:1546:9
parachain-2000-1_1    |       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
parachain-2000-1_1    |              at rustc/d6eaea1c8860adb5302d2fbaad409e36585ab217/library/alloc/src/boxed.rs:1546:9
parachain-2000-1_1    |       std::sys::unix::thread::Thread::new::thread_start
parachain-2000-1_1    |              at rustc/d6eaea1c8860adb5302d2fbaad409e36585ab217/library/std/src/sys/unix/thread.rs:71:17
parachain-2000-1_1    |   28: start_thread
parachain-2000-1_1    |   29: __clone
parachain-2000-1_1    |
parachain-2000-1_1    |
parachain-2000-1_1    | Thread 'tokio-runtime-worker' panicked at 'SelectNextSome polled after terminated', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/stream/stream/select_next_some.rs:32
parachain-2000-1_1    |
parachain-2000-1_1    | This is a bug. Please report it at:
parachain-2000-1_1    |
parachain-2000-1_1    | 	https://github.com/AcalaNetwork/Acala/issues
parachain-2000-1_1    |
```

**Comment by pepyakin** [comment]
Any closing words?

**Comment by bkchr** [comment]
Sorry, I actually thought this was older than last year. However, this was sitting here without anything actionable. I have also not seen any similar report. If you have a way of reproducing, please reopen.

**Comment by pepyakin** [comment]
Fair! I haven't seen this anymore myself and probably it's fine if we close it for now until next report. 

As an aside: i would be really grateful if you left a message with the reason when closing even if that message is just stale! Thanks in advance

**Comment by bkchr** [comment]
Yeah sorry for not leaving messages, that was my fault. I will do it better next time.
