### ISSUE TITLE
Test `database_role_subdir_migration` is flaky

### ISSUE THREAD

**Issue by emostov** [paritytech/substrate#9731]
Relates to: https://github.com/paritytech/substrate/pull/9645, where the test was introduced (cc @hirschenberger, @cheme, @arkpar)  

I first ran into the issue on this CI check https://gitlab.parity.io/parity/substrate/-/jobs/1106480. 

I am able to intermittently reproduce the issue on master (821496d19b39acdec83f1e36fc3b0d7121f991e8) by running `cargo remote test -b "RUST_BACKTRACE=full" -- -p node-cli --test database_role_subdir_migration`:

```
    Running tests/database_role_subdir_migration.rs (target/debug/deps/database_role_subdir_migration-30929ebd751dda05)

running 2 tests
2021-09-09 01:45:01 Running in --dev mode, RPC CORS has been disabled.
2021-09-09 01:45:01 Substrate Node
2021-09-09 01:45:01 ✌️  version 3.0.0-dev-unknown-x86_64-linux-gnu
2021-09-09 01:45:01 ❤️  by Parity Technologies <admin@parity.io>, 2017-2021
2021-09-09 01:45:01 📋 Chain specification: Development
2021-09-09 01:45:01 🏷 Node name: awake-income-6723
2021-09-09 01:45:01 👤 Role: LIGHT
2021-09-09 01:45:01 💾 Database: RocksDb at /tmp/.tmpFRvAo9/chains/dev/db/light
2021-09-09 01:45:01 ⛓  Native runtime: node-267 (substrate-node-1.tx2.au10)
2021-09-09 01:45:01 Running in --dev mode, RPC CORS has been disabled.
2021-09-09 01:45:01 Substrate Node
2021-09-09 01:45:01 ✌️  version 3.0.0-dev-unknown-x86_64-linux-gnu
2021-09-09 01:45:01 ❤️  by Parity Technologies <admin@parity.io>, 2017-2021
2021-09-09 01:45:01 📋 Chain specification: Development
2021-09-09 01:45:01 🏷 Node name: accessible-calculator-3157
2021-09-09 01:45:01 👤 Role: AUTHORITY
2021-09-09 01:45:01 💾 Database: RocksDb at /tmp/.tmpNfi7UX/chains/dev/db/full
2021-09-09 01:45:01 ⛓  Native runtime: node-267 (substrate-node-1.tx2.au10)
2021-09-09 01:45:02 Migrating database to a database-type-based subdirectory: '"/tmp/.tmpFRvAo9/chains/dev/db"' -> '"/tmp/.tmpFRvAo9/chains/dev/db/light"'
Error: Service(Client(Backend("Error in migration to role subdirectory: Backend error: Unexpected database type. Expected: full")))
2021-09-09 01:45:03 🔨 Initializing Genesis block/state (state: 0xda8d…3e70, header-hash: 0xf07c…c1dd)
2021-09-09 01:45:03 👴 Loading GRANDPA authority set from genesis on what appears to be first startup.
2021-09-09 01:45:06 ⏱  Loaded block-time = 3s from block 0xf07c2abd06b5152c057614097bd0cdb76a803d0974b060e5f7a17d1a1c4cc1dd
2021-09-09 01:45:06 👶 Creating empty BABE epoch changes on what appears to be first startup.
2021-09-09 01:45:06 Using default protocol ID "sup" because none is configured in the chain specs
2021-09-09 01:45:06 🏷 Local node identity is: 12D3KooWLXcdgnhtfGesAiXvXHCieb1FxHcopdqCgP15UyqA9MSY
2021-09-09 01:45:06 📦 Highest known block at #0
2021-09-09 01:45:06 Listening for new connections on 127.0.0.1:44445.
test database_role_subdir_migration_fail_on_different_role ... ok
2021-09-09 01:45:11 💤 Idle (0 peers), best: #0 (0xf07c…c1dd), finalized #0 (0xf07c…c1dd), ⬇ 0 ⬆ 0
2021-09-09 01:45:16 💤 Idle (0 peers), best: #0 (0xf07c…c1dd), finalized #0 (0xf07c…c1dd), ⬇ 0 ⬆ 0
2021-09-09 01:45:21 💤 Idle (0 peers), best: #0 (0xf07c…c1dd), finalized #0 (0xf07c…c1dd), ⬇ 0 ⬆ 0
2021-09-09 01:45:26 💤 Idle (0 peers), best: #0 (0xf07c…c1dd), finalized #0 (0xf07c…c1dd), ⬇ 0 ⬆ 0
pthread lock: Invalid argument
test database_role_subdir_migration ... FAILED

failures:

---- database_role_subdir_migration stdout ----
thread 'database_role_subdir_migration' panicked at 'assertion failed: wait_for(&mut cmd, 40).map(|x| x.success()).unwrap_or_default()', bin/node/cli/tests/common.rs:68:5
stack backtrace:
   0:     0x55a3e828c450 - std::backtrace_rs::backtrace::libunwind::trace::h34055254b57d8e79
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55a3e828c450 - std::backtrace_rs::backtrace::trace_unsynchronized::h8f1e3fbd9afff6ec
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55a3e828c450 - std::sys_common::backtrace::_print_fmt::h3a99a796b770c360
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55a3e828c450 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h32d1f94a80615d18
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55a3e82b064c - core::fmt::write::h306731c068f7162c
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/fmt/mod.rs:1110:17
   5:     0x55a3e8288c15 - std::io::Write::write_fmt::h87f19b0a2cd190bc
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/io/mod.rs:1588:15
   6:     0x55a3e828ea7b - std::sys_common::backtrace::_print::h5abaa2601a852287
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55a3e828ea7b - std::sys_common::backtrace::print::h8d81445442bb638f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55a3e828ea7b - std::panicking::default_hook::{{closure}}::hcfe804496a9fa747
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:208:50
   9:     0x55a3e828e58c - std::panicking::default_hook::hbea8e3ccf2ba8901
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:222:9
  10:     0x55a3e828f144 - std::panicking::rust_panic_with_hook::h7ee9e1a2d0f8975a
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:622:17
  11:     0x55a3e828ebf7 - std::panicking::begin_panic_handler::{{closure}}::h8ab3b4491718b2c7
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:517:13
  12:     0x55a3e828c94c - std::sys_common::backtrace::__rust_end_short_backtrace::hd489062ffa586a9f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55a3e828eb89 - rust_begin_unwind
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
  14:     0x55a3e7cb4dd1 - core::panicking::panic_fmt::hca6330e3e14086b4
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
  15:     0x55a3e7cb4d1d - core::panicking::panic::h1a48d878ff3dcd40
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:50:5
  16:     0x55a3e7cea7aa - database_role_subdir_migration::common::run_node_for_a_while::h60c83b29287fbfc2
                               at /home/emostov/remote-builds/substrate-master/bin/node/cli/tests/common.rs:68:2
  17:     0x55a3e7ce437e - database_role_subdir_migration::database_role_subdir_migration::h0626f094b24e7b83
                               at /home/emostov/remote-builds/substrate-master/bin/node/cli/tests/database_role_subdir_migration.rs:52:2
  18:     0x55a3e7ceb64a - database_role_subdir_migration::database_role_subdir_migration::{{closure}}::h8f0cd94d7c292497
                               at /home/emostov/remote-builds/substrate-master/bin/node/cli/tests/database_role_subdir_migration.rs:30:1
  19:     0x55a3e7cdd7fe - core::ops::function::FnOnce::call_once::h27d160030014d9da
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
  20:     0x55a3e7d24bd3 - core::ops::function::FnOnce::call_once::h152e7e439ff59e19
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
  21:     0x55a3e7d24bd3 - test::__rust_begin_short_backtrace::h0908f3b1fdbb72ab
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/test/src/lib.rs:577:5
  22:     0x55a3e7d23690 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf6d2a51e5587546c
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/boxed.rs:1575:9
  23:     0x55a3e7d23690 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h8af660f3a89ef593
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:347:9
  24:     0x55a3e7d23690 - std::panicking::try::do_call::hd36aef60f84b6d36
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
  25:     0x55a3e7d23690 - std::panicking::try::h9932b4480e69817c
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
  26:     0x55a3e7d23690 - std::panic::catch_unwind::h6aa177099cfff5f8
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
  27:     0x55a3e7d23690 - test::run_test_in_process::h5884d6f2d99e20c3
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/test/src/lib.rs:600:18
  28:     0x55a3e7d23690 - test::run_test::run_test_inner::{{closure}}::h6fdc58c6d5f5b6e3
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/test/src/lib.rs:492:39
  29:     0x55a3e7cfcd42 - test::run_test::run_test_inner::{{closure}}::h408365d67a78ade8
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/test/src/lib.rs:519:37
  30:     0x55a3e7cfcd42 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb560b77c4f701523
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:125:18
  31:     0x55a3e7d008f8 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hf2e7831dad93c597
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/mod.rs:481:17
  32:     0x55a3e7d008f8 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hd2e08783d8be4d02
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:347:9
  33:     0x55a3e7d008f8 - std::panicking::try::do_call::h062597b7acfd6b82
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
  34:     0x55a3e7d008f8 - std::panicking::try::h0d7b79db04c14552
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
  35:     0x55a3e7d008f8 - std::panic::catch_unwind::hb01a0b5e7c8cd43b
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
  36:     0x55a3e7d008f8 - std::thread::Builder::spawn_unchecked::{{closure}}::h5bde48cc887e0d1e
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/mod.rs:480:30
  37:     0x55a3e7d008f8 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h745ea30807a29e55
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
  38:     0x55a3e8294f47 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7ece6cfefaff1005
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/boxed.rs:1575:9
  39:     0x55a3e8294f47 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb8b48e55c21f193e
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/boxed.rs:1575:9
  40:     0x55a3e8294f47 - std::sys::unix::thread::Thread::new::thread_start::h8c7c4450dba62914
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys/unix/thread.rs:71:17
  41:     0x7f4e956e5f27 - start_thread
  42:     0x7f4e954cb2af - clone
  43:                0x0 - <unknown>


failures:
    database_role_subdir_migration

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 31.16s

error: test failed, to rerun pass '-p node-cli --test database_role_subdir_migration'
```

**Comment by hirschenberger** [comment]
I can reproduce it in master but it works in 6e15de9703bfe09b85efa33fd6e3a94d2446dd01. 

It looks as if the client was not killed here: https://github.com/paritytech/substrate/blob/master/bin/node/cli/tests/common.rs#L67

I'll bisect my commit to master to see where it broke.

**Comment by bkchr** [comment]
> That output: `pthread lock: Invalid argument` looks suspicious.

This is not related to your changes. I think this is related to the upgrade of tokio and my changes there. I'm already working on a pr to hopefully fix this.
