### ISSUE TITLE
Can't start the template node again

### ISSUE THREAD

**Issue by i5possible** [paritytech/substrate#9828]
I tried https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/interact days ago and everything works. I could start a local node and see the UI.

But when I try to start it again today, I got this issue:
```
### Run 
./target/release/node-template --dev --tmp

### Logs:
2021-09-21 10:25:11 Running in --dev mode, RPC CORS has been disabled.
2021-09-21 10:25:11 Substrate Node
2021-09-21 10:25:11 ✌️  version 3.0.0-monthly-2021-09+1-bf52814-x86_64-macos
2021-09-21 10:25:11 ❤️  by Substrate DevHub <https://github.com/substrate-developer-hub>, 2017-2021
2021-09-21 10:25:11 📋 Chain specification: Development
2021-09-21 10:25:11 🏷 Node name: material-business-4021
2021-09-21 10:25:11 👤 Role: AUTHORITY
2021-09-21 10:25:11 💾 Database: RocksDb at /var/folders/ps/htk5h32x6qd4742vg229qh9h0000gn/T/substrateHeKZyP/chains/dev/db
2021-09-21 10:25:11 ⛓  Native runtime: node-template-100 (node-template-1.tx1.au1)
2021-09-21 10:25:11 🔨 Initializing Genesis block/state (state: 0x40aa…10c5, header-hash: 0x54f9…f290)
2021-09-21 10:25:11 👴 Loading GRANDPA authority set from genesis on what appears to be first startup.
2021-09-21 10:25:11 ⏱  Loaded block-time = 6s from block 0x54f949c814b3b61bb3f74f2dfa9b140bd6f025090d2ef9669afa912ba1cbf290
2021-09-21 10:25:11 Using default protocol ID "sup" because none is configured in the chain specs
2021-09-21 10:25:11 🏷 Local node identity is: 12D3KooWR55vq2b3ku8Y7kcPoPRux4wwvwJroTXVk8P8Vv8ZGAYX
2021-09-21 10:25:12 📦 Highest known block at #0
2021-09-21 10:25:12 Unable to listen on 127.0.0.1:9944

====================

Version: 3.0.0-monthly-2021-09+1-bf52814-x86_64-macos

   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: sp_panic_handler::set::{{closure}}
   3: std::panicking::rust_panic_with_hook
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:626:17
   4: std::panicking::begin_panic::{{closure}}
   5: std::sys_common::backtrace::__rust_end_short_backtrace
   6: std::panicking::begin_panic
   7: tokio::runtime::blocking::shutdown::Receiver::wait
   8: tokio::runtime::blocking::pool::BlockingPool::shutdown
   9: <tokio::runtime::blocking::pool::BlockingPool as core::ops::drop::Drop>::drop
  10: core::ptr::drop_in_place<tokio::runtime::blocking::pool::BlockingPool>
  11: jsonrpc_ws_server::server::Server::start
  12: sc_rpc_server::inner::start_ws
  13: sc_service::start_rpc_servers::{{closure}}
  14: sc_service::start_rpc_servers
  15: sc_service::builder::spawn_tasks
  16: node_template::service::new_full
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  18: tokio::park::thread::CachedParkThread::block_on
  19: tokio::runtime::thread_pool::ThreadPool::block_on
  20: sc_cli::runner::Runner<C>::run_node_until_exit
  21: node_template::command::run
  22: node_template::main
  23: std::sys_common::backtrace::__rust_begin_short_backtrace
  24: std::rt::lang_start::{{closure}}
  25: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
      std::panicking::try
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
      std::panic::catch_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
      std::rt::lang_start_internal
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:34:21
  26: _main


Thread 'main' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', /Users/hong.liang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/blocking/shutdown.rs:51
```

Any ideas what happened and how can I get through it?

**Comment by bkchr** [comment]
This is fixed in master
