### ISSUE TITLE
Benchmark panics on `--steps=1 --repeat=1 --output` flags

### ISSUE THREAD

**Issue by ucover** [paritytech/substrate#9985]
## Problem
Running a node benchmark with flags `--steps 1 --repeat 1 --output weights.rs` panics in  `/utils/frame/benchmarking-cli/src/writer.rs:170` with:  
<details>
<summary>Trace</summary>

```pre
Version: 3.0.0-monthly-2021-10-865c0c0-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/9dbb26efe8a886f7bba94c2b996c9535ce07f917/library/std/src/panicking.rs:628:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9dbb26efe8a886f7bba94c2b996c9535ce07f917/library/std/src/panicking.rs:521:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9dbb26efe8a886f7bba94c2b996c9535ce07f917/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/9dbb26efe8a886f7bba94c2b996c9535ce07f917/library/std/src/panicking.rs:517:5
   5: core::panicking::panic_fmt
             at /rustc/9dbb26efe8a886f7bba94c2b996c9535ce07f917/library/core/src/panicking.rs:100:14
   6: core::panicking::panic_display
             at /rustc/9dbb26efe8a886f7bba94c2b996c9535ce07f917/library/core/src/panicking.rs:64:5
   7: core::option::expect_failed
             at /rustc/9dbb26efe8a886f7bba94c2b996c9535ce07f917/library/core/src/option.rs:1624:5
   8: frame_benchmarking_cli::writer::write_results
   9: frame_benchmarking_cli::command::<impl frame_benchmarking_cli::BenchmarkCmd>::run
  10: node_template::main
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: std::rt::lang_start::{{closure}}
  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/9dbb26efe8a886f7bba94c2b996c9535ce07f917/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/9dbb26efe8a886f7bba94c2b996c9535ce07f917/library/std/src/panicking.rs:403:40
      std::panicking::try
             at /rustc/9dbb26efe8a886f7bba94c2b996c9535ce07f917/library/std/src/panicking.rs:367:19
      std::panic::catch_unwind
             at /rustc/9dbb26efe8a886f7bba94c2b996c9535ce07f917/library/std/src/panic.rs:133:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/9dbb26efe8a886f7bba94c2b996c9535ce07f917/library/std/src/rt.rs:128:48
      std::panicking::try::do_call
             at /rustc/9dbb26efe8a886f7bba94c2b996c9535ce07f917/library/std/src/panicking.rs:403:40
      std::panicking::try
             at /rustc/9dbb26efe8a886f7bba94c2b996c9535ce07f917/library/std/src/panicking.rs:367:19
      std::panic::catch_unwind
             at /rustc/9dbb26efe8a886f7bba94c2b996c9535ce07f917/library/std/src/panic.rs:133:14
      std::rt::lang_start_internal
             at /rustc/9dbb26efe8a886f7bba94c2b996c9535ce07f917/library/std/src/rt.rs:128:20
  14: main
  15: __libc_start_main
  16: _start


Thread 'main' panicked at 'analysis function should return an extrinsic time for valid inputs', /home/vados/.cargo/git/checkouts/substrate-7e08433d4c370a21/bf9683e/utils/frame/benchmarking-cli/src/writer.rs:170

This is a bug. Please report it at:

	support.anonymous.an
```
</details>

[trace.txt](https://github.com/paritytech/substrate/files/7314112/trace.txt)  
Tested versions: `3.0.0-monthly-2021-10`.

## How to reproduce
Using the substrate-node-template:  
```sh
git clone -b v3.0.0+monthly-2021-10 git@github.com:substrate-developer-hub/substrate-node-template.git
cd substrate-node-template
cargo build --release --features runtime-benchmarks
./target/release/node-template benchmark --execution=wasm --wasm-execution=compiled --chain dev --pallet '*' --extrinsic '*' --steps 1 --repeat 1 --raw --output ./weights.rs
```

## Probable cause
I did not yet investigate myself.  
quoting @shawntabrizi
>probably the analysis library cannot generate a linear graph without multiple data points

## How it should be
Up for discussion, but definitely not panic :laughing:  
quoting @shawntabrizi
>so rather than panic, we should return an error or not allow --output along with --step=1 --repeat=1 or something

## Next steps
I will take a look and see if the fix is trivial, in which case I will MR it.  
Otherwise if someone already has the fix or ideas, all welcome.

**Comment by shawntabrizi** [comment]
Using latest master I am able to run:

```
./target/release/node-template benchmark --chain=dev --steps=1 --repeat=1 --pallet="*" --extrinsic="*" --execution=wasm --wasm-execution=compiled --raw > out
```

without issue.

The output is:

<details>

<summary>Show</summary>

```
Pallet: "frame_benchmarking", Extrinsic: "addition", Lowest values: [], Highest values: [], Steps: 1, Repeat: 1
i,extrinsic_time_ns,storage_root_time_ns,reads,repeat_reads,writes,repeat_writes,proof_size_bytes
0,0,1000,0,0,0,0,0
1000000,0,2000,0,0,0,0,0

Raw Storage Info
========

Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=        0
    + i        0
              µs

Reads = 0 + (0 * i)
Writes = 0 + (0 * i)

Min Squares Analysis
========

Pallet: "frame_benchmarking", Extrinsic: "subtraction", Lowest values: [], Highest values: [], Steps: 1, Repeat: 1
i,extrinsic_time_ns,storage_root_time_ns,reads,repeat_reads,writes,repeat_writes,proof_size_bytes
0,1000,1000,0,0,0,0,0
1000000,0,2000,0,0,0,0,0

Raw Storage Info
========

Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=        1
    + i        0
              µs

Reads = 0 + (0 * i)
Writes = 0 + (0 * i)

Min Squares Analysis
========

Pallet: "frame_benchmarking", Extrinsic: "multiplication", Lowest values: [], Highest values: [], Steps: 1, Repeat: 1
i,extrinsic_time_ns,storage_root_time_ns,reads,repeat_reads,writes,repeat_writes,proof_size_bytes
0,0,1000,0,0,0,0,0
1000000,1000,1000,0,0,0,0,0

Raw Storage Info
========

Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=        0
    + i        0
              µs

Reads = 0 + (0 * i)
Writes = 0 + (0 * i)

Min Squares Analysis
========

Pallet: "frame_benchmarking", Extrinsic: "division", Lowest values: [], Highest values: [], Steps: 1, Repeat: 1
i,extrinsic_time_ns,storage_root_time_ns,reads,repeat_reads,writes,repeat_writes,proof_size_bytes
0,1000,1000,0,0,0,0,0
1000000,0,2000,0,0,0,0,0

Raw Storage Info
========

Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=        1
    + i        0
              µs

Reads = 0 + (0 * i)
Writes = 0 + (0 * i)

Min Squares Analysis
========

Pallet: "frame_benchmarking", Extrinsic: "hashing", Lowest values: [], Highest values: [], Steps: 1, Repeat: 1
i,extrinsic_time_ns,storage_root_time_ns,reads,repeat_reads,writes,repeat_writes,proof_size_bytes
0,25161000,5000,0,0,0,0,0
100,25050000,3000,0,0,0,0,0

Raw Storage Info
========

Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=    25160
    + i        0
              µs

Reads = 0 + (0 * i)
Writes = 0 + (0 * i)

Min Squares Analysis
========

Pallet: "frame_benchmarking", Extrinsic: "storage_read", Lowest values: [], Highest values: [], Steps: 1, Repeat: 1
i,extrinsic_time_ns,storage_root_time_ns,reads,repeat_reads,writes,repeat_writes,proof_size_bytes
0,0,1000,0,0,0,0,0
1000,2662000,2000,0,0,0,0,0

Raw Storage Info
========
Storage: Skipped Metadata (r:0 w:0)

Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=        0
    + i    2.662
              µs

Reads = 0 + (1 * i)
Writes = 0 + (0 * i)

Min Squares Analysis
========

Pallet: "frame_benchmarking", Extrinsic: "storage_write", Lowest values: [], Highest values: [], Steps: 1, Repeat: 1
i,extrinsic_time_ns,storage_root_time_ns,reads,repeat_reads,writes,repeat_writes,proof_size_bytes
0,0,2000,0,0,0,0,0
1000,424000,9000,0,0,0,0,0

Raw Storage Info
========
Storage: Skipped Metadata (r:0 w:0)

Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=        0
    + i    0.424
              µs

Reads = 0 + (0 * i)
Writes = 0 + (1 * i)

Min Squares Analysis
========

Pallet: "frame_system", Extrinsic: "remark", Lowest values: [], Highest values: [], Steps: 1, Repeat: 1
b,extrinsic_time_ns,storage_root_time_ns,reads,repeat_reads,writes,repeat_writes,proof_size_bytes
0,1000,1000,0,0,0,0,0
3932160,1524000,3000,0,0,0,0,0

Raw Storage Info
========

Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=        1
    + b        0
              µs

Reads = 0 + (0 * b)
Writes = 0 + (0 * b)

Min Squares Analysis
========

Pallet: "frame_system", Extrinsic: "remark_with_event", Lowest values: [], Highest values: [], Steps: 1, Repeat: 1
b,extrinsic_time_ns,storage_root_time_ns,reads,repeat_reads,writes,repeat_writes,proof_size_bytes
0,10000,1000,0,0,0,0,0
3932160,5870000,3000,0,0,0,0,0

Raw Storage Info
========

Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=       10
    + b    0.001
              µs

Reads = 0 + (0 * b)
Writes = 0 + (0 * b)

Min Squares Analysis
========

Pallet: "frame_system", Extrinsic: "set_heap_pages", Lowest values: [], Highest values: [], Steps: 1, Repeat: 1
extrinsic_time_ns,storage_root_time_ns,reads,repeat_reads,writes,repeat_writes,proof_size_bytes
4000,1000,0,0,0,0,0

Raw Storage Info
========
Storage: System Digest (r:1 w:1)
Storage: unknown [0x3a686561707061676573] (r:0 w:1)

Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=        4
              µs

Reads = 1
Writes = 2

Min Squares Analysis
========
-- Extrinsic Time --

Model:
Time ~=        4
              µs

Reads = 1
Writes = 2

Pallet: "frame_system", Extrinsic: "set_storage", Lowest values: [], Highest values: [], Steps: 1, Repeat: 1
i,extrinsic_time_ns,storage_root_time_ns,reads,repeat_reads,writes,repeat_writes,proof_size_bytes
1,2000,2000,0,0,0,0,0
1000,491000,2000,0,0,0,0,0

Raw Storage Info
========
Storage: Skipped Metadata (r:0 w:0)

Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=     1.51
    + i    0.489
              µs

Reads = 0 + (0 * i)
Writes = 0 + (1 * i)

Min Squares Analysis
========

Pallet: "frame_system", Extrinsic: "kill_storage", Lowest values: [], Highest values: [], Steps: 1, Repeat: 1
i,extrinsic_time_ns,storage_root_time_ns,reads,repeat_reads,writes,repeat_writes,proof_size_bytes
1,2000,1000,0,0,0,0,0
1000,344000,3000,0,0,0,0,0

Raw Storage Info
========
Storage: Skipped Metadata (r:0 w:0)

Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=    1.657
    + i    0.342
              µs

Reads = 0 + (0 * i)
Writes = 0 + (1 * i)

Min Squares Analysis
========

Pallet: "frame_system", Extrinsic: "kill_prefix", Lowest values: [], Highest values: [], Steps: 1, Repeat: 1
p,extrinsic_time_ns,storage_root_time_ns,reads,repeat_reads,writes,repeat_writes,proof_size_bytes
1,8000,2000,0,0,0,0,0
1000,785000,3000,0,0,0,0,0

Raw Storage Info
========
Storage: Skipped Metadata (r:0 w:0)

Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=    7.222
    + p    0.777
              µs

Reads = 0 + (0 * p)
Writes = 0 + (1 * p)

Min Squares Analysis
========

Pallet: "pallet_balances", Extrinsic: "transfer", Lowest values: [], Highest values: [], Steps: 1, Repeat: 1
extrinsic_time_ns,storage_root_time_ns,reads,repeat_reads,writes,repeat_writes,proof_size_bytes
45000,2000,0,0,0,0,0

Raw Storage Info
========
Storage: System Account (r:1 w:1)

Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=       45
              µs

Reads = 1
Writes = 1

Min Squares Analysis
========
-- Extrinsic Time --

Model:
Time ~=       45
              µs

Reads = 1
Writes = 1

Pallet: "pallet_balances", Extrinsic: "transfer_keep_alive", Lowest values: [], Highest values: [], Steps: 1, Repeat: 1
extrinsic_time_ns,storage_root_time_ns,reads,repeat_reads,writes,repeat_writes,proof_size_bytes
27000,1000,0,0,0,0,0

Raw Storage Info
========
Storage: System Account (r:1 w:1)

Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=       27
              µs

Reads = 1
Writes = 1

Min Squares Analysis
========
-- Extrinsic Time --

Model:
Time ~=       27
              µs

Reads = 1
Writes = 1

Pallet: "pallet_balances", Extrinsic: "set_balance_creating", Lowest values: [], Highest values: [], Steps: 1, Repeat: 1
extrinsic_time_ns,storage_root_time_ns,reads,repeat_reads,writes,repeat_writes,proof_size_bytes
16000,1000,0,0,0,0,0

Raw Storage Info
========
Storage: System Account (r:1 w:1)

Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=       16
              µs

Reads = 1
Writes = 1

Min Squares Analysis
========
-- Extrinsic Time --

Model:
Time ~=       16
              µs

Reads = 1
Writes = 1

Pallet: "pallet_balances", Extrinsic: "set_balance_killing", Lowest values: [], Highest values: [], Steps: 1, Repeat: 1
extrinsic_time_ns,storage_root_time_ns,reads,repeat_reads,writes,repeat_writes,proof_size_bytes
18000,1000,0,0,0,0,0

Raw Storage Info
========
Storage: System Account (r:1 w:1)

Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=       18
              µs

Reads = 1
Writes = 1

Min Squares Analysis
========
-- Extrinsic Time --

Model:
Time ~=       18
              µs

Reads = 1
Writes = 1

Pallet: "pallet_balances", Extrinsic: "force_transfer", Lowest values: [], Highest values: [], Steps: 1, Repeat: 1
extrinsic_time_ns,storage_root_time_ns,reads,repeat_reads,writes,repeat_writes,proof_size_bytes
112000,3000,0,0,0,0,0

Raw Storage Info
========
Storage: System Account (r:2 w:2)

Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=      112
              µs

Reads = 2
Writes = 2

Min Squares Analysis
========
-- Extrinsic Time --

Model:
Time ~=      112
              µs

Reads = 2
Writes = 2

Pallet: "pallet_balances", Extrinsic: "transfer_all", Lowest values: [], Highest values: [], Steps: 1, Repeat: 1
extrinsic_time_ns,storage_root_time_ns,reads,repeat_reads,writes,repeat_writes,proof_size_bytes
35000,1000,0,0,0,0,0

Raw Storage Info
========
Storage: System Account (r:1 w:1)

Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=       35
              µs

Reads = 1
Writes = 1

Min Squares Analysis
========
-- Extrinsic Time --

Model:
Time ~=       35
              µs

Reads = 1
Writes = 1

Pallet: "pallet_balances", Extrinsic: "force_unreserve", Lowest values: [], Highest values: [], Steps: 1, Repeat: 1
extrinsic_time_ns,storage_root_time_ns,reads,repeat_reads,writes,repeat_writes,proof_size_bytes
18000,1000,0,0,0,0,0

Raw Storage Info
========
Storage: System Account (r:1 w:1)

Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=       18
              µs

Reads = 1
Writes = 1

Min Squares Analysis
========
-- Extrinsic Time --

Model:
Time ~=       18
              µs

Reads = 1
Writes = 1

Pallet: "pallet_timestamp", Extrinsic: "set", Lowest values: [], Highest values: [], Steps: 1, Repeat: 1
extrinsic_time_ns,storage_root_time_ns,reads,repeat_reads,writes,repeat_writes,proof_size_bytes
7000,2000,0,0,0,0,0

Raw Storage Info
========
Storage: Timestamp Now (r:1 w:1)
Storage: Aura CurrentSlot (r:1 w:0)

Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=        7
              µs

Reads = 2
Writes = 1

Min Squares Analysis
========
-- Extrinsic Time --

Model:
Time ~=        7
              µs

Reads = 2
Writes = 1

Pallet: "pallet_timestamp", Extrinsic: "on_finalize", Lowest values: [], Highest values: [], Steps: 1, Repeat: 1
extrinsic_time_ns,storage_root_time_ns,reads,repeat_reads,writes,repeat_writes,proof_size_bytes
3000,2000,0,0,0,0,0

Raw Storage Info
========

Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=        3
              µs

Reads = 0
Writes = 0

Min Squares Analysis
========
-- Extrinsic Time --

Model:
Time ~=        3
              µs

Reads = 0
Writes = 0

Pallet: "pallet_template", Extrinsic: "do_something", Lowest values: [], Highest values: [], Steps: 1, Repeat: 1
s,extrinsic_time_ns,storage_root_time_ns,reads,repeat_reads,writes,repeat_writes,proof_size_bytes
0,12000,2000,0,0,0,0,0
100,12000,2000,0,0,0,0,0

Raw Storage Info
========
Storage: TemplateModule Something (r:0 w:1)

Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=       12
    + s        0
              µs

Reads = 0 + (0 * s)
Writes = 1 + (0 * s)

Min Squares Analysis
========

```
</details>
